import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "adonis",
  category: "cocktail",
  title: "아도니스 — 저도수로 즐기는 셰리와 스위트 버무스의 잔잔한 여운",
  dek: "「아도니스」는 아주 오래된 칵테일로, 그와 관련된 이야기는 그다지 많지 않습니다.",
  publishedAt: "2025-05-03",
  hero: "/articles/adonis/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223854364359",
  relatedCocktailSlugs: ["adonis"],
  blocks: [
    { kind: "figure", src: "/articles/adonis/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「아도니스」는 아주 오래된 칵테일로, 그와 관련된 이야기는 그다지 많지 않습니다. 일단 공통적으로 1884년에 초연된 후 브로드웨이에서 500회 이상 공연된 동명의 뮤지컬에서 이름을 따왔다고 합니다." },
    { kind: "paragraph", text: "어떤 설에서는 뉴욕의 *「월도프-아스토리아(Waldorf-Astoria) 호텔」에서 만들어졌다고도 합니다만, 정확한 근거가 있는 건 아니고 추정되는 정도인 것 같습니다.*1893~1929" },
    { kind: "paragraph", text: "이와 관련해서는 difford's Guide에서 아주 자세하게 소개하고 있습니다." },
    { kind: "paragraph", text: "살펴보자면 1887년 3월 27일 자로 발행된 뉴욕 한 신문의 칼럼에서 처음으로 '아도니스'라는 이름의 칵테일에 관한 일화가 나오는데, 이 아도니스가 우리가 현재 아는 그 아도니스가 맞는지는 알 수 없습니다." },
    { kind: "paragraph", text: "하지만, 이후에 *자크 스트라우브의 저서에서 현재 우리가 아는 아도니스가 소개되었고, 이후 **알버트 스티븐스 크로켓의 두 저서에서 그 이름의 유래가 소개되었습니다." },
    { kind: "paragraph", text: "*Straub's Manual of Mixed Drinks(1913)" },
    { kind: "paragraph", text: "**Old Waldorf Bar Days(1931), Old Waldorf-Astoria Bar Book(1935)" },
    { kind: "paragraph", text: "종합해 보자면, \"적어도 1913년 이전에 아마도 월도프-아스토리아 호텔의 바에서 아도니스가 만들어졌을 것이다!\"라고 추정할 수는 있겠죠." },
    { kind: "quote", text: "'왜 하필 월도프-아스토리아 호텔일까?'" },
    { kind: "paragraph", text: "뮤지컬 '아도니스'는 당시 브로드웨이에서 큰 인기를 끈 뮤지컬." },
    { kind: "paragraph", text: "정보와 문화가 퍼지는 속도가 느렸기 때문에 동명의 칵테일은 뉴욕에서 만들어졌을 것." },
    { kind: "paragraph", text: "당시 쉐리 와인과 버무스는 가격대가 높은 주류, 주로 상류층이 즐기던 술, 고급 레스토랑이나 호텔에서나 취급." },
    { kind: "paragraph", text: "월도프-아스토리아 호텔은 당대 상류층과 저명인사들이 방문하던 곳으로, 사교의 중심지였음." },
    { kind: "paragraph", text: "*1931년과 1935년에 호텔의 칵테일 레시피를 담은 책들이 출판될 정도." },
    { kind: "paragraph", text: "당시에 이미 맨하탄, 마티니처럼 버무스를 사용하는 칵테일들이 이미 존재했음" },
    { kind: "paragraph", text: "*해당 책들에서 아도니스 이름의 유래에 대해 설명" },
    { kind: "paragraph", text: "이런 점들 때문에 이 칵테일이 월도프-아스토리아 호텔에서 만들어졌다고 추정하는 것은 꽤 합당해 보입니다." },
    { kind: "figure", src: "/articles/adonis/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "아도니스의 레시피는 정말 다양합니다. 1:1 ~ 3:1로 비율이 다양하고, 피노 쉐리 말고 다른 쉐리를 쓴다든지, 피노 쉐리에 다른 쉐리도 블렌딩한다든지 만드는 사람마다 천차만별입니다." },
    { kind: "paragraph", text: "이것저것 시도해 보시고 입맛에 맞는 아도니스를 찾아가는 게 가장 좋겠죠." },
    { kind: "figure", src: "/articles/adonis/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 모든 재료를 믹싱 글라스에 넣어줍니다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채우고, 스터합니다." },
    { kind: "paragraph", text: "3. 칵테일 잔에 따라줍니다." },
    { kind: "paragraph", text: "아도니스의 맛" },
    { kind: "paragraph", text: "- 압도적인 감칠맛" },
    { kind: "paragraph", text: "- 와인스러움에 더해 약간의 한약스러운 맛" },
    { kind: "paragraph", text: "- 약간의 오렌지에 더불어, 아주 살짝 열대과일 같은 느낌도 스쳐감" },
    { kind: "paragraph", text: "- 약간의 견과류의 캐릭터" },
    { kind: "paragraph", text: "- 복잡한 향신료, 허브, 차의 캐릭터가 훅하고 지나감." },
    { kind: "paragraph", text: "그 외" },
    { kind: "paragraph", text: "- 아도니스는 '뱀부(Bamboo)'에서 드라이 버무스를 스위트 버무스로 바꾼 칵테일로, 어느 정도 비슷한 캐릭터를 공유" },
    { kind: "paragraph", text: "- 뱀부와 더불어 도수가 낮은 편의 칵테일로, 주로 식전주로 소개되고 있기도" },
    { kind: "paragraph", text: "- 인지도면에서는 뱀부만큼의 유명세를 가지고 있지는 못함" },
  ],
};
