import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "americano",
  category: "cocktail",
  title: "아메리카노 — 커피가 아니라 칵테일, 미국인이 아니라 이탈리아인입니다!!",
  dek: "흔히 커피로 오해받기 쉬운 \"아메리카노 칵테일\"은 그 이름과는 다르게 커피나 미국적인 요소가 하나도 들어가지 않은, 이탈리아에서 탄생한 칵테일입니다.",
  publishedAt: "2024-09-06",
  hero: "/articles/americano/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223574457761",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/americano/00.webp", width: 500, height: 500 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "흔히 커피로 오해받기 쉬운 \"아메리카노 칵테일\"은 그 이름과는 다르게 커피나 미국적인 요소가 하나도 들어가지 않은, 이탈리아에서 탄생한 칵테일입니다." },
    { kind: "paragraph", text: "아메리카노 칵테일의 기원에 대해서는 두 가지 이야기가 있습니다." },
    { kind: "paragraph", text: "① 1860년대에 가스파레 캄파리(Gaspare Campari)가 아메리카노 칵테일에 들어가는 재료인 캄파리라는 술을 만들었고, 자신의 바에서 캄파리를 사용한 칵테일을 제공하였습니다." },
    { kind: "paragraph", text: "이 바에서는 캄파리와 스윗 버무스가 동량으로 들어가는 '밀라노-토리노(Milano-Torino)'라는 칵테일을 탄산수로 희석한 칵테일을 제공하였는데, 이 칵테일이 아메리카노입니다." },
    { kind: "paragraph", text: "다만, 아메리카노라는 이름이 붙은 건 금주법 시대 당시에 미국 관광객의 인기를 얻으면서 붙게 되었다고 합니다." },
    { kind: "paragraph", text: "② 1920년대 미국 금주법 시대에 미국 관광객들이 이탈리아에서 '밀라노-토리노'의 쌉쌀한 맛을 좀 더 편하게 즐기기 위해서 탄산수를 넣었고, 이게 미국 관광객들의 인기를 끌어서 '아메리카노'라 이름을 붙인 칵테일이 탄생했다고 합니다." },
    { kind: "paragraph", text: "시기에 차이가 있지만, 중요한 건 아메리카노 칵테일이 '밀라노-토리노'라는 칵테일에서 시작된 것이고, 후에 '네그로니(Negroni)'라는 칵테일에도 영향을 미치게 된다는 점입니다." },
    { kind: "paragraph", text: "여담으로, 소설 제임스 본드 시리즈의 첫 번째 작품인 카지노 로얄에서 애주가인 제임스 본드가 가장 첫 번째로 주문한 칵테일이 아메리카노입니다." },
    { kind: "figure", src: "/articles/americano/01.webp", width: 499, height: 499 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 캄파리 (Campari)" },
    { kind: "paragraph", text: "30ml 스윗 버무스 (Sweet Vermouth, Italian)" },
    { kind: "paragraph", text: "탄산수 적당량" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질 or 오렌지 휠 반쪽" },
    { kind: "figure", src: "/articles/americano/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 얼음을 채운 긴 잔에 캄파리와 버무스를 넣어줍니다." },
    { kind: "paragraph", text: "2. 바스푼으로 살짝 스터해서 온도를 낮춰줍니다." },
    { kind: "paragraph", text: "3. 탄산수를 넣어줍니다." },
    { kind: "paragraph", text: "4. 오렌지 껍질을 쓰는 경우, 칵테일에 오일을 짜고 넣어줍니다." },
    { kind: "paragraph", text: "or" },
    { kind: "paragraph", text: "오렌지 휠 반 쪽을 쓰는 경우 그냥 넣어줍니다." },
    { kind: "figure", src: "/articles/americano/03.webp", width: 500, height: 500 },
    { kind: "paragraph", text: "아메리카노는 유럽에서 식전주로 아주 인기가 많은 칵테일로, 달큰쌉쌀하고 허브감이 탄산과 함께 상쾌하게 다가오는 것이 입맛을 돋구기 딱 좋은 칵테일입니다." },
    { kind: "paragraph", text: "오렌지 껍질을 가니시로 쓰는 경우에는 쌉쌀한 오렌지 캐릭터가, 오렌지 휠을 가니시로 쓰는 경우에는 묵직하게 달큰한 오렌지의 캐릭터가 좀 더 두드러집니다." },
    { kind: "paragraph", text: "확실히 식전주로 아주 좋은 칵테일이며, 식후에도 입을 싹 씻어줄만한 칵테일이기도 합니다." },
    { kind: "paragraph", text: "참고로 저는 작은 용량의 잔을 사용해서 30미리씩 넣었으니, 사용하시는 잔에 따라 용량을 맞춰서 드시면 되겠습니다." },
  ],
};
