import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "ardbeg-bizarrebq",
  category: "spirits",
  title: "아드벡 비자르비큐 — 위스키와 바베큐의 만남",
  dek: "\"아드벡 비자르비큐\"는 아일라 섬의 피트 위스키로 유명한 '아드벡 증류소'에서 2023년 '아드벡 커미티(Ardbeg Committee)' 한정으로 출시한 바틀로, 특이하게도 \"바베큐\"에서 영감을 받은 위스키입니다.",
  publishedAt: "2024-07-27",
  hero: "/articles/ardbeg-bizarrebq/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223527447243",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/ardbeg-bizarrebq/00.webp", width: 524, height: 524 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "\"아드벡 비자르비큐\"는 아일라 섬의 피트 위스키로 유명한 '아드벡 증류소'에서 2023년 '아드벡 커미티(Ardbeg Committee)' 한정으로 출시한 바틀로, 특이하게도 \"바베큐\"에서 영감을 받은 위스키입니다." },
    { kind: "paragraph", text: "'아드벡 증류소'에서는 이따금씩 일종의 아드벡 커뮤니티/팬클럽인 '아드벡 커미티' 한정의 특이한 바틀을 출시하는데, 그 중 하나입니다." },
    { kind: "paragraph", text: "마스터 디스틸러인 빌 럼스덴 박사(Dr. Bill Lumsden)과 그릴 전문가 크리스찬 스티븐슨(일명 DJ BBQ)이 협업하여 만든 바틀로, 강렬한 고기맛 · 피트감이 어우러지는 독특한 캐릭터를 가지게 됩니다." },
    { kind: "paragraph", text: "캐스크는 이중으로 태운 오크 캐스크(Double Charred Oak Cask), 페드로 히메네스 캐스크(Pedro Ximenez Sherry Cask)와 \"BBQ 캐스크(BBQ Cask)\"를 사용했다고 하는데, 이 \"BBQ 캐스크\"가 뭔지는 수수께끼네요." },
    { kind: "quote", text: "증류소: 아드벡 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트" },
    { kind: "quote", text: "캐스크 정보: Double Charred Oak Cask, PX Sherry Cask, BBQ Cask" },
    { kind: "quote", text: "도수: 50.9%" },
    { kind: "figure", src: "/articles/ardbeg-bizarrebq/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 달달하고 다소 무거운 피트감" },
    { kind: "paragraph", text: "- 훈제향, 구수한 곡식, 훈제향에 숨은 건포도" },
    { kind: "paragraph", text: "- 커피 찌꺼기" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 달달한 스모키함, 구수한 곡식" },
    { kind: "paragraph", text: "- 스파이스, 약간의 생강, 가죽" },
    { kind: "paragraph", text: "- 혀에 남는 탄 설탕의 느낌" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 그렇게 강하지 않은 적당히 기분 좋은 피트감" },
    { kind: "paragraph", text: "- 훈제향, 약간의 스파이스" },
    { kind: "paragraph", text: "- 피트가 지나가면 달달함이 올라옴" },
    { kind: "paragraph", text: "'아드벡 비자르비큐'는 국내에서는 두 번째로 정식 출시된 아드벡 커미티 바틀로, 159,000원이라는 아주아주 합리적인 가격으로 출시되어 저도 무지성으로 일단 한 병 구입을 했었습니다." },
    { kind: "paragraph", text: "오픈한지 얼마 안됐을 때는 훈제 베이컨, 고기 같은 캐릭터가 강했던 걸로 기억하는데, 얼마 남지 않은 상태로 오래 브리딩이 되고 나니 베이컨보다는 훈제+건과일 같은 달달함이 부각되는 것 같습니다." },
    { kind: "paragraph", text: "제가 올린 테이스팅 노트는 반 이상 마신 후에 거의 1년 정도가 지난 상태니 이 점도 참고해주시면 좋을 것 같습니다." },
    { kind: "paragraph", text: "'아드벡 비자르비큐'는 합리적인 가격에 비해 아주 잘 만들어진 바틀이라 생각되며, 마실 기회가 있다면 반드시 한 번 정도는 맛보시는 걸 추천드립니다." },
  ],
};
