import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "around-the-world",
  category: "cocktail",
  title: "어라운드 더 월드",
  dek: "\"어라운드 더 월드(Around The World)\"라는 칵테일은 비행기 세계일주 노선 운항을 기념한 칵테일 대회에서 우승한 작품으로, 미국인 바텐더의 작품이라 알려져 있다고 합니다.",
  publishedAt: "2024-07-18",
  hero: "/articles/around-the-world/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223516976562",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/around-the-world/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"어라운드 더 월드(Around The World)\"라는 칵테일은 비행기 세계일주 노선 운항을 기념한 칵테일 대회에서 우승한 작품으로, 미국인 바텐더의 작품이라 알려져 있다고 합니다." },
    { kind: "paragraph", text: "다만, 이러한 주장이나, 칵테일 레시피는 일본에서만 있는 것으로 그 출처는 명확하지가 않습니다." },
    { kind: "paragraph", text: "진(Gin), 민트 리큐르, 파인애플 주스라는 간단한 재료의 꽤나 생소한 조합의 칵테일로 궁금증을 자극하며, 상단의 표면이 하얀색 구름과 같이 있는 아름다운 초록색 칵테일입니다." },
    { kind: "figure", src: "/articles/around-the-world/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml 진(Gin)" },
    { kind: "paragraph", text: "15ml 크렘 드 민트(Creme de Menthe)" },
    { kind: "paragraph", text: "15ml 파인애플 주스(Pineapple Juice)" },
    { kind: "paragraph", text: "1 민트 체리(Mint Cherry) - 옵션" },
    { kind: "figure", src: "/articles/around-the-world/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 민트 체리 이외의 재료를 셰이커 안에 모두 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 넣고 셰이킹해줍니다." },
    { kind: "paragraph", text: "3. 칵테일 잔 안에 민트 체리를 하나 넣어줍니다." },
    { kind: "paragraph", text: "(옵션)" },
    { kind: "paragraph", text: "4. 셰이킹 한 칵테일을 잔에 부어줍니다." },
    { kind: "figure", src: "/articles/around-the-world/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/around-the-world/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "이 칵테일은 진, 민트 리큐르, 파인애플이라는 생소한 조합의 칵테일인데, 진과 민트의 궁합은 워낙 좋지만 파인애플은 좀 글쎄다 싶었습니다. 그런데 의외로 잘 어울리는 것이 웃음이 지어지는 맛입니다." },
    { kind: "paragraph", text: "아주 상쾌하고 약간은 달달한 맛으로, 진의 맛이 딱 중심을 잡아주고, 민트 리큐르가 시원함을, 파인애플 주스가 달달함과 과일의 캐릭터를 더해줘 보기보다 밸런스가 꽤 좋은 칵테일이라는 생각이 들었습니다." },
    { kind: "paragraph", text: "만들기 전에는 레시피가 단순해 뭔가 비터나 다른 재료를 넣고 싶었지만, 마셔보고 나니 이대로도 아주 좋아서 다른 재료를 넣기가 애매하네요." },
    { kind: "paragraph", text: "진의 비율이 적어 도수감이 조금 있고, 거기에 더해 시트러스 캐릭터가 있는 진과 어울리겠다 싶어서 일반 진보다는 도수가 살짝 높고(47.3%), 자몽 캐릭터가 강한 탱커레이 넘버 텐(Tanqueray No.10)을 사용했는데, 중심을 확실히 잡아줘서 좋은 선택이었던 것 같습니다." },
    { kind: "paragraph", text: "\"어라운드 더 월드\" 칵테일은 다양한 레시피가 있으니 레시피를 바꾸거나 진의 종류를 바꿔 비교해 보는 것도 하나의 재미가 되겠습니다." },
  ],
};
