import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "arran-machrie-moor-cs",
  category: "spirits",
  title: "아란 마크리 무어 CS",
  dek: "마크리 무어 CS는 CS 위스키들 중에서도 유명해",
  publishedAt: "2021-09-26",
  hero: "/articles/arran-machrie-moor-cs/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222517346261",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "paragraph", text: "제가 마크리 무어 CS를 처음 만난 건" },
    { kind: "paragraph", text: "광교에 있는 바 글렌베니였습니다." },
    { kind: "figure", src: "/articles/arran-machrie-moor-cs/00.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "마크리 무어 CS는 CS 위스키들 중에서도 유명해" },
    { kind: "paragraph", text: "언젠가 한 번쯤은 마셔보고 싶던 찰나에" },
    { kind: "paragraph", text: "백 바에 있는 보틀을 보고 바로 주문을 했습니다." },
    { kind: "paragraph", text: "이 한 잔에 마크리 무어 CS의 매력에 빠져들었고," },
    { kind: "paragraph", text: "때마침 와인앤모어에서 할인행사를 해서 보틀째로 구입을 하게 되었습니다." },
    { kind: "paragraph", text: "여담으로 글렌베니는 수원에 있는" },
    { kind: "paragraph", text: "몇 안되는 괜찮은 바입니다." },
    { kind: "paragraph", text: "특히 위스키 종류가 다양하고, 바텐더분의 서비스가 아주 친절하니" },
    { kind: "paragraph", text: "수원 지역에 사는 분들에게 추천합니다!" },
    { kind: "paragraph", text: "위스키 뿐만아니라 칵테일도 주문할 수 있습니다." },
    { kind: "figure", src: "/articles/arran-machrie-moor-cs/01.webp", width: 966, height: 966, caption: "포장과 보틀 디자인부터 매력적" },
    { kind: "heading", text: "About The Whisk(e)y" },
    { kind: "paragraph", text: "마크리 무어라는 이름 자체는 아란 섬 서쪽 해안의 피트 습지에서 따온 것입니다." },
    { kind: "paragraph", text: "보틀의 개는 아란 섬 지역의 전설에서 아이디어를 얻은 것으로," },
    { kind: "paragraph", text: "전설 속의 거인 전사인 핑갈(Fingal)이" },
    { kind: "paragraph", text: "자신이 가장 좋아하는 개인 브랜(Bran)을" },
    { kind: "paragraph", text: "마크리 무어 지역에 있는 자신의 의자인 큰 돌에 묶어둔 것에서 영감을 얻었다고 합니다." },
    { kind: "paragraph", text: "CS 제품답게 아주 높은 도수를 자랑하며" },
    { kind: "paragraph", text: "원래는 한정판 제품의 개념으로 출시되어 각 배치마다 도수가 달랐지만," },
    { kind: "paragraph", text: "마크리 무어가 엄청난 인기를 끌면서" },
    { kind: "paragraph", text: "2018년 아란 디스틸러리는 이를 정규 라인으로 들이게 됩니다." },
    { kind: "paragraph", text: "정규 라인으로 들인 이후부터는 56.2도로 고정되었습니다." },
    { kind: "figure", src: "/articles/arran-machrie-moor-cs/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "향 자체는 꽤 프루티 하며 서양배의 향이 약간 납니다." },
    { kind: "paragraph", text: "피트향이 느껴지기는 하지만" },
    { kind: "paragraph", text: "아일라 지역의 피트와는 결이 다른 부드러운 피트함이 느껴집니다." },
    { kind: "paragraph", text: "전체적으로 프루티함과 피트함이 기분 좋은 밸런스를 이룹니다." },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "부드럽지만 역시 고도수답게 목을 뜨겁게 데워줍니다." },
    { kind: "paragraph", text: "맛은 향에 이어서 뭐라고 딱 집을 수는 없지만 과일의 맛이 꽤 납니다." },
    { kind: "paragraph", text: "마지막에는 약간의 꿀과 초콜릿스러운 맛이 혀끝에 남았습니다." },
    { kind: "paragraph", text: "고도수이지만 전체적으로 맛은 달달하고 부드러운 편인데," },
    { kind: "paragraph", text: "이게 CS의 가장 큰 매력이라 생각됩니다." },
    { kind: "paragraph", text: "물을 조금 첨가하면 약간의 라즈베리의 풍미가 느껴지는데" },
    { kind: "paragraph", text: "정말 짧은 순간에 느껴지며, 이어서 빵의 풍미가 납니다." },
    { kind: "paragraph", text: "물을 넣으면 맛이 풀리지만 반대로 향과 피니쉬를 많이 잃게 되는데," },
    { kind: "paragraph", text: "개인적으로 피니쉬를 좋아해서 물을 첨가하지 않는 게" },
    { kind: "paragraph", text: "개인적인 입맛에 맞았습니다." },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "피니쉬로 첫번째 숨에 강렬하지만 부드러운 피트의 향이 폭발하고," },
    { kind: "paragraph", text: "두 번째 숨부터 피트향이 은은하고 부드럽고 달달해집니다." },
    { kind: "paragraph", text: "피니쉬는 꽤 긴 편으로" },
    { kind: "paragraph", text: "처음의 강렬함이 지나가면 부드럽고 은은하게 계속됩니다." },
    { kind: "paragraph", text: "피니쉬에서도 아일라 지역의 피트와는 다르게" },
    { kind: "paragraph", text: "부드러운 피트함이 느껴집니다." },
    { kind: "figure", src: "/articles/arran-machrie-moor-cs/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "인스타그램" },
  ],
};
