import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "attaboy",
  category: "bar",
  title: "모던 클래식 칵테일의 아이콘, 아타보이의 샘 로스를 찰스 H에서 만나다",
  dek: "샘 로스는 호주 출신의 바텐더로, 이후 뉴욕의 밀크 앤 허니(Milk & Honey), 리틀 브랜치(Little Branch) 등을 거치며 페이퍼 플레인(Paper Plane)과 페니실린(Penicillin)과 같은 모던 클래식 칵테일 중에서도 아이코",
  publishedAt: "2024-09-26",
  hero: "/articles/attaboy/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223597381823",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/attaboy/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "샘 로스는 호주 출신의 바텐더로, 이후 뉴욕의 밀크 앤 허니(Milk & Honey), 리틀 브랜치(Little Branch) 등을 거치며 페이퍼 플레인(Paper Plane)과 페니실린(Penicillin)과 같은 모던 클래식 칵테일 중에서도 아이코닉한 불후의 명작을 만들어낸 장본인입니다." },
    { kind: "paragraph", text: "샘 로스를 얘기할 때 지금은 고인이 된 그의 멘토인 사샤 페트라스케(Sasha Petraske)를 빼놓을 수 없는데, 샘 로스가 밀크 앤 허니에서 근무할 때 오너인 사샤 페트라스케에게서 많은 영향을 받게 되었습니다." },
    { kind: "paragraph", text: "사샤 페트라스케는 1999년 밀크 앤 허니를 오픈하면서 스피크이지(Speakeasy) 스타일의 바를 유행시켰고, 크래프트 칵테일 운동(Craft Cocktail Movement, AKA 칵테일 르네상스)에 큰 영향을 미친 사람 중 한 명입니다." },
    { kind: "paragraph", text: "샘 로스는 현재 이전의 밀크 앤 허니가 있었던 자리에 아타보이(Attaboy)를 오픈하여 이 곳을 본거지로 활동하고 있으며, 현대 칵테일계의 아이콘, 바텐더들의 바텐더라 할 수 있습니다." },
    { kind: "paragraph", text: "이번에 포시즌스에 위치한 바인 찰스 H에서 샘 로스의 게스트 바텐딩이 있어서 방문했습니다." },
    { kind: "figure", src: "/articles/attaboy/01.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "이번 게스트 바텐딩에서는 그레이트 밤비노, 드래프트 데이, 페이퍼 플레인, 페어뱅크스의 4가지 메뉴에 페니실린까지 더해서 5종의 칵테일을 마셔볼 수 있었습니다." },
    { kind: "paragraph", text: "먼저 페니실린은 기주로 피트감이 없는 블렌디드 몰트 위스키를 사용하면서 아일라 위스키를 소량 플로팅했기 때문에 맛에서는 피트 캐릭터가 그렇게 많이 나지는 않습니다. 샘 로스는 애초에 기주로 너무 피트 캐릭터가 강한 위스키를 사용하면 안된다고 이야기합니다." },
    { kind: "figure", src: "/articles/attaboy/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/attaboy/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/attaboy/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/attaboy/05.webp", width: 966, height: 966, caption: "페니실린 / 페이퍼 플레인 / 드래프트 데이 페어뱅크스 / 그레이트 밤비노" },
    { kind: "paragraph", text: "페이퍼 플레인은 생각했던 것보다 아마로의 진득하고 무거운 캐릭터가 많이 느껴져서 놀랐는데, 페이퍼 플레인을 어떻게 만들려고 의도했는지 드디어 알 수 있는 한 잔이었습니다." },
    { kind: "paragraph", text: "드래프트 데이는 기주로 라이 위스키와 자메이칸 럼을 블렌딩하는 독특한 칵테일인데, 이게 또 바나나 리큐르와 압생트의 캐릭터와 절묘한 조합을 만들어내며 아주 재미있는 맛이었습니다." },
    { kind: "paragraph", text: "페어뱅크스는 올드패션드에서 재료 중 당에 아프리콧 리큐르를 추가한 것으로, 맛은 솔직히 딱 그 재료들이 낼 수 있는 맛이었고, 팬시 프리라는 칵테일과 비슷한 인상을 받았습니다." },
    { kind: "paragraph", text: "그레이트 밤비노는 버번 위스키, 퍼넷 브랑카, 배 거기에 오르쟈(아몬드 시럽)이 들어가는 독특한 조합의 칵테일인데 배와 퍼넷 브랑카의 캐릭터가 생각보다 잘 어울리며, 단맛과 쓴맛의 밸런스가 좋은, 꽤나 매력적인 칵테일이었습니다." },
    { kind: "paragraph", text: "전체적으로 칵테일의 온도감이 생각보다 낮았다고 느껴졌는데, 일부로 의도한 것인지가 궁금했습니다만 너무 붐벼서 물어보지는 못했네요." },
    { kind: "figure", src: "/articles/attaboy/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/attaboy/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "전체적으로 아주 붐비는 분위기였지만 칵테일이 본인의 바가 아닌 게스트 바텐딩에서 이런 맛을 낸다고? 싶을 정도로 아주 맛있었습니다. 개인적으로 게스트 바텐딩을 몇 번 가봤지만 이렇게까지 만족스러웠던 적은 처음이네요." },
    { kind: "paragraph", text: "칵테일을 좋아하는 저로서는 글과 사진으로만 접하던 사람과 칵테일을 만나니 약간 위인전의 인물을 보는 것 같은 느낌이었습니다. 너무 들떠서 책에 사인까지 받아왔네요." },
    { kind: "paragraph", text: "나중에 뉴욕을 간다면 아타보이는 꼭 방문해보고 싶습니다." },
  ],
};
