import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "b-and-b",
  category: "cocktail",
  title: "비앤비 — 베네딕틴과 꼬냑, 단순함 속에서 피어나는 깊은 풍미",
  dek: "「B&B」는 Benedictine & Brandy의 약자로, 이름 그대로 베네딕틴 돔과 브랜디(주로 꼬냑)의 두 가지 재료로 만들어내는 꽤나 간단한 칵테일입니다.",
  publishedAt: "2025-07-05",
  hero: "/articles/b-and-b/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223922952994",
  relatedCocktailSlugs: ["bnb"],
  blocks: [
    { kind: "figure", src: "/articles/b-and-b/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "「B&B」는 Benedictine & Brandy의 약자로, 이름 그대로 베네딕틴 돔과 브랜디(주로 꼬냑)의 두 가지 재료로 만들어내는 꽤나 간단한 칵테일입니다." },
    { kind: "paragraph", text: "비앤비에 대해서 가장 잘 알려진 이야기는 1930년대, 당시 뉴욕의 유명한 사교클럽이었던 '21 Club'의 바텐더에 의해서 탄생했다는 것입니다." },
    { kind: "figure", src: "/articles/b-and-b/01.webp", width: 499, height: 160, caption: "https://euvs-vintage-cocktail-books.cld.bz/1910-The-Barkeeper-s-Manual-by-Raymond-E-Sullivan-second-edition/32/" },
    { kind: "paragraph", text: "그러나, 사실 비앤비는 이미 1910년에 레이먼드 설리번(Raymond E. Sullivan)의 저서인 'The Barkeeper's Manual'에서 푸스카페 스타일의 칵테일로 기록된 적이 있습니다. 현재의 비율과는 다르게 베네딕틴과 꼬냑의 비율이 2:1이었죠." },
    { kind: "paragraph", text: "즉, 베네딕틴과 꼬냑의 조합은 이미 존재했었는데, 베네딕틴이 19세기에 상품화되어 판매된 것을 생각해 본다면 1910년 이전에 이미 비앤비 조합이 존재했을 수도 있을 거라는 추측도 무리는 아닙니다." },
    { kind: "paragraph", text: "아무튼, 이 칵테일은 해외에서도 꽤나 인기가 많았던 모양인지 1937년에는 베네딕틴에서 자체적으로 베네딕틴 60%와 프랑스 브랜디 40%를 섞은 일종의 RTD 제품인 B&B by Benedictine을 출시하기도 하였습니다." },
    { kind: "figure", src: "/articles/b-and-b/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "30ml 꼬냑" },
    { kind: "paragraph", text: "30ml 베네딕틴 돔(Benedictine DOM)" },
    { kind: "paragraph", text: "비앤비는 칵테일 이름대로 재료가 두 가지 밖에 들어가지 않습니다만, 취향에 따라서 비율을 조정하는 재미가 있는 칵테일입니다. 주로 1:1이나 꼬냑과 베네딕틴을 2:1로 만드는 게 일반적이죠." },
    { kind: "paragraph", text: "가니시는 굳이 필요 없지만, 한다면 오렌지 껍질을 살짝 짜주는 정도면 충분할 것 같습니다." },
    { kind: "figure", src: "/articles/b-and-b/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 잔에 재료를 넣고 충분히 젓는다." },
    { kind: "paragraph", text: "2. 잔에 채우고, 조금만 스터한다." },
    { kind: "paragraph", text: "3. 큰 얼음으로 교체해준다." },
    { kind: "paragraph", text: "비앤비 같은 칵테일은 도수가 높기 때문에 약간 시간을 들여가면서 마시게 됩니다. 그러니 메이킹 시에는 칵테일 자체에 *다일루션이 소량만 필요하며, 잔 안에 얼음이 있기 때문에 오래 스터할 필요가 없습니다." },
    { kind: "paragraph", text: "*얼음이 녹으면서 음료에 물이 섞여 희석되는 현상" },
    { kind: "paragraph", text: "개인적으로는 70~80% 정도의 맛을 낼 정도만 스터한 후, 잔 안의 얼음이 녹으면서 희석되는 것을 선호하는 편입니다." },
    { kind: "paragraph", text: "큰 얼음으로 처음부터 만들거나, 얼음을 교체하지 않아도 되지만, 새로운 큰 얼음으로 서브하는 게 최대한 얼음이 느리게 녹게 되는 장점이 있습니다." },
    { kind: "figure", src: "/articles/b-and-b/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "비앤비는 베네딕틴의 사프론, 꿀, 허브 캐릭터와 함께 느껴지는 꼬냑의 풍미가 매우 인상적인 칵테일로, 들어가는 재료가 2개 밖에 없는데, 베네딕틴의 맛은 정해져 있으니 어떤 꼬냑을 쓰냐에 따라서 맛이 꽤 달라집니다." },
    { kind: "paragraph", text: "비앤비를 즐기는 방법은 이외에도 푸스카페 스타일, 따뜻하게 뎁혀서 마시는 스타일 등 다양하게 있기도 합니다만, 개인적으로는 이런 빌드 스타일이 제일 마음에 드네요." },
  ],
};
