import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bamboo",
  category: "cocktail",
  title: "뱀부 — 군더더기 없이, 깔끔하고 조용한 한 잔",
  dek: "「뱀부」는 흔히 1890년대에 일본의 *요코하마 그랜드 호텔에서 독일계 미국인 바텐더였던 루이스 에핑어(Louis Eppinger)에 의해서 만들어졌다고 하는데, 그 출처는 위의 윌리엄 부스비(William Boothby)의 **저서인 것으로 보입니다",
  publishedAt: "2025-05-11",
  hero: "/articles/bamboo/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223862015358",
  relatedCocktailSlugs: ["bamboo"],
  blocks: [
    { kind: "figure", src: "/articles/bamboo/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "figure", src: "/articles/bamboo/01.webp", width: 674, height: 186, caption: "**The World's Drinks and How to Mix Them(1908)" },
    { kind: "paragraph", text: "「뱀부」는 흔히 1890년대에 일본의 *요코하마 그랜드 호텔에서 독일계 미국인 바텐더였던 루이스 에핑어(Louis Eppinger)에 의해서 만들어졌다고 하는데, 그 출처는 위의 윌리엄 부스비(William Boothby)의 **저서인 것으로 보입니다." },
    { kind: "paragraph", text: "*관동대지진 후 「호텔 뉴 그랜드」가 후신으로 세워져 현재까지 영업" },
    { kind: "figure", src: "/articles/bamboo/02.webp", width: 524, height: 181, caption: "1886.9.11. Western Kansas world" },
    { kind: "paragraph", text: "그러나 1886년 9월 11일에 발간된 'Western Kansas world'에 따르면 뱀부는 이미 영국인에 의하여 전파되어 뉴욕에서 인기를 끌고 있었다고 합니다. 다만, 어떤 셰리와 버무스를 사용한 것인지는 알 수 없죠." },
    { kind: "paragraph", text: "개인적으로 여기서 주목해야 할 점은 영국인에 의해서 만들어졌다는 게 아니라 \"몇 영국인들에 의해 소개되되어 왔다.\"라는 점이라 생각됩니다." },
    { kind: "paragraph", text: "에핑어는 1880년대 초중반에 미국 북서부의 항구도시에서 술집과 레스토랑을 활발하게 운영했는데, '이 영국인들이 여기서 에핑어의 뱀부를 맛보고 다른 도시로 이동해 소개했을까?'하는 상상을 할 수 있게 해주죠." },
    { kind: "paragraph", text: "하지만 결국 이에 대한 더 이상의 기록이나 증거는 없습니다." },
    { kind: "figure", src: "/articles/bamboo/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "어찌 됐건 셰리+버무스의 조합으로 만들어진 뱀부라는 칵테일이 1880년대 중반부터 존재했고, 1890년대~1910년대 사이에 버무스의 종류만 다른 「아도니스」라는 칵테일이 만들어진 것을 보면, 당시 이러한 조합이 새로운 것이 아니었다고도 짐작할 수 있습니다." },
    { kind: "paragraph", text: "그렇다 보니 \"에핑어가 뱀부라는 칵테일의 창작자\"인지 정확히 알 수 없습니다. 그러나 만들어진 시기는 신빙성이 없더라도 적어도 에핑어가 창작했다는 기록이 존재하기 때문에 현재까지도 통설로 여겨지고 있습니다." },
    { kind: "figure", src: "/articles/bamboo/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "45ml 피노 셰리(Fino Sherry)" },
    { kind: "paragraph", text: "15ml 드라이 버무스(Dry Vermouth)" },
    { kind: "paragraph", text: "*1dash 오렌지 비터(Orange Bitters)" },
    { kind: "paragraph", text: "*8~10drops" },
    { kind: "paragraph", text: "아도니스 칵테일처럼 뱀부에도 꽤나 다양한 레시피가 존재합니다. 비율, 셰리의 종류, 비터의 조합을 다르게 한다는 식으로 말이죠." },
    { kind: "paragraph", text: "그렇지만 뱀부라는 칵테일 자체가 일본의 이미지를 떠올리게 하는 칵테일인 만큼 살짝 드라이하고, 깔끔한 맛을 위해서는 피노 셰리를 사용하는 걸 추천드립니다." },
    { kind: "figure", src: "/articles/bamboo/05.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 모든 재료를 믹싱 글라스에 넣는다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채워준다." },
    { kind: "paragraph", text: "3. 스터 후, 잔에 따라준다." },
    { kind: "paragraph", text: "뱀부의 맛" },
    { kind: "paragraph", text: "- 드라이하고, 깔끔하며, 약간은 떫고 약간의 독특한 짠맛" },
    { kind: "paragraph", text: "- 피노 셰리에서 오는 약간의 견과류 캐릭터" },
    { kind: "paragraph", text: "- 버무스에서 오는 약간의 허브와 향신료 캐릭터" },
    { kind: "paragraph", text: "뱀부는 낮은 도수감과 특유의 깔끔함 등으로 인해서 흔히 식전주로 인식되는 칵테일입니다. 일본에서도 잘 알려져 있는 칵테일이지만, 서양 쪽에서도 꽤나 인기 있는 것으로 보입니다." },
  ],
};
