import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "banana-boulevardier",
  category: "cocktail",
  title: "바나나 불바디에 — 진지한 클래식에 얹은 장난스러운 바나나",
  dek: "「바나나 불바디에」는 클래식 칵테일인 불바디에의 간단한 변형으로, 휴스턴의 앤빌 바 & 레퓨지(Anvil Bar & Refuge)에서 2015년 8월에 총괄 매니저였던 테리 윌리엄스(Terry Williams)에 의해 만들어졌다고 합니다.",
  publishedAt: "2025-05-06",
  hero: "/articles/banana-boulevardier/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223856829267",
  relatedCocktailSlugs: ["bananaboulevardier"],
  blocks: [
    { kind: "figure", src: "/articles/banana-boulevardier/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「바나나 불바디에」는 클래식 칵테일인 불바디에의 간단한 변형으로, 휴스턴의 앤빌 바 & 레퓨지(Anvil Bar & Refuge)에서 2015년 8월에 총괄 매니저였던 테리 윌리엄스(Terry Williams)에 의해 만들어졌다고 합니다." },
    { kind: "paragraph", text: "이 칵테일이 만들어지게 된 계기가 꽤 단순한데, 어느 날 윌리엄스는 메뉴 개발 후에 소량 남아있던 바나나 리큐르를 비우고 싶어 했습니다." },
    { kind: "paragraph", text: "그렇게 윌리엄스는 캄파리와 바나나 리큐르를 샷잔에 동률로 섞어서 마셔봤는데, 이게 엄청나게 맛있었다고 합니다. 그 후에 이 조합은 바나나 불바디에를 만들어내게 되었다고." },
    { kind: "figure", src: "/articles/banana-boulevardier/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "30ml 버번 위스키(Bourbon Whiskey)" },
    { kind: "paragraph", text: "15ml 캄파리(Campari)" },
    { kind: "paragraph", text: "15ml *바나나 리큐르(Banana Liqueur)" },
    { kind: "paragraph", text: "30ml 스위트 버무스(Sweet Vermouth)" },
    { kind: "paragraph", text: "*오리지널 레시피에서는 지파드 프리미엄 브라질 바나나 사용" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질, 말린 바나나(옵션)" },
    { kind: "figure", src: "/articles/banana-boulevardier/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 가니시 외의 재료를 락 잔에 넣어준다." },
    { kind: "paragraph", text: "2. 잔에 얼음을 채우고, 스터 해준다." },
    { kind: "paragraph", text: "3. 잔 위로 오렌지 껍질을 짜서 오일을 더해주고," },
    { kind: "paragraph", text: "사용한 껍질과 말린 바나나를 넣어준다." },
    { kind: "figure", src: "/articles/banana-boulevardier/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "바나나 불바디에의 맛" },
    { kind: "paragraph", text: "- 쨍하고 확실한 바나나의 맛" },
    { kind: "paragraph", text: "- 캄파리의 쌉쌀함과 오렌지 캐릭터" },
    { kind: "paragraph", text: "- 버무스의 허브감" },
    { kind: "paragraph", text: "- 중심을 잡아주는 버번의 견과류 캐릭터" },
    { kind: "paragraph", text: "- 마지막에는 바나나맛+버번의 바닐라, 견과류가 혀에 남음" },
    { kind: "paragraph", text: "바나나 불바디에는 개인적으로 꽤나 단맛이 강한 칵테일이었는데, 바나나 리큐르와 캄파리의 비율을 살짝 조정해 주는 게 더 낫다고 생각합니다." },
    { kind: "paragraph", text: "우드포드 리저브에는 좀 풀리고 난 뒤에 바나나 캐릭터가 다른 버번에 비해 강하다고 생각하는데, 이 칵테일의 기주로 쓰니 꽤 만족스러웠습니다." },
    { kind: "paragraph", text: "전체적으로 아주 간단한 변형이기는 하지만, 쉽게 생각하기 어렵고 재미있는 조합의 칵테일이라 생각됩니다." },
    { kind: "paragraph", text: "바나나의 캐릭터가 캄파리의 캐릭터와도 꽤 재밌는 조화를 이룬다는 생각이 들고, 기주를 버번이 아니라 오버프루프 자메이칸 럼으로 만들면 아주 펑키하고 재밌는 네그로니 변형이 되지 않을까도 싶습니다." },
  ],
};
