import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bar-barns",
  category: "bar",
  title: "바 반즈 — 히노키에 담긴 진토닉",
  dek: "나고야 후시미의 지하, 타베로그 4점대의 바. 편백나무 마스에 서브되는 진토닉이 첫 모금부터 다른 얼굴을 보여준다.",
  publishedAt: "2025-08-23",
  hero: "/articles/bar-barns/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223980767545",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bar-barns/00.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/bar-barns/01.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "「반즈」는 나고야 후시미역과 사카에역 사이에 있는 한 빌딩의 지하에 위치한 바로, 특이하게 타베로그에서 4점대를 넘기고 있는 바입니다. 타베로그에서 바가 4점대인 경우는 흔치 않은데 말이죠." },
    { kind: "paragraph", text: "4점대의 점수에 걸맞게 예약이 꽉 차있는데, 방문 전에 예약을 하고 방문하던가, 아예 저처럼 오픈하자마자 방문해서 뒷 시간대의 예약시간까지 1~2시간 즐기는 걸 추천드립니다." },
    { kind: "paragraph", text: "바를 방문하면 메뉴판은 딱히 없는 것 같고, 먼저 물 수건을 건네준 다음 꽤나 빠르게 주문을 받습니다." },
    { kind: "quote", text: "급작스럽긴 하지만," },
    { kind: "quote", text: "첫 잔은 어떻게 준비해 드릴까요?" },
    { kind: "figure", src: "/articles/bar-barns/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/bar-barns/03.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-barns/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "사실 이 바를 찾은 이유는 반즈만의 독특한 진 토닉 때문입니다. 반즈에서는 진 토닉을 히노키(편백나무)로 만든 마스(되)에 서브해 주는데, 이로 인해서 칵테일에 나무의 특성이 자연스럽게 스며듭니다." },
    { kind: "paragraph", text: "히노키의 캐릭터가 진 토닉에 배어 나오게 되면서 아주아주 복잡한 캐릭터를 만들어내게 되는데, 글로 잘 표현하기가 정말 어렵네요." },
    { kind: "paragraph", text: "마시다가 유자소금을 올려서 같이 마시는 걸 얘기해 주셨는데, 이건 개인적으로 굳이 싶기는 했습니다. 아마 이 칵테일의 첫 모금에 꽤나 충격을 받아서 그러지 않았을까 싶네요." },
    { kind: "figure", src: "/articles/bar-barns/05.webp", width: 966, height: 1289 },
    { kind: "figure", src: "/articles/bar-barns/06.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "친구는 메뉴에 있던 오오바(청차조기 잎)를 사용한 칵테일을 추천받았는데,  달콤 상큼하고, 꽤나 자극적인 칵테일로 이것도 정말 맛있게 마셨습니다." },
    { kind: "paragraph", text: "듣기로는 어떤 손님이 이 칵테일이 맛있어서 9잔을 연거푸 마셨고, 그게 최고 기록이라고 하던데,  개인적으로 납득이 되는 맛이었습니다." },
    { kind: "paragraph", text: "정확히 기억은 안 나는데, 온천 근처에서 만들어진 오오바를 사용한 진에 홈메이드 오오바 리큐르를 사용한다고 했던 것 같습니다." },
    { kind: "figure", src: "/articles/bar-barns/07.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "다음으로는 사이드카를 주문했는데, 코앵트로는 못 봤지만 기주인 레미 마틴은 올드보틀로 만들어주셨습니다. 맛은 생각했던 레미 마틴 올드보틀로 만든 사이드카 그대로." },
    { kind: "paragraph", text: "이 사이드카에서 가장 마음에 들었던 게 바로 잔이었는데, 세라믹 잔으로 기주인 꼬냑의 원재료인 포도가 그려져 있는 것이 아주 멋진 센스라 생각됐습니다." },
    { kind: "figure", src: "/articles/bar-barns/08.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-barns/09.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "반즈는 칵테일도 아주 훌륭하지만, 위스키 종류도 아주 훌륭합니다. 특히, 반즈에서 픽한 독립병입 위스키들이 있는데, 가격은 꽤 나가는 편이지만 맛 자체는 훌륭하다고 생각됩니다." },
    { kind: "paragraph", text: "왼쪽의 보틀이 반즈 픽의 쿨리인데, 아무래도 거의 막바지인데다가 아이리시 위스키이다 보니 점잖은 면은 있지만, 꽤나 섬세하고, 거의 라벨 그대로의 캐릭터를 가지고 있습니다. 개인적으로 많이 느낀 건 딸기의 캐릭터." },
    { kind: "paragraph", text: "오른쪽은 도쿄에 있는 '아일라'라는 바를 위해 병입된 스프링뱅크인데, 개인적으로 고숙성 스프링뱅크를 선호하지 않아서 크게 와닿지는 않았습니다. 단순히 생년 빈티지+바 이름 때문에 마신 기억이..." },
    { kind: "figure", src: "/articles/bar-barns/10.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "반즈는 바텐더분들이 아주아주 젠틀하시고, 특이하게 칵테일을 찍을 때마다 라이트를 비춰주는 점이 재미있으며, 칵테일이 정말 정말 맛있습니다." },
    { kind: "paragraph", text: "개인적으로 타베로그에서의 바의 평점은 믿지 않는 편인데, 이곳의 평점이 4점대인 걸 납득할 수 있었습니다." },
    { kind: "paragraph", text: "나고야를 가게 된다면 한 번쯤은 방문하시는 걸 강력하게 추천드리고, 인기가 아주 많으니 예약 또는 방문 전 자리가 있는지 문의는 필수일 것 같습니다." },
  ],
};
