import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bar-heart-strings",
  category: "bar",
  title: "하트 스트링스 — 후쿠오카의 재패니즈 클래식 바",
  dek: "\"하트 스트링스(Heart Strings)\"는 후쿠오카 나카스의 한 빌딩 5층에 위치한 바로, 딱 재패니즈 클래식 바라 할 수 있는 바입니다.",
  publishedAt: "2024-07-13",
  hero: "/articles/bar-heart-strings/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223511440055",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bar-heart-strings/00.webp", width: 966, height: 1718 },
    { kind: "figure", src: "/articles/bar-heart-strings/01.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "\"하트 스트링스(Heart Strings)\"는 후쿠오카 나카스의 한 빌딩 5층에 위치한 바로, 딱 재패니즈 클래식 바라 할 수 있는 바입니다." },
    { kind: "paragraph", text: "이곳의 오너 바텐더인 '하시모토 코지'님은 약 40년 경력의 후쿠오카 내에서도 오래된 경력의 바텐더이며, '하트 스트링스'는 1994년 오픈하여 올해로 30년이 되는 노포입니다." },
    { kind: "figure", src: "/articles/bar-heart-strings/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-heart-strings/03.webp", width: 966, height: 1288, caption: "오너 바텐더의 메이킹 / 뉴욕(New York) /                    잭로즈 하이볼(Jack Rose Highball)" },
    { kind: "paragraph", text: "'하트 스트링스'에서 마신 칵테일 중 가장 인상적인 것은 '뉴욕(New York)'이었습니다. 짐빔 화이트와 메이지야의 그레나딘을 사용하는데, 짐빔 화이트의 아몬드 같은 견과류의 맛과 확실한 달달한 석류 맛을 내는 그레나딘이 상큼하게 다가오는 게 아주아주 만족스러웠습니다." },
    { kind: "paragraph", text: "'그레나딘은 수제를 사용해야 칵테일에서 제일 맛있다.'라는 제 생각을 완전히 깨주는 한 잔이었고, 짐빔 화이트의 의외의 장점을 볼 수 있었습니다." },
    { kind: "paragraph", text: "오너 '하시모토'님은 본인의 바텐더 경력에서 가장 많이 만든 칵테일이 '뉴욕(New York)'이라 하니, 꼭 한 번 주문하는 걸 추천드립니다." },
    { kind: "paragraph", text: "그레나딘과 뉴욕 칵테일에 대해 이런저런 얘기를 하다보니, 오너로부터 매장에서 사용하는 메이지야의 그레나딘 시럽을 한 병 선물로 받게 되었습니다(감사히 잘 쓰겠습니다!!)." },
    { kind: "figure", src: "/articles/bar-heart-strings/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-heart-strings/05.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "일본에서는 올드패션드를 일반적으로 시트러스, 체리, 각설탕을 그대로 서브해주고, 손님이 직접 쇠 머들러로 으깨는 정도를 조절할 수 있게 하는데, 이곳은 또 다르게 레몬, 오렌지, 체리를 먼저 머들링하고나서 스터한 후 서브를 합니다. 아주 주시한 게 또다른 매력이 있는 올드패션드였습니다." },
    { kind: "paragraph", text: "진토닉 같은 경우에는 일본에서 흔하게 사용되는 슈웹스 토닉이 아닌, 캐나다 드라이의 토닉 워터를 사용합니다. 이에 대해 오너인 '하시모토'님은 이런저런 토닉 워터를 비교해서 맛본 적이 있는데, 본인에게도 충격이었던 것이 캐나다 드라이가 가장 맛있었다고 합니다." },
    { kind: "figure", src: "/articles/bar-heart-strings/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-heart-strings/07.webp", width: 966, height: 1288, caption: "아일라 바이올렛(Islay Violets) / 타케츠루 퓨어몰트 17년" },
    { kind: "paragraph", text: "'하트 스트링스'는 물론 칵테일도 다양하나, 위스키도 다양한 종류가 있으며, 특히 재패니즈 위스키 라인업이 꽤 갖춰져있다는 인상을 받았습니다." },
    { kind: "paragraph", text: "개인적으로 재패니즈 중에서는 하쿠슈를 좋아하는데, 하쿠슈 18년이 있는 바는 아주 오랜만입니다. 물론 비싸기도 하고, 오너가 굳이 마실 필요 없다고도 해서 마시진 않았습니다." },
    { kind: "paragraph", text: "아일라 바이올렛(Islay Violets) 33년은 독립병입자에서 출시한 보모어(Bowmore)로, 아주 플로럴하고, 은은한 피트가 더해진 꽤나 우아한 한 잔이었습니다. 보모어를 좋아하신다면 당연히 마셔봐야 할 한 잔이며, 정확한 가격은 기억이 안나지만 그렇게 비싸지 않았던 것 같습니다." },
    { kind: "paragraph", text: "타케츠루 퓨어몰트 17년은 두 번째 방문에서 마지막 잔으로 오너가 선물로 주셨습니다. 지금 구하기 힘든데 어렵게 구했다면서 한 잔 주셨는데, 겨우 두 번째 방문에서 이렇게까지 챙겨주셔서 정말 감사했습니다. 꽤 취할 즈음이어서 맛이 세세하게 기억나지는 않았지만 정말 맛있게 마신 기억이 남아있네요." },
    { kind: "paragraph", text: "'하트 스트링스'는 재패니즈 클래식 바를 경험하고 싶은 분들에게 강력하게 추천드리며, 위스키 라인도 다양하게 갖춰져 있으니 위스키를 주로 드시는 분들에게도 추천드리고 싶은 곳입니다." },
  ],
};
