import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bar-rummy",
  category: "bar",
  title: "러미 — 럼을 좋아하세요?",
  dek: "\"러미(Rummy)\"는 후쿠오카의 와타나베도리역과 야쿠인역 근처에 위치한 바로, 전 세계의 럼(Rum/Rhum/Ron)을 전문으로 하는 바입니다.",
  publishedAt: "2024-07-19",
  hero: "/articles/bar-rummy/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223518285590",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bar-rummy/00.webp", width: 966, height: 1288, caption: "럼주란 뭘까?" },
    { kind: "paragraph", text: "\"러미(Rummy)\"는 후쿠오카의 와타나베도리역과 야쿠인역 근처에 위치한 바로, 전 세계의 럼(Rum/Rhum/Ron)을 전문으로 하는 바입니다. 나카스의 마두로(Bar Maduro)와 함께 일본 내에서도 마니악한 카테고리의 럼을 전문으로 하는 바입니다." },
    { kind: "figure", src: "/articles/bar-rummy/01.webp", width: 966, height: 1288, caption: "모히또(Mojito)" },
    { kind: "paragraph", text: "럼 전문 바이긴 하지만 당연히 칵테일도 가능합니다. 저는 날씨가 너무 더워서 모히또를 첫 잔으로 마셨는데, 럼을 재료로 하는 칵테일만 가능한 건지, 다른 기주의 칵테일도 가능한지까지는 모르겠네요." },
    { kind: "figure", src: "/articles/bar-rummy/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-rummy/03.webp", width: 966, height: 1288, caption: "Caroni 1997 / Uitvlugt Guyana 1995" },
    { kind: "paragraph", text: "첫 잔으로는 오기 전부터 신경쓰였던 카로니 1997을 마셨습니다. 이 바틀은 이제는 폐쇄된 트리니다드의 카로니(Caroni) 증류소의 럼으로, 일본의 주류판매점인 시나노야의 도움으로 럼 전문 바인 '러미', '바 럼 & 위스키(Bar Rum & Whisky/교토)'와 '바 램프(Bar Lamp/도쿄 긴자)'에 의해 병입된 것으로 보입니다." },
    { kind: "paragraph", text: "카로니 1997은 가볍지도, 그렇다고 그렇게 묵직하지도 않지만 도수감(62%)에서 오는 강렬함이 가장 기억에 남습니다. 다만, 제가 딱 좋아하는 캐릭터가 아닌데다가 다양한 럼을 접해보지 못한 저로서는 조금은 어려운 바틀이었습니다." },
    { kind: "paragraph", text: "다음으로 데메라라 럼을 추천해달라고 부탁드렸는데, 아이플럭트 가이아나 1995를 추천해주셨습니다. 아마 독립병입자에서 낸 제품인 것 같은데, 제가 럼에 대해서는 아직 잘 몰라서 정확히는 모르겠습니다." },
    { kind: "paragraph", text: "이 럼은 21년 숙성되었으나, 숙성감은 그렇게 느껴지지 않고, 어딘가 그라빠(Grappa)나 마르(Marc) 같은 느낌을 받았는데, 이건 카로니 1997보다 더 이해하기 어려운 바틀이었습니다." },
    { kind: "figure", src: "/articles/bar-rummy/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/bar-rummy/05.webp", width: 966, height: 1288, caption: "Cadenhead's Alcoholes Finos Dominicanos 11yo / Compagnie Des Indes Jamaca 12 ans" },
    { kind: "paragraph", text: "다음으로 부탁드린 건 도미니카 럼이었습니다. 여기서부터는 아주 묵직하고 직관적인 단맛이 느껴지는 것이 제 취향에 딱 맞았네요." },
    { kind: "paragraph", text: "'예전에 한국에서 달지 않은 도미니칸 럼을 마신적이 있는데, 좋은 기억은 아니다!'라고 불평하니, 오너가 '도미니카 럼에서도 달지 않은 게 있긴 한데...정말 드문 경우이긴 하다.'고 하신 게 기억에 남네요." },
    { kind: "paragraph", text: "마지막으로 '펑키함의 극치'와 같은 럼을 부탁드리니 콤파니 데산드(Compagnie Des Indes)라는 독립병입자의 자메이카 럼을 추천해주셨습니다." },
    { kind: "paragraph", text: "펑키한 럼을 좋아하신다면 이건 꼭 드셔보는 걸 추천드리는데, 정말정말 맛있었습니다. 도수감은 느껴지지도 않고, 정말 다채로운 캐릭터의 럼입니다." },
    { kind: "figure", src: "/articles/bar-rummy/06.webp", width: 966, height: 1288, caption: "Arcabuz" },
    { kind: "paragraph", text: "중간에 옆에 앉았던 단골 손님이 주신 럼도 맛있게 마셨는데, 알카버즈(Arcabuz)라는 일본에서 만들어지는 럼이라 합니다. 최근 일본에서도 많은 럼이 만들어지고 있는데, 이건 그 중에 특이하게도 럼 아그리꼴(Rhum Agricole) 스타일로 만든 제품입니다." },
    { kind: "paragraph", text: "제가 마셨던 7월 10일 기준으로, 그 전주에 병입되어 판매된 블랑(Blanc-White)급으로 아직 숙성이 되지 않았다고 합니다." },
    { kind: "paragraph", text: "정말 확실하게 럼 아그리꼴의 그 쿰쿰한 느낌이 나는데, 솔직히 꽤 맛있어서 놀랐습니다. 단골 손님과 오너는 일본 쇼츄에서 나는 특유의 캐릭터가 난다고 하기도 했습니다. 나중에 숙성된 걸 가지고 나올 때가 또 기대되네요." },
    { kind: "paragraph", text: "'러미'는 오너 바텐더 혼자 운영하는 곳으로, 응대가 그렇게 살갑지는 않고, 단골이 많아 단골을 주로 챙기려는 성향이 있는 것 같습니다. 저는 일본어 회화가 가능했고, 다른 단골 손님과 얘기를 하다보니 같이 오너와도 이런저런 얘기를 했었습니다." },
    { kind: "paragraph", text: "일본어가 유창하지 않다면 약간은 뻘쭘하게 있을 수도 있을 것 같고, 내부 흡연이 가능하니 이 점 참고해서 방문해주시기 바랍니다. 다만, 럼이라는 카테고리를 경험하고 싶다, 이미 좋아한다! 하시는 분들에게는 꼭 추천드리고 싶네요." },
  ],
};
