import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "barcelona-paradiso",
  category: "bar",
  title: "파라디소",
  dek: "\"파라디소(Paradiso)\"는 2015년 바르셀로나 대성당과 바르셀로네타 해변 근처에 오픈한 바로, 2023년까지 The World's Best Bars 50(월드 베스트 바)에 6번 선정되었으며, 2022년에는 1위에 이름을 올렸습니다.",
  publishedAt: "2024-07-06",
  hero: "/articles/barcelona-paradiso/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223503460517",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/barcelona-paradiso/00.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/barcelona-paradiso/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/barcelona-paradiso/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "\"파라디소(Paradiso)\"는 2015년 바르셀로나 대성당과 바르셀로네타 해변 근처에 오픈한 바로, 2023년까지 The World's Best Bars 50(월드 베스트 바)에 6번 선정되었으며, 2022년에는 1위에 이름을 올렸습니다." },
    { kind: "paragraph", text: "겉으로는 파스트라미 가게처럼 보이지만, 가게 내부의 냉장고 문을 열면 바로 들어갈 수 있는 스피크이지(Speakeasy) 스타일의 바입니다." },
    { kind: "paragraph", text: "파라디소는 창의적이고 비주얼적으로 아름다운 칵테일을 만들며, 시그니처 칵테일마다 멋진 가니시와 퍼포먼스까지 갖추고 있는 바로, 확실히 보는 재미가 있는 칵테일을 제공하며, 심상치 않은 형광 메뉴부터 이 바의 성격을 엿볼 수 있습니다." },
    { kind: "figure", src: "/articles/barcelona-paradiso/03.webp", width: 966, height: 1287 },
    { kind: "figure", src: "/articles/barcelona-paradiso/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/barcelona-paradiso/05.webp", width: 966, height: 966, caption: "Great Gatsby / The Cloud" },
    { kind: "paragraph", text: "\"위대한 개츠비(Great Gatsby)\"는 기본적으로 올드패션드 칵테일의 구조로, '맥캘란 12년 더블캐스크'를 기주로 하는 칵테일입니다. 그 외에 트러플, 꿀, 아마로, 라벤더 에센스 등이 들어가며, 훈연을 한 번 해주는 칵테일입니다." },
    { kind: "paragraph", text: "사실 개인적인 감상으로는 '맥캘란 12년 더블캐스크를 쓴 올드패션드'가 끝입니다. 그렇게 특별하지는 않은.....다만 '맥캘란 12년 더블캐스크'로 만드는 올드패션드를 마셔볼 일이 없으니, 하나의 경험으로 볼 수 있겠네요." },
    { kind: "paragraph", text: "\"구름(The Cloud)\"이라는 칵테일은 메즈칼, 히비스커스, 아마로 몬테네그로, 버무스, 탄산 등이 들어가는 어딘가 아메리카노 칵테일스러운 느낌이 있네요." },
    { kind: "paragraph", text: "메이킹 후 잔 위에 커피 거품을 올려 마무리하는 칵테일입니다. 먼저 음료를 준비해주고, 커피 거품을 만들어서 직접 올려주는데, 시각적인 재미 하나는 확실하네요." },
    { kind: "figure", src: "/articles/barcelona-paradiso/06.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/barcelona-paradiso/07.webp", width: 966, height: 966, caption: "Ramses / Supercool Martini" },
    { kind: "paragraph", text: "\"람세스(Ramses)\"는 로쿠 진(Roku Gin), 듀어스 12년, 홉(hop) 버무스, 와인 코디얼, 아마로 등이 들어가는 달콤상큼한 캐릭터의 칵테일입니다." },
    { kind: "paragraph", text: "이름에서 볼 수 있듯이 이집트와 관련된 가니시를 한 것이 특징인데, 잔을 들어보면 그 안에 미이라의 관 형태의 초콜릿이 들어있는, 아주 센스 넘치는 칵테일입니다." },
    { kind: "paragraph", text: "\"과냉각 마티니(Supercool Martini)\"는 클래식 마티니에 과냉각이라는 기술을 더한 칵테일입니다. 과냉각한 물을 따르는 순간 물이 샤베트처럼 얼어붙고, 여기에 버무스를 뿌리고, 파라디소에서 재증류한 아주 차가운 진을 넣은 다음, 올리브를 꽂은 픽으로 얼음을 녹여줘 다일루션을 주는 형식입니다." },
    { kind: "paragraph", text: "마티니를 만드는 과정을 재해석한 것이라 할 수 있으며, 이렇게 만드는 이유는 아주 차가운 마티니를 만들기 위해서라고 합니다." },
    { kind: "paragraph", text: "파라디소는 다양한 재료와 기법으로 아주 창의적인 가니시와 퍼포먼스로 눈을 즐겁게 해주는 경험을 주는 바입니다. 저도 개인적으로 이렇게까지 시각적으로 즐거운 바는 처음이었습니다." },
    { kind: "paragraph", text: "물론 칵테일은 맛도 중요하긴 하지만 시각적인 부분과 그 공간이 주는 분위기의 영향을 많이 받기도 합니다. 제가 마셨던 칵테일들은 특정 재료의 맛이 좀 튀는 경향이 있었는데, 그렇다고 맛이 없었다는 건 아니고, 이건 믹솔로지 성향의 칵테일 바라면 어쩔 수 없는 부분이라 생각합니다." },
    { kind: "paragraph", text: "오픈 시에 방문하는 걸 추천드리는데, 조금만 시간이 지나면 웨이팅이 꽤 많이 늘어납니다. 저는 오픈한지 얼마 안돼서 갔는데, 친구와 30~40분 정도 기다리다가 들어갔네요." },
    { kind: "paragraph", text: "아무래도 밤이 깊어질수록 바를 찾는 사람들이 많아지니 웨이팅은 더 길어질 수 있으니 이른 시간 방문하는 걸 추천드립니다." },
  ],
};
