import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "beer-americano",
  category: "cocktail",
  title: "비어 아메리카노 — 맥주로 더한, 산뜻하고 폭신한 아메리카노의 변형",
  dek: "「비어 아메리카노」는 이름에서도 알 수 있듯이 클래식 칵테일 중 하나인 아메리카노에 맥주라는 요소를 더한 칵테일로, 약 10년 전에 밀라노의 Cafe Trussardi에서 토마소 세카(Tommaso Cecca)라는 바텐더에 의해 만들어졌다고 합니다.",
  publishedAt: "2026-04-30",
  hero: "/articles/beer-americano/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224270366931",
  relatedCocktailSlugs: ["beeramericano"],
  blocks: [
    { kind: "figure", src: "/articles/beer-americano/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「비어 아메리카노」는 이름에서도 알 수 있듯이 클래식 칵테일 중 하나인 아메리카노에 맥주라는 요소를 더한 칵테일로, 약 10년 전에 밀라노의 Cafe Trussardi에서 토마소 세카(Tommaso Cecca)라는 바텐더에 의해 만들어졌다고 합니다." },
    { kind: "paragraph", text: "기본적으로 아메리카노에서 탄산수를 맥주로 바꾼 것인데, 사실 단순히 캄파리+버무스에 맥주를 넣는다던가, 맥주에 캄파리를 소량 넣어서 마시는 방식은 이전부터 꽤 있었어서 식상해 보일 수도 있습니다." },
    { kind: "paragraph", text: "다만, 토마소 세카는 하나의 변형을 주는데, 바로 맥주를 휘핑해서 실질적으로 거품을 넣는다는 것으로, 이 칵테일의 특별함이 여기에 있습니다." },
    { kind: "paragraph", text: "맥주하면 청량한 탄산감을 생각하게 되는 게 당연합니다. 그러나 여기서는 맥주를 휘핑해 거품을 내서 칵테일에 넣어주는데, 칵테일에 폭신폭신한 질감을 더해주게 됩니다." },
    { kind: "paragraph", text: "기존의 클래식한 아메리카노가 캄파리와 스윗 버무스에 탄산수를 더해 쓴 맛을 비교적 가볍고 청량하게 즐길 수 있는 칵테일이라면, 비어 아메리카노는 폭신한 질감과 맥주의 풍미로 보다 부드럽고 무게감은 잃지 않게 즐길 수 있는 칵테일이라 할 수 있습니다." },
    { kind: "figure", src: "/articles/beer-americano/01.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/beer-americano/02.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "Ingredietns" },
    { kind: "paragraph", text: "30ml 캄파리 (Campari)" },
    { kind: "paragraph", text: "30ml 스윗 버무스 (Sweet Vermouth)" },
    { kind: "paragraph", text: "맥주(가급적 가볍고 깔끔한 느낌)" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질 또는 휠" },
    { kind: "figure", src: "/articles/beer-americano/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/beer-americano/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/beer-americano/05.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 얼음을 채운 하이볼 잔에 맥주 외의 재료를 넣고, 스터한다." },
    { kind: "paragraph", text: "2. 맥주를 휘핑해서 거품을 만들어준다." },
    { kind: "paragraph", text: "3. 커품을 잔에 따라준다." },
    { kind: "paragraph", text: "4. 바스푼으로 잘 섞어준다." },
    { kind: "paragraph", text: "5. 오렌지 웨지로 가니시한다." },
    { kind: "paragraph", text: "맥주라는 요소가 들어간 것치고 생각보다 쓴맛이 안나고, 오히려 들큰하면서도 산뜻하며, 폭신폭신한 질감이 상당히 매력적인 칵테일입니다." },
    { kind: "paragraph", text: "어떤 맥주가 오리지널 레시피에 쓰였는지는 모르겠으나, 대부분 가벼운 캐릭터의 라거를 사용하라고 설명하고 있습니다." },
    { kind: "paragraph", text: "아메리카노라는 칵테일의 변형인데다가 맥주까지 들어가기 때문에 재료만 보면 탄산을 기대하게 되지만, 맥주를 휘핑해 거의 거품을 더해주는 것이기 때문에 탄산은 없고, 폭신한 느낌이 더해집니다." },
    { kind: "paragraph", text: "캄파리의 쓴맛을 꽤나 가려주면서도, 그 쌉쌀들큰한 캐릭터가 산뜻하게 다가오니 캄파리를 싫어하시는 분들이라도 가볍게 마실 수 있을 것 같네요." },
    { kind: "paragraph", text: "정말 기분 좋은 식전주로 어울리고, 봄 또는 가을에 마시면 가장 좋을 것 같습니다." },
  ],
};
