import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "belle-aile",
  category: "cocktail",
  title: "벨 에르 — 산토리 칵테일 어워드 1996 대회 우승작",
  dek: "\"벨 에르\"는 1996년 산토리 칵테일 어워드 대회 우승작으로, 당시 오사카에 위치한 바 알폰테(Bar Alponte)에서 근무하던 일본의 후지타 토시아키 바텐더가 만들어낸 칵테일입니다.",
  publishedAt: "2024-09-05",
  hero: "/articles/belle-aile/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223573457961",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/belle-aile/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"벨 에르\"는 1996년 산토리 칵테일 어워드 대회 우승작으로, 당시 오사카에 위치한 바 알폰테(Bar Alponte)에서 근무하던 일본의 후지타 토시아키 바텐더가 만들어낸 칵테일입니다." },
    { kind: "paragraph", text: "후지타 토시아키씨는 1997년에는 독립을 하여 오사카의 우메다에 하버 인(Bar Habour Inn)이라는 바를 차리게 되며, 현재에도 바의 메뉴에 한 자리를 차지하고 있다고 합니다." },
    { kind: "paragraph", text: "하버 인이라는 이름은 아일라섬의 도시 보모어에서 보모어 증류소 근처에 있는 숙소인 하버 인(Harbour Inn)에서 이름을 따온 것으로, 후지타씨가 아일라 여행을 할 때 묵은 숙소라 합니다." },
    { kind: "paragraph", text: "칵테일의 이름인 \"벨 에르 (Belle Aile)\"라는 단어는 프랑스어로, \"아름다운 날개\"라는 의미라 합니다." },
    { kind: "figure", src: "/articles/belle-aile/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml  VSOP급 꼬냑 (Cognac VSOP)" },
    { kind: "paragraph", text: "20ml 크렘 드 피치 (Creme de Peche)" },
    { kind: "paragraph", text: "10ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "5ml 블루 큐라소 (Blue Curacao)" },
    { kind: "figure", src: "/articles/belle-aile/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 셰이커에 모든 재료를 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹해줍니다." },
    { kind: "paragraph", text: "3. 차게 해둔 잔에 따라줍니다." },
    { kind: "paragraph", text: "벨 에르는 꼬냑, 크렘 드 피치, 블루큐라소, 레몬이라는 좀처럼 보기 드문 조합의 칵테일로, 재료 조합이나 색깔이나 어딘가모르게 킹스 밸리(King's Valley)를 떠오르게 하기도 합니다." },
    { kind: "paragraph", text: "맛은 꽤나 달달한 편인데, 꼬냑과 복숭아, 시트러스의 캐릭터가 아주 잘 어울리며, 이 맛들이 어우러지면서 약간은 리치 같은 캐릭터로도 느껴집니다. 약간 과일맛이 들어간 플레이버드 티 같기도 하네요." },
    { kind: "paragraph", text: "도수 자체는 그렇게 낮은 편은 아님에도 술을 잘 못마시는 사람들에게 추천하고 싶습니다." },
    { kind: "paragraph", text: "원 레시피는 꼬냑을 크루보아제(Courvoisier)를 사용했는데, 개인적으로 헤네시 VSOP는 우디함이 강한 편이라 어울리지 않는다고 생각됩니다." },
    { kind: "paragraph", text: "피치 리큐르의 경우도 원래는 다른 브랜드를 사용하는데, 피치트리를 사용하는 경우에는 레시피 조정이 필요해보입니다." },
  ],
};
