import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "between-the-sheets",
  category: "cocktail",
  title: "비트윈 더 시츠 — 관능적인 이름과 그렇지 못한 맛",
  dek: "'비트윈 더 시츠'는 1920~1930년대에 파리의 해리스 뉴욕 바(Harry's New York Bar)에서 해리 맥켈혼(Harry MacElhone)에 의해서 만들어졌다는 설이 가장 많이 알려져 있습니다.",
  publishedAt: "2024-11-16",
  hero: "/articles/between-the-sheets/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223662864531",
  relatedCocktailSlugs: ["betweenthesheets"],
  blocks: [
    { kind: "figure", src: "/articles/between-the-sheets/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "'비트윈 더 시츠'는 1920~1930년대에 파리의 해리스 뉴욕 바(Harry's New York Bar)에서 해리 맥켈혼(Harry MacElhone)에 의해서 만들어졌다는 설이 가장 많이 알려져 있습니다." },
    { kind: "paragraph", text: "다만, 1921년에 런던의 버클리 호텔(Berkeley Hotel)에서 매니저였던 폴리(Mr.Polly)에 의해서 만들어졌다는 설도 있으며, 해리 맥켈혼의 저서에서 실린 칵테일 중에서도 그가 만든 것이 아니지만 마치 그가 만들었다는 듯이 잘못 알려지는 경우도 다수 있어서 확실하지는 않습니다." },
    { kind: "paragraph", text: "비트윈 더 시츠는 사이드카(Sidecar)의 변형으로 여겨지고 있으며, 실제로 사이드카에서 꼬냑의 양을 줄이고 그만큼 럼을 기주로 추가한 구조입니다." },
    { kind: "paragraph", text: "다만, 어떠한 럼을 사용하느냐에 따라서 색과 맛이 달라지게 되며, 레시피도 꽤나 다양하게 있습니다. 이건 사실 원래 레시피로 하면 너무 맛이 없어서 그런... 예..." },
    { kind: "paragraph", text: "이름 자체는 '침대 안에서'이라는 뜻으로 관능적인 이름이며, 이름대로 나이트캡으로 마시는 칵테일이라고 합니다. 그렇지만 사실 이런 신맛의 칵테일은 나이트캡으로 잘 마시지 않는 걸 감안하면 이름 때문에 나이트캡 칵테일이라 하는 것 같습니다." },
    { kind: "figure", src: "/articles/between-the-sheets/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "22.5ml 꼬냑 (VSOP Cognac)" },
    { kind: "paragraph", text: "22.5ml 화이트럼 (White Rum)" },
    { kind: "paragraph", text: "20ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "15ml 코앵트로 (Cointreau or Orange Curacao)" },
    { kind: "paragraph", text: "*이 레시피는 오리지널 레시피가 아니라 제가 조정한 레시피입니다." },
    { kind: "paragraph", text: "**취향에 따라 숙성된 럼을 사용해도 무방합니다." },
    { kind: "figure", src: "/articles/between-the-sheets/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹합니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 잔에 부어줍니다." },
    { kind: "paragraph", text: "비트윈 더 시츠는 원형인 사이드카보다 오렌지 맛이나 알코올에서 오는 단맛이 좀 더 강하게 나는 칵테일이며, 다만 사이드카보다는 당연히 복합성 자체는 꽤나 많이 떨어집니다." },
    { kind: "paragraph", text: "저 같은 경우는 오리지널 레시피보다 레몬즙을 꽤 많이 넣는 편인데, 오리지널 레시피는 알코올감이 너무 강해서 레몬즙을 좀 많이 넣게 됐습니다." },
    { kind: "paragraph", text: "사이드카의 못난 형제 같은 느낌으로, 솔직히 왜 마시는지는 잘 모르겠는... 저한테는 그런 느낌의 칵테일입니다." },
  ],
};
