import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "big-peat-the-smokehouse-edition-feis-ile-2023",
  category: "spirits",
  title: "빅 피트 스모크하우스 에디션 페스 아일 2023",
  dek: "'빅 피트'는 독립병입자인 더글라스 랭(Douglas Laing)에서 출시하는 지역 몰트 위스키 중 하나로 아일라 지역의 싱글 몰트 위스키를 블렌딩한 블렌디드 몰트 위스키입니다.",
  publishedAt: "2024-10-02",
  hero: "/articles/big-peat-the-smokehouse-edition-feis-ile-2023/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223604449606",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/big-peat-the-smokehouse-edition-feis-ile-2023/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "'빅 피트'는 독립병입자인 더글라스 랭(Douglas Laing)에서 출시하는 지역 몰트 위스키 중 하나로 아일라 지역의 싱글 몰트 위스키를 블렌딩한 블렌디드 몰트 위스키입니다." },
    { kind: "paragraph", text: "빅 피트에 사용되는 키 몰트로는 아일라 지역의 쿨일라(Caol Ila), 아드벡(Ardbeg), 보모어(Bowmore) 및 최근 재개장한 포트 엘런(Port Ellen)이 있습니다." },
    { kind: "paragraph", text: "그 중에서 '스모크하우스 에디션'은 매년 5월 마지막 주에 아일라(Islay) 섬과 주라(Jura) 섬에서 약 1~2주간에 걸친 위스키 관련 축제인 페스 아일(Feis Ile)을 기념하기 위해 2023년 페스 아일에 출시한 제품입니다." },
    { kind: "paragraph", text: "특징으로는 빅피트 시리즈 중 최초로 레드 와인 캐스크로 피니시를 했다는 점입니다." },
    { kind: "figure", src: "/articles/big-peat-the-smokehouse-edition-feis-ile-2023/01.webp", width: 966, height: 1288 },
    { kind: "quote", text: "병입자: 더글라스 랭" },
    { kind: "quote", text: "위스키 타입: 블렌디드 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 레드 와인 캐스크 피니시 / NAS" },
    { kind: "quote", text: "도수: 48%" },
    { kind: "quote", text: "시리즈: 페스 아일(Feis Ile)" },
    { kind: "figure", src: "/articles/big-peat-the-smokehouse-edition-feis-ile-2023/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 왁시하고 살짝 쌉쌀한 피트감, 어씨함(Earthy)" },
    { kind: "paragraph", text: "- 곡식의 달달함과 살짝의 베이컨" },
    { kind: "paragraph", text: "- 탄 것 같은 캬라멜" },
    { kind: "paragraph", text: "- 스쳐지나가는 버터리함과 솔티함" },
    { kind: "paragraph", text: "- 바닐라, 약간의 베리 같은 캐릭터" },
    { kind: "paragraph", text: "- 쿨일라스러운 피트감이 지배적으로 느껴짐" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 왁시함, 달달한 곡식" },
    { kind: "paragraph", text: "- 짭짤하고 쌉쌀함" },
    { kind: "paragraph", text: "- 쓴맛이 꽤나 많이 나는 편" },
    { kind: "paragraph", text: "- 태운 나무나 숯 같은 캐릭터" },
    { kind: "paragraph", text: "- 후추" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "- 생각보다 길고 풍부한 피니시" },
    { kind: "paragraph", text: "- 다크 초콜릿" },
    { kind: "paragraph", text: "- 쌉쌀함, 후추의 캐릭터" },
    { kind: "paragraph", text: "레드 와인 캐스크의 캐릭터는 꽤나 약하게 스쳐지나가서 솔직히 와인 캐스크의 장점이 크게 느껴지지는 않는다고 생각합니다. 다만, 제가 마지막 잔을 마셨어서 그런 걸 수도 있으니 참고해주세요." },
    { kind: "paragraph", text: "제일 특이했던 점은 끝맛이 꽤나 쓴 편이며, 맛과 피니시에서 후추의 캐릭터가 꽤 강하게 느껴진다는 점입니다. 고기와의 궁합이 좋을 것 같네요." },
  ],
};
