import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "blood-and-sand",
  category: "cocktail",
  title: "블러드 앤 샌드 — 체리, 오렌지 그리고 스파이스의 콤비네이션",
  dek: "\"블러드 앤 샌드\"는 1930년에 해리 크래독(Harry Craddock)의 저서 사보이 칵테일 북(The Savoy Cocktail Book)에 처음 기록으로 등장했습니다.",
  publishedAt: "2024-09-20",
  hero: "/articles/blood-and-sand/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223589936245",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/blood-and-sand/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "\"블러드 앤 샌드\"는 1930년에 해리 크래독(Harry Craddock)의 저서 사보이 칵테일 북(The Savoy Cocktail Book)에 처음 기록으로 등장했습니다." },
    { kind: "paragraph", text: "누가 무슨 의도로 만들었는지에 대한 정보는 전혀 없으며, 해리 크래독이 만든 것인지, 그가 단순히 기록만 한 것인지도 알 수 없습니다." },
    { kind: "paragraph", text: "다만, 1922년에 개봉한 동명의 무성 영화에서 이름을 따온 것으로 추정하고 있지만 그마저도 확실하지 않은 아주 미스터리한 칵테일입니다." },
    { kind: "paragraph", text: "해당 영화는 한 스타 투우사의 몰락과 죽음에 관한 영화라 하는데, 사실 칵테일 자체는 꽤나 달달한 칵테일이기 때문에 개인적으로 색감 이외에는 이름과 매치가 잘 안된다고 생각됩니다." },
    { kind: "figure", src: "/articles/blood-and-sand/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "22.5ml 블렌디드 스카치 위스키" },
    { kind: "paragraph", text: "(Blended Scotch Whisky)" },
    { kind: "paragraph", text: "22.5ml 체리 히링 (Cherry Heering)" },
    { kind: "paragraph", text: "22.5ml 스윗 버무스 (Sweet Vermouth)" },
    { kind: "paragraph", text: "22.5ml 오렌지즙 (Orange Juice)" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질 (Orange Peel)" },
    { kind: "figure", src: "/articles/blood-and-sand/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 가니시 이외의 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹 합니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 칵테일 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 오렌지 껍질에서 오일을 짜내고, 장식해 줍니다." },
    { kind: "paragraph", text: "전체적으로 확실한 오렌지 캐릭터에 신맛의 생 체리 맛이 더해지며, 올스파이스나 시나몬 같은 스파이스가 달달하게 다가옵니다. 살짝 신맛이 있지만 확실히 달달하네요." },
    { kind: "paragraph", text: "체리 히링과 스윗 버무스의 콤비네이션을 오렌지와 함께 느낄 수 있는 칵테일입니다." },
    { kind: "paragraph", text: "블러드 앤 샌드는 재료에서부터 느낄 수 있지만, 꽤나 달달한 칵테일입니다. 이런 점 때문에 밸런스가 안 좋은 칵테일이라는 예기를 많이 듣기도 하죠." },
    { kind: "paragraph", text: "따라서 몇몇 바텐더들은 레몬즙이나 라임즙을 소량 첨가하기도 하며, 아예 오렌지즙을 넣는 것이 아니라 껍질을 위스키에 인퓨징해서 만들기도 합니다." },
    { kind: "paragraph", text: "개인적으로도 원래 레시피 자체가 그렇게 밸런스 좋은 칵테일이라 생각되지는 않지만, 재료가 갖춰져 있다면 한 번쯤은 만들어보는 걸 추천드립니다." },
  ],
};
