import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bobby-burns",
  category: "cocktail",
  title: "바비 번스 — 이름 뒤의 이야기만큼이나 복잡한 향미",
  dek: "「바비 번스」는 일반적으로 스코틀랜드의 국민 시인인 로버트 번스*를 기리기 위해 만들어진 칵테일로 알려져 있으며, 그의 생일을 기념하는 번스 나이트(Burns Night) 행사에서 자주 언급되는 칵테일입니다.",
  publishedAt: "2026-06-07",
  hero: "/articles/bobby-burns/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224308583292",
  relatedCocktailSlugs: ["bobbyburns"],
  blocks: [
    { kind: "figure", src: "/articles/bobby-burns/00.webp", width: 966, height: 966 },
    { kind: "quote", text: "로버트 번스(Robert Burns)와 바비 번스" },
    { kind: "paragraph", text: "「바비 번스」는 일반적으로 스코틀랜드의 국민 시인인 로버트 번스*를 기리기 위해 만들어진 칵테일로 알려져 있으며, 그의 생일을 기념하는 번스 나이트(Burns Night) 행사에서 자주 언급되는 칵테일입니다." },
    { kind: "paragraph", text: "*로버트의 애칭이 바비(Bobby)" },
    { kind: "paragraph", text: "다만, 칵테일 이름이 로버트 번스의 이름과 같다는 점 말고는 근거가 빈약하며, 오히려 알버트 크로켓(Albert Stevens Crockett)은 본인의 저서에서 다른 가능성을 제시합니다." },
    { kind: "figure", src: "/articles/bobby-burns/01.webp", width: 472, height: 187, caption: "Old Waldorf-Astoria Bar Days(1931)" },
    { kind: "paragraph", text: "크로컷은 로버트 번스라는 이름의 칵테일을 소개하면서 스코틀랜드의 시인의 이름을 따왔을 것이라면서도, 옛 월도프 호텔 바의 단골손님이었던 시가 판매원의 이름을 땄을 가능성도 있다고 기록했습니다." },
    { kind: "paragraph", text: "실제로 옛 월도프 호텔의 바가 개장 및 운영되던 시기에 로버트 번스라는 이름의 시가 브랜드 내지는 시가 판매점이 있었다는 점에서 실제 해당 시가 브랜드(또는 판매점)의 이름이 붙었을 가능성이 있다는 주장이 제기되기도 합니다." },
    { kind: "quote", text: "칵테일의 확립" },
    { kind: "paragraph", text: "바비 번스라는 이름의 칵테일의 가장 오래된 기록은 1899년까지 거슬러 올라가나, 스카치 위스키·진저 코디얼·오렌지 비터스 등이 들어가는 현재의 바비 번스와는 상당히 다른 칵테일입니다." },
    { kind: "paragraph", text: "1900년대 초반에는 베이비 번스(Baby Burns)라는 이름으로 현재와 비슷한 레시피의 칵테일이 기록되었으며, 그 외에도 보비 번스(Bobbie Burns), 로버트 번스 등 의 다양한 레시피와 이름의 칵테일이 기록되었습니다." },
    { kind: "figure", src: "/articles/bobby-burns/02.webp", width: 502, height: 155, caption: "The Savoy Cocktail Book(1930)" },
    { kind: "paragraph", text: "이후, 현재의 바비 번스는 해리 크래독(Harry Cradock)의 저서 사보이 칵테일 북(The Savoy Cocktail Book)에 기록된 이름과 내용을 바탕으로 정립되게 되었습니다." },
    { kind: "figure", src: "/articles/bobby-burns/03.webp", width: 966, height: 966 },
    { kind: "quote", text: "칵테일 레시피" },
    { kind: "paragraph", text: "- 스카치 위스키 45ml" },
    { kind: "paragraph", text: "- 스윗 버무스 15ml" },
    { kind: "paragraph", text: "- 베네딕틴 돔 5~8ml" },
    { kind: "paragraph", text: "- 가니시: 레몬 껍질" },
    { kind: "figure", src: "/articles/bobby-burns/04.webp", width: 966, height: 966 },
    { kind: "quote", text: "How to Mix" },
    { kind: "paragraph", text: "1. 믹싱 글라스에 모든 재료를 넣는다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채워주고, 스터해준다." },
    { kind: "paragraph", text: "3. 차게 해 둔 잔에 부어준다." },
    { kind: "paragraph", text: "4. 레몬 껍질을 짜서 오일을 뿌려준다." },
    { kind: "paragraph", text: "바비 번스는 아주아주 복합적인 맛의 칵테일로, 스카치의 바닐라함과 숙성감, 버무스의 와인스러움과 향신료, 베니딕틴의 꿀과 약간의 허브함까지 정말 다양한 캐릭터가 느껴지는 칵테일입니다." },
    { kind: "paragraph", text: "스카치 위스키의 경우는 각자 좋아하는 걸 사용하시면 될 것 같은데, 개인적으로는 피트가 없고, 숙성감이 과하지 않은 싱글몰트 또는 블렌디드 스카치 위스키를 사용하는 것을 추천드립니다." },
    { kind: "paragraph", text: "또한, 바비 번스가 재료적으로나 만들어진 시기상(또는 기록상) 롭 로이(Rob Roy)라는 칵테일의 변형이 아닐까 생각하고 있으며, 제 레시피는 이를 염두에 둔 비율입니다. 또, 그러한 접근법으로 앙고스투라 비터를 첨가하기도 하구요." },
    { kind: "paragraph", text: "유튜브에도 다양한 레시피가 있으니, 참고해서 본인만의 비율을 만들어가는 재미가 있는 칵테일이고, 스카치·버무스·베네딕틴의 밸런스를 절묘하게 맞추기 생각보다 어렵기도 한 칵테일입니다." },
    { kind: "paragraph", text: "개인적으로 스카치 위스키 칵테일을 추천해달라 하는 경우 항상 상위권에 드는 칵테일이고, 나이트캡에 딱 어울릴만한 칵테일이라 상각됩니다." },
  ],
};
