import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "boston-cooler",
  category: "cocktail",
  title: "보스턴 쿨러 — 레몬의 산미와 생강의 청량감을 담은 칵테일",
  dek: "「보스턴 쿨러」는 이름에서도 볼 수 있듯이 \"쿨러(Cooler)\"라는 카테고리의 칵테일로, 쿨러란 현재에는 주로 \"기주+시트러스 즙+당+탄산 믹서\"의 형태로 만들어지는 칵테일입니다.",
  publishedAt: "2025-06-03",
  hero: "/articles/boston-cooler/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223887226154",
  relatedCocktailSlugs: ["bostoncooler"],
  blocks: [
    { kind: "figure", src: "/articles/boston-cooler/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "About the Cockail" },
    { kind: "paragraph", text: "「보스턴 쿨러」는 이름에서도 볼 수 있듯이 \"쿨러(Cooler)\"라는 카테고리의 칵테일로, 쿨러란 현재에는 주로 \"기주+시트러스 즙+당+탄산 믹서\"의 형태로 만들어지는 칵테일입니다." },
    { kind: "paragraph", text: "형태만 보면 \"피즈(Fizz)\", \"콜린스(Collins)\"나 \"벅(Buck)\" 계열의 칵테일들을 떠올리게 하는데, 사실 구분에 큰 의미가 없다시피 합니다." },
    { kind: "figure", src: "/articles/boston-cooler/01.webp", width: 601, height: 119, caption: "The Fine Art of Mixing drinks(1948)" },
    { kind: "paragraph", text: "이에 대해 데이비드 엠버리(David A. Embury)는 그의 저서에서 쿨러는 근본적으로 \"홀시스 넥(Horse's Neck)의 변형\"이라고 표현하기도 했는데, 이건 아마 '렘센 쿨러(Remsen Cooler)\"라는 칵테일이 \"쿨러\"류의 원조라는 견해 때문에 그런 것 같습니다." },
    { kind: "paragraph", text: "다만, 갈수록 대부분의 쿨러 계열 칵테일들이 시트러스 즙과 당을 필요로 했기 때문에, 현재와는 좀 맞지 않는 부분도 있다고 생각됩니다." },
    { kind: "figure", src: "/articles/boston-cooler/02.webp", width: 966, height: 1287 },
    { kind: "paragraph", text: "개인적으로 보스턴 쿨러에서 가장 흥미로운 점은, 분명 이 칵테일이 서양에서 만들어진 것으로 보이나, 현재에는 서양에서의 인지도는 전혀 없고, 일본이나 우리나라 정도에서나 인지도가 있다는 점입니다." },
    { kind: "paragraph", text: "영문으로 보스턴 쿨러를 검색해 보면 칵테일에 대한 내용은 거의 없고, 진저에일에 바닐라 아이스크림을 플로팅 한 디트로이트 지역의 음료만 주로 검색되는데 말이죠." },
    { kind: "figure", src: "/articles/boston-cooler/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "*45ml 럼" },
    { kind: "paragraph", text: "18~20ml 레몬즙" },
    { kind: "paragraph", text: "**10ml 시럽(1:1 심플 시럽의 경우)" },
    { kind: "paragraph", text: "진저비어 or 진저에일" },
    { kind: "paragraph", text: "*럼은 아무 럼이나 사용해도 무관한데, 좀 더 다양한 맛을 내고 싶다면 골드 럼을 사용한다던가, 자메이칸 럼을 사용하는 것도 하나의 방법입니다." },
    { kind: "paragraph", text: "**리치 심플 시럽을 사용하는 경우에는 양을 살짝만 줄이는 걸 추천합니다." },
    { kind: "figure", src: "/articles/boston-cooler/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 진저비어 외의 모든 재료를 셰이커 안에 넣는다." },
    { kind: "paragraph", text: "2. 얼음을 채우고, 셰이킹 한다." },
    { kind: "paragraph", text: "3. 긴 잔에 얼음을 채우고, 셰이커에서 부어준다." },
    { kind: "paragraph", text: "4. 진저비어를 더해주고," },
    { kind: "paragraph", text: "얼음을 위아래로 두 세번 움직여준다." },
    { kind: "paragraph", text: "5. 레몬 휠을 넣어준다." },
    { kind: "paragraph", text: "보스턴 쿨러의 맛" },
    { kind: "paragraph", text: "- 상큼 달달하고, 생강의 알싸한 맛이 매력적인 맛" },
    { kind: "paragraph", text: "- 약간의 탄산감" },
    { kind: "paragraph", text: "- 모스코뮬에서 럼의 풍미가 추가된 느낌" },
    { kind: "paragraph", text: "보스턴 쿨러는 상큼함, 생강의 알싸한 맛, 탄산감으로 인해서 꽤 리프레시가 되는 칵테일로, 개인적으로는 봄부터 가을까지 첫 잔으로 또는 음식과 함께 마시기에 꽤 좋은 칵테일이라 생각됩니다." },
  ],
};
