import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "boulevardier",
  category: "cocktail",
  title: "불바디에 — 버번 위스키를 사용한 네그로니의 형제 칵테일",
  dek: "1920년대에 미국에서는 금주법이 시행되면서 많은 미국인들이 유럽, 특히 파리로 건너가 술과 문화를 자유롭게 즐겼으며, 그 중 유명한 곳으로 「해리스 뉴욕 바(Harry’s New York Bar)」가 있었습니다.",
  publishedAt: "2025-04-19",
  hero: "/articles/boulevardier/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223839734664",
  relatedCocktailSlugs: ["boulevardier"],
  blocks: [
    { kind: "figure", src: "/articles/boulevardier/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "1920년대에 미국에서는 금주법이 시행되면서 많은 미국인들이 유럽, 특히 파리로 건너가 술과 문화를 자유롭게 즐겼으며, 그 중 유명한 곳으로 「해리스 뉴욕 바(Harry’s New York Bar)」가 있었습니다." },
    { kind: "paragraph", text: "이 곳의 주인이던 해리 맥켈혼(Harry McElhone)이 1927년 출간한 칵테일 책 Barflies and Cocktails의 마지막 부분에 '아서 모스(Arthur Moss)'가 쓴 에세이인 'Cocktails Round Town'이 있는데, 여기서 불바디에가 처음 기록되었습니다." },
    { kind: "quote", text: "Now is the time for all good Barflies to come to the aid of the party, since Erskinne Gwynne crashed in with his Boulevardier Cocktail; 1/3 Campari, 1/3 Italian vermouth, 1/3 Bourbon whisky." },
    { kind: "paragraph", text: "여기서 모스는 에르스킨 그윈(Erskine Gwynne)이라는 인물이 그의 불바디에와 난입했다고 적었는데, 이게 그윈이라는 인물이 창작한 칵테일인지, 아니면 그냥 그윈이 좋아하는 칵테일인 건지가 좀 모호합니다." },
    { kind: "figure", src: "/articles/boulevardier/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "본질적으로 불바디에는 네그로니(Negroni)의 변형이면서도, 이전에 포스팅한 같은 저서에서 등장하는 '올드 팔(Old Pal)'이라는 칵테일과 아주 유사한 구조의 형제 칵테일이기도 합니다." },
    { kind: "paragraph", text: "불바디에와 올드 팔은 위스키, 버무스, 캄파리의 구조는 동일한데, 위스키와 버무스에서 차이가 나는 칵테일로, 이로 인해 불바디에가 올드 팔보다는 기본적으로 묵직한 느낌이 있습니다." },
    { kind: "figure", src: "/articles/boulevardier/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml 버번 위스키(Bourbon Whiskey)" },
    { kind: "paragraph", text: "30ml 캄파리(Campari)" },
    { kind: "paragraph", text: "30ml 스윗 버무스(Sweet Vermouth)" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질(Orange Peel)" },
    { kind: "figure", src: "/articles/boulevardier/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 온더락 잔에 모든 재료를 넣어줍니다." },
    { kind: "paragraph", text: "2. 얼음을 채우고, 스터해줍니다." },
    { kind: "paragraph", text: "3. 잔 위로 오렌지 껍질을 짜서 오일을 뿌려줍니다." },
    { kind: "paragraph", text: "4. 사용한 껍질을 다듬어서 잔에 넣어줍니다." },
    { kind: "paragraph", text: "불바디에의 맛" },
    { kind: "paragraph", text: "- 묵직하면서도 부드러운 바닐리함, 달큰하면서도 씁쓸함, 허브감" },
    { kind: "paragraph", text: "- 진으로 만든 네그로니보다는 허브감 자체는 살짝 덜합니다." },
    { kind: "paragraph", text: "- 초콜레티한 맛도 나는데, 아마도 코키 디 토리노와 우드포드 리저브의 조합 때문인 것 같습니다." },
    { kind: "paragraph", text: "팁?" },
    { kind: "paragraph", text: "- 사용하는 버번의 캐릭터에 따라서 맛이 꽤 다르게 만들어지기도 하니 이런저런 기주를 많이 경험해 보는 것이 좋습니다." },
    { kind: "paragraph", text: "- 올드 팔과 같이 쇼트 칵테일 잔에 업 스타일로 서브하기도 하는데, 이건 개인의 취향에 맞게 해주시면 됩니다." },
  ],
};
