import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bramble",
  category: "cocktail",
  title: "브램블 — 베리류 칵테일 최강자",
  dek: "\"브램블\"은 1980년대 중반에 런던 소호의 프레드스 클럽(Fred's Club)에서 당시 바 매니저였던 딕 브래드셀(Dick Bradsell)에 의해 만들어졌습니다.",
  publishedAt: "2024-08-27",
  hero: "/articles/bramble/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223562540663",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bramble/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"브램블\"은 1980년대 중반에 런던 소호의 프레드스 클럽(Fred's Club)에서 당시 바 매니저였던 딕 브래드셀(Dick Bradsell)에 의해 만들어졌습니다." },
    { kind: "paragraph", text: "딕 브래드셀은 브램블 이외에도 에스프레소 마티니 등의 칵테일을 만들어낸 바텐더로도 유명합니다." },
    { kind: "paragraph", text: "브램블이라는 이름은 블랙베리가 자라는 덤불에서 따온 것으로, 브래드셀 본인이 어린 시절에 자랐던 와이트 섬(Isle of Wight)에서 블랙베리를 따먹다가 덤불에 긁혔던 추억을 바탕으로 만든 것이라 합니다." },
    { kind: "paragraph", text: "기본적으로 이 칵테일의 구조는 진 사워(Gin Sour)에 베리류의 리큐르를 더한 꽤나 간단한 칵테일이지만, 진 사워라는 완성된 칵테일에 다시 무언가를 더한다는 점에서 당시에 발상의 전환 같은 칵테일이었을 수도 있겠습니다." },
    { kind: "paragraph", text: "그 외에 사보이 스타일의 싱가폴 슬링(진, 레몬즙, 체리 브랜디, 설탕 시럽, 탄산수)과도 연관점을 찾는 사람들도 있습니다." },
    { kind: "figure", src: "/articles/bramble/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "45ml 진 (Gin)" },
    { kind: "paragraph", text: "20ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "10ml 설탕 시럽 (Simple Syrup)" },
    { kind: "paragraph", text: "10-15ml **크렘 드 뮬 (Creme de Mure)" },
    { kind: "paragraph", text: "가니시: 레몬 휠 + 베리류(옵션)" },
    { kind: "paragraph", text: "**크렘 드 뮬이 없다면, 크렘 드 카시스(Creme de Cassis), 크렘 드 프람보아즈(Creme de Framboise), 샴보드(Chambord) 등과 같은 베리 리큐르를 사용해도 괜찮습니다." },
    { kind: "paragraph", text: "저는 같이 칵테일 동아리를 하는 동생이 만든 크렘 드 뮬을 선물로 받아서 사용했습니다." },
    { kind: "figure", src: "/articles/bramble/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/bramble/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 크렘 드 뮬을 제외한 재료를 셰이커에 넣어준다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고 셰이킹 한다." },
    { kind: "paragraph", text: "3. 온더락 잔에 잔얼음을 채워준다." },
    { kind: "paragraph", text: "4. 잔에 셰이킹 한 걸 부어준다." },
    { kind: "paragraph", text: "5. 크렘 드 뮬을 부어주고, 얼음을 더 채워준다." },
    { kind: "paragraph", text: "6. 가니시를 해주고, 짧은 빨대를 꽂아준다." },
    { kind: "figure", src: "/articles/bramble/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "브램블은 진 사워의 신맛에 베리류의 묵직한 달달함이 더해지는 새콤달달한 칵테일입니다. 어떤 베리 리큐르를 사용하냐에 따라서 맛이 조금씩 다른 것도 하나의 재미이기도 합니다." },
    { kind: "paragraph", text: "브램블의 묘미는 베리 리큐르를 부어줄 때 잔얼음 사이사이로 아름답게 흘러내리는 점입니다. 플로팅 하는 칵테일이 아니고서야 이렇게 칵테일을 만들어놓고 무거운 리큐르를 따르는 연출은 그렇게 많지 않기도 하니 더 특별하죠." },
    { kind: "paragraph", text: "잔얼음 같은 경우는 한 잔 기준으로 편의점에서 플라스틱 잔에 든 큰 사이즈의 잔 얼음 하나면 충분합니다." },
    { kind: "paragraph", text: "진 같은 경우는 일부러 비피터를 사용했는데, 비피터가 시트러스 캐릭터를 가지고 있어서 브램블에 잘 어울릴 거라 생각해서 사용했습니다. 탱커레이 넘버텐도 나쁘지 않겠네요." },
    { kind: "paragraph", text: "베리 리큐르는 15ml를 넘지 않게 부어주시는 걸 추천하는데, 아무래도 리큐르다 보니 너무 많이 넣게되면 알콜감이 튀게되기 때문입니다." },
  ],
};
