import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "brandy-alexander",
  category: "cocktail",
  title: "브랜디 알렉산더 — 꼬냑, 크리미한 초콜릿, 완벽한 디저트 칵테일",
  dek: "\"브랜디 알렉산더\"는 진, 크렘 드 카카오, 생크림으로 만들어지는 \"알렉산더\"라는 칵테일의 변형이며, 그 기원이 명확하지는 않으나 확실한 건 정복자 알렉산더 대왕(알렉산드로스)과는 전혀 상관이 없다는 것입니다.",
  publishedAt: "2024-09-14",
  hero: "/articles/brandy-alexander/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223584032606",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/brandy-alexander/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"브랜디 알렉산더\"는 진, 크렘 드 카카오, 생크림으로 만들어지는 \"알렉산더\"라는 칵테일의 변형이며, 그 기원이 명확하지는 않으나 확실한 건 정복자 알렉산더 대왕(알렉산드로스)과는 전혀 상관이 없다는 것입니다." },
    { kind: "paragraph", text: "진으로 만드는 알렉산더는 금주법 이전에 만들어진 칵테일이며, 1916년 휴고 엔슬린(Hugo Ensslin)의 저서 Recipes for Mixed Drinls에 처음 기록으로 등장했습니다(그가 만들었다는 게 아님)." },
    { kind: "paragraph", text: "브랜디 알렉산더는 누가 만들었는지는 알 수 없지만, 1930년 해리 크래독(Harry Craddock)의 저서 사보이 칵테일 북(The Savoy Cocktail Book)에서 처음 기록으로 등장하게 됩니다." },
    { kind: "paragraph", text: "다만, 이때의 이름은 브랜디 알렉산더가 아닌 \"알렉산더 칵테일 넘버 2(Alexander Cocktail No.2)\"라는 이름으로 등장하며, 모든 재료가 동일한 비율로 소개됩니다." },
    { kind: "paragraph", text: "이후 1937년에는 좀 더 최근의 레시피로 조정된 브랜디 알렉산더가 윌리엄 탈링(W.J Tarling)의 저서인 카페 로얄 칵테일 북(Cafe Royal Cocktail Book)에서 소개되기도 합니다." },
    { kind: "paragraph", text: "브랜디 알렉산더는 많은 대중매체에서도 꾸준하게 등장하며 많은 사랑을 받아왔는데, 반대로 원형인 진으로 만드는 알렉산더는 그 유명세에 밀리게 되었습니다." },
    { kind: "paragraph", text: "우리나라에서도 알렉산더 칵테일은 브랜디 알렉산더를 지칭할 확률이 아주아주아주 높습니다." },
    { kind: "figure", src: "/articles/brandy-alexander/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml 꼬냑 (Cognac)" },
    { kind: "paragraph", text: "20ml 크렘 드 카카오 (Creme de Cacao)" },
    { kind: "paragraph", text: "20ml 생크림 (Heavy Cream)" },
    { kind: "paragraph", text: "가니시: 육두구" },
    { kind: "figure", src: "/articles/brandy-alexander/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 가니시 이외의 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 칵테일 잔에 따라줍니다." },
    { kind: "paragraph", text: "4. 칵테일 위에 육두구를 소량 갈아줍니다." },
    { kind: "paragraph", text: "레시피는 다양하게 있는데, 좀 더 단 맛을 좋아한다고 하시면 1:1:1의 레시피를, 꼬냑의 캐릭터를 크리미한 초콜릿 캐릭터와 같이 즐기고 싶다고 하신다면 3:2:2의 레시피를 추천드립니다." },
    { kind: "paragraph", text: "2:1:1의 레시피도 있긴 한데, 이 레시피는 도수가 높은 꼬냑으로 인해 알콜감이 튈 확률이 좀 높기 때문에 추천드리지는 않습니다. 만약 XO급 이상으로 만든다면 2:1:1도 괜찮겠네요." },
    { kind: "paragraph", text: "개인적으로 브랜디 알렉산더에 추천드리는 꼬냑은 헤네시 VSOP로, 특유의 묵직한 단맛과 바닐라, 스파이스(향신료)의 캐릭터가 꽤나 잘 어울립니다." },
    { kind: "paragraph", text: "브랜디 알렉산더는 크림과 카카오의 맛으로 인해 술맛도 별로 안 나고, 부드럽고 달달하며, 거기에 꼬냑 뉘앙스가 같이 나게 됩니다." },
    { kind: "paragraph", text: "그렇기 때문에 술을 잘 못 마시는 사람이더라도 충분히 맛있게 한 잔을 다 마칠 수 있을 만한 디저트 칵테일입니다." },
  ],
};
