import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "brandy-crusta",
  category: "cocktail",
  title: "브랜디 크러스타",
  dek: "브랜디 크러스타는 1850년대에 뉴올리언스 지방에서 바텐더로 활동하던 Joseph Santini에 의해 만들어졌으며, 1862년 Jerry Thomas의 저서인 'Bartender's Guide'에 처음 기록되었다고 합니다.",
  publishedAt: "2024-01-28",
  hero: "/articles/brandy-crusta/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223336279208",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/brandy-crusta/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "About the Drink" },
    { kind: "paragraph", text: "브랜디 크러스타는 1850년대에 뉴올리언스 지방에서 바텐더로 활동하던 Joseph Santini에 의해 만들어졌으며, 1862년 Jerry Thomas의 저서인 'Bartender's Guide'에 처음 기록되었다고 합니다. 하지만 크게 인기를 끌지는 못했는지 2000년대 전까지 잊혀져 있다가, 'Imbibe!'의 저자 David Wondrich와 뉴올리언스 지역에서 활동하고 있는 바텐더 Chris Hannah 등의 노력으로 다시 각광을 받기 시작했습니다." },
    { kind: "paragraph", text: "이 칵테일이 만들어진 19세기말에서 20세기 초에는 마라스키노 리큐르의 인기에 힘입어 임프루브드 위스키 칵테일(Improved Whiskey Cocktail), 에비에이션(Aviation), 라스트 워드(Last Word) 등 마라스키노 리큐르를 사용한 칵테일들이 많이 등장했는데, 참 이상하게도 이런 칵테일들은 모두 사장될 뻔한 위험을 겪은 친구들(현재 라스트 워드의 컬트적인 인기는 차치하고)이라는 공통점이 있습니다." },
    { kind: "paragraph", text: "브랜디 크러스타는 사이드카와의 관계에서 항상 \"브랜디 크러스타가 사이드카의 원형인가\"라는 논쟁을 불러일으킵니다. 브랜디, 레몬즙, 큐라소(또는 트리플섹)이라는 공통적인 재료와 맛의 프로파일 때문이죠. 그러나 사이드카가 처음 만들어졌을 때는 잔에 설탕으로 가니시를 하지도 않았고, 크러스타와 사이드카를 구성하는 시트러스의 양과 설탕의 유무로 인해 \"사이드카의 원형은 데이지 칵테일\"이라는 주장과 대립각을 이루게 됩니다." },
    { kind: "paragraph", text: "본래 크러스타는 레몬즙이 조금 들어가는 반면에(제 레시피에는 많이 들어가기는 합니다만....), 사이드카에는 레몬즙이 비교적 많이 들어가고, 사이드카는 당을 오렌지 큐라소(또는 트리플섹)으로 대체했으며, 데이지 칵테일(진 + 큐라소 + 레몬즙 + 약간의 탄산수)의 변형에 좀 더 부합하다는 것입니다. 저는 이런 주장에 기본적으로 동의합니다만, 사이드카와 브랜디 크러스타가 비슷한 프로파일을 가진다는 것 자체는 부정할 수 없는 사실이긴 합니다." },
    { kind: "paragraph", text: "따라서 어느 쪽 주장이 꼭 맞냐 보다는 어떤 식으로 본인이 브랜디 크러스타와 사이드카에 접근하려는지에 좀 더 주안점을 주면 될 것 같습니다." },
    { kind: "figure", src: "/articles/brandy-crusta/01.webp", width: 966, height: 725 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "50ml 꼬냑" },
    { kind: "paragraph", text: "10ml 오렌지 큐라소 / 트리플섹" },
    { kind: "paragraph", text: "10ml 마라스키노 리큐르" },
    { kind: "paragraph", text: "20ml 레몬 즙" },
    { kind: "paragraph", text: "5ml 심플 시럽" },
    { kind: "paragraph", text: "2dashes 앙고스투라 비터스" },
    { kind: "paragraph", text: "가니쉬: 설탕 리밍 & 길다란 레몬 필" },
    { kind: "figure", src: "/articles/brandy-crusta/02.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 잔 바깥 부분에 설탕을 두껍게 묻히고, 긴 레몬 필을 둥글게 말아 림 안쪽에 고정해줍니다." },
    { kind: "paragraph", text: "2. 가니쉬 이외의 재료를 모두 쉐이커에 넣어줍니다." },
    { kind: "paragraph", text: "3. 쉐이킹 후 잔에 따라줍니다." },
    { kind: "figure", src: "/articles/brandy-crusta/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/brandy-crusta/04.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "브랜디 크러스타는 레시피가 정말 많기 때문에 이것저것 찾아보시고 가장 맛있겠다 싶은 레시피를 사용하시거나, 조정하시는 것을 추천드리며, 꼬냑의 경우는 어느정도 퀄리티가 있는 종류를 사용하시는 걸 추천드립니다. 아무래도 꼬냑의 맛에 따라 칵테일의 맛에 차이가 많이 차이가 나게 됩니다." },
    { kind: "paragraph", text: "개인적인 감상으로는 \"사이드카를 좋아하는데, 브랜디 크러스타를 마셔보지 않았다는 것은 죄악\"이라는 생각이 드는 한 잔이었습니다." },
    { kind: "paragraph", text: "마실 때에는 가니시한 레몬 필의 한 부분을 잔 아래로 꾹 눌러주신 후에 드시면 됩니다. 전체적으로 꼬냑의 아로마틱함, 룩사르도의 달달한 체리, 그랑 마르니에에서 오는 오렌지, 레몬의 시트러스함이 모두 뭉뜽그러져서 나는 맛이 아주 일품입니다." },
    { kind: "paragraph", text: "이전에 올렸던 포스팅에서도 언급했듯이, 저는 마라스키노 리큐르 자체는 그닥 좋아하지는 않습니다만.....에비에이션, 라스트 워드도 그렇고, 이 칵테일도 그렇고 마라스키노 리큐르가 들어간 칵테일은 대부분 맛있게 마신게 참 신기합니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
