import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bruichladdich-bere-barley",
  category: "spirits",
  title: "브룩라디 비어발리 2012",
  dek: "\"브룩라디 비어 발리\"는 원액이 증류된 연도를 달고 해마다 나오는 '브룩라디 증류소'의 위스키 라인 중 하나로, 10년 숙성 · 논피트 · 50%의 도수로 출시됩니다.",
  publishedAt: "2024-07-26",
  hero: "/articles/bruichladdich-bere-barley/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223526188695",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bruichladdich-bere-barley/00.webp", width: 540, height: 540 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "\"브룩라디 비어 발리\"는 원액이 증류된 연도를 달고 해마다 나오는 '브룩라디 증류소'의 위스키 라인 중 하나로, 10년 숙성 · 논피트 · 50%의 도수로 출시됩니다." },
    { kind: "paragraph", text: "독특하게 현재 위스키 산업에서는 거의 사용되지 않는 \"비어 발리(Bere Barley)\"라는 보리 품종을 사용하는데, 20세기에 효율성 및 수익성으로 인해 다른 품종의 보리를 사용하게 되면서 외면받게 되었다고 합니다." },
    { kind: "paragraph", text: "브룩라디 증류소는 2005년부터 하이랜드 앤 아일랜드 대학(UHI)의 농경학 연구소와 협력하여 비어 발리가 다시금 위스키 생산에 쓰일 수 있도록 노력했으며, 이 비어 발리 라인업이 그 결과라 할 수 있습니다." },
    { kind: "quote", text: "증류소 정보: 브룩라디 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트" },
    { kind: "quote", text: "캐스크 정보: 퍼스트필 버번 캐스크(1st Fill Bourbon) 10년" },
    { kind: "quote", text: "보리 정보: 오크니 대학(UHI)의 농경학 연구소에서 재배한 비어 발리 / 2011년 수확" },
    { kind: "quote", text: "도수: 50%" },
    { kind: "figure", src: "/articles/bruichladdich-bere-barley/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 달달한 과실, 참외 속 부분, 오크, 꿀, 샤프한 시트러스?" },
    { kind: "paragraph", text: "- 약간의 화사한 플로럴함" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 아주 달달한 과실감, 약간의 복숭아와 망고" },
    { kind: "paragraph", text: "- 약간의 짭짤함, 끝에 살짝 남는 쌉쌀함" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 달달한 생강, 오크, 짭짤함, 약간의 후추" },
    { kind: "paragraph", text: "- 10년 숙성치고는 약간은 아쉬운 피니시" },
    { kind: "paragraph", text: "브룩라디 비어 발리 2012는 과실의 달달함의 캐릭터가 빛이 나는 한 잔으로, 처음 오픈했을 때는 오크의 캐릭터가 강해 셰리 캐스크를 썼나? 싶었던 기억이 있습니다. 다만, 비교군이 적어 비어 발리라는 보리 품종의 특징까지는 잘 모르겠네요." },
    { kind: "paragraph", text: "브룩라디 비어 발리 시리즈는 국내에서는 찾아보기 어렵지만, 일본에서는 쉽게 찾아볼 수 있으며, 가격이 현지보다 오히려 쌉니다. 저는 올해 7월 후쿠오카에서 10만 원 안되는 가격으로 구입을 했습니다." },
    { kind: "paragraph", text: "가격 대비 만족도가 괜찮았으며, 브룩라디 증류소의 팬이거나, 가성비 좋은 바틀을 일본에서 구입하시는 분들에게는 추천드릴만 하네요." },
  ],
};
