import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bruichladdich-valinch-feis-ile-2024",
  category: "spirits",
  title: "브룩라디 발린치 페스 아일 2024",
  dek: "아일라(Islay) 섬에 위치한 브룩라디(Bruichladdich) 증류소에는 증류소샵에서만 구매할 수 있는 위스키 바틀이 존재합니다.",
  publishedAt: "2024-07-20",
  hero: "/articles/bruichladdich-valinch-feis-ile-2024/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223519293671",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bruichladdich-valinch-feis-ile-2024/00.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/bruichladdich-valinch-feis-ile-2024/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "아일라(Islay) 섬에 위치한 브룩라디(Bruichladdich) 증류소에는 증류소샵에서만 구매할 수 있는 위스키 바틀이 존재합니다. \"더 라디 발린치(The Laddie Valinch)\"가 그것으로, 이 바틀은 증류소의 직원들을 기념하기 위한 바틀로, 출시되는 바틀마다 각각 다른 직원의 얼굴을 달고 릴리즈 됩니다." },
    { kind: "figure", src: "/articles/bruichladdich-valinch-feis-ile-2024/02.webp", width: 966, height: 543, caption: "브룩라디 증류소샵의 발린치 시리즈. 2024.06기준으로 73번까지 출시." },
    { kind: "paragraph", text: "각 릴리즈는 싱글캐스크(Single Cask) 및 캐스크 스트렝스(Cask Strength)로 출시되며, 릴리즈마다 캐스크는 모두 다르며, 증류소 자체적으로는 증류소 현장 샵에서만 판매하고 있으며, 핸드필(Hand-filled)로도 구매할 수 있습니다. 500ml로 출시되는 건 아쉽지만, 증류소 기념품이라고 볼 수도 있죠." },
    { kind: "paragraph", text: "이러한 발린치 시리즈 중에서도 증류소 직원 전체의 사진을 달고 릴리즈 된 것들이 있는데, 이 바틀들은 아일라의 연례 행사인 페스 아일(Feis Ile) 한정 바틀로, 이번에 리뷰할 위스키는 2024년 페스 아일에 릴리즈된 발린치 제품입니다." },
    { kind: "quote", text: "증류소: 브룩라디 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 / 싱글 캐스크 / 캐스크 스트렝스" },
    { kind: "quote", text: "캐스크 정보: 세컨드 필 셰리 벗(2nd Fill Sherry Butt) 17년" },
    { kind: "quote", text: "도수: 57.1%" },
    { kind: "figure", src: "/articles/bruichladdich-valinch-feis-ile-2024/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 말린 대추, 꿀, 무화과, 카카오닙, 카카오, 건과일" },
    { kind: "paragraph", text: "- 꿀에 절인 대추 같은 향" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 단맛이 있긴 하지만 향만큼 달지는 않고, 약간의 스파이스" },
    { kind: "paragraph", text: "- 카카오닙처럼 쌉쌀한 느낌도 남음" },
    { kind: "paragraph", text: "- 약간의 꿀 같은 캐릭터가 입에 남음" },
    { kind: "paragraph", text: "- 생각만큼 도수감이 느껴지지 않음" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 달달하고 안정적인 피니시" },
    { kind: "paragraph", text: "- 말린 대추, 살짝의 카카오닙" },
    { kind: "paragraph", text: "개인적으로 셰리 캐스크를 사용한 위스키를 그렇게 좋아하는 편은 아닌데, 이 위스키는 아주 맛있게 마셨습니다. 아마 셰리 캐스크 특유의 스파이스 캐릭터나 팥 같은 캐릭터가 강하지 않아서 그런 것 같습니다." },
    { kind: "paragraph", text: "여담으로 브룩라디 발린치의 경우 대부분의 릴리즈가 좋은 평가를 받아왔습니다(위스키베이스 기준 80점대 후반). 아마 직원들을 기념하는 바틀인 만큼 캐스크 선정에 신경을 쓴 것 같은데, 이런 증류소에서 일하는 직원들은 애사심이 절로 생기겠네요." },
  ],
};
