import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "bunnahabhain-feis-ile-2024",
  category: "spirits",
  title: "부나하벤 페스 아일 2024 — 루비 포트 피니시",
  dek: "아일라까지 가서 못 만난 축제 보틀을 싱가포르 창이 공항에서 만났다. 브리딩 후에 완전히 다른 위스키가 되는 14년 숙성.",
  publishedAt: "2024-11-23",
  hero: "/articles/bunnahabhain-feis-ile-2024/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223670507851",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/bunnahabhain-feis-ile-2024/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "'부나하벤(Bunnahabhain)'은 스코틀랜드 아일라섬(Islay)의 북동쪽에 위치한 부나하벤 증류소에서 만들어지는 위스키로, 아일라 위스키지만 피트를 사용하지 않는다는 것이 특징인 위스키입니다." },
    { kind: "paragraph", text: "이 아일라 섬에서는 해마다 5월 마지막 주에 옆의 주라 섬(Jura)과 함께 '페스 아일(Feis Ile)'이라는 축제가 열리는데,  두 섬의 증류소들은 축제를 기념하기 위한 보틀을 출시합니다." },
    { kind: "paragraph", text: "올해 열렸던 페스아일에서 부나하벤 증류소는 4가지 스펙의 제품을 출시하였는데, 이번에 리뷰하는 바틀은 14년 숙성의 루비 포트 피니시입니다." },
    { kind: "paragraph", text: "올해 페스 아일 기간에 부나하벤의 오픈데이 당일 아일라 섬을 방문했었는데 일정상 부나하벤은 들리지 못했었습니다만, 가족 여행을 갔다 오면서 창이 공항에서 발견하고는 바로 확보했습니다." },
    { kind: "paragraph", text: "아일라 섬까지 가서 구경도 못한 걸 싱가포르에서 만나다니 약간은 아이러니하네요." },
    { kind: "quote", text: "증류소: 부나하벤 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 버번 캐스크(Bourbon Cask) 11년 숙성 후, 루피 포트 혹스헤드(Ruby Port Hogshead)에서 3년 피니시" },
    { kind: "quote", text: "도수: 58.7%" },
    { kind: "quote", text: "시리즈: 페스 아일(Feis Ile)" },
    { kind: "figure", src: "/articles/bunnahabhain-feis-ile-2024/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 처음 오픈했을 때, 스파이시함이 강하고, 블루베리 요거트 같은 느낌. 어느정도 브리딩 후에는 전혀 달라짐." },
    { kind: "paragraph", text: "- 어느정도 숙성된 그랑 샹파뉴 꼬냑의 란시오와 오렌지 캐릭터와 비슷한 느낌의 첫 향" },
    { kind: "paragraph", text: "- 풍부한 어두운 계열의 베리류, 말린 망고" },
    { kind: "paragraph", text: "- 오렌지 과육 위에서 카라멜라이즈된 설탕" },
    { kind: "paragraph", text: "- 크리미함, 코코아의 캐릭터" },
    { kind: "paragraph", text: "- 약간의 향신료와 스파이시함" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 스파이시함이 코를 탁 치지만, 전혀 거슬리지 않고 오히려 기분이 좋을 정도." },
    { kind: "paragraph", text: "- 스파이시함 > 오크 캐릭터 > 단맛으로 이어짐" },
    { kind: "paragraph", text: "- 단맛은 시럽 같은 단맛이 지배적임." },
    { kind: "paragraph", text: "- 어딘가 꼬냑을 연상시키는 끝맛" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 달달함과 스파이시함의 절묘한 밸런스" },
    { kind: "paragraph", text: "테이스팅 노트를 적다보니 '꼬냑'에 대해서 꽤나 많이 적었는데, 그렇다고 꼬냑과 완전히 비슷하다! 이런 건 아니고, 그랑 샹파뉴 꼬냑의 뉘앙스가 어딘가 느껴지는 정도입니다." },
    { kind: "paragraph", text: "처음 오픈했을 때는 스파이시함이 꽤 강하고, 블루베리 요거트 같은 캐릭터가 꽤나 강했는데, 브리딩 후에는 완전히 다른 위스키가 됐습니다. 아마 브리딩 하면서 스파이시 함이 좀 빠지면서 다른 캐릭터들이 올라온 탓이겠죠." },
    { kind: "paragraph", text: "개인적으로는 브리딩 후에 정말 맛있게 마셨고, 포트 캐스크 피니시를 정말 잘했다고 느꼈습니다. 포트 캐스크를 활용한 위스키 중에서는 지금까지 마셔본 것 중에 가장 마음에 드네요." },
  ],
};
