import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "caipiroska",
  category: "cocktail",
  title: "카이피로스카 — 보드카로 간단하게 담아낸 브라질의 국민 칵테일의 변형",
  dek: "「카이피로스카」는 브라질의 국민 칵테일인 카이피리냐(Caipirinha)의 변형으로, 기주를 카샤샤(Cachaca)에서 보드카로 바꾼 아주 간단한 변주로, 카이피로브스카(Caipirovska)로 불리기도 합니다.",
  publishedAt: "2025-06-08",
  hero: "/articles/caipiroska/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223892302657",
  relatedCocktailSlugs: ["caipiroska"],
  blocks: [
    { kind: "figure", src: "/articles/caipiroska/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "「카이피로스카」는 브라질의 국민 칵테일인 카이피리냐(Caipirinha)의 변형으로, 기주를 카샤샤(Cachaca)에서 보드카로 바꾼 아주 간단한 변주로, 카이피로브스카(Caipirovska)로 불리기도 합니다." },
    { kind: "paragraph", text: "카이피리냐는 브라질의 상파울루 지역에서 오래전부터 시작된 것으로 알려져 있으며, 브라질에서는 국민 칵테일로 취급될 정도로 많은 사랑을 받고 있다고 합니다." },
    { kind: "paragraph", text: "카이피로스카가 어떻게 만들어졌는지는 정확히 알 수는 없습니다만, 대부분 80~90년대에 보드카가 전 세계적으로 인기를 끌었던 시기에 처음 만들어졌다고 추측하고 있습니다." },
    { kind: "paragraph", text: "우리나라에서도 편의점 앱 등을 통해서 카샤샤를 구할 수 있기는 한데, 아무래도 사용할 곳이 많지 않고, 보드카가 훨씬 구하기 쉽기 때문에 카이피리냐보다 이 칵테일을 추천하는 편입니다." },
    { kind: "figure", src: "/articles/caipiroska/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Recipe" },
    { kind: "paragraph", text: "50~60ml 보드카" },
    { kind: "paragraph", text: "라임 반 개" },
    { kind: "paragraph", text: "3~4barspoon 설탕" },
    { kind: "paragraph", text: "라임은 개체마다 양이 다르기 때문에 작은 라임이면 라임 즙을 살짝 더 넣어줍니다." },
    { kind: "figure", src: "/articles/caipiroska/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/caipiroska/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. *라임 반 개를 머들링하기 좋게 자른다." },
    { kind: "paragraph", text: "2. 라임과 설탕을 잔에 넣고, 머들링한다." },
    { kind: "paragraph", text: "3. **크러시드 아이스를 넣고, 다소 길게 섞는다." },
    { kind: "paragraph", text: "4. 얼음을 더 채워주고, 라임을 가니시로 올린다." },
    { kind: "paragraph", text: "*라임은 되도록이면 6등분, 또는 9등분으로 깍둑썰기하는 걸 추천합니다. 웨지를 그대로 넣으면 잔에 비해서 조각이 좀 클 수 있어서 머들링이 잘 안될 수 있습니다." },
    { kind: "paragraph", text: "**크러시드 아이스는 편의점 커피 얼음을 사용해도 괜찮고, 꼭 크러시드 아이스가 아니어도 괜찮습니다." },
    { kind: "figure", src: "/articles/caipiroska/04.webp", width: 966, height: 1288 },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 리프레시 하기 좋은 달고 상큼한 칵테일" },
    { kind: "paragraph", text: "- 비교적 직관적이고 단순한 맛" },
    { kind: "paragraph", text: "카이피로스카는 재료도 구하기 쉽고, 만들는 과정도 쉬운 편인지라 더운 여름에 간편하게 마시기 딱 좋은 칵테일입니다." },
    { kind: "paragraph", text: "또한, 딸기나 블루베리 등을 함께 넣는 종류의 카이피로스카 변형도 다수 존재하니 좀 더 달고 과일의 맛을 느끼고 싶다면 쉽고 자유롭게 변형이 가능하기도 하죠." },
  ],
};
