import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "calvados-tonic",
  category: "cocktail",
  title: "칼바도스 토닉 — 사과 캐릭터가 매력적인 간단한 탄산 칵테일",
  dek: "「칼바도스 토닉」은 진 토닉처럼 이름 그대로 칼바도스라는 술에 토닉 워터를 넣어서 만들어주는 아주아주 간단한 칵테일입니다.",
  publishedAt: "2025-02-06",
  hero: "/articles/calvados-tonic/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223750222811",
  relatedCocktailSlugs: ["calvadostonic"],
  blocks: [
    { kind: "figure", src: "/articles/calvados-tonic/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「칼바도스 토닉」은 진 토닉처럼 이름 그대로 칼바도스라는 술에 토닉 워터를 넣어서 만들어주는 아주아주 간단한 칵테일입니다." },
    { kind: "paragraph", text: "여기서 '칼바도스(Calvados)'란 브랜디의 일종으로, 사과(또는 배)를 발효해서 만든 시드르/사이더(Cidre/Cider)를 증류한 후 숙성을 해서 만들어지는 증류주입니다." },
    { kind: "paragraph", text: "칼바도스는 프랑스 노르망디의 칼바도스라는 지역에서 수확하여 만들어져야 하는데, 「지역명 = 술 이름」이라는 점이 프랑스 꼬냑 지방의 브랜디인 '꼬냑(Cognac)'과 비슷한 이치라 보면 되겠습니다." },
    { kind: "paragraph", text: "칼바도스 또한 꼬냑처럼 AOC(원산지 명칭제)를 통하여 보호 및 관리 받고 있는데, 이를 바탕으로 「AOC 칼바도스(AOC Calvados)」, 「칼바도스 돔프롱테(calvados Domfrontais)」, 「칼바도스 페이도쥬(Calvados Pays d'Auge)」로 분류됩니다." },
    { kind: "paragraph", text: "다시 칼바도스 토닉으로 돌아와서, 칼바도스는 꽤 달달한 사과의 캐릭터를 가지는 술로, 진토닉보다는 훨씬 달고 가볍게 마시기 좋은 칵테일입니다." },
    { kind: "figure", src: "/articles/calvados-tonic/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "브랜드별로 다르겠지만, 토닉 워터는 생각보다 탄산감이 약합니다. 좀 더 탄산감을 원하신다면 소닉 스타일로 탄산수를 소량 추가해주는 걸 추천드립니다. 토닉 워터와 탄산수의 비율은 취향에 따라서 조절해주시면 되겠습니다." },
    { kind: "figure", src: "/articles/calvados-tonic/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 긴 잔에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "2. 칼바도스(+비터)를 잔에 부어주고," },
    { kind: "paragraph", text: "살짝 스터해줍니다." },
    { kind: "paragraph", text: "3. 토닉 워터(+탄산수)를 부어줍니다." },
    { kind: "paragraph", text: "4. 바스푼으로 얼음을 살짝 들었다 놔줍니다." },
    { kind: "paragraph", text: "5. 레몬 껍질에서 오일을 짜넣어주고," },
    { kind: "paragraph", text: "넣어줍니다." },
    { kind: "paragraph", text: "칼바도스 토닉은 아주 간단한 칵테일이지만, 앙고스투라 비터를 넣어서 조금 더 풍부한 맛을 내게 하고, 토닉을 줄이고 탄산을 넣어서 탄산감을 높여준다거나 하는 식으로 디테일함을 더해 줄 수도 있습니다." },
    { kind: "paragraph", text: "빈대로 칼바도스와 토닉 워터만 섞어서 간단하게 마시기에도 아주 훌륭한 칵테일입니다." },
    { kind: "paragraph", text: "잔을 입으로 가져가면 먼저 향긋한 레몬과 달큰한 사과의 향이 나고, 맛은 보면 달달한 사과, 꿀, 토닉 워터의 약간은 쌉쌀함이 청량감 있게 느껴집니다." },
    { kind: "paragraph", text: "칼바도스의 단맛과 토닉 워터의 쓴 맛이 절며하게 밸런스를 이루면서 청량감도 느껴지는 칵테일로, 개인적으로는 봄과 여름에 아주 잘 어울리는 칵테일이라 생각합니다." },
  ],
};
