import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "china-blue",
  category: "cocktail",
  title: "차이나 블루 — 달달한 리치 리큐르가 들어간 아름다운 칵테일",
  dek: "\"차이나 블루\"라는 칵테일은 이름에서 '차이나'는 중국이 아니라 도자기(China 또는 Chinaware)를 의미하며, 전체적으로 풀어보자면 \"청색의 아름다운 도자기\"를 본따 만든 칵테일이라 할 수 있습니다.",
  publishedAt: "2024-10-19",
  hero: "/articles/china-blue/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223625072530",
  relatedCocktailSlugs: ["chinablue"],
  blocks: [
    { kind: "figure", src: "/articles/china-blue/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"차이나 블루\"라는 칵테일은 이름에서 '차이나'는 중국이 아니라 도자기(China 또는 Chinaware)를 의미하며, 전체적으로 풀어보자면 \"청색의 아름다운 도자기\"를 본따 만든 칵테일이라 할 수 있습니다." },
    { kind: "paragraph", text: "차이나 블루는 뭔가 이름 때문에 중국에서 만들어진 칵테일이 아닐까? 싶을 수도 있지만, 사실 일본에서 만들어진 칵테일입니다." },
    { kind: "paragraph", text: "이 칵테일은 일본의 도야마현에 위치한 노포 바인 하쿠바칸(Bar Hakubakan)에서 \"우치다 테루히로\" 바텐더에 의해 만들어 졌다고 합니다." },
    { kind: "paragraph", text: "바 하쿠바칸은 아직도 운영되고 있으며, 할아버지, 아버지, 아들이 3대에 걸쳐서 운영하고 있다고 합니다." },
    { kind: "figure", src: "/articles/china-blue/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml 리치 리큐르 (콰이페 or 디타)" },
    { kind: "paragraph", text: "45ml 자몽즙 (Grapefruit Juice)" },
    { kind: "paragraph", text: "60~75ml 토닉워터 (Tonic Water)" },
    { kind: "paragraph", text: "10ml 블루 큐라소 (Blue Curacao)" },
    { kind: "figure", src: "/articles/china-blue/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/china-blue/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 긴 잔에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "2. 리치 리큐르와 자몽즙을 넣고 잠시 스터해줍니다." },
    { kind: "paragraph", text: "3. 토닉워터를 얼음에 닿지 않게 넣어줍니다." },
    { kind: "paragraph", text: "4. 바스푼으로 얼음을 위아래로 들어줍니다." },
    { kind: "paragraph", text: "5. 블루큐라소를 부어줍니다." },
    { kind: "paragraph", text: "**마실 때는 다시 바스푼으로 얼음을 위아래로 들어주면서 블루 큐라소를 잘 섞은 후 마셔줍니다." },
    { kind: "figure", src: "/articles/china-blue/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "차이나 블루는 리치의 달달하고 화려한 맛에 더해 자몽의 신맛, 블루 큐라소의 달달한 시트러스 등 간단하지만 복합적인 맛을 내는 칵테일이며, 비주얼이 정말 화려합니다." },
    { kind: "paragraph", text: "원래 차이나 블루는 토닉이 들어가지 않고, 자몽즙이 더 많이 들어가는 쇼트 스타일의 칵테일이었다고 하지만 토닉이 첨가되는 롱 스타일의 칵테일이 더 대중적입니다." },
    { kind: "paragraph", text: "차이나 블루는 바텐더마다 만드는 스타일이 다 다른데, 토닉 워터 이외의 재료를 셰이킹하고 토닉워터를 부어주는 경우도 있으며, 이렇게 만드는 편이 일체감은 오히려 좋습니다." },
    { kind: "paragraph", text: "다만, 연한 핑크색에 파란색 블루 큐라소를 부어주면서 색이 변하는 연출을 할 수 있다는 점에서 개인적으로는 블루 큐라소를 따로 부어주는 방법을 더 좋아합니다." },
  ],
};
