import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "espresso-martini-2021",
  category: "cocktail",
  title: "커피를 좋아한다면 꼭 한 번 마셔봐야 하는 칵테일, 에스프레소 마티니",
  dek: "오히려 블랙 러시안의 베리에이션이라고 봐야 하죠.",
  publishedAt: "2021-04-26",
  hero: "/articles/espresso-martini-2021/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222323553996",
  relatedCocktailSlugs: ["espresso"],
  blocks: [
    { kind: "paragraph", text: "에스프레소 마티니는 이름에서도 알 수 있듯이" },
    { kind: "paragraph", text: "에스프레소가 들어간 칵테일입니다." },
    { kind: "paragraph", text: "마티니 베리에이션으로 분류하고 있지만" },
    { kind: "paragraph", text: "마티니 칵테일과는 관련이 없고" },
    { kind: "paragraph", text: "오히려 블랙 러시안의 베리에이션이라고 봐야 하죠." },
    { kind: "paragraph", text: "단지 90년대에 V자 형태의 마티니 글라스에" },
    { kind: "paragraph", text: "보드카가 들어간 칵테일의 이름을 마티니로 붙이는 것이 유행하면서 이름이 변형된 경우로," },
    { kind: "paragraph", text: "원래의 이름은 보드카 에스프레소(Vodka Espresso)" },
    { kind: "paragraph", text: "이전에는 좀 더 직관적인 이름이었네요." },
    { kind: "figure", src: "/articles/espresso-martini-2021/00.webp", width: 342, height: 395, caption: "영국의 전설적인 바텐더 딕 브래드셀(Dick Bradsell),        출처 sub13.net" },
    { kind: "paragraph", text: "에스프레소 마티니는 80년대 영국의 바텐더 딕 브래드셀(Dick Bradsell)에 의해서 탄생되었습니다." },
    { kind: "paragraph", text: "1983년 딕 브레드셀이 소호의 한 레스토랑에서" },
    { kind: "paragraph", text: "일하던 당시 런던의 한 톱 모델이" },
    { kind: "paragraph", text: "\"잠을 깨워줄 수 있는 술\"을 부탁했습니다." },
    { kind: "paragraph", text: "후에 브래드셀은" },
    { kind: "paragraph", text: "\"내가 음료를 서빙하는 곳 바로 옆에 커피 머신이 있었고, 모든 사람들이 보드카를 마시던 시절이었다.\"라며" },
    { kind: "paragraph", text: "에스프레소 마티니의 탄생 비화를 회상하였습니다." },
    { kind: "paragraph", text: "여담으로 이 톱 모델에 대해서" },
    { kind: "paragraph", text: "케이트 모스(Kate Moss) 또는 나오미 캠벨(Naomi Cambell)일 것이라는 추측이 나왔지만" },
    { kind: "paragraph", text: "당시 케이트 모스가 9살, 나오미 캠벨이 13살이었기 때문에 그저 카더라에 불과했죠." },
    { kind: "paragraph", text: "브래드셀은 이 모델이 누구였는지에 대해서는 밝히지 않았다고 합니다." },
    { kind: "paragraph", text: "처음 탄생되었을 때는" },
    { kind: "paragraph", text: "보드카 에스프레소라는 이름으로 소개되었지만" },
    { kind: "paragraph", text: "이후 90년대를 지나면서 그 당시 유행하던 칵테일 작명법으로 에스프레소 마티니라는 이름으로 바뀌게 됩니다." },
    { kind: "paragraph", text: "에스프레소 마티니는 크게 두 가지 레시피가 있습니다." },
    { kind: "paragraph", text: "저는 이 중에서 더 간편한 레시피를 선호하는 편이에요." },
    { kind: "paragraph", text: "바로 '1:1:1' 레시피입니다." },
    { kind: "paragraph", text: "에스프레소 마티니에 들어가는 재료인" },
    { kind: "paragraph", text: "에스프레소, 보드카, 커피리큐르를 같은 비율로 넣어주면 되는 간단한 레시피입니다." },
    { kind: "paragraph", text: "에스프레소는 되도록이면" },
    { kind: "paragraph", text: "방금 내려서 크레마가 가득한 걸 사용해 주세요." },
    { kind: "paragraph", text: "'차가운 칵테일에 뜨거운 에스프레소?'라고" },
    { kind: "paragraph", text: "생각하실 수 있지만 에스프레소의 크레마가 이 칵테일의 생명이라 할 수 있습니다." },
    { kind: "paragraph", text: "저는 집에 돌체가 있어 쉽게 구할 수 있지만" },
    { kind: "paragraph", text: "집에 커피 머신이 없는 분들은 집 근처의" },
    { kind: "paragraph", text: "카페나 편의점에서 에스프레소를 구매하시면 됩니다." },
    { kind: "figure", src: "/articles/espresso-martini-2021/01.webp", width: 406, height: 406 },
    { kind: "figure", src: "/articles/espresso-martini-2021/02.webp", width: 383, height: 383 },
    { kind: "figure", src: "/articles/espresso-martini-2021/03.webp", width: 402, height: 402 },
    { kind: "figure", src: "/articles/espresso-martini-2021/04.webp", width: 409, height: 409, caption: "셰이킹은 강하게!" },
    { kind: "paragraph", text: "셰이커에 에스프레소, 보드카, 커피리큐르를" },
    { kind: "paragraph", text: "각각 1온스(30ml) 씩 넣어주시고" },
    { kind: "paragraph", text: "얼음으로 셰이커를 채운 다음" },
    { kind: "paragraph", text: "다른 칵테일을 만들 때보다 강하게 셰이킹 해주시면 됩니다." },
    { kind: "paragraph", text: "셰이킹 시간은" },
    { kind: "paragraph", text: "\"셰이커가 차가워져서 잡고 있기 어려울 정도\"," },
    { kind: "paragraph", text: "대략 8~10초 길면 12초 정도가 됩니다." },
    { kind: "paragraph", text: "셰이킹을 하고 나면 자잘한 얼음조각이 나오게 되는데" },
    { kind: "paragraph", text: "이런 얼음조각들이 녹으면 칵테일에 예상보다" },
    { kind: "paragraph", text: "물이 더 들어가게 되어 맛이 변하게 됩니다." },
    { kind: "paragraph", text: "얼음조각들이 칵테일에 들어가지 않게" },
    { kind: "paragraph", text: "아래 사진처럼 더블 스트레인을 하는 걸 추천드립니다." },
    { kind: "figure", src: "/articles/espresso-martini-2021/05.webp", width: 436, height: 436, caption: "'스트레인(Strain)'이란 완성된 칵테일을 얼음과 분리하여 잔에 따라주는 과정" },
    { kind: "paragraph", text: "마지막으로 옵션이지만" },
    { kind: "paragraph", text: "커피콩으로 가니시를 하면 에스프레소 마티니가 완성됩니다." },
    { kind: "figure", src: "/articles/espresso-martini-2021/06.webp", width: 966, height: 543, caption: "완성된 에스프레소 마티니" },
    { kind: "paragraph", text: "에스프레소 마티니의 가장 큰 매력은" },
    { kind: "paragraph", text: "에스프레소의 크레마로 인해 생기는 거품 층입니다." },
    { kind: "paragraph", text: "다른 아메리카노나 콜드브루로는 거품 층이 생기지 않거나 너무 적은 거품 층이 생기게 됩니다." },
    { kind: "paragraph", text: "거품 층을 제대로 만들기 위한 방법으로는" },
    { kind: "paragraph", text: "1. 갓 내린 에스프레소를 사용하기" },
    { kind: "paragraph", text: "2. 강하게 셰이킹 하기" },
    { kind: "paragraph", text: "가 있습니다." },
    { kind: "paragraph", text: "에스프레소 마티니는 커피를 좋아하는 분들이" },
    { kind: "paragraph", text: "특히 좋아할 만한 칵테일입니다." },
    { kind: "paragraph", text: "다만 30도 정도 되는 도수가 높은 술이기 때문에" },
    { kind: "paragraph", text: "주의해서 마셔주세요!" },
    { kind: "paragraph", text: "#칵테일 #커피칵테일 #커피 #에스프레소 #마티니 #앱솔루트 #보드카 #깔루아" },
    { kind: "paragraph", text: "#홈텐딩 #홈칵테일 #홈바" },
  ],
};
