import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "espresso-martini",
  category: "cocktail",
  title: "에스프레소 마티니 — 커피와 술이 동시에 필요할 때",
  dek: "\"정신이 번쩍 들게 해주고, 그러고 나서 제대로 취하게 만들어줘.\" 런던의 칵테일 킹 딕 브래드셀이 그 주문에 내놓은 대답.",
  publishedAt: "2025-04-05",
  hero: "/articles/espresso-martini/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223823035796",
  relatedCocktailSlugs: ["espresso"],
  blocks: [
    { kind: "figure", src: "/articles/espresso-martini/00.webp", width: 966, height: 543 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「에스프레소 마티니」는 1980년대 후반에 런던의 '프레드 바(Fred's Bar)'에서 탄생했는데, 커피 칵테일 중 독보적인 인기를 끌고 있는 이 칵테일은 런던의 칵테일 킹이었던 딕 브래드셀(Dick Bradsell)에 의해 만들어졌습니다." },
    { kind: "figure", src: "/articles/espresso-martini/01.webp", width: 966, height: 1288 },
    { kind: "quote", text: "Wake me up, and then Fxxk me up" },
    { kind: "quote", text: "정신이 번쩍 들게 해주고, 그러고 나서 제대로 취하게 만들어줘." },
    { kind: "paragraph", text: "어느 날, 어린 모델(나중에는 유명해진)이 바에 들어와서는 \"정신이 번쩍 들게 해주고, 그러고 나서 제대로 취하게 만들어줘.\"라는 주문을 했다고 합니다." },
    { kind: "paragraph", text: "이런 재밌는 요청에 브래드셀은 보드카, 커피 리큐르 그리고 갓 내린 에스프레소를 조합해서 칵테일을 만들어냈는데, 당시에 머신에서 갓 내린 에스프레소는 칵테일 재료로 거의 쓰이지 않았기 때문에 아주 담대한 선택이었죠." },
    { kind: "paragraph", text: "에스프레소 마티니는 기주와 이름에서 당시 칵테일 트렌드를 아주 잘 보여주는데, 1980년대엔 보드카 칵테일들이 인기였고, 1990년대에는 마티니 잔('V' 모양)에 담긴 칵테일에 '~마티니' 같은 이름을 붙이는 것이 유행이었죠." },
    { kind: "paragraph", text: "사실 브래드셀이 처음 칵테일을 만들었을 때는 「보드카 에스프레소(Vodka Espresso)」라는 이름을 붙였었는데, 1990년대 유행에 따라서 이름을 바꿨다고 합니다. 저는 지금의 이름이 좀 더 캐치한 것 같네요." },
    { kind: "paragraph", text: "*'애플 마티니, 레몬 드롭 마티니' 등처럼 이런 식으로 이름 붙은 마티니 칵테일이 많은데, 이런 칵테일들은 진과 드라이 버무스가 들어가는 클래식 마티니의 변형도 아니고, 잔의 모양 빼고는 아무런 관계가 없습니다." },
    { kind: "figure", src: "/articles/espresso-martini/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "20ml 냉동한 보드카(Vodka)" },
    { kind: "paragraph", text: "30ml 미스터 블랙(Mr Black)" },
    { kind: "paragraph", text: "30ml 갓 내린 에스프레소(Espresso)" },
    { kind: "paragraph", text: "10ml 리치 시럽 or  8g 데메라라 설탕" },
    { kind: "paragraph", text: "*에스프레소 마티니는 재료에 따라서, 만드는 사람에 따라서 레시피가 천차 만별입니다. 이런저런 레시피를 많이 비교해 보시고 만드는 걸 추천드립니다." },
    { kind: "paragraph", text: "다만, 깔루아로 만드는 경우에는 시럽(또는 설탕)을 빼고 재료를 1:1:1로 넣어서 만드는 게 가장 일반적인 레시피기도 합니다." },
    { kind: "figure", src: "/articles/espresso-martini/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 쉐이커에 모든 재료를 넣어줍니다." },
    { kind: "paragraph", text: "2. 쉐이커에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "3. 쉐이킹 후에 차갑게 식힌 칵테일 잔에 따라준다." },
    { kind: "paragraph", text: "4. 거품층 위에 커피콩 3개를 얹어준다(옵션)." },
    { kind: "heading", text: "에스프레소 마티니의 맛" },
    { kind: "paragraph", text: "- 커피의 풍미에 리큐르와 설탕의 적당한 단맛." },
    { kind: "paragraph", text: "- 에스프레소 마티니는 재료의 선택과 비율에 따라서 맛의 차이가 꽤 많이 나게 됩니다." },
    { kind: "paragraph", text: "- 조합에 따라서는 더위사냥 같은 맛의 에스프레소 마티니가 만들어지기도 하죠." },
    { kind: "heading", text: "쫀쫀하고 풍부한 거품층" },
    { kind: "paragraph", text: "- 갓 내린 에스프레소를 사용하는 걸 추천하는데, 크레마가 칵테일의 거품층 형성에 아주 중요하기 때문." },
    { kind: "paragraph", text: "- 개인적으로는 캡슐 커피 머신을 사용." },
    { kind: "paragraph", text: "- 쉐이킹을 다소 강하게 해주기." },
    { kind: "heading", text: "온도 조절" },
    { kind: "paragraph", text: "- 갓 내린 에스프레소는 뜨겁기 때문에 보드카는 냉동실에서 차갑게 보관해 두기." },
    { kind: "paragraph", text: "- 상온의 보드카를 사용하면 얼음이 원하는 것보다 더 녹게 되고, 칵테일의 맛이 좀 맹맹해질 수 있습니다." },
  ],
};
