import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "espresso-martini-mr-black",
  category: "cocktail",
  title: "미스터블랙으로 만든 에스프레소 마티니",
  dek: "일단 미스터블랙이라는 리큐르에 대해서 알아야 합니다.",
  publishedAt: "2021-04-26",
  hero: "/articles/espresso-martini-mr-black/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222323597775",
  relatedCocktailSlugs: ["espresso"],
  blocks: [
    { kind: "paragraph", text: "미스터블랙으로 만든 에스프레소 마티니는" },
    { kind: "paragraph", text: "어떤 게 특별할까요?" },
    { kind: "paragraph", text: "일단 미스터블랙이라는 리큐르에 대해서 알아야 합니다." },
    { kind: "paragraph", text: "미스터블랙은 쉽게 말해서 설탕은 적게 넣어" },
    { kind: "paragraph", text: "단 맛을 줄이고," },
    { kind: "paragraph", text: "커피 함량을 높여 커피 본연의 향과 맛에 집중한" },
    { kind: "paragraph", text: "리큐르라고 보면 되죠." },
    { kind: "paragraph", text: "미스터블랙은" },
    { kind: "paragraph", text: "에스프레소와 미스터블랙의 비율을 1:2로 하는" },
    { kind: "paragraph", text: "자신들만의 에스프레소 마티니 레시피를 만들었습니다." },
    { kind: "paragraph", text: "별로 특별할 것 없다고 생각할 수 있지만" },
    { kind: "paragraph", text: "보드카를 넣지 않고 커피와 커피리큐르만 들어간 칵테일로 커피 본연의 맛에 집중한 칵테일이라는 것이 특별합니다." },
    { kind: "paragraph", text: "커피 자체의 맛이라는 본인들의 강점을" },
    { kind: "paragraph", text: "잘 반영한 칵테일이라고 할 수 있죠." },
    { kind: "paragraph", text: "만드는 것 자체는 간단합니다." },
    { kind: "paragraph", text: "에스프레소 1온스(30ml)와 미스터블랙 2온스(60ml)를 셰이커에 넣고" },
    { kind: "paragraph", text: "얼음을 채워준 후" },
    { kind: "paragraph", text: "강하게 셰이킹을 하면 됩니다." },
    { kind: "paragraph", text: "셰이킹은 \"셰이커가 차가워져서 잡고 있지 못할 정도\"," },
    { kind: "paragraph", text: "대략 8~12초 동안 셰이킹 해주면 됩니다." },
    { kind: "figure", src: "/articles/espresso-martini-mr-black/00.webp", width: 966, height: 664, caption: "완성된 미스터블랙 에스프레소 마티니" },
    { kind: "paragraph", text: "사진에서 볼 수 있는 것처럼" },
    { kind: "paragraph", text: "거품이 아주 오밀조밀하게 만들어집니다." },
    { kind: "paragraph", text: "에스프레소뿐만 아니라 미스터블랙 자체에도 커피가 들어있기 때문에 거품 층이 더 잘 형성되는 것 같습니다." },
    { kind: "paragraph", text: "미스터블랙에서 주는 약간의 단맛만 있기 때문에" },
    { kind: "paragraph", text: "깔루아로 만든 에스프레소 마티니보다 훨씬 단맛이 적습니다." },
    { kind: "paragraph", text: "그렇지만 커피 본연의 쌉쌀한 향과 맛은 더욱 잘 살리고 있네요." },
    { kind: "paragraph", text: "그렇기 때문에 커피의 쌉쌀한 맛을 선호하는 사람들에게는" },
    { kind: "paragraph", text: "미스터블랙으로 만드는 에스프레소 마티니를," },
    { kind: "paragraph", text: "단맛의 칵테일을 선호하는 사람들에게는" },
    { kind: "paragraph", text: "깔루아로 만드는 에스프레소 마티니를 추천하고 싶습니다." },
    { kind: "paragraph", text: "주의할 점으로는" },
    { kind: "paragraph", text: "카페인이 무지막지하게 들어간 칵테일이라는 것입니다." },
    { kind: "paragraph", text: "미스터블랙 1온스(30ml)와 에스프레소 1온스(30ml)에 들어있는 카페인의 함량이 같은데" },
    { kind: "paragraph", text: "결국 한 잔에 에스프레소 3샷을 마시는 것이죠." },
    { kind: "paragraph", text: "마시는 날 잠은 다 잤다고 봐야 할 듯" },
    { kind: "paragraph", text: "다행인 것은 도수가 보드카가 들어가지 않고" },
    { kind: "paragraph", text: "미스터블랙이 23도이기 때문에" },
    { kind: "paragraph", text: "기존의 에스프레소 마티니보다 훨씬 낮다는 것" },
    { kind: "paragraph", text: "조만간 바에서도 미스터블랙으로 만든 칵테일들을" },
    { kind: "paragraph", text: "만나게 되면 좋겠습니다." },
    { kind: "paragraph", text: "#칵테일 #커피 #커피칵테일 #에스프레소 #마티니 #미스터블랙 #리큐르 #리큐어" },
    { kind: "paragraph", text: "#홈텐딩 #홈칵테일 #홈바" },
    { kind: "paragraph", text: "인스타그램" },
  ],
};
