import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "garibaldi",
  category: "cocktail",
  title: "캄파리-오렌지 말고 가리발디",
  dek: "캄파리와 가장 잘 어울리는 조합은 뭐니뭐니해도 오렌지입니다.",
  publishedAt: "2021-09-26",
  hero: "/articles/garibaldi/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222517436206",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "paragraph", text: "캄파리는 이탈리아의 쌉쌀-달달한 리큐르로," },
    { kind: "paragraph", text: "다양한 칵테일에 이용되고 있으며" },
    { kind: "paragraph", text: "전세계에서 큰 사랑을 받고 있습니다." },
    { kind: "paragraph", text: "캄파리와 가장 잘 어울리는 조합은 뭐니뭐니해도 오렌지입니다." },
    { kind: "paragraph", text: "캄파리 자체에서도 오렌지의 단 맛이 나 좋은 조합을 이루며," },
    { kind: "paragraph", text: "캄파리-오렌지는 캄파리의 쓴 맛을 줄이고 오렌지즙의 단 맛을 통해" },
    { kind: "paragraph", text: "캄파리를 부담되지 않고 간편하게 즐길 수 있는 칵테일 중 하나입니다." },
    { kind: "paragraph", text: "가리발디는 이 캄파리-오렌지를" },
    { kind: "paragraph", text: "좀 더 재미있고 부드럽게 즐길 수 있는 칵테일입니다." },
    { kind: "paragraph", text: "About The Drink" },
    { kind: "paragraph", text: "가리발디는 이탈리아 통일 영웅인데" },
    { kind: "paragraph", text: "왜 칵테일에 이런 이름을 붙였을지 의문일 수도 있습니다." },
    { kind: "paragraph", text: "여기에는 두가지 설이 있습니다." },
    { kind: "paragraph", text: "첫째로는" },
    { kind: "paragraph", text: "재료 중 하나인 캄파리는 이탈리아의 북부인 밀라노에서," },
    { kind: "paragraph", text: "오렌지는 이탈리아의 남부에서 가져와" },
    { kind: "paragraph", text: "잔 안에서 하나의 칵테일로 완성되어" },
    { kind: "paragraph", text: "이탈리아의 통일을 의미한다는 것" },
    { kind: "paragraph", text: "둘째로는" },
    { kind: "paragraph", text: "가리발디의 군대인 '붉은 셔츠단 / 가리발디니'가" },
    { kind: "paragraph", text: "입던 옷의 색과 닮았다는 것" },
    { kind: "paragraph", text: "둘 중 무엇이든 가리발디와 관련이 있어 이러한 이름이 붙은 것으로 보입니다." },
    { kind: "paragraph", text: "단순한 캄파리-오렌지였던 이 칵테일이 유명세를 얻게 된 것은" },
    { kind: "paragraph", text: "뉴욕의 단테 바(bar Dante)의 나렌 영(Naren Young)에 의해서입니다." },
    { kind: "paragraph", text: "그는 오렌지 즙을 블랜더에 넣고 돌려 최대한으로 공기를 주입하였으며," },
    { kind: "paragraph", text: "이를 통해 지루했던 캄파리-오렌지를 특별한 칵테일로 변모시켰습니다." },
    { kind: "paragraph", text: "Ingredients?" },
    { kind: "figure", src: "/articles/garibaldi/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "재료는 캄파리와 오렌지(또는 과즙 100% 오렌지 주스) 2가지로" },
    { kind: "paragraph", text: "구하기 아주 간단합니다." },
    { kind: "paragraph", text: "캄파리는 이마트나 편의점에서도 쉽게 구할 수 있습니다." },
    { kind: "paragraph", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 롱 글라스에 얼음을 채우고," },
    { kind: "paragraph", text: "캄파리를 45ml, 오렌지 즙을 30ml를 넣어주고 짧게 스터해줍니다." },
    { kind: "paragraph", text: "2. 셰이커(블렌더를 이용해도 됨)에 오렌지 즙 90ml를 넣고" },
    { kind: "paragraph", text: "강하게 셰이킹을 해줍니다." },
    { kind: "paragraph", text: "3. 잔 안에 있는 캄파리와 섞이지 않게" },
    { kind: "paragraph", text: "셰이킹한 오렌지 즙을 조심스럽게 잔 안에 따라줍니다." },
    { kind: "paragraph", text: "4. 오렌지 휠 반쪽으로 가니시를 해줍니다." },
    { kind: "figure", src: "/articles/garibaldi/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "이 칵테일의 키는 오렌지 즙을 강하게 흔들어" },
    { kind: "paragraph", text: "공기를 억지로 주입해주는 것입니다." },
    { kind: "paragraph", text: "이러한 과정을 거치게 되면 오렌지 즙은 아주 부드러워지게 되어" },
    { kind: "paragraph", text: "캄파리의 쓴맛을 좀 더 잘 잡아주기 때문에" },
    { kind: "paragraph", text: "일반 캄파리-오렌지보다 훨씬 마시기 편해집니다." },
    { kind: "paragraph", text: "'일반적인 캄파리-오렌지와 큰 차이가 나겠어?'" },
    { kind: "paragraph", text: "라고 생각할 수도 있지만 칵테일의 질감에서 아주 큰 차이가 납니다." },
    { kind: "paragraph", text: "제대로 공기가 주입되면 아주 부드러워지고," },
    { kind: "paragraph", text: "캄파리의 쓴맛과 오렌지 즙의 단맛이 절묘한 밸런스를 이루게 됩니다." },
    { kind: "paragraph", text: "인스타그램" },
  ],
};
