import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "giffard-home-cocktails",
  category: "cocktail",
  title: "아침의 햇살부터 밤의 티파티까지 — 지파드 시럽·리큐르로 하루를 담은 홈칵테일",
  dek: "아침부터 밤까지, 지파드 시럽과 리큐르로 만든 홈칵테일 모음. 지파드의 지원을 받아 쓴 제휴 콘텐츠다.",
  publishedAt: "2026-05-25",
  hero: "/articles/giffard-home-cocktails/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224295903778",
  relatedCocktailSlugs: [],
  isSponsored: true,
  blocks: [
    { kind: "paragraph", text: "\"본 콘텐츠는 지파드로부터 제품 및 활동 지원을 받아 작성되었습니다.\"" },
    { kind: "figure", src: "/articles/giffard-home-cocktails/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "이번 지파드 서포터즈 홈칵테일 팀미션에서는 하루가 흘러가는 분위기를 두 잔의 칵테일을 지파드 시럽과 지파드 리큐르로 표현해보았습니다." },
    { kind: "paragraph", text: "햇살이 가장 부드러운 아침부터 이른 오후의 공기부터, 하루 끝에 천천히 내려앉는 밤의 온도까지 지파드 시럽과 지파드 리큐르를 활용해 시간의 흐름을 한 잔 안에 담아보려 노력했습니다" },
    { kind: "figure", src: "/articles/giffard-home-cocktails/01.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/giffard-home-cocktails/02.webp", width: 966, height: 1449 },
    { kind: "figure", src: "/articles/giffard-home-cocktails/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "《Sunday Spritz》" },
    { kind: "paragraph", text: "이른 낮시간 창문으로 햇빛이 밝게 비추는 순간을 떠올리며 만든 논알콜 칵테일로, 복잡한 맛보다는 가볍고 산뜻한 인상을 남기기 위해 허브와 시트러스 중심으로 구성했습니다." },
    { kind: "paragraph", text: "로즈마리의 은은한 허브감과 함께 블러드오렌지의 달큰한 과실감이 자연스럽게 이어지고, 논알콜 스파클링 와인과 탄산수의 기포가 전체적인 분위기를 가볍게 정리해줍니다." },
    { kind: "paragraph", text: "이름에서도 알 수 있듯이 칵테일의 구조는 햇살과 아주 잘 어울리는 여러 스프리츠 계열의 칵테일을 참고해서 만들었는데, 칵테일의 분위기와 맛 모두 이른 브런치와 잘 어우러지는 칵테일입니다." },
    { kind: "paragraph", text: "📍Recipe" },
    { kind: "paragraph", text: "지파드 로즈마리 시럽 30ml" },
    { kind: "paragraph", text: "지파드 블러드오렌지 시럽 10ml" },
    { kind: "paragraph", text: "논알콜 스파클링 와인 90ml" },
    { kind: "paragraph", text: "탄산수 90ml" },
    { kind: "paragraph", text: "📍Garnish" },
    { kind: "paragraph", text: "오렌지 하프 휠 / 로즈마리" },
    { kind: "paragraph", text: "📍How to Mix" },
    { kind: "paragraph", text: "1. 잔에 로즈마리, 블러드오렌지 시럽을 넣고, 탄산수를 살짝 넣어준다." },
    { kind: "paragraph", text: "2. 얼음을 넣고 잠시 스터해준다." },
    { kind: "paragraph", text: "3. 논알콜 스파클링 와인과 탄산수를 넣고, 얼음을 움직여 섞어준다." },
    { kind: "paragraph", text: "4. 오렌지와 로즈마리로 가니시해준다." },
    { kind: "figure", src: "/articles/giffard-home-cocktails/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/giffard-home-cocktails/05.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/giffard-home-cocktails/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/giffard-home-cocktails/07.webp", width: 966, height: 967 },
    { kind: "paragraph", text: "《Garden Tea Party》" },
    { kind: "paragraph", text: "밤에는 조금 더 차분하고 깊은 무드로 접근했는데, 앞선 허브감과 과실감의 연장선상에서 정원이 있는 티 파티가 밤까지 이어진다면 어떤 맛일까 상상하며 만든 칵테일입니다." },
    { kind: "paragraph", text: "럼의 묵직한 베이스 위에 피치와 카시스 리큐르로 과실감을 더하고, 자스민 티의 플로럴한 캐릭터와 시나몬의 따뜻한 향신료 캐릭터를 겹쳐 정원에서 즐기는 밤 공기처럼 부드럽고 천천히 퍼지는 느낌을 표현했습니다." },
    { kind: "paragraph", text: "클레리파이드 밀크 펀치 방식으로 완성해 투명하게 만들고, 다양한 꽃을 가니시로 해서 정원에서의 티 파티에 어울릴만한 느낌으로 표현했습니다." },
    { kind: "paragraph", text: "📍Recipe" },
    { kind: "paragraph", text: "플렌터레이 화이트 럼 45ml" },
    { kind: "paragraph", text: "지파드 크렘 드 페슈  20ml" },
    { kind: "paragraph", text: "지파드 크렘 드 카시스 10ml" },
    { kind: "paragraph", text: "트리플섹 15ml" },
    { kind: "paragraph", text: "자스민 티 50ml" },
    { kind: "paragraph", text: "레몬즙 17ml" },
    { kind: "paragraph", text: "시나몬 시럽 15ml" },
    { kind: "paragraph", text: "우유 50ml" },
    { kind: "paragraph", text: "📍Garnish" },
    { kind: "paragraph", text: "오렌지 슬라이스 / 자스민 잎 / 식용꽃" },
    { kind: "paragraph", text: "📍How to Mix" },
    { kind: "paragraph", text: "1. 우유, 가니시 이외의 재료를 모두 섞어준다." },
    { kind: "paragraph", text: "2. 우유에 섞은 재료를 부어주면서 저어준다." },
    { kind: "paragraph", text: "3. 잠시 후 커피 필터로 걸러준다." },
    { kind: "paragraph", text: "4. 걸러진 칵테일을 얼음이 든 잔에 부어주고, 가니시해준다" },
    { kind: "paragraph", text: "이번 팀미션에서는 단순히 두 잔의 칵테일을 만드는 것을 넘어, 아침부터 밤까지 이어지는 하루의 흐름과 분위기를 지파드만의 향과 맛으로 표현해보고자 했습니다." },
    { kind: "paragraph", text: "가볍고 밝은 햇살이 떠오르는 낮의 무드부터, 천천히 온도가 내려앉는 밤의 공기까지. 서로 다른 시간대의 감정을 각기 다른 스타일의 칵테일 안에 담아내며, 지파드가 가진 다양한 매력을 자연스럽게 풀어내고 싶었습니다." },
    { kind: "paragraph", text: "\"지나친 음주는 뇌졸중, 기억력 손상이나 치매를 유발합니다. 임신 중 음주는 기형아 출생 위험을 높입니다.\"" },
  ],
};
