import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "gin-rickey",
  category: "cocktail",
  title: "진 리키 — 무더운 여름 갈증을 날려줄 상쾌한 한 잔",
  dek: "\"진 리키\"는 아주 오래된 칵테일임에도 불구하고 그 기원이 상당히 명확한데, 19세기 후반 워싱턴 DC에서 민주당의 로비스트로 활동하던 \"조 리키(Joe Rickey)\"의 이름을 딴 것이며, 1880년 워싱턴 DC의 \"슈메이커스 바(Shoomaker’",
  publishedAt: "2024-08-06",
  hero: "/articles/gin-rickey/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223538391938",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/gin-rickey/00.webp", width: 382, height: 382 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"진 리키\"는 아주 오래된 칵테일임에도 불구하고 그 기원이 상당히 명확한데, 19세기 후반 워싱턴 DC에서 민주당의 로비스트로 활동하던 \"조 리키(Joe Rickey)\"의 이름을 딴 것이며, 1880년 워싱턴 DC의 \"슈메이커스 바(Shoomaker’s bar)\"에서 \"조지 A. 윌리엄슨(George A. Williamson)\"이라는 바텐더에 의해 만들어졌다 합니다." },
    { kind: "paragraph", text: "이 \"조 리키\"라는 인물은 버번 위스키&소다를 즐겨 마셨는데, 하루는 바텐더에게 라임을 조금 추가해 줄 것을 요청하였고, 그렇게 버번 리키(Bourbon Rickey)가 탄생하게 되었습니다." },
    { kind: "paragraph", text: "이후에 버번은 진으로 대체되면서 진 리키가 유행하게 되었고, 1900년 즈음에는 리키 스타일의 칵테일은 진 리키가 기본적인 레시피로 자리잡았다고 합니다." },
    { kind: "paragraph", text: "다만, 이러한 스토리는 각 문헌마다 차이가 있는데, 리키 스타일의 칵테일의 탄생이 버번 위스키인지 라이 위스키 베이스인지 확실하지 않다는 설, 라임이 아닌 레몬이 원조라는 설, 탄생 계기가 조금씩 다른 설 등 다양하게 있습니다." },
    { kind: "paragraph", text: "리키 스타일의 칵테일이 위스키 하이볼에서 파생된 것이니, \"진 리키\"를 가장 심플하게 표현하자면 \"라임즙이 소량 들어간 진 하이볼\"이라 할 수 있겠네요." },
    { kind: "figure", src: "/articles/gin-rickey/01.webp", width: 500, height: 500 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "40ml 진 (Gin)" },
    { kind: "paragraph", text: "8ml 라임즙 (Lime Juice)" },
    { kind: "paragraph", text: "100 ~ 120ml 탄산수 (Soda Water)" },
    { kind: "paragraph", text: "가니시: 라임 웨지" },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 차갑게 해둔 긴 잔에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "2. 라임즙과 진을 부어준 후, 살짝 스터해줍니다." },
    { kind: "paragraph", text: "3. 탄산수를 얼음에 닿지 않게 부어줍니다." },
    { kind: "paragraph", text: "4. 바스푼으로 얼음을 살짝 들어줍니다." },
    { kind: "paragraph", text: "5. 라임 웨지로 가니시해줍니다." },
    { kind: "figure", src: "/articles/gin-rickey/02.webp", width: 500, height: 500 },
    { kind: "paragraph", text: "\"진 리키\"는 라임과 진의 허브감에 탄산이 더해져 아주 상큼하고, 깔끔하게 맛이 딱 떨어지는 칵테일로, 갈증나는 여름에 딱 어울리죠." },
    { kind: "paragraph", text: "사실 진 하이볼에 라임즙을 살짝 더한 것인데, 이 때 진의 선택과 라임즙의 양이 맛에 꽤 큰 영향을 줍니다. 아무래도 들어가는 재료가 적으니까요." },
    { kind: "paragraph", text: "진은 개인적으로 탱커레이, 고든스, 비피터와 같이 스탠다드한 것들이나 카다멈 같이 시원하고 상쾌한 향이 메인인 진(ex. 포필라스 네이비 스트렝스를 소량 블렌딩)을 사용하는 걸 추천드립니다. 아무래도 진 리키의 상큼하고 깔끔한 캐릭터를 잘 살릴 수 있는 기주가 좋습니다." },
    { kind: "paragraph", text: "다만, 이 또한 제 개인적인 취향이니 개인의 취향에 잘 맞는 진을 사용해도 전혀 상관 없습니다." },
  ],
};
