import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "gin-fizz",
  category: "cocktail",
  title: "진 피즈 — 덥거나 비오는 날에 첫 잔으로 마시기 완벽한 한 잔",
  dek: "\"진 피즈\"는 그 기원이 모호한 칵테일 중에 하나인데, 그도 그럴 것이 아주 오래된 칵테일이기 때문입니다. 그중 유력하다고 여겨지는 설이 두 가지가 있습니다.",
  publishedAt: "2024-08-26",
  hero: "/articles/gin-fizz/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223561330867",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/gin-fizz/00.webp", width: 500, height: 500 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"진 피즈\"는 그 기원이 모호한 칵테일 중에 하나인데, 그도 그럴 것이 아주 오래된 칵테일이기 때문입니다. 그중 유력하다고 여겨지는 설이 두 가지가 있습니다." },
    { kind: "paragraph", text: "첫 번째 설은 진피즈가 처음으로 등장한 기록은 제리 토마스(Jerry Thomas)의 저서인 바텐더스 가이드(The Bar-tenders Guide)의 재판(再版, 1876년)의 부록이었다는 것이며, 이건 서양에서 정설로 여겨지는 것 같습니다." },
    { kind: "paragraph", text: "두 번째 설은 1888년 뉴올리언스의 임페리얼 캐비닛 살롱(Imperial Cabinet Saloon)의 오너인 헨리 라모스(Henry Carl Ramos)에 의해 만들어졌다는 설인데, 주로 일본에서 정설로 여겨집니다." },
    { kind: "paragraph", text: "개인적으로 이런 형태의 기주, 산(시트러스), 당(설탕)에 탄산을 더하는 식의 칵테일은 훨씬 이전부터 존재했을 것이고, 두 번째 설은 일반적인 진피즈와 다른 \"라모스 진 피즈\"의 기원을 얘기하는 것이라 생각합니다." },
    { kind: "paragraph", text: "즉, 진 피즈라는 칵테일과 명칭이 이미 존재한 상태에서 라모스가 본인 스타일대로 만들어낸 라모스 진 피즈를 \"라모스씨의 진 피즈\"로 지칭하다가 그가 진 피즈를 만들어냈다고 잘못 알려진 게 아닐까 싶습니다." },
    { kind: "paragraph", text: "진 피즈는 \"톰 콜린스(Tom Collins)\"라는 형제 칵테일이 있는데, 톰 콜린스는 진 피즈와 같은 재료를 빌드로 만들어 내는 칵테일이며, 진의 종류가 다르고, 다일루션 차이로 탄산감이 다른 등의 차이가 있습니다." },
    { kind: "figure", src: "/articles/gin-fizz/01.webp", width: 500, height: 500 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "45ml 진 (Gin)" },
    { kind: "paragraph", text: "20ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "7.5~10ml 설탕 시럽 (Simple Syrup)" },
    { kind: "paragraph", text: "탄산수" },
    { kind: "paragraph", text: "가니시: 레몬 필(Lemon Peel)" },
    { kind: "figure", src: "/articles/gin-fizz/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 탄산수 외에 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 얼음을 채운 긴 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 탄산수를 적당량 채워줍니다." },
    { kind: "paragraph", text: "5. 레몬 필에서 오일을 짜주고," },
    { kind: "paragraph", text: "잘 다듬어서 넣어줍니다." },
    { kind: "paragraph", text: "진 피즈는 상큼하고 산뜻한 칵테일로, 더운 날씨나 비 내리는 날에 첫 잔으로 마시기 아주 좋은 칵테일입니다." },
    { kind: "paragraph", text: "진 피즈에서 가장 중요하다고 생각되는 건 당과 산의 조화입니다. 너무 달아져버리면 레모네이드 같은 느낌이 될 수 있으니 어느 정도 산과 당을 조절하면서 진의 캐릭터도 다소는 느껴질 수 있어야겠습니다." },
    { kind: "paragraph", text: "또, 탄산을 너무 많이 넣어버리면 맛이 밍밍해져 버릴 수 있습니다. '적당량'이라고 하면 참 애매한데, 저는 개인적으로 45-60ml 정도 넣는 것 같습니다." },
    { kind: "paragraph", text: "여담으로 만화 바텐더의 영향 때문에 진 피즈가 바텐더의 전투력 측정기라고 여기는 경우가 꽤 많습니다만, 그건 만화일 뿐이니 너무 그대로 받아들이지 않는 편이 좋지 않을까 싶습니다." },
  ],
};
