import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "gin-gin-mule",
  category: "cocktail",
  title: "진진뮬 — 모히또와 모스코뮬이 만난 칵테일, 근데 이제 진을 곁들인",
  dek: "\"진 진 뮬\"은 2000년 오드리 손더스(Audrey Saunders)가 뉴욕의 바 비콘(Beacon)에서 만들어낸 칵테일입니다.",
  publishedAt: "2024-08-20",
  hero: "/articles/gin-gin-mule/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223554367690",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/gin-gin-mule/00.webp", width: 500, height: 500 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "\"진 진 뮬\"은 2000년 오드리 손더스(Audrey Saunders)가 뉴욕의 바 비콘(Beacon)에서 만들어낸 칵테일입니다." },
    { kind: "paragraph", text: "어느 날 오드리 손더스의 스승인 데일 데그로프(Dale Degroff)는 그녀에게 신선한 허브(민트)를 사용해서 만드는 클래식한 모히또를 만드는 방법을 보여주었습니다." },
    { kind: "paragraph", text: "이게 무슨 대수냐라고 할 수 있지만, 당시만 하더라도 칵테일에 신선한 재료를 사용하는 경우가 많지 않았고, 크래프트 칵테일 운동의 선구적인 역할을 했던 데일 데그로프 정도였으니 관심을 가졌을 겁니다." },
    { kind: "paragraph", text: "오드리 손더스는 보드카가 주류인 시절에 진에 많은 관심을 두고 있었는데, 모히또(Mojito)에 모스코 뮬(Moscow Mule)을 더하고, 기주를 진으로 바꿔서 이 칵테일을 만들어냈습니다." },
    { kind: "paragraph", text: "당시 주류가 아닌 기주에 신선한 재료를 사용한 것뿐만 아니라, 진저비어까지 수제로 만들어서 이 칵테일을 만들어냈는데, 이러한 점이 시간이 지나면서 이 칵테일을 모던 클래식 칵테일에서 중요한 자리를 차지하게 해줍니다." },
    { kind: "paragraph", text: "이후 오드리 손더스는 2005년 뉴욕에 페구 클럽(Pegu Club)이라는 바를 오픈했는데, 진진뮬은 2020년 이 바가 문을 닫을 때까지 당당하게 주요 메뉴의 하나로 자리 잡았습니다." },
    { kind: "figure", src: "/articles/gin-gin-mule/01.webp", width: 436, height: 436 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "45ml 진 (Gin)" },
    { kind: "paragraph", text: "20ml 라임즙 (Lime Juice)" },
    { kind: "paragraph", text: "10ml 설탕 시럽 (Simple Syrup)" },
    { kind: "paragraph", text: "민트 잎 6~8개" },
    { kind: "paragraph", text: "진저비어 (Ginger Beer)" },
    { kind: "paragraph", text: "가니시: 민트 다발 (Mint Bouquet)" },
    { kind: "figure", src: "/articles/gin-gin-mule/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 진저비어를 제외한 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 머들러로 민트 입을 너무 강하지 않게 눌러줍니다." },
    { kind: "paragraph", text: "3. 셰이커에 얼음을 채운 후, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "4. 얼음을 채운 잔에 **더블스트레이닝해줍니다." },
    { kind: "paragraph", text: "5. 진저비어를 채워줍니다." },
    { kind: "paragraph", text: "6. 민트 다발로 가니 시 해줍니다." },
    { kind: "figure", src: "/articles/gin-gin-mule/03.webp", width: 448, height: 448 },
    { kind: "paragraph", text: "진진뮬을 마시려고 잔을 입으로 가져다 대면, 먼저 코에 민트 다발의 향이 상쾌하고 기분 좋게 다가옵니다." },
    { kind: "paragraph", text: "맛을 보면 민트의 상쾌함과 생강의 알싸함이 아주 상쾌하게 다가오며, 라임의 상큼함에 약간의 탄산감까지 있어서 산뜻한 느낌까지 줍니다." },
    { kind: "paragraph", text: "모히또나와 모스코뮬의 장점만을 가져와 합친 것 같은 느낌으로, 역시 여름에 마시기에 좋은 칵테일이라는 생각이 듭니다." },
    { kind: "paragraph", text: "다른 레시피들에서는 시럽을 30ml 넣으라고 하고 있지만, 진저비어에도 당도가 있기 때문에 그대로 다 넣으면 너무 달아지게 되니 아무리 많이 넣더라도 15ml를 넘지 않는 걸 추천드립니다." },
  ],
};
