import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "glen-scotia-exclusive-cask-for-korea-2024-tawny-port",
  category: "spirits",
  title: "글렌스코시아 익스클루시브 캐스크 포 코리아 2024",
  dek: "\"글렌 스코시아\"는 스코틀랜드 캠벨타운(Campbeltown)에 위치한 글렌 스코시아 증류소에서 만들어지는 위스키로, 게일어로 '스코틀랜드의 계곡(Valley of the Scots)'이라는 뜻을 가지고 있다고 합니다.",
  publishedAt: "2024-09-13",
  hero: "/articles/glen-scotia-exclusive-cask-for-korea-2024-tawny-port/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223582856831",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/glen-scotia-exclusive-cask-for-korea-2024-tawny-port/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "\"글렌 스코시아\"는 스코틀랜드 캠벨타운(Campbeltown)에 위치한 글렌 스코시아 증류소에서 만들어지는 위스키로, 게일어로 '스코틀랜드의 계곡(Valley of the Scots)'이라는 뜻을 가지고 있다고 합니다." },
    { kind: "paragraph", text: "글렌 스코시아 증류소는 1832년에 문을 열어 현재까지 운영되고 있는데, 이 당시에 캠벨타운에는 약 20~30여 개의 위스키 증류소가 존재했다고 합니다." },
    { kind: "paragraph", text: "당시 스코틀랜드 전역에 약 130개의 증류소가 있었던 점을 고려하면 이 작은 마을이 빅토리아 시대 당시에 \"세계 위스키의 수도\"라 불렸다는 것에 고개가 끄덕여집니다." },
    { kind: "paragraph", text: "이후 미국의 대공황, 금주령 및 세계대전 등으로 위스키 자체에 대한 수요가 줄어들면서 캠벨타운의 많은 증류소도 문을 닫게 되었는데, 글렌 스코시아는 현재까지 자리를 지키고 있습니다." },
    { kind: "paragraph", text: "현재 캠벨타운에는 2000년에 글렌가일 증류소가 오픈하면서 스프링뱅크 증류소까지 3곳의 증류소가 가동되고 있으며, 최근에는 신생 증류소가 지어지고 있습니다." },
    { kind: "paragraph", text: "글렌스코시아 익스클루시브 캐스크 포 코리아 2024는 세 가지 바틀로 나온 것으로 아는데, 제가 마셔본 것은 토니 포트 혹스헤드로, 그 외에 자메이카 럼 배럴, 올로로소 셰리 캐스크가 있다고 합니다." },
    { kind: "figure", src: "/articles/glen-scotia-exclusive-cask-for-korea-2024-tawny-port/01.webp", width: 966, height: 966 },
    { kind: "quote", text: "증류소: 글렌 스코시아" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 토니 포트 혹스헤드, 8년 숙성" },
    { kind: "quote", text: "도수: 56.8%" },
    { kind: "figure", src: "/articles/glen-scotia-exclusive-cask-for-korea-2024-tawny-port/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 포도 껍질, 말린 대추, 바닐라" },
    { kind: "paragraph", text: "- 조금 뒤에 향이 급변함" },
    { kind: "paragraph", text: "> 치즈 비스킷, 건포도" },
    { kind: "paragraph", text: "- 향이 일반적인 포트 캐스크와는 좀 다르고, 향이 계속해서 변함" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 드라이한데 맛 자체는 꽤나 달다" },
    { kind: "paragraph", text: "- 캐러멜, 바닐라, 우디함, 그래시(Grassy)" },
    { kind: "paragraph", text: "- 탄닌감" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "- 화한 느낌(아마도 진저?)" },
    { kind: "paragraph", text: "- 바닐라" },
    { kind: "paragraph", text: "이 바틀이 정말 웃겼던 게 시간을 좀 두고 마시면 계속해서 향이 왔다 갔다 합니다. 처음에는 포트 캐스크의 캐릭터가 났다가 갑자기 아메리칸 캐스크의 캐릭터로 급변합니다." },
    { kind: "paragraph", text: "그리고 향 중에 치즈 비스킷을 적어두었는데, 이 부분이 정말 인상 깊었습니다(바 사장님은 뽀또라 하심.... 근데 맞음....)." },
    { kind: "paragraph", text: "최근 마신 바틀 중에 가장 재미있는 바틀 중 하나였으며, 저숙성 한정 바틀을 만들려면 안정적인 것보다는 이렇게 도파민 터지는 바틀을 만드는 게 좋을 것 같다는 생각이 드는 한 잔이었습니다." },
  ],
};
