import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "grasshopper",
  category: "cocktail",
  title: "그래스호퍼 — 주의)민초단 이외에는 보지마세요",
  dek: "\"그래스호퍼\"는 민트 리큐르와 카카오 리큐르가 들어가 민트초코맛이 나는 칵테일로, 민초단을 위한 칵테일이라 할 수 있습니다.",
  publishedAt: "2024-08-07",
  hero: "/articles/grasshopper/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223539574029",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/grasshopper/00.webp", width: 500, height: 500 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"그래스호퍼\"는 민트 리큐르와 카카오 리큐르가 들어가 민트초코맛이 나는 칵테일로, 민초단을 위한 칵테일이라 할 수 있습니다." },
    { kind: "paragraph", text: "그래스호퍼는 필립 기셰(Philip Guichet)가 1918년 뉴욕에서 열린 칵테일 대회에서 만들어낸 칵테일로, 당시 대회에서 2위를 차지하였으며, 이후 뉴올리언스에 있는 자신의 가게인 Tujague's Restaurant에 이 칵테일을 선보이면서 가게 간판 메뉴 같은 존재가 되었다고 합니다." },
    { kind: "paragraph", text: "이 Tujague's Restaurant라는 레스토랑은 1856년에 오픈해 아직도 영업을 하고 있으며(한 번 이사를 했지만), 2018년에는 그래스호퍼 탄생 100주년을 기념하여 반값에 판매하는 이벤트를 하였다고 합니다." },
    { kind: "paragraph", text: "민초 논쟁이 있는 우리나라에서는 아주 호불호가 극명하게 갈릴 수 밖에 없는 칵테일이지만, 개인적으로는 크리미한 민트초코의 맛은 거부할 수가 없네요." },
    { kind: "figure", src: "/articles/grasshopper/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "20ml 크렘 드 카카오 화이트 (Creme de Cacao White)" },
    { kind: "paragraph", text: "20ml 크렘 드 망트 (Creme de Menthe)" },
    { kind: "paragraph", text: "20ml 생크림 (Heavy Cream)" },
    { kind: "paragraph", text: "가니시: 민트 잎 1개 or 갈아둔 초콜릿" },
    { kind: "paragraph", text: "(옵션)" },
    { kind: "paragraph", text: "*모든 재료를 같은 양으로 넣는다고 생각하자!" },
    { kind: "figure", src: "/articles/grasshopper/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커 안에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후 차갑게 해둔 칵테일 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 가니시로 장식해줍니다." },
    { kind: "figure", src: "/articles/grasshopper/03.webp", width: 500, height: 500 },
    { kind: "paragraph", text: "\"그래스호퍼\"는 들어가는 재료들이 아주 직관적이게 느껴지는 단순한 칵테일로, 재료가 재료다보니 딱히 복잡한 맛을 느끼기는 어렵습니다." },
    { kind: "paragraph", text: "당연히 민초단인 분들은 좋아하시겠지만, 민트초코를 싫어하시는 분들은 모르고 바에서 시켰다가 한 입만 마시고 후회하는 불상사가 일어나게 되겠죠." },
    { kind: "paragraph", text: "개인적으로는 민트초코에 대해서 거부감이 없기 때문에 훌륭한 디저트 칵테일이라 생각합니다." },
    { kind: "paragraph", text: "다만, Tujague's Restaurant의 오리지널 레시피는 오늘날 잘 알려진 1:1:1의 비율과 재료와는 좀 다른 면이 있고, 브랜디가 들어가기도 하니, 나중에 그 레시피도 소개하도록 하겠습니다." },
  ],
};
