import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "greenhorn",
  category: "cocktail",
  title: "그린혼",
  dek: "비주얼에서부터 강렬한 Greenhorn 칵테일은 2022년 미국 텍사스의 휴스턴에 있는 Refuge라는 바에서 바텐더(그리고 오너인) Bobby Heugel에 의해서 만들어졌습니다.",
  publishedAt: "2023-10-02",
  hero: "/articles/greenhorn/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223226334602",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/greenhorn/00.webp", width: 966, height: 723 },
    { kind: "paragraph", text: "About the Drink" },
    { kind: "paragraph", text: "비주얼에서부터 강렬한 Greenhorn 칵테일은 2022년 미국 텍사스의 휴스턴에 있는 Refuge라는 바에서 바텐더(그리고 오너인) Bobby Heugel에 의해서 만들어졌습니다." },
    { kind: "paragraph", text: "그는 자신이 가장 좋아하는 맛의 조합인 아가베 증류주와 멜론의 조합에서 영감을 얻어 이 칵테일을 만들었다고 하며, 그 결과 \"네그로니류에서 튀어나온 흥미로운(의역)\" 맛을 내게 되었다고 그는 말합니다." },
    { kind: "paragraph", text: "데킬라 + 미도리 + 수즈의 조합은 정말이지 어디서도 보기 힘든 조합이고, 특히 블랑코 데킬라와 미도리는 스터하는 칵테일에서는 더더욱 보기가 힘들죠. 여기에 수즈를 사용한 것을 보면 원작자는 어느정도 화이트 네그로니의 캐릭터에서 영감을 받았을지도 모르겠습니다." },
    { kind: "figure", src: "/articles/greenhorn/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "37.5ml 블랑코 데킬라 (Blanco Tequila)" },
    { kind: "paragraph", text: "30ml 미도리 (Midori)" },
    { kind: "paragraph", text: "22.5ml 수즈 (Suze)" },
    { kind: "paragraph", text: "가니쉬: 그린 체리" },
    { kind: "paragraph", text: "데킬라는 본인이 선호하는 블랑코(=실버, 플라타) 데킬라를 사용하되, 미도리와 수즈는 되도록이면 그대로 사용하시는 걸 추천드립니다." },
    { kind: "paragraph", text: "그린 체리 같은 경우는 구하는 데에 꽤 난이도가 있는데, 저 같은 경우에는 예~전에 쿠팡에서 영어로 green cherry, mint cherry로 검색해서 간신히 찾았었습니다. 작성하는 날짜 기준으로 판매 중지가 되어있네요...." },
    { kind: "paragraph", text: "다만, 맛에 영향을 주는 가니쉬는 아니니 생략하거나 빨간색의 체리를 사용하셔도 무방합니다." },
    { kind: "figure", src: "/articles/greenhorn/02.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 가니쉬 이외의 재료를 모두 믹싱 글라스에 넣습니다." },
    { kind: "paragraph", text: "2. 믹싱글라스에 얼음을 채워주고, 스터합니다." },
    { kind: "paragraph", text: "3. 칠링한 칵테일 글라스에 따라주고, 그린 체리를 넣어 가니쉬해줍니다." },
    { kind: "figure", src: "/articles/greenhorn/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "색깔, 가니쉬, 재료 뭐 하나 빠짐 없이 칵테일 애호가들이라면 흥미가 생길만한 칵테일입니다. 사실 미도리는 그 색과 우리나라에서는 캐주얼한 칵테일에 많이 들어가서 저평가되어 있다고 생각되는데, 이 칵테일은 미도리를 재평가하게 해줄만한 칵테일이라고 생각됩니다. 저에게 또한 미도리에 대한 인상을 바꿔준 칵테일이었습니다." },
    { kind: "paragraph", text: "데킬라의 아가베 느낌이 수즈의 맛과 함께 잘 드러나고, 거기에 미도리의 달달한 멜론맛이 약간 추가되는 느낌이었습니다. 수즈로 인해 쌉쌀하기는 하지만 어느 정도 단 느낌이 있습니다. 색과 미도리 때문에 엄청 달 것 같지만 전혀 그맇지 않고, 오히려 저는 단맛보다는 쌉쌀한 맛이 약간 더 잘 느껴졌습니다." },
    { kind: "paragraph", text: "참 오묘한 맛이지만 생각보다 맛의 조화 자체는 잘 맞았고, 쌉쌀함과 단맛의 밸런스를 위해 당을 약간 추가해도 좋을 것 같습니다(특히, 아가베 시럽). 술만 들어간데다가 스터하는 칵테일이라 도수감이 좀 쎄게 느껴집니다." },
    { kind: "paragraph", text: "개인적으로 입맛에 맞는 칵테일은 아니었지만 유니크한 조합의 칵테일이니 한 번쯤은 마셔보는 걸 추천드립니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
