import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "grinchhopper",
  category: "cocktail",
  title: "그린치호퍼 — 어른스러운 입맛의 민초단을 위한 칵테일",
  dek: "\"그린치호퍼\"는 크리미한 민트초코맛이 나는 \"그래스호퍼(Grasshopper)\"라는 칵테일의 변형으로, 어른스러운 입맛의 민초단을 위한 칵테일이라 할 수 있습니다.",
  publishedAt: "2024-08-09",
  hero: "/articles/grinchhopper/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223542145727",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/grinchhopper/00.webp", width: 500, height: 500 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"그린치호퍼\"는 크리미한 민트초코맛이 나는 \"그래스호퍼(Grasshopper)\"라는 칵테일의 변형으로, 어른스러운 입맛의 민초단을 위한 칵테일이라 할 수 있습니다." },
    { kind: "paragraph", text: "이 칵테일은 라스 베이거스의 더 코스모폴리탄 호텔(The Cosmopolitan of Las Vegas)의 \"스키 롯지(Ski Lodge)\"라는 바에서 \"니코 노빅(Niko Novick)\"에 의해 만들어졌으며, 2022년 크리스마스 시즌을 위해 만들어진 칵테일로 보입니다." },
    { kind: "paragraph", text: "'Las Vegas Magazine'에 2022년 12월 16일 처음으로 미야사토 키코에 의해 기록됐으며(추정), 이후 2022년 12월 19일 '임바이브 매거진(Imbibe Magazine)'에 자세한 레시피가 공개됐습니다." },
    { kind: "paragraph", text: "기존의 그래스호퍼 칵테일에 '페르넷 브랑카'라는 복잡하고도 쓴 약초맛이 특징인 아마로를 추가해 좀 더 복잡한 맛을 내는 그래스호퍼라 할 수 있습니다." },
    { kind: "figure", src: "/articles/grinchhopper/01.webp", width: 500, height: 500 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "22.5ml 크렘 드 카카오 화이트" },
    { kind: "paragraph", text: "(Creme de Cacao White)" },
    { kind: "paragraph", text: "15ml 크렘 드 망트 그린" },
    { kind: "paragraph", text: "(Creme de Menthe Green)" },
    { kind: "paragraph", text: "15ml 페르넷 브랑카" },
    { kind: "paragraph", text: "(Fernet Branca)" },
    { kind: "paragraph", text: "30ml 생크림" },
    { kind: "paragraph", text: "민트 잎 3개" },
    { kind: "paragraph", text: "가니시: 민트 잎 1개" },
    { kind: "figure", src: "/articles/grinchhopper/02.webp", width: 403, height: 403 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후 차갑게 해 둔 칵테일 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 가니시로 장식해줍니다." },
    { kind: "figure", src: "/articles/grinchhopper/03.webp", width: 500, height: 500 },
    { kind: "paragraph", text: "페르넷 브랑카는 꽤나 쓴 약초의 캐릭터가 아주 복잡하게 나는 매력적인 술로, 개인적으로 쌉쌀한 다크 초콜릿이나 민트의 화한 캐릭터도 가지고 있다고 느껴집니다." },
    { kind: "paragraph", text: "그린치호퍼는 이런 페르넷 브랑카를 단순한 그래스호퍼에 넣어서 일반적인 그래스호퍼보다 당도는 살짝 낮추고, 복합성을 더해주는 아주 재밌는 변형이라 할 수 있죠." },
    { kind: "paragraph", text: "화한 민트의 느낌이라기 보다는 약간은 묵직하고 쌉쌀한 느낌의 허브 캐릭터가 나는 민트초코의 맛이랄까요. 어른스러운 입맛의 민초단을 위한 한 잔입니다." },
    { kind: "paragraph", text: "추가적으로, 페르넷 브랑카에서 민트 캐릭터가 부각된 '브랑카 멘타'를 사용하는 것도 아주 잘 어울릴 것 같습니다." },
  ],
};
