import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "hunter",
  category: "cocktail",
  title: "헌터 — 위스키와 체리 히링, 두 가지 재료가 만들어내는 의외의 복잡한 풍미",
  dek: "「헌터(Hunter) 칵테일」은 잘 알려지지 않은 칵테일이지만, 확실히 칵테일 마니아 사이에서는 어느 정도 인지도를 가지고 있으며, 특히 일본의 칵테일 씬을 좋아하는 분들이라면 한 번쯤은 들어봤을 법한 칵테일입니다.",
  publishedAt: "2026-08-17",
  hero: "/articles/hunter/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224381235796",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/hunter/00.webp", width: 966, height: 966 },
    { kind: "quote", text: "75% Rye Whiskey" },
    { kind: "quote", text: "25% Cherry Brandy" },
    { kind: "paragraph", text: "「헌터(Hunter) 칵테일」은 잘 알려지지 않은 칵테일이지만, 확실히 칵테일 마니아 사이에서는 어느 정도 인지도를 가지고 있으며, 특히 일본의 칵테일 씬을 좋아하는 분들이라면 한 번쯤은 들어봤을 법한 칵테일입니다." },
    { kind: "figure", src: "/articles/hunter/01.webp", width: 273, height: 132, caption: "Jack's Manual (1908)" },
    { kind: "paragraph", text: "1908년 출판된 Jacob A. Grohusko의 저서인 「Jack's Manual」에서 등장한 것이 이 칵테일에 대한 가장 오래된 기록이며, 라이 위스키와 체리브랜디를 3:1의 비율로 만들었습니다." },
    { kind: "paragraph", text: "이후 몇십 년 동안 다양한 칵테일 북에서 일부 변형이 추가되는 식의 레시피도 있었으나, 라이 위스키와 체리브랜디를 3:1 또는 2:1 비율로 하는 기본 구조 자체는 크게 변형되지 않고 소개되었습니다." },
    { kind: "paragraph", text: "다만, 그 외에 인기를 끌었다는 식의 기록은 없는 걸 보니, 딱히 메인스트림에 있던 칵테일이라 보기는 어려울 것 같습니다." },
    { kind: "figure", src: "/articles/hunter/02.webp", width: 966, height: 966 },
    { kind: "quote", text: "칵테일 레시피" },
    { kind: "quote", text: "버번 위스키 vs 라이 위스키" },
    { kind: "paragraph", text: "- 라이 or 버번 위스키 45ml / Rye or  Bourbon Whiskey 45ml" },
    { kind: "paragraph", text: "- 체리 히링 15ml / Cherry Heering 15ml" },
    { kind: "paragraph", text: "- (옵션) 마라스키노 체리 1개" },
    { kind: "paragraph", text: "이 칵테일에서 제일 중요한 건 기주입니다." },
    { kind: "paragraph", text: "이에 관련해서 진 바질 스매시라는 불후의 모던 클래식 칵테일을 만든 요르그 마이어와 일본 긴자의 Bar High Five의 오너이자 세계적으로 유명한 바텐더인 우에노 히데츠구의 흥미로운 일화가 있습니다(출처: difford's guide)." },
    { kind: "paragraph", text: "요르그 마이어에 따르면, 우에노 히데츠구는 그에게 노아스밀(Noah's Mill) 버번과 체리 히링을 2:1로 한 헌터 칵테일을 소개하면서 버번이 이 칵테일과 완벽한 궁합을 이루기 때문에 변경했다고 합니다." },
    { kind: "paragraph", text: "다만, 이 노아스밀은 버번이긴 하지만 제 생각에는 꽤나 라이 위스키스러운 민트, 스파이시함이 느껴지는 버번이기 때문에 조금 의아한 면이 있기는 합니다만, 그 당시와 맛이 변했을 수도 있죠." },
    { kind: "paragraph", text: "개인적으로는 기주는 결국 어떤 캐릭터를 내고 싶을지에 따라 다를 것 같습니다. 예를 들어 라이 위스키를 사용하게 되면 비교적 드라이하고, 스파이시함에 체리 캐릭터를 더하는 느낌이, 버번 위스키를 사용하게 되면 체리·바닐라·캐러멜 캐릭터의 비교적 달고 묵직한 느낌이 주가 됩니다." },
    { kind: "paragraph", text: "또한, 같은 라이 위스키, 버번 위스키라 하더라도 브랜드 및 매시빌 등에 따라 맛이 또 다르기 때문에, 만들기 전에 기주의 맛을 참고해서 정하는 게 좋지 않을까 싶습니다." },
    { kind: "figure", src: "/articles/hunter/03.webp", width: 966, height: 966 },
    { kind: "quote", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 믹싱 글라스에 모든 재료를 넣어줍니다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채워주고, 스터해줍니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 마라스키노 체리를 넣어줍니다(*옵션)." },
    { kind: "paragraph", text: "헌터 칵테일은 라이 위스키의 캐릭터에 체리 히링의 캐릭터가 자연스럽게 더해져 풍미를 확장시키는 느낌이 듭니다." },
    { kind: "paragraph", text: "구체적으로 가벼운 바닐라와 스파이시한 풍미를 시작으로, 묵직한 체리 및 건포도 등의 풍미가 따뜻한 향신료와 함께 이어지고, 은은한 쌉쌀함이 남습니다. 상당히 복잡한 맛이고, 어딘가 맨하탄을 떠올리게 하기도 합니다." },
    { kind: "paragraph", text: "헌터 칵테일은 2개의 재료만이 사용되고, 그중에서 체리 브랜디는 체리 히링을 사용하는 것이 권장되기 때문에 기주에 따라 맛이 천차만별이 될 수 있습니다. 또한, 재료가 적어 만들기도 상당히 어려운 칵테일입니다." },
  ],
};
