import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "japanese-slipper",
  category: "cocktail",
  title: "재패니즈 슬리퍼 — 미도리를 사용한 초록색 네온사인 같이 강렬한 색감의 칵테일",
  dek: "\"재패니즈 슬리퍼\"는 1984년 멜버른에서 미에타스 레스토랑(Mietta's Restaurant)에서 장 폴 부르기뇽(Jean-Paul Bourguignon)에 의해 만들어진 칵테일입니다.",
  publishedAt: "2024-09-30",
  hero: "/articles/japanese-slipper/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223602035796",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/japanese-slipper/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"재패니즈 슬리퍼\"는 1984년 멜버른에서 미에타스 레스토랑(Mietta's Restaurant)에서 장 폴 부르기뇽(Jean-Paul Bourguignon)에 의해 만들어진 칵테일입니다." },
    { kind: "paragraph", text: "자극적인 캐릭터의 칵테일이 만들어지던 흔히 칵테일 암흑기라 부르는 시기에 만들어진 것을 한눈에 알 수 있는데, 초록색 네온사인 같은 비비드한 색감이 특징인 칵테일입니다." },
    { kind: "paragraph", text: "칵테일 암흑기라는 좋지 않은 어감의 시대입니다만, 이건 서양의 바텐더들, 특히 칵테일 르네상스 시기를 강하게 주장하는 사람들이 만들어낸 것일 뿐입니다." },
    { kind: "paragraph", text: "사실 이 시기에 코스모폴리탄, 롱아일랜드 아이스티, 에스프레소 마티니 등과 같은 현재에도 많은 사랑을 받는 칵테일들이 탄생하기도 했던 시기이기도 합니다." },
    { kind: "paragraph", text: "재패니즈 슬리퍼는 기주(멜론 리큐르), 큐라소, 레몬즙이 들어가는 것이 얼핏 데이지 스타일로 보이기도 하는데, 이건 사람마다 다르게 느낄 수도 있겠네요." },
    { kind: "figure", src: "/articles/japanese-slipper/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 미도리 / 멜론 리큐르" },
    { kind: "paragraph", text: "(Midori / Melon Liqueur)" },
    { kind: "paragraph", text: "30ml 코앵트로 / 트리플 섹" },
    { kind: "paragraph", text: "(Cointreau / Triple Sec)" },
    { kind: "paragraph", text: "30ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "가니시: 체리 (옵션)" },
    { kind: "figure", src: "/articles/japanese-slipper/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 가니시 이외의 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 차게 해둔 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 체리 한 알을 넣어줍니다(옵션)." },
    { kind: "paragraph", text: "재패니즈 슬리퍼는 초록색 네온사인 같은 겉모습에 걸맞게 아주 자극적인 맛의 칵테일로, 달고 살짝 신맛의 칵테일입니다." },
    { kind: "paragraph", text: "개인적으로는 죠스바의 남색부분에 오렌지맛을 더한 것 같은 살짝은 유치한 불량식품 같은 맛입니다. 오랜만에 이런 맛의 칵테일을 마셨는데, 생각보다 꽤나 맛있었습니다." },
    { kind: "paragraph", text: "칵테일에 대해서 잘 모르거나, 달달한 칵테일을 좋아하시는 분들에게는 추천할만한 칵테일입니다." },
  ],
};
