import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "kaikan-fizz",
  category: "cocktail",
  title: "카이칸 피즈 — 우유로 변장한 진 피즈",
  dek: "「카이칸 피즈」는 제2차 세계대전이 끝난 후에 일본 도쿄의 동경회관(도쿄카이칸/東京會舘)에서 만들어지게 됩니다.",
  publishedAt: "2025-02-15",
  hero: "/articles/kaikan-fizz/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223761734109",
  relatedCocktailSlugs: ["kaikanfizz"],
  blocks: [
    { kind: "figure", src: "/articles/kaikan-fizz/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "「카이칸 피즈」는 제2차 세계대전이 끝난 후에 일본 도쿄의 동경회관(도쿄카이칸/東京會舘)에서 만들어지게 됩니다." },
    { kind: "paragraph", text: "이 동경회관은 전쟁 전에는 서양식 건물의 사교장으로 이용되었으나, 전후에는 연합군 최고사령부(GHQ)에 의해 1945~1952의 기간 동안 「아메리칸 클럽 오브 도쿄」라는 이름의 장교들을 위한 장소(장교 클럽)으로 이용되었습니다." },
    { kind: "paragraph", text: "카이칸 피즈는 이 기간 동안에 만들어지게 되었는데, 몇몇 설이 있지만 가장 유명한 것으로는 당시의 장교들이 낮부터 몰래 술을 마실 수 있도록 진피즈에 우유를 넣도록 요청하여, 마치 우유를 마시는 것처럼 위장하기 위해서 시작한 것이라 합니다." },
    { kind: "paragraph", text: "몇 번의 재건축이 있었지만, 동경회관은 현재에도 계속해서 운영되고 있고, 이 안의 메인 바(Main Bar)에서는 현재에도 카이칸 피즈가 만들어지고 있다고 합니다. 이 바에서는 당시 최고사령관이었던 맥아더도 이 칵테일을 좋아했다고 소개하고 있습니다." },
    { kind: "paragraph", text: "카이칸 피즈는 그 외에도 「진 피즈, 카이칸 스타일」 또는 「모닝 피즈」로도 불리고 있다고 하며, 우리나라에서는 인지도가 거의 없지만, 일본에서는 웬만한 바에서 주문해도 맛볼 수 있을 정도의 인지도를 가지고 있습니다." },
    { kind: "figure", src: "/articles/kaikan-fizz/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "figure", src: "/articles/kaikan-fizz/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 탄산수를 제외한 재료를 쉐이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 쉐이커에 얼음을 넣어주고," },
    { kind: "paragraph", text: "다소 길게 쉐이킹해줍니다." },
    { kind: "paragraph", text: "3. 긴 잔에 얼음을 채우고, 쉐이커에서 부어줍니다." },
    { kind: "paragraph", text: "4. 탄산을 살살 부어줍니다." },
    { kind: "paragraph", text: "5. 얼음을 위아래로 2~3번 들었다 내려줍니다." },
    { kind: "paragraph", text: "카이칸 피즈는 레시피 적으로는 단순히 '우유가 들어간 진 피즈'로, 비주얼 적으로는 라모스 진 피즈의 그것을 떠올리게 합니다만, 맛 자체는 일반적인 진피즈에서 더 부드럽고, 실키한 느낌입니다." },
    { kind: "paragraph", text: "약간은 칼피스 또는 밀키스를 살짝 떠올리게도 하는 맛." },
    { kind: "paragraph", text: "칵테일에는 우유와 시트러스(레몬)이 들어가는 꽤나 특이한 조합을 하고 있는데, 이는 그닥 좋은 선택은 아닙니다. 레몬즙에는 산이 들어 있는데, 이 산이 우유 속 단백질을 응고시키게 되기 때문입니다." },
    { kind: "paragraph", text: "게다가 만들어진 혼합물에 강한 탄산수를 확 부어버리면 거품이 순식간에 넘쳐버리기 때문에 탄산수를 따를 때에도 주의를 요해야 합니다." },
    { kind: "paragraph", text: "이런 점들 때문에 카이칸 피즈는 꽤 만들기 까다로운 칵테일로 통하며, 개인적으로는 바텐더의 역량을 시험한다는 일반 진 피즈보다는 카이칸 피즈를 만드는 게 더 어렵다고 생각합니다." },
  ],
};
