import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "kilkerran-8cs-batch10",
  category: "spirits",
  title: "킬커란 8cs 배치 10 — 캐스크 스트렝스 시음기",
  dek: "형제의 분쟁에서 태어나 두 번 죽고 되살아난 글렌가일 증류소. 올로로소 캐스크 8년, 57.4%의 배치 10을 마셔봤다.",
  publishedAt: "2024-10-14",
  hero: "/articles/kilkerran-8cs-batch10/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223618444164",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/kilkerran-8cs-batch10/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Whisky" },
    { kind: "paragraph", text: "킬커란은 캠벨타운의 글렌가일 증류소(Glengyle Distillery)에서 생산되는 위스키로, 스프링뱅크 증류소와 인연이 있는 증류소의 위스키입니다." },
    { kind: "paragraph", text: "글렌가일 증류소는 윌리엄 미첼(William Mitchell)에 의해서 1872년에 설립되었는데, 윌리엄은 이전에 그의 형제인 존 미첼(John Mitchell)과 스프링뱅크 증류소를 운영하였는데, 둘 사이의 분쟁으로 인해 윌리엄이 독립하게 되었습니다." },
    { kind: "paragraph", text: "20세기 초에 1차 세계대전 전후로 많은 증류소들이 그랬듯이 글렌가일 증류소는 경제적 어려움을 겪다가 결국 1919년 매각되어버리고, 이후 1925년에는 완전히 생산이 중단되어 버립니다." },
    { kind: "paragraph", text: "2000년에는 글렌가일 증류는 미첼 가족의 후손인 헤들리 라이트(Hedley G Wright)가 이끄는 Mitchell's Glengyle Ltd에 의해 인수되어 복구되기 시작했고, 2004년에는 첫 번째 원액이 증류되었습니다." },
    { kind: "paragraph", text: "킬커란 8cs는 매년 1~2번 릴리즈 되며, 제가 구매한 것은 2024년 1월에 병입된 배치 10이며, 올로로소 캐스크에서 숙성되었습니다. 배치마다 캐스크가 동일하지 않으며, 이전에는 버번 캐스크, 포트 캐스크에서도 숙성한 배치가 있다고 합니다." },
    { kind: "figure", src: "/articles/kilkerran-8cs-batch10/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/kilkerran-8cs-batch10/02.webp", width: 966, height: 1288 },
    { kind: "quote", text: "증류소: 글렌가일 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 올로로소 셰리 캐스크" },
    { kind: "quote", text: "도수: 57.4%" },
    { kind: "figure", src: "/articles/kilkerran-8cs-batch10/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 비릿하고, 강하지는 않은 피트향" },
    { kind: "paragraph", text: "- 신문지(?)스러운 향, 건초" },
    { kind: "paragraph", text: "- 그 아래로 부드럽게 느껴지는 약간의 땅콩 같은 견과류" },
    { kind: "paragraph", text: "- 라즈베리, 체리, 신 딸기" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 고소한 몰트의 캐릭터, 우디함" },
    { kind: "paragraph", text: "- 베리류의 캐릭터와 탄닌감" },
    { kind: "paragraph", text: "- 약한 피트감" },
    { kind: "paragraph", text: "- 혀에 남는 짭짤함과 쌉쌀함" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "-신 베리류 > 우디함 > 약간의 피트감 > 마지막에 남는 후추와 진저" },
    { kind: "paragraph", text: "이런 순으로 변해가면서 얇고 길게 가는 느낌" },
    { kind: "paragraph", text: "킬커란 8cs 배치10은 맛에서 전체적으로 뭔가 다양한 맛이 앞다투어 나는데, 깊이감 자체는 아쉬운 느낌입니다. 물론 8년 숙성이니만큼 깊이감을 바라기는 어렵고, 오히려 8년치고는 괜찮은 편이지 않을까 싶습니다." },
    { kind: "paragraph", text: "또한 뭔가 조금 더티한 느낌이며, 달기도 하지만 그 후에 쓴맛이 꽤 올라오는 편입니다. 향·맛·피니시를 모두 합해보면 시고, 달고, 쓴 느낌을 강하게 받았습니다." },
    { kind: "paragraph", text: "킬커란을 마셔본 적이 한두번 밖에 없었는데, 이번 보틀을 계기로 다른 킬커란이 보인다면 한 잔씩 마셔보고 싶어지네요." },
  ],
};
