import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "kingston-negroni",
  category: "cocktail",
  title: "킹스톤 네그로니 — 자메이카 펑크로 완성한 클래식의 변주",
  dek: "「킹스톤 네그로니」는 이름에서도 단번에 알 수 있듯이 클래식 칵테일인 네그로니의 변형입니다. 다만, 여기에서는 '진'이 아니라 '럼'이 기주로 들어가게 되죠.",
  publishedAt: "2025-06-28",
  hero: "/articles/kingston-negroni/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223914797273",
  relatedCocktailSlugs: ["kingstonnegroni"],
  blocks: [
    { kind: "figure", src: "/articles/kingston-negroni/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "「킹스톤 네그로니」는 이름에서도 단번에 알 수 있듯이 클래식 칵테일인 네그로니의 변형입니다. 다만, 여기에서는 '진'이 아니라 '럼'이 기주로 들어가게 되죠." },
    { kind: "paragraph", text: "킹스톤 네그로니는 2010년 전후로 유명 바텐더인 호아킨 시모(Joaquin Simo)에 의해 탄생했으며, 당시 주류 수입업자로부터 '스미스 앤 크로스(Smith & Cross)'라는 럼을 건네받고 5분 만에 만들어냈다고 합니다." },
    { kind: "paragraph", text: "이 스미스 앤 크로스라는 럼은 자메이카 럼, 그중에서도 *오버 프루프 럼(Overproof Rum)에 해당하기 때문에 아주아주 강렬한 캐릭터를 자랑합니다." },
    { kind: "paragraph", text: "*도수가 100proof(50%) 이상인 럼" },
    { kind: "figure", src: "/articles/kingston-negroni/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "럼은 흔히 지역에 따라서 가지는 특징이 있기도 한데, 자메이카 럼은 '펑키함(Funky)'이 특징으로, 개인적으로는 과하게 후숙된 바나나, 열대 과일들, 약간의 따뜻한 계열의 향신료들이 삐죽삐죽하게 느껴지는 캐릭터라 생각합니다." },
    { kind: "paragraph", text: "아무튼 스미스 앤 크로스는 이런 펑키함과 높은 도수로 인해서 클래식 칵테일과는 궁합이 좋지 않을 것 같지만, 오히려 이 점이 캐릭터가 강한 캄파리와 잘 어울러서 독특한 캐릭터의 네그로니를 만들어냅니다." },
    { kind: "figure", src: "/articles/kingston-negroni/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "Recipe" },
    { kind: "paragraph", text: "30ml 자메이카 럼" },
    { kind: "paragraph", text: "30ml 캄파리" },
    { kind: "paragraph", text: "30ml 스위트 버무스" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질" },
    { kind: "paragraph", text: "자메이카 럼은 '펑키함'이라는 특수한 캐릭터를 가지고 있기 때문에 다른 지역의 럼으로 만들게 되면 그냥 럼 네그로니가 되어 버립니다. 스미스 앤 크로스를 구하기 어렵다면 도수가 아쉽긴 하지만 '애플톤(Appleton)'이 그 대안이 될 수 있습니다." },
    { kind: "paragraph", text: "스위트 버무스 같은 경우에는 스미스 앤 크로스와 캄파리 둘 다 캐릭터가 꽤나 강하니 코키 디 토리노, 안티카 포뮬라 등과 같이 어느 정도 캐릭터가 강한 것들을 사용하는 걸 추천드립니다." },
    { kind: "figure", src: "/articles/kingston-negroni/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 락 글라스에 모든 재료를 넣는다." },
    { kind: "paragraph", text: "2. 얼음을 넣고, 스터해준다." },
    { kind: "paragraph", text: "3. 오렌지 껍질의 오일을 잔 위에 뿌려준다." },
    { kind: "paragraph", text: "4. 사용한 오렌지 껍질을 다듬어서 넣어준다." },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 허브감이 덜한 네그로니" },
    { kind: "paragraph", text: "- 후숙된 바나나, 흑당(?), 초콜릿, 향신료" },
    { kind: "paragraph", text: "- 클래식 네그로니보다는 단순한 맛" },
    { kind: "paragraph", text: "- 복합성은 떨어지지만, 통통 튀고 자극적인 매력" },
    { kind: "paragraph", text: "킹스톤 네그로니는 클래식한 네그로니보다는 허브감이 훨씬 덜하고 단순한데다가, 술의 들큰함과 후숙된 바나나의 캐릭터 등으로 오히려 더 쉽게 마실 수도 있습니다." },
    { kind: "paragraph", text: "마실 때는 도수감이 크게 느껴지지는 않습니다만, 아마 네그로니의 변형 중 가장 도수가 놓은 칵테일이니 마실 때에는 주의해야겠습니다." },
  ],
};
