import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "kings-valley",
  category: "cocktail",
  title: "킹스 밸리 — 스카치 위스키의 색깔놀이",
  dek: "\"킹스 밸리(King's Valley)\"는 도쿄의 긴자에 위치한 바 '텐더(Tender)'의 일본 칵테일 씬의 전설인 \"우에다",
  publishedAt: "2024-07-24",
  hero: "/articles/kings-valley/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223524202319",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/kings-valley/00.webp", width: 501, height: 501 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"킹스 밸리(King's Valley)\"는 도쿄의 긴자에 위치한 바 '텐더(Tender)'의 일본 칵테일 씬의 전설인 \"우에다 카즈오\"에 의해 만들어진 칵테일로, 1986년에 개최된 제1회 스카치 위스키 칵테일 콩쿨 우승작입니다." },
    { kind: "paragraph", text: "우리나라에서는 잘 알려져 있지 않지만, 일본에서는 인지도 있는 칵테일이며, '유키구니(Yukiguni)'와 함께 일본에서 탄생한 칵테일 중 가장 사랑 받는 칵테일 중 하나입니다." },
    { kind: "paragraph", text: "스카치 위스키의 산지인 스코틀랜드의 산의 깊은 계곡을 이미지한 칵테일이며, 재료 중 녹색을 띄는 것이 없음에도 불구하고, 재료의 조합으로 녹색을 띄는 것이 특징입니다." },
    { kind: "figure", src: "/articles/kings-valley/01.webp", width: 526, height: 526 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "40ml 스카치 위스키(Scotch Whisky)" },
    { kind: "paragraph", text: "10ml 화이트 큐라소(White Curacao)" },
    { kind: "paragraph", text: "10ml 라임즙(Lime Juice)" },
    { kind: "paragraph", text: "5ml 블루 큐라소(Blue Curacao)" },
    { kind: "figure", src: "/articles/kings-valley/02.webp", width: 420, height: 420 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹해줍니다." },
    { kind: "paragraph", text: "3. 차게 해둔 칵테일 잔에 부어줍니다." },
    { kind: "figure", src: "/articles/kings-valley/03.webp", width: 529, height: 529 },
    { kind: "paragraph", text: "\"킹스 밸리\"는 꽤 간단한 재료에 비해서 아주 화려한 색을 낼 수 있는 칵테일입니다. 제가 만든 건 청록색에 가까운 색이며, 기주인 스카치 위스키의 종류나 비율, 잔의 종류 등에 따라서 색이 다르게 나올 수 있습니다. 그에 따라서 맛도 달라지겠죠." },
    { kind: "paragraph", text: "\"우에다 카즈오\"님의 저서인 '칵테일 테크닉'에서는 '그란츠'나 '화이트 앤 맥케이'를 사용했던 걸로 보아, 어느 하나 특징이 튀지 않고 부드러운 블렌디드 위스키를 사용하는 걸 선호했던 것으로 보입니다. 또한, 위스키를 좋아하는 손님을 위해서는 '올드파'를 사용했다고 하네요." },
    { kind: "paragraph", text: "다만, 이 저서는 꽤 오래된 저서라서 최근에는 사용하는 기주가 바뀌었을 수도 있겠네요. 개인적으로는 '페이머스 그라우스'가 기주에 적합하다고 느꼈습니다." },
    { kind: "paragraph", text: "맛 자체는 요즘 만들어지는 칵테일에 비해서는 무난하다고 할 수 있지만 안정감이 있는 맛으로, 밸런스가 아주 좋습니다. 레시피 자체는 '사일런트 서드(Silent Third)의 변형처럼도 보이네요." },
  ],
};
