import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "lagavulin-10yo-feis-ile-2024",
  category: "spirits",
  title: "라가불린 10년 페스 아일 2024",
  dek: "페스 아일(Feis Ile)은 매년 5월 마지막 주에 아일라(Islay) 섬과 주라(Jura) 섬에서 약 1~2주간에 걸친 위스키 관련 축제입니다.",
  publishedAt: "2024-08-28",
  hero: "/articles/lagavulin-10yo-feis-ile-2024/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223563873221",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/lagavulin-10yo-feis-ile-2024/00.webp", width: 966, height: 644 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "페스 아일(Feis Ile)은 매년 5월 마지막 주에 아일라(Islay) 섬과 주라(Jura) 섬에서 약 1~2주간에 걸친 위스키 관련 축제입니다." },
    { kind: "paragraph", text: "증류소에서는 해마다 페스 아일을 기념하기 위해서 위스키를 출시하는데, 라가불린 증류소에서는 올해 페스아일에 10년 숙성과 29년 숙성을 출시하였습니다." },
    { kind: "paragraph", text: "그 중 29년은 말도 안 되는 가격 때문에 바틀만 구경해 봤고, 10년은 라가불린 증류소 투어 중 테이스팅을 하다가 남은 것을 담아왔습니다." },
    { kind: "paragraph", text: "테이스팅을 하면서 들은 것 중에 기억에 남는 건 이번 10년 페스 아일 바틀은 기존의 라가불린보다 피트감이 더 강하다는 점이었습니다." },
    { kind: "paragraph", text: "라가불린 10년 페스 아일 2024는 1,800병이 출시되었으며, 소매가는 175파운드였다고 합니다. 10년 숙성치고는 가격대가 꽤 나가는 편이죠." },
    { kind: "figure", src: "/articles/lagavulin-10yo-feis-ile-2024/01.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/lagavulin-10yo-feis-ile-2024/02.webp", width: 966, height: 966, caption: "가운데가 10년 페스 아일 2024 29년 페스 아일 2024의 소매가는 2,500파운드" },
    { kind: "quote", text: "증류소: 라가불린 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 리필 헤빌리 차드 캐스크(Refill, Heavily Charred Cask), 퍼스트 필 엑스 버번 아메리칸 오크 혹스헤드 캐스크(1st fill ex-Bourbon American Oak Hogshead Cask) / 10년 숙성" },
    { kind: "quote", text: "도수: 56.7%" },
    { kind: "quote", text: "시리즈: 페스 아일 (Feis Ile)" },
    { kind: "figure", src: "/articles/lagavulin-10yo-feis-ile-2024/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/lagavulin-10yo-feis-ile-2024/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 타고 남은 재 같은 피트감으로, 확실히 기존 라가불린보다는 강함" },
    { kind: "paragraph", text: "- 라가불린 특유의 고소한 곡식" },
    { kind: "paragraph", text: "- 버터리한 크루아상이 달달하게 다가옴" },
    { kind: "paragraph", text: "- 짠 느낌, 약간은 해초스러움" },
    { kind: "paragraph", text: "- 시트러스" },
    { kind: "paragraph", text: "- 달달하지만 오일리 하지는 않고, 오히려 살짝 드라이함" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 라가불린 특유의 고소한 곡식" },
    { kind: "paragraph", text: "- 지나가고 나면 다크초콜릿과 카카오닙" },
    { kind: "paragraph", text: "- 약간의 견과류와 생강" },
    { kind: "paragraph", text: "- 날카롭고 강한 피트감" },
    { kind: "paragraph", text: "- 맛은 달지 않고 약간 쌉쌀한 정도" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 생각보다 긴 피니시" },
    { kind: "paragraph", text: "- 달달한 피트감" },
    { kind: "paragraph", text: "- 일반적인 라가불린보다는 좀 더 재 같은 캐릭터가 있음" },
    { kind: "paragraph", text: "다 마시고 난 뒤에 라가불린의 고소한 곡식의 캐릭터에 더해 재 같은 피트 캐릭터가 코와 입안에 아주 오래 남게 됩니다." },
    { kind: "paragraph", text: "라가불린 10년 페스 아일 2024는 기본적으로 라가불린 특유의 고소한 곡식의 캐릭터가 구조감을 잡아주고, 타고 남은 재 같은 피트감에 더해 짭짤하고 버터리한 빵 같은 향이 매력적인 위스키입니다." },
    { kind: "paragraph", text: "꽤나 재미있는 라가불린으로, 숙성년수에 비해서 가격이 다소 비싼 감은 있지만, 개인적으로 향과 맛을 봤을 때 한 병 사두고 싶을 정도입니다." },
  ],
};
