import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "london-tayer-elementary",
  category: "bar",
  title: "테이어 + 엘리멘트리",
  dek: "\"Tayēr + Elementary\"는 영국 런던에 위치한 바로, 2019년에 주류 및 바텐딩 업계에서 다양한 상을 수상하고 많은 존경을 받는 알렉스 크라테나(Alex Kratena)와 모니카 버그(Monica Berg)에 의해 오픈된 바입니다.",
  publishedAt: "2024-06-24",
  hero: "/articles/london-tayer-elementary/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223489497394",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "paragraph", text: "\"Tayēr + Elementary\"는 영국 런던에 위치한 바로, 2019년에 주류 및 바텐딩 업계에서 다양한 상을 수상하고 많은 존경을 받는 알렉스 크라테나(Alex Kratena)와 모니카 버그(Monica Berg)에 의해 오픈된 바입니다." },
    { kind: "paragraph", text: "오픈한 직후 2020년부터 2023년까지 The World's Best Bars(월드 베스트 바)에 연속으로 TOP10에 위치했으며, 2021년과 2022년 연속으로 2위를 차지하기도 할 정도로 인정을 받고 있는 바 입니다." },
    { kind: "paragraph", text: "이름의 '+'가 눈에 띄는데, 사실 이 바는 'Tayēr'와 'Elementary', 이 두 공간으로 각각 테마에 의해 나뉘어져 있습니다." },
    { kind: "paragraph", text: "바에 들어서면 먼저 'Elementary' 공간에 들어가게 되는데, 이 공간에서는 주로 RTD에 가까울 정도의 미리 만들어진(Pre-batched) 칵테일, 맥주, 와인 등을 마셔볼 수 있습니다." },
    { kind: "paragraph", text: "그 너머의 'Tayēr' 공간에서는 이 바의 진면목을 볼 수 있는데, 아래 사진처럼 아예 메뉴 자체도 다르고, 메이킹을 하는 칵테일을 주로 서브합니다." },
    { kind: "paragraph", text: "'Tayēr' 공간을 이용하기 위해서는 사전에 예약을 하시거나, 방문 시에 직원 분에게 꼭 'Tayēr' 공간을 방문하고 싶다고 말씀해주셔야 합니다(특히 외국 바나 주류샵 등은 얘기해야 안내를 하는 경우가 왕왕 있어 꼭 문의를 하는 편이 좋습니다)." },
    { kind: "figure", src: "/articles/london-tayer-elementary/00.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "Elementary" },
    { kind: "figure", src: "/articles/london-tayer-elementary/01.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "첫 잔으로 저와 제 친구는 각각 \"페니실린(Penicilin)\"과 \"라즈베리 캄파리 소다(Raspberry Campari Soda)\"를 주문했습니다. 페니실린은 미리 투명화를 한 상태로 서브하였고, 라즈베리 캄파리 소다는 라즈베리를 캄파리에 인퓨징해서 서브한 것으로 보입니다." },
    { kind: "paragraph", text: "페니실린은 아몬티야도 쉐리의 캐릭터를 더했지만 투명화한 것 빼고는 그렇게 특별하다는 생각은 별로 들지 않았고, 오히려 기존의 강렬함이 없이 너무 점잖은 느낌이 들었습니다. 라즈베리 캄파리 소다는 기존의 캄파리 소다의 쌉쌀달달함에 상큼함을 더해 리프레시하기에 아주 좋은 음료였습니다." },
    { kind: "figure", src: "/articles/london-tayer-elementary/02.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "두 번째 잔으로는 \"한 입 마티니(One Sip Martini)\"를 주문했는데, 꽤나 귀여운 모습으로 이름에 걸맞는 비주얼의 마티니가 나왔습니다. 서브를 해주면서 이름대로 원샷이 권장사항이지만, 꼭 그러지 않아도 된다는 설명은 덤." },
    { kind: "paragraph", text: "맛 자체는 마티니 치고는 꽤 도수감이 적게 느껴져 마일드했고, 피노 쉐리의 캐릭터가 많이 느껴졌는데, 원래 이렇게 작은 사이즈로 나오는 마티니들은 가볍게 마실 수 있도록 만들어주는 경우가 많기 때문에 고개가 끄덕여지는 맛이었습니다." },
    { kind: "paragraph", text: "Tayēr" },
    { kind: "figure", src: "/articles/london-tayer-elementary/03.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "저는 바에 방문한 후에야 공간이 나뉘어져 있는 걸 알고, 직원 분께 문의를 하였고, 운 좋게도 20~30분 정도가 지나 'Tayēr' 공간에 입장할 수 있었습니다." },
    { kind: "paragraph", text: "앞서 말했듯이, 문의하지 않으면 먼저 물어봐주지 않으니 꼭꼭 'Tayēr' 공간을 이용할 수 있는지 문의하시고 'Tayēr' 공간을 이용하시는 걸 추천드립니다. 이렇게까지 얘기하는 이유는 'Tayēr'가 'Elementary'와 메뉴 자체가 다르고, 좀 더 메이킹하는 것을 볼 수 있어서 그렇습니다." },
    { kind: "figure", src: "/articles/london-tayer-elementary/04.webp", width: 600, height: 600 },
    { kind: "figure", src: "/articles/london-tayer-elementary/05.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "'Tayēr'의 칵테일 메뉴는 매일 바뀐다고 하며, 이름이 아닌 재료만이 적혀 있는 것이 큰 특징입니다." },
    { kind: "paragraph", text: "이 날 제 친구가 주문한 칵테일(첫 번째와 두 번째 사진)이 친구의 주문을 마지막으로 매진되었는데, 왜 매진되었을지 알 정도로 정말 맛있는 한 잔이었습니다. 럼과 피트 위스키의 조합, 마티니스러운 구성, 구운 파인애플과 버터라는 독창적인 재료까지 'Tayēr'의 성격을 아주 잘 보여주는 칵테일이었습니다." },
    { kind: "figure", src: "/articles/london-tayer-elementary/06.webp", width: 600, height: 600 },
    { kind: "figure", src: "/articles/london-tayer-elementary/07.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "그 뒤로도 두 잔씩을 더 시켰는데, 메뉴에 이름이 정해져 있는 게 아니라서 리뷰로 풀어내기가 어려운 데다가, 사실 이후로는 개인적인 입맛에서 인상적인 느낌을 받은 칵테일은 없었기도 했습니다. 다만, 단순한 칵테일 구조를 재밌는 재료와 조합 등을 통해 매력적인 칵테일을 만들어내는 것은 충분한 재미요소였습니다." },
    { kind: "paragraph", text: "전체적으로 \"Tayēr + Elementary\"는 많은 서양의 바들이 그렇듯 믹솔로지(Mixology)스러운 성향이 강하며, 이런 점에 부담스러움을 느낄 분들도 있을 거라 생각합니다." },
    { kind: "paragraph", text: "그렇지만 창의적인 재료의 선택, 조합, 기법, 국내에서는 구할 수 없는 주류의 사용 등등 다양한 부분에 있어서 충분히 즐길 점이 많다고 생각됩니다. 또한 직원분들도 매우 친절하니 망설이지 말고 물어보시고, 칵테일 추천도 받아보는 것을 추천드립니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
