import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "london-soma",
  category: "bar",
  title: "소마",
  dek: "\"Bar SOMA\"는 런던 소호에 위치한 바로, 2021년에 오픈한 아직 어린 바입니다. 저는 국내의 \"뽐(Pomme)\"이라는 바의 현재 매니저님에게 추천을 받아서 방문하게 되었습니다.",
  publishedAt: "2024-06-27",
  hero: "/articles/london-soma/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223493239728",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "paragraph", text: "\"Bar SOMA\"는 런던 소호에 위치한 바로, 2021년에 오픈한 아직 어린 바입니다. 저는 국내의 \"뽐(Pomme)\"이라는 바의 현재 매니저님에게 추천을 받아서 방문하게 되었습니다." },
    { kind: "paragraph", text: "\"SOMA\"란 '증류 및 추출'을 의미하는 베다 산스크리트어 단어이며, 이 바에서는 클래식 칵테일을 재해석하면서 인도 등지의 재료를 사용하는 것을 주로 한다고 합니다." },
    { kind: "paragraph", text: "\"SOMA\"는 스피크이지(Speakeasy)가 컨셉인 바로, 처음 간다면 저처럼 약간 헤멜 수 있습니다. 먼저 아래 사진과 같은 간판을 찾으시면 그 옆에 가드가 앉아 있을텐데, 그 가드에게 말을 걸면 안내를 해줍니다. 그 후 어두운 공간에서 계단을 한 층 내려가 입장하게 됩니다." },
    { kind: "figure", src: "/articles/london-soma/00.webp", width: 600, height: 799, caption: "SOMA의 간판" },
    { kind: "paragraph", text: "처음 방문할 때는 저처럼 간판만 보고 옆 가게로 착각하고 들어가려는 일이 발생할 수 있으니, 문 앞의 가드분에게 말을 걸어주세요. 저 같은 경우에는 간판 잘 찾고 옆 가게로 가려는 걸 가드분이 말을 걸어주셔서 제대로 들어갔습니다 ㅎㅎㅎ" },
    { kind: "figure", src: "/articles/london-soma/01.webp", width: 600, height: 1066 },
    { kind: "figure", src: "/articles/london-soma/02.webp", width: 600, height: 1066 },
    { kind: "figure", src: "/articles/london-soma/03.webp", width: 600, height: 1066 },
    { kind: "paragraph", text: "\"SOMA\"의 주요 메뉴를 살펴보면 칵테일의 주요 캐릭터가 큰 글자로 되어있고, 그 밑으로는 재료가, 그 위로 원형이 되는 클래식 칵테일이 괄호로 표기되어 있습니다.  일단 칵테일의 캐릭터를 크게 써놓으니 주문하기에 어렵지가 않다는 점은 매우 좋은 점이라 생각됩니다." },
    { kind: "figure", src: "/articles/london-soma/04.webp", width: 600, height: 600 },
    { kind: "figure", src: "/articles/london-soma/05.webp", width: 600, height: 600 },
    { kind: "paragraph", text: "첫 잔으로는 저와 친구는 '캐슈(CASHEW)'와 '리프(LEAF)'를 주문했습니다." },
    { kind: "paragraph", text: "'캐슈'는 네그로니의 변형으로, 보타니컬한 진 대신에 어시(earthy)하고 스모키한 메즈칼을 기주로 하며, 구운 캐슈넛과 커피 열매의 과육인 카스카라(Cascara)를 사용해서 만들어진 버무스를 사용한 것을 특징으로 합니다. 스모키한 네그로니에 약간의 너티함이 추가된 듯한 느낌이었습니다." },
    { kind: "paragraph", text: "'리프'는 김렛의 변형으로 오리엔탈 스파이스의 캐릭터가 특징인 오피르(Opihr) 진을 기주로, 라임 잎과 커리 잎을 사용하는, 향신료의 느낌이 가득한 조합의 김렛을 만들어냅니다." },
    { kind: "paragraph", text: "보통의 김렛과는 다르게 투명화를 거친 것으로 산미는 크게 느껴지지 않고, 라임 오일(?)을 그 위에 떨어뜨린 식으로 김렛의 캐릭터를 잃지 않도록 하는 느낌이었습니다." },
    { kind: "figure", src: "/articles/london-soma/06.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/london-soma/07.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "다음잔으로는 '코코넛(COCONUT)'과 '커피(COFFEE)'를 주문했는데, '코코넛'은 비주얼적으로 꽤 예뻐서인지 꽤 많은 사람들이 주문하는 메뉴였습니다." },
    { kind: "paragraph", text: "'코코넛'에는 코코넛 요거트, 시트러스 블러썸(아마도 시트러스 오일 또는 추출물), 핑크 자몽 소다가 들어가는데 재료의 조합이 꽤 직관적으로 느껴지는 맛이었습니다." },
    { kind: "paragraph", text: "'커피'는 카카오 럼과 VS급 꼬냑을 기주로, 다양한 향신료가 들어가는 탄다이(인도의 음료)에 버터스카치가 들어가는 칵테일인데, 이게 맛이 그냥 스카치 캔디 커피맛과 완~~~전히 똑같습니다." },
    { kind: "paragraph", text: "버터스카치와 커피의 캐릭터가 지배적이었는데, 향신료의 느낌이 거의 느껴지지 않았다는 점이 아쉬웠습니다. 이 뒤로 인도의 진을 쓴 진토닉과 위스키 사워를 시켰는데, 굳이 리뷰할 정도의 것은 아니었네요." },
    { kind: "paragraph", text: "전체적으로 '바 소마'는 믹솔로지(Mixology)적인 성격이 강한데, 차별점이라 한다면 클래식 칵테일에서 영감을 받지만 그 구조를 완전히 따라가지는 않는다는 점과 인도의 향신료를 적극적으로 사용한다는 점을 들 수 있습니다." },
    { kind: "paragraph", text: "평소에 국내에서 접하기 어려운 재료들, 특히 향신료나 인도의 진 등을 경험할 수 있다는 점에서 아주 좋았습니다." },
  ],
};
