import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "long-island-iced-tea",
  category: "cocktail",
  title: "롱아일랜드 아이스티 — 칵테일계의 원기옥",
  dek: "\"롱아일랜드 아이스티\"는 서양에서는 1970~1980년대(특히 미국)에 큰 인기를 끌었으며, 우리나라에서도 예전부터 바 뿐만 아니라 펍에서도 흔하게 볼 수 있을 정도로 잘 알려진 칵테일입니다.",
  publishedAt: "2024-09-09",
  hero: "/articles/long-island-iced-tea/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223577739711",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/long-island-iced-tea/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"롱아일랜드 아이스티\"는 서양에서는 1970~1980년대(특히 미국)에 큰 인기를 끌었으며, 우리나라에서도 예전부터 바 뿐만 아니라 펍에서도 흔하게 볼 수 있을 정도로 잘 알려진 칵테일입니다." },
    { kind: "paragraph", text: "1972년 뉴욕 주의 롱아일랜드에 위치한 오크 비치 인(Oak Beach Inn/OBI)에서 칵테일 콘테스트가 열렸고, 칵테일에 트리플 섹을 넣을 것을 요구했다고 합니다." },
    { kind: "paragraph", text: "당시에 OBI에서 일하던 로버트 \"로즈버드\" 버트(Robert \"Rosebud\" Butt)는 이 콘테스트에 참가하기 위해 이 칵테일을 만들었다고 합니다." },
    { kind: "paragraph", text: "로버트 버트가 회상하기로는 \"만들고 나서 5년이 지나고는 어디에서든 이 칵테일을 판매했다.\"라고 하며, 1985년 뉴욕 타임스는 롱아일랜드 아이스티라는 독한 칵테일이 전국의 술집을 휩쓸고 있다고 보도하기도 할 정도였다고 합니다." },
    { kind: "paragraph", text: "롱아일랜드 아이스티는 기주라 할 게 없고, 5개의 높은 도수의 술이 동률로 들어가 칵테일로서는 \"근본 없는\" 조합으로 이루어져 있는데 사실 이게 인기의 포인트라 할 수 있습니다." },
    { kind: "paragraph", text: "들어가는 술을 모두 싸게 구할 수 있어 700미리 병 기준으로 40잔 이상 만들 수 있는 데다가, 잔에 얼음 채우고 대충 넣어서 쉽게 만들 수도 있어서 캐주얼하고, 도수가 높아 가격에 비해 가성비가 좋은 등 친구들이 삼삼오오 모여서 간단하게 기분 내며 마실 수 있는 칵테일이기 때문입니다." },
    { kind: "paragraph", text: "\"롱아일랜드 아이스티\"라는 이름에서 립톤 사의 아이스티 같은 복숭아 티 같은 맛이 날 거라 생각하기 쉬운데, 사실 그런 맛이 나지는 않고 색깔이 아이스티와 비슷해서 붙은 이름입니다." },
    { kind: "figure", src: "/articles/long-island-iced-tea/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "15ml 진 (Gin)" },
    { kind: "paragraph", text: "15ml 화이트 럼 (White Rum)" },
    { kind: "paragraph", text: "15ml 블랑코 데킬라 (Blanco Tequila)" },
    { kind: "paragraph", text: "15ml 보드카 (Vodka)" },
    { kind: "paragraph", text: "15ml 코앵트로 (Cointreau)" },
    { kind: "paragraph", text: "30ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "10ml 설탕 시럽 (Simple Syrup)" },
    { kind: "paragraph", text: "**콜라 소량" },
    { kind: "paragraph", text: "가니시: 레몬 웨지 or 레몬 휠" },
    { kind: "paragraph", text: "**콜라는 양을 너무 많이 넣지 않도록 해줍니다(약 30-45ml)." },
    { kind: "paragraph", text: "칵테일의 제작자인 로버트 버트는 \"색을 내기 위해 콜라를 소량 넣는다(a little Coke just to make the color).\"라고 한 걸 보면 콜라는 맛보다는 그저 아이스티 같은 색을 내기 위해서 넣는 것에 불과합니다." },
    { kind: "figure", src: "/articles/long-island-iced-tea/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/long-island-iced-tea/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 콜라를 제외한 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 얼음을 채운 긴 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 색을 내기 위해 콜라를 소량 부어줍니다." },
    { kind: "paragraph", text: "5. 레몬으로 가니시해줍니다." },
    { kind: "figure", src: "/articles/long-island-iced-tea/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "롱아일랜드 아이스티는 대학 시절에 누구나 한 번쯤은 마셔봤을 법한 칵테일로, 펍에서도 아주 쉽게 찾아볼 수 있습니다." },
    { kind: "paragraph", text: "개인적인 입맛으로는 그렇게 맛있는 칵테일이라 생각하지는 않지만, 우리나라 바텐더들 중에서는 롱아일랜드 아이스티를 좋아해 이를 개량한 사람들도 종종 있습니다." },
    { kind: "paragraph", text: "롱아일랜드 아이스티는 레시피가 사람마다 달라서 너무 종류가 많은데, 잔의 용량이나 만드는 방법에 따라서 술을 얼마나 넣을지를 정해야 합니다." },
    { kind: "paragraph", text: "예를 들어 제가 사용한 잔은 용량이 360ml로 크지 않은 편이고, 셰이킹 해서 다일루션이 더 생겼기 때문에 술을 15ml씩 사용했습니다." },
    { kind: "paragraph", text: "롱아일랜드 아이스티는 40도의 술을 기준으로 적어도 두 잔 반 이상의 용량이 술로 들어가기 때문에 마실 때에는 취하지 않도록 조심해야 합니다." },
  ],
};
