import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "longrow-16yo-campbeltown-malts-festival-2024",
  category: "spirits",
  title: "롱로우 16년 캠벨타운 몰츠 페스티벌 2024",
  dek: "\"캠벨타운 몰츠 페스티벌(Campbeltown Malts Festival)\"은 캠벨타운의 스프링뱅크 증류소, 글렌가일 증류소, 글렌스코시아 증류소, 카덴헤드가 중심이 되어 열리는 위스키 관련 축제입니다.",
  publishedAt: "2024-09-02",
  hero: "/articles/longrow-16yo-campbeltown-malts-festival-2024/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223569207842",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/longrow-16yo-campbeltown-malts-festival-2024/00.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/longrow-16yo-campbeltown-malts-festival-2024/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "\"캠벨타운 몰츠 페스티벌(Campbeltown Malts Festival)\"은 캠벨타운의 스프링뱅크 증류소, 글렌가일 증류소, 글렌스코시아 증류소, 카덴헤드가 중심이 되어 열리는 위스키 관련 축제입니다." },
    { kind: "paragraph", text: "올해의 캠벨타운 몰츠 페스티벌의 주인공은 킬커란이었다고 할 수 있는데, 킬커란은 현 스프링뱅크의 소유주인 J&A 미첼이 글렌가일 증류소를 인수하고 처음으로 증류한 2004년으로부터 올해로 20년이 되었습니다." },
    { kind: "paragraph", text: "이를 기념하기 위해서도 글렌가일 증류소에서는 올해 축제의 오픈 데이 바틀로 2004년 증류해 20년 동안 숙성한 킬커란을 출시하기도 하였습니다." },
    { kind: "paragraph", text: "\"롱로우\"는 스프링뱅크 증류소에서 출시되는 세 가지 싱글몰트 위스키의 코어 라인 중 하나로, 세 위스키 중 가장 피트감이 강한 위스키입니다." },
    { kind: "paragraph", text: "스프링뱅크는 올해 오픈 데이에서 아래의 스펙으로 세 가지 위스키를 출시했습니다." },
    { kind: "paragraph", text: "스프링뱅크" },
    { kind: "paragraph", text: "-피지 럼 캐스크 (Fijian Rum Casks) 10년, 57.1%" },
    { kind: "paragraph", text: "헤이즐번" },
    { kind: "paragraph", text: "-버번 & 올로로소 캐스크 (Bourbon & Oloroso Casks) 8년, 52.8%" },
    { kind: "paragraph", text: "롱로우" },
    { kind: "paragraph", text: "-루비 포트 캐스크 (Ruby Port Casks) 16년, 54.7%" },
    { kind: "figure", src: "/articles/longrow-16yo-campbeltown-malts-festival-2024/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/longrow-16yo-campbeltown-malts-festival-2024/03.webp", width: 966, height: 966 },
    { kind: "quote", text: "증류소: 스프링뱅크 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 루비 포트 캐스크 (Ruby Port Casks), 16년" },
    { kind: "quote", text: "도수: 54.7%" },
    { kind: "quote", text: "시리즈: 캠벨타운 몰츠 페스티벌 오픈 데이" },
    { kind: "figure", src: "/articles/longrow-16yo-campbeltown-malts-festival-2024/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 묵직한 달달함" },
    { kind: "paragraph", text: "- 포도, 말린 대추야자, 베리류의 건과일" },
    { kind: "paragraph", text: "- 약간의 피트" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 향에서 크게 변하지 않으며, 롱로우 특유의 캐릭터에서 좀 더 달달하고 우디함" },
    { kind: "paragraph", text: "- 달달한 피트에서 갑작스럽게 우디함으로 변함" },
    { kind: "paragraph", text: "- 혀 끝에 남는 꿀의 캐릭터" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "- 달달한 포도나 살짝의 우디함이 꽤 길게 느껴짐" },
    { kind: "paragraph", text: "- 기분 좋을 정도의 피트" },
    { kind: "paragraph", text: "개인적으로 스프링뱅크에서 출시되는 세 가지의 위스키를 모두 좋아하는데, 올해의 오픈 데이에 출시된 것들 중에서는 롱로우가 가장 맛있었습니다." },
    { kind: "paragraph", text: "오픈 데이 스프링뱅크와 헤이즐번은 증류소의 워시백 바에서 마셔봤는데, 개인적으로 엔트리에 비해서 그렇게 특별함을 느끼지는 못했습니다." },
    { kind: "paragraph", text: "워시백 바에서 못마셨던 오픈 데이 롱로우가 용량이 350ml로 작아서 한 병 사들고 유럽 여행 내내 친구와 나눠마셨는데, 이건 정말 맛있게 마셨네요." },
    { kind: "paragraph", text: "350ml에 아마 60파운드(?)였었는데, 이 가격이면 몇 병이라도 쟁여두고 마시고 싶을 정도였습니다." },
    { kind: "paragraph", text: "무카와에는 28,800엔으로 재고가 2개 있던데, 스프링뱅크 증류소 제품 + 숙성년수 + 용량을 총합해서 비교해보면 그렇게 비싸지 않은 것 같기도 한 것 같고...." },
  ],
};
