import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "mars-the-lucky-cat-double-individuals-hana-and-choco",
  category: "spirits",
  title: "마르스 럭키 캣 하나 & 초코",
  dek: "\"마르스 럭캐 캣\" 시리즈는 일본의 \"마르스(Mars) 위스키\"의 리미티드 에디션으로, 블렌디드 위스키로 릴리즈되며, 사랑스러운 고양이 라벨이 특징인 냥스키입니다.",
  publishedAt: "2024-07-31",
  hero: "/articles/mars-the-lucky-cat-double-individuals-hana-and-choco/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223531891910",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/mars-the-lucky-cat-double-individuals-hana-and-choco/00.webp", width: 526, height: 526 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "\"마르스 럭캐 캣\" 시리즈는 일본의 \"마르스(Mars) 위스키\"의 리미티드 에디션으로, 블렌디드 위스키로 릴리즈되며, 사랑스러운 고양이 라벨이 특징인 냥스키입니다." },
    { kind: "paragraph", text: "그 중에서 \"하나 & 초코\"는 시리즈의 9번째 위스키로, 라벨에 그러진 응석받이인 하나와 말괄량이인 초코라는 자매 고양이를 모티브로 해서 만들어졌다고 합니다." },
    { kind: "paragraph", text: "올로로소 셰리 캐스크, 와인 캐스크, 스패니시 오크 캐스크를 사용해 스패니시 오크가 구조를 탄탄하게 받혀주며, 올로로소 셰리 및 와인 캐스크로 부드러운 단맛과 과실 캐릭터를 부여하려 했다고 합니다." },
    { kind: "paragraph", text: "2024년 5월에 병입되어 7,920병이 출시되었으며, 한국에는 210병이 들어왔다고 합니다. 이전 럭키 캣 시리즈가 소량만 들어온 것에 비해서는 꽤 많은 바틀이 들어왔네요." },
    { kind: "figure", src: "/articles/mars-the-lucky-cat-double-individuals-hana-and-choco/01.webp", width: 540, height: 720 },
    { kind: "figure", src: "/articles/mars-the-lucky-cat-double-individuals-hana-and-choco/02.webp", width: 507, height: 676 },
    { kind: "quote", text: "증류소: 마르스 코마가타케 증류소" },
    { kind: "quote", text: "시리즈: 럭키 캣" },
    { kind: "quote", text: "위스키 타입: 블렌디드 위스키" },
    { kind: "quote", text: "캐스크 정보: Oloroso Sherry Cask, Wine Cask, Spanish Oak Cask" },
    { kind: "quote", text: "생산량: 7,920병" },
    { kind: "quote", text: "도수: 43%" },
    { kind: "figure", src: "/articles/mars-the-lucky-cat-double-individuals-hana-and-choco/03.webp", width: 540, height: 540 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 말린 무화과, 바닐라(?), 복숭아나 살구같은 과실의 달달함" },
    { kind: "paragraph", text: "- 약간의 스파이스(향신료)" },
    { kind: "paragraph", text: "- 알콜감이 튀어 약간은 거칠지만 달달함이 있음" },
    { kind: "paragraph", text: "- 시간이 지날수록 알콜감이 적어지고, 달달함이 더 올라옴" },
    { kind: "paragraph", text: "- 약간은 크리미 또는 밀키함" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 단맛, 뭔지 모를 향신료(아마 시나몬?), 우디함" },
    { kind: "paragraph", text: "- 다만, 맛이 너무 약해 캐릭터를 캐치하기 어려움" },
    { kind: "paragraph", text: "- 약간은 저숙성 럼 같은 느낌도 듬" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "- 달달함과 우디함이 쓱 지나감" },
    { kind: "paragraph", text: "- 구체적인 캐릭터보다는 어떤 느낌이 난다 정도" },
    { kind: "paragraph", text: "향은 괜찮았던 것에 비해 맛과 피니시가 다소 아쉬웠으며, 어느정도 단순한 캐릭터였던 것 같으나 라벨이 정말 맛있습니다." },
    { kind: "paragraph", text: "사실 라벨이 너무 마음에 들어서 구입한 것도 있는데, 냥스키 오우너가 되고 싶거나 시리즈를 모으지 않는 한 굳이 살 것 같지는 않습니다." },
    { kind: "paragraph", text: "한국에서 출시하면 10만원대인 걸로 알고 있는데, 좀 비싸다고 생각하고, 저는 5월에 후쿠오카에서 우연히 발견해서 7~8천엔에 구입했던 것 같습니다." },
    { kind: "paragraph", text: "라벨은 참 이쁜데...." },
  ],
};
