import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "mary-pickford",
  category: "cocktail",
  title: "메리 픽포드 — 아름다운 아메리칸 스윗하트를 위한 칵테일",
  dek: "\"메리 픽포드\"는 1920년대 초 쿠바에서 만들어진 칵테일로, 당시 '미국의 연인(America's Sweetheart)'이라는 애칭을 처음으로 받은 여배우의 이름이 붙여진 것입니다.",
  publishedAt: "2024-07-29",
  hero: "/articles/mary-pickford/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223529434771",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/mary-pickford/00.webp", width: 515, height: 515 },
    { kind: "paragraph", text: "\"메리 픽포드\"는 1920년대 초 쿠바에서 만들어진 칵테일로, 당시 '미국의 연인(America's Sweetheart)'이라는 애칭을 처음으로 받은 여배우의 이름이 붙여진 것입니다." },
    { kind: "paragraph", text: "오래된 칵테일이 종종 그렇듯 그 탄생이 명확하지 않은데, 가장 유력한 설은 1920년대 초 메리 픽포드가 영화 촬영을 위해 배우자인 더글러스 페어뱅크스와 그의 절친인 찰리 채플린과 함께 쿠바에 방문했을 때, 나시오날 호텔(Nacional Hotel)의 바텐더가 그녀를 위해 만들었고, 그녀의 이름을 붙였다고 합니다." },
    { kind: "paragraph", text: "다만, 그 바텐더가 누구였는지에 대해 논란이 있는데, 에디 웰케(Eddie Woelke)와 프레드 카우프먼(Fred Kaufman)이 유력한 후보이며, 후자가 좀 더 신빙성이 있다고 보는 것이 대세라 합니다." },
    { kind: "paragraph", text: "그러나 이후에 1920년대에 메리 픽포드가 영화 촬영을 위해 쿠바를 방문한 적이 없으며, 더욱이 결혼 생활 동안 쿠바에서 영화 촬영을 한 적이 없다는 것이 밝혀지면서 이 가설은 힘을 잃게 됩니다." },
    { kind: "paragraph", text: "이후 1928년에 바질 운(Basil Woon)의 저서인 \"When It’s Cocktail Time in Cuba\"에서 처음 기록되었으며, 1930년에는 해리 크래독(Harry Craddock)의 저서인 \"The Savoy Cocktail Book\"에 등장하였습니다." },
    { kind: "figure", src: "/articles/mary-pickford/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "40ml 화이트 럼 (White Rum)" },
    { kind: "paragraph", text: "40ml 파인애플 주스 (Pineapple Juice)" },
    { kind: "paragraph", text: "10ml 그레나딘 시럽 (Grenadine Syrup)" },
    { kind: "paragraph", text: "3ml 마라스키노 리큐르 (Maraschino Liqueur)" },
    { kind: "figure", src: "/articles/mary-pickford/02.webp", width: 430, height: 430 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 쉐이커 안에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후, 차게 해 둔 칵테일 잔에 부어줍니다." },
    { kind: "figure", src: "/articles/mary-pickford/03.webp", width: 516, height: 516 },
    { kind: "paragraph", text: "\"메리 픽포드\"는 트로피컬한 과실의 단맛이 장점인 칵테일로, 상큼하고 달달한 느낌이 나며, 거기에 마라스키노 리큐르의 체리 캐릭터가 살짝 더해져 칵테일의 맛을 좀 더 풍부하게 해줍니다." },
    { kind: "paragraph", text: "숏 칵테일임에도 불구하고 파인애플 주스가 기주와 동량으로 꽤 많이 들어가게 되는 것이 특징인데, 이 파인애플 주스의 양을 조절하는 게 이 칵테일의 핵심이 아닐까 싶습니다. 너무 적게 넣으면 럼의 알콜감이 튀고, 너무 많이 넣으면 럼의 풍미가 죽어버리게 됩니다." },
    { kind: "paragraph", text: "금주법 시대에 만들어진 아주 오래된 칵테일이니 만큼 레시피가 딱 정해져 있는 것이 아닌, 정말 많은 레시피가 존재합니다. 다른 레시피들을 참고하면서 본인의 입맛에 맞춰가는 재미가 있는 칵테일이죠." },
    { kind: "paragraph", text: "저 같은 경우는 그레나딘을 늘리고, 마라스키노를 줄였습니다. 그레나딘은 파인애플 주스의 캐릭터가 과하지 않게 좀 눌러주기 위해서, 마라스키노는 캐릭터가 강한 걸 개인적으로 좋아하지 않아서 은은하게 날 수 있게 조정을 햇습니다." },
  ],
};
