import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "matador",
  category: "cocktail",
  title: "마타도르 — 무더운 여름, 간단하게 음식과 곁들여 마시기 좋은 칵테일",
  dek: "\"마타도르\"는 투우에서 소에게 최후의 일격을 가하는 투우사라는 뜻을 가지는데, 사실 칵테일 자체는 생각보다 달큰한 감이 있어서 약간은 이름과 이미지가 미스매치인 듯한 칵테일입니다.",
  publishedAt: "2024-08-05",
  hero: "/articles/matador/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223537145044",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/matador/00.webp", width: 473, height: 473 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"마타도르\"는 투우에서 소에게 최후의 일격을 가하는 투우사라는 뜻을 가지는데, 사실 칵테일 자체는 생각보다 달큰한 감이 있어서 약간은 이름과 이미지가 미스매치인 듯한 칵테일입니다." },
    { kind: "paragraph", text: "다소 오래된 칵테일로, 그 기원 자체는 명확하지는 않습니다. 다만, 1972년 빅터 버거론(Victor Jules Bergeron)의 저서인 \"Trader Vic's Bartender's Guide\"에서 \"데킬라 마타도르(Tequila Matador)\"라는 이름으로 소개된 것이 가장 오래된 기록이라 합니다." },
    { kind: "paragraph", text: "물론 그 이전부터 칵테일 자체는 존재하기는 했다고 합니다. 가장 오래된 기록이 빅터 버거론의 저서에서 발견됐다 정도로 이해하면 될 것 같습니다(빅터 버거론의 비율은 2:4:1)." },
    { kind: "paragraph", text: "제가 알기로 서양에서는 거의 사장되다 싶이 한 칵테일이고, 찾아보더라도 좀 다른 레시피가 많습니다. 우리나라 바에서는 간혹 볼 수 있는데, 이건 우리나라 바가 일본 바의 영향을 많이 받아서 그런 것으로 보입니다." },
    { kind: "figure", src: "/articles/matador/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "30ml 블랑코 데킬라 (Blanco Tequila)" },
    { kind: "paragraph", text: "45ml 파인애플 주스 (Pineapple Juice)" },
    { kind: "paragraph", text: "15ml 라임즙 또는 레몬즙 (Lime/Lemon Juice)" },
    { kind: "figure", src: "/articles/matador/02.webp", width: 390, height: 390 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후, 얼음을 채운 락글라스에 부어줍니다." },
    { kind: "figure", src: "/articles/matador/03.webp", width: 449, height: 449 },
    { kind: "paragraph", text: "\"마타도르\"는 트로피컬한 단맛과 상큼한 신맛이 적절히 어우러지면서도 데킬라의 캐릭터가 뼈대를 잡아주는 칵테일입니다. 달큰한 맛 뒤에 오는 데킬라의 맛이 마타도르를 이미지화한 것이라고 생각할 수도 있겠네요." },
    { kind: "paragraph", text: "아직 데킬라의 특유의 맛과 향에 익숙하지 않은 분들도 부담 없이 즐길만한 칵테일이며, 간이 세거나 매운 음식과 궁합이 꽤 좋을 것 같습니다. 트로피컬한 칵테일이니 만큼 여름에 마시기에 좋은 칵테일이죠." },
    { kind: "paragraph", text: "원래 레시피에는 라임을 사용하나, 좀 더 상큼한 캐릭터를 내고 싶으시다면 레몬즙을 사용하는 것도 좋은 선택입니다." },
    { kind: "paragraph", text: "원래 가니시는 없지만, 마타도르의 상징이 붉은 천인 만큼 붉은 색의 체리로 간단하게 가니시해주는 것도 칵테일의 매력을 높이는 방법이겠네요." },
  ],
};
