import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "milk-and-honey-mokpo",
  category: "bar",
  title: "밀크앤허니 — 목포에서 만난 스피크이지 바",
  dek: "노크하면 작은 창이 먼저 열리는 목포의 스피크이지 바. 사샤 페트라스케의 이름을 이어받은 클래식 칵테일이 있다.",
  publishedAt: "2025-04-20",
  hero: "/articles/milk-and-honey-mokpo/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223840422282",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/00.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/01.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "「밀크앤허니」는 목포의 평화공원 근처에 위치한 바로, 지방에서는 보기 드물게 스피크이지(Speakeasy) 콘셉트로 운영하고 있는 곳입니다." },
    { kind: "paragraph", text: "스피크이지 바란 미국 금주령 시대에 생긴 개념으로, \"겉으로 봐서는 바라고는 생각할 수 없는 외관에 아는 사람만 알음알음 찾아가는 바\"입니다." },
    { kind: "paragraph", text: "90년대 후반 ~ 2000년대 초부터 미국을 중심으로 '사샤 페트라스케'에 의해 다시 유행하게 된 콘셉트로, 현재에는 국내에서도 심심찮게 찾아볼 수 있습니다." },
    { kind: "paragraph", text: "'밀크 앤 허니(Milk & Honey)'라는 바 이름은 아마 사샤 페트라스케가 뉴욕에서 운영했었던 동명의 바에서 따온 것으로 보이는데, 이 바의 지향점을 엿볼 수 있는 부분입니다." },
    { kind: "paragraph", text: "밀크앤허니에서는 스피크이지 콘셉트에 따라서 문을 노크하면 문 위의 작은 창을 열어 확인을 하고, 문을 열어주는 식입니다." },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/02.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "바에 들어서면 한 쪽 벽면에는 사샤 페트라스케의 글귀를 적어 놓았고. 내부 사진을 깜빡하고 안찍었는데, 바테이블 + 별도의 테이블로 나뉘어져 있습니다." },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "첫 잔은 역시 하이볼" },
    { kind: "paragraph", text: "첫 잔은 당연히 하이볼을 생각하고 있었는데, 기주에 올드 파 12년이 있길래 바로 주문했습니다. 아직까지 올드 파로 하이볼을 마셔본 적이 없었거든요. 첫 입을 마셔보고 '아, 다른 칵테일이 기대된다'는 생각이 바로 들었습니다." },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/05.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/07.webp", width: 966, height: 1289, caption: "왼쪽부터 김렛, 사이드카, 사제락, 네그로니" },
    { kind: "paragraph", text: "친구와 함께 가서 서로 좋아하는 칵테일을 두 잔씩 시켰는데, 개인적으로 최근에 방문한 바 중에 제 입맛에 가장 맞았습니다." },
    { kind: "paragraph", text: "예를 들어서 사이드카 같은 경우에는 쥬시하고, 살짝 무게감 있고, 거품층이 생기는 걸 좋아하는데, 딱 이 취향에 맞는 맛이었습니다. 네그로니도 쓴맛과 단맛의 밸런스가 절묘했던." },
    { kind: "paragraph", text: "제가 클래식 칵테일을 워낙 좋아하다 보니, 이곳의 시그니처를 못 마셨던 게 살짝 아쉬웠지만, 마신 칵테일들이 전부 맛있었습니다." },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/08.webp", width: 966, height: 1287 },
    { kind: "figure", src: "/articles/milk-and-honey-mokpo/09.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "칵테일 외에도 이곳에서는 3가지 술을 골라서 15ml(?)씩 주문할 수가 있었는데, 평소에는 좀 가격대가 있어서 마시기 망설여지던 녀석들을 마시기에 딱 좋습니다." },
    { kind: "paragraph", text: "그래서 평소에 친구와 궁금했던 데킬라 '클라세 아줄 레포사도'와 위스키 '탈리스커 DE', '아란 증류소의 익스플로러 시리즈 중에서 킬도넌 & 플라다 아일랜드'를 주문해 봤습니다. '드루마둔'은 사장님이 비교해 보라고 주신 서비스." },
    { kind: "paragraph", text: "개인적으로 그중에서는 킬도넌 & 플라다 아일랜드가 가장 기억에 남는데, 50.4도임에도 도수감이 느껴지지 않고, 모난 부분 없이 꽤나 달큰했었습니다. 구할 수만 있으면 한 병 구하고 싶을 정도." },
    { kind: "paragraph", text: "제가 밀크앤허니를 방문했을 때는 아마 2월 정도였던 걸로 기억하는데, 클래식 칵테일이 정말 맛있어서 다음잔이 기대되고, 가격이 합리적이었어서 인상 깊었던 바였습니다." },
    { kind: "paragraph", text: "방문하신다면 클래식 칵테일이나, 모던 클래식 칵테일을 꼭 한 잔 정도는 주문해보시길" },
  ],
};
