import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "miraon-very-young",
  category: "spirits",
  title: "미라온 베리영 — 쌀의 즐거움",
  dek: "'미라온'은 스코틀랜드 아일라 섬의 아드벡 증류소에서 바텐더로 근무했던 '오수민 대표'가 운영하는 '화심주조'에서 출시한 숙성된 증류식 소주입니다.",
  publishedAt: "2024-12-04",
  hero: "/articles/miraon-very-young/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223681955688",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/miraon-very-young/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "About the Soju" },
    { kind: "paragraph", text: "'미라온'은 스코틀랜드 아일라 섬의 아드벡 증류소에서 바텐더로 근무했던 '오수민 대표'가 운영하는 '화심주조'에서 출시한 숙성된 증류식 소주입니다." },
    { kind: "paragraph", text: "다만, 일반적인 증류식 소주가 원료인 쌀을 불리고 찐 후에 누룩을 사용해서 발효하는 것과는 다르게, 쌀을 구운 후에 당화 과정을 거친 후, 위스키용 효모를 사용해서 발효를 하고 나서 2번의 증류를 한다고 합니다." },
    { kind: "paragraph", text: "그러니 한국의 증류식 소주에 전통적인 스카치 위스키의 양조 방법을 대입한 것이라 할 수 있으며, 이 미라온 베리 영은 전통적인 의미의 증류식 소주라기보다는 그레인 위스키에 가깝지 않을까 싶습니다." },
    { kind: "paragraph", text: "아드벡을 좋아하시는 분들이라면 '베리 영(Very Young)'이라는 부분에 저처럼 눈이 갈 것 같은데, 맞습니다. 이 부분은 아드벡에 대한 오마주입니다." },
    { kind: "paragraph", text: "아드벡은 1997년에 글렌모렌지에 인수된 후, 첫 번째 아드벡 10년(인트로듀싱 텐/Introducing Ten)을 출시하기 전, '베리 영'>스틸 영(Still Young)>올모스트 데어(Almost There)>르네상스(Renaissance)로 이어지는 일련의 시리즈를 출시했습니다." },
    { kind: "paragraph", text: "미라온은 아드벡처럼 이 시리즈를 완성시킬 예정이며, 베리영은 그 첫 번째 제품이라 할 수 있습니다. 여담으로 미라온의 보틀은 아드벡의 보틀과 셰입이 같은 점 또한 아드벡에 대한 오마주라 할 수 있습니다." },
    { kind: "figure", src: "/articles/miraon-very-young/01.webp", width: 966, height: 1288 },
    { kind: "quote", text: "증류소: 화심주조" },
    { kind: "quote", text: "주류 타입: 증류식 소주" },
    { kind: "quote", text: "캐스크 정보: 헤븐힐 버번 캐스크에서 1년 숙성" },
    { kind: "quote", text: "도수: 58.3%" },
    { kind: "figure", src: "/articles/miraon-very-young/02.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "향" },
    { kind: "paragraph", text: "- 쌀, 대놓고 고소한 향" },
    { kind: "paragraph", text: "- 증류식 소주에서 날만한 곡물의 향이 나기는 하지만, 그렇게 강하지는 않음" },
    { kind: "paragraph", text: "- 약간의 바닐라, 참기름, 달달한 계피" },
    { kind: "paragraph", text: "- 시간이 다소 지나고 난 후에는 초콜릿 캐릭터가 느껴짐" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 곡식, 살짝의 달달함" },
    { kind: "paragraph", text: "- 참기름" },
    { kind: "paragraph", text: "- 혀에 남는 짭짤함과 약간의 쌉쌀함" },
    { kind: "paragraph", text: "- 시간이 다소 지나고 난 후에는 향에서 나는 초콜릿 캐릭터가 살짝 느껴짐" },
    { kind: "paragraph", text: "여운" },
    { kind: "paragraph", text: "- 참기름" },
    { kind: "paragraph", text: "- 고소하고 달달함" },
    { kind: "paragraph", text: "미라온 베리 영의 가장 재미있는 점은 곡식의 고소함과 달달함에 더해 참기름 같은 캐릭터가 꽤나 직관적으로 느껴진다는 점인데, 위스키에서는 보기 어려운 독특한 캐릭터라 할 수 있겠습니다." },
    { kind: "paragraph", text: "다른 증류식 소주들보다는 좀 더 위스키스러운 느낌으로, 버번 캐스크를 꽤나 멋들어지게 사용했다는 느낌이 개인적으로 크게 와닿았습니다." },
  ],
};
