import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "mojito",
  category: "cocktail",
  title: "모히또 — 이걸 마시지 않으면 여름이 아니지!",
  dek: "\"모히또\"는 16세기에 탄생한 \"드라케(Draque)\"라는 칵테일에서 파생된 칵테일이라 합니다.",
  publishedAt: "2024-08-08",
  hero: "/articles/mojito/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223540829379",
  relatedCocktailSlugs: ["mojito"],
  blocks: [
    { kind: "figure", src: "/articles/mojito/00.webp", width: 520, height: 520 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"모히또\"는 16세기에 탄생한 \"드라케(Draque)\"라는 칵테일에서 파생된 칵테일이라 합니다. 이 드라케라는 칵테일은 럼의 전신격인 아과르디엔테(Aguardiente)와 설탕, 라임, 민트로 만들어진 것으로, 나중에 아과르디엔테를 럼으로 바꾼 것이 \"모히또\"가 되었다고 합니다." },
    { kind: "paragraph", text: "모히또 하면 \"모히또에서 몰디브 한 잔\"과 \"나의 모히또는 라 보데기타에, 나의 다이키리는 엘 플로리디타에\"라는 두 문장으로 아주 유명한 칵테일입니다." },
    { kind: "paragraph", text: "\"모히또에서 몰디브 한 잔\"은 영화 내부자들에서 이병헌 배우의 애드리브로, 국내에 모히또라는 칵테일을 일반인에게도 각인시키는 대사가 되었죠." },
    { kind: "paragraph", text: "\"나의 모히또는 라 보데기타에, 나의 다이키리는 엘 플로리디타에\"라는 대사는 소설가 어니스트 헤밍웨이가 \"라 보데기타 델 메디오(La Bodeguita del Medio)\"라는 쿠바의 바에 써놓은 메모로, 모히또와 관련된 가장 유명한 명문입니다." },
    { kind: "paragraph", text: "다만, 이 역사적인 명문은 마케팅용으로 조작된 것으로, 헤밍웨이가 쓴 것이 아니라고 보는 견해도 있습니다." },
    { kind: "paragraph", text: "애주가로서 본인의 저서에 여러번 다른 바와 칵테일을 적었던 헤밍웨이가 본인의 책에서 모히또나 라 보데기타를 기록한 적이 없으며, 무엇보다 당뇨에 시달려 시럽 대신에 마라스키노 리큐르를 넣는 \"헤밍웨이 다이키리\"라는 칵테일을 주문한 장본인이기 때문이죠." },
    { kind: "figure", src: "/articles/mojito/01.webp", width: 540, height: 540 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "45ml 화이트 럼 (White Rum)" },
    { kind: "paragraph", text: "민트 잎 12~15개 (되도록이면 스피아민트)" },
    { kind: "paragraph", text: "라임 반 개 (깍둑 썰기로 4등분 커트)" },
    { kind: "paragraph", text: "설탕 시럽 또는 사탕수수 시럽 10ml" },
    { kind: "paragraph", text: "15-30ml 탄산수" },
    { kind: "paragraph", text: "*잔얼음 / 크러시드 아이스" },
    { kind: "paragraph", text: "옵션 가니시: 민트 부케" },
    { kind: "paragraph", text: "(줄기 있는 민트를 여러 개 합한 것)" },
    { kind: "figure", src: "/articles/mojito/02.webp", width: 502, height: 502 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 긴 잔에 민트, 라임, 시럽, 럼을 넣어줍니다." },
    { kind: "paragraph", text: "2. 머들러로 머들링해줍니다(누르면서 살짝 비틀기)." },
    { kind: "paragraph", text: "3. 잔얼음을 액면보다 좀 더 위에 오게 채워줍니다." },
    { kind: "paragraph", text: "4. 바스푼을 가장 아래로 찔러 넣고," },
    { kind: "paragraph", text: "위아래로 강하게 저어줍니다." },
    { kind: "paragraph", text: "5. 얼음을 더 채우고, 탄산수를 부어주고," },
    { kind: "paragraph", text: "다시 바스푼으로 위아래로 저어줍니다." },
    { kind: "paragraph", text: "6. 얼음을 잔 끝까지 채워주고," },
    { kind: "paragraph", text: "빨대와 가니시로 장식해줍니다." },
    { kind: "figure", src: "/articles/mojito/03.webp", width: 511, height: 511 },
    { kind: "paragraph", text: "모히또는 역시 시각적으로부터 아주 시원합니다. 맛은 다 알만한 그 상큼하고 달달하고 시원한 그 맛입니다. 역시 여름에는 모히또 만한 칵테일이 없네요." },
    { kind: "paragraph", text: "모히또를 집에서 만들어 마실 때 가장 큰 애로사항은 신선한 민트와 잔얼음이 아닐까 싶습니다. 민트를 오프라인에서 사자니 마땅히 살 곳도 없고, 얼음을 깨서 잔얼음을 만들자니 귀찮죠." },
    { kind: "paragraph", text: "민트는 웬만하면 시장, 쿠팡이나 당일배송되는 곳에서 구매하시는 게 좋습니다. 대형마트에서 몇 번 사봤는데 잎이 작은데다 맛과 향이 약한 편이고, 딱히 신선하지도 않아 절반을 버린 적도 허다합니다." },
    { kind: "paragraph", text: "만약 민트의 상태가 별로여서 맛과 향이 약하다 싶으면 민트를 더 많이 넣어주셔도 됩니다." },
    { kind: "paragraph", text: "잔얼음은 쿠팡에서 같이 시키거나, 편의점 컵 얼음을 추천드립니다. 얼음의 퀄리티 자체가 중요한 칵테일은 아닌데다가 일단 편리하니까요...." },
  ],
};
