import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "mr-black",
  category: "cocktail",
  title: "깔루아의 아성을 위협하는 리큐르계의 다크호스",
  dek: "커피리큐르 시장에 새로운 바람을 일으키고 있습니다.",
  publishedAt: "2021-04-24",
  hero: "/articles/mr-black/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222321544398",
  relatedCocktailSlugs: ["espresso"],
  blocks: [
    { kind: "paragraph", text: "흔히 우리나라에서 커피리큐르라고 하면" },
    { kind: "paragraph", text: "깔루아를 생각하죠." },
    { kind: "paragraph", text: "오히려 커피리큐르를 깔루아라고 부를 정도로" },
    { kind: "paragraph", text: "그 아성이 대단합니다." },
    { kind: "paragraph", text: "그런데 최근 몇 년간 해외에서" },
    { kind: "paragraph", text: "한 리큐르가 다양한 대회에서 수상을 하면서" },
    { kind: "paragraph", text: "커피리큐르 시장에 새로운 바람을 일으키고 있습니다." },
    { kind: "paragraph", text: "바로 미스터블랙(MR.BLACK)이죠!!" },
    { kind: "figure", src: "/articles/mr-black/00.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "The World's Best Coffe Liquor" },
    { kind: "paragraph", text: "미스터블랙 디스틸러리는" },
    { kind: "paragraph", text: "2013년 호주에서 설립되었습니다." },
    { kind: "paragraph", text: "설립된 지 몇 년 되지 않은 디스틸러리의 리큐르이지만" },
    { kind: "paragraph", text: "그 맛만으로도 전 세계의 바텐더들과 커피 애호가들의" },
    { kind: "paragraph", text: "관심을 끌기에 충분했습니다." },
    { kind: "paragraph", text: "The world's best라고 쓰인 부분에서" },
    { kind: "paragraph", text: "자기 제품에 대한 프라이드를 느낄 수 있죠." },
    { kind: "paragraph", text: "미스터블랙은 호주 시드니의 북부에 있는" },
    { kind: "paragraph", text: "미스터블랙 디스틸러리 및 로스터리에서" },
    { kind: "paragraph", text: "호주에서 만들어진 보드카와 아라비카 원두를 사용하여" },
    { kind: "paragraph", text: "만들어진다고 합니다." },
    { kind: "paragraph", text: "그러니까 커피, 보드카 그리고 약간의 설탕만이 들어가고 이외의 인공적인 재료는 들어가지 않는 것이죠." },
    { kind: "paragraph", text: "미스터블랙을 특별하게 만들어주는 건" },
    { kind: "paragraph", text: "리큐르에 함량 된 설탕과 커피의 양입니다." },
    { kind: "paragraph", text: "다른 커피리큐르들에 비해 설탕을 반으로 줄이고" },
    { kind: "paragraph", text: "커피 함량을 10배로 늘려" },
    { kind: "paragraph", text: "단 맛을 줄이고 커피 자체의 향을" },
    { kind: "paragraph", text: "더욱 잘 느끼게 할 수 있도록 해줍니다." },
    { kind: "paragraph", text: "커피 함량을 늘린 만큼 1온스(약 30ml)를 기준으로 25~40%의 카페인이 들어있는데," },
    { kind: "paragraph", text: "보통 에스프레소 1 shot에 들어있는 카페인의 양과 동일하다고 합니다." },
    { kind: "figure", src: "/articles/mr-black/01.webp", width: 828, height: 1472 },
    { kind: "paragraph", text: "우리나라에는 수입되지 않다가" },
    { kind: "paragraph", text: "2021년 4월 24일부터 유픽에서 수입해" },
    { kind: "paragraph", text: "이마트 트레이더스에서 판매하고 있습니다." },
    { kind: "paragraph", text: "가격은 솔직히 더 비싸게 들어올 거라" },
    { kind: "paragraph", text: "생각한 것에 비해 합리적입니다." },
    { kind: "paragraph", text: "깔루아보다는 비싸지만 그 값을 하는 리큐르라고 생각해요." },
    { kind: "paragraph", text: "또 병도 정말 감각적이게 만들었습니다." },
    { kind: "paragraph", text: "저는 오늘 나오자마자 한 병 집어왔습니다!!" },
    { kind: "figure", src: "/articles/mr-black/02.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "확실히 깔루아보다 단 맛이 적고" },
    { kind: "paragraph", text: "커피의 맛과 향이 더 잘 느껴집니다." },
    { kind: "paragraph", text: "깔루아에 항상 아쉬웠던 게" },
    { kind: "paragraph", text: "너무 달고 인공적인 맛과 향이었는데" },
    { kind: "paragraph", text: "미스터블랙은 전혀 인공적이지 않네요." },
    { kind: "paragraph", text: "오히려 부드럽고 끝 맛까지 좋습니다." },
    { kind: "paragraph", text: "그냥 마셔도 전혀 위화감이 들지 않아요." },
    { kind: "paragraph", text: "마시고 난 이후에도" },
    { kind: "paragraph", text: "입안에서 커피의 향이 기분 좋게 남아있습니다." },
    { kind: "paragraph", text: "미스터블랙이 어떻게 짧은 시간 안에 명성을 쌓았는지" },
    { kind: "paragraph", text: "알 수 있는 맛입니다." },
    { kind: "paragraph", text: "인공적인 단 맛과 향이 싫으시다면" },
    { kind: "paragraph", text: "미스터블랙을 강추 드립니다!!" },
    { kind: "paragraph", text: "+주의점" },
    { kind: "figure", src: "/articles/mr-black/03.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "이렇게 침전물이 생기기도 하는데" },
    { kind: "paragraph", text: "인공적인 재료를 사용하지 않기 때문에" },
    { kind: "paragraph", text: "생기는 침전물이라고 합니다." },
    { kind: "paragraph", text: "그러니까 처음 봤을 때 너무 당황하지 말고" },
    { kind: "paragraph", text: "마시기 전에 흔들어주시면 됩니다!" },
    { kind: "paragraph", text: "다음에는 미스터블랙으로 만든" },
    { kind: "paragraph", text: "칵테일을 올려보도록 할게요!" },
    { kind: "paragraph", text: "모두 맛술하세요~" },
    { kind: "paragraph", text: "#커피 #리큐르 #커피리큐르 #리큐어 #칵테일 #미스터블랙 #깔루아" },
    { kind: "paragraph", text: "인스타그램" },
  ],
};
