import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "nagoya-bar-curacao",
  category: "bar",
  title: "바 큐라소 — 사이드카 한 잔, 잔의 차이가 만든 맛",
  dek: "「바 큐라소」는 나고야의 사카에 지역의 한 빌딩에 위치해 있는 바로, 오렌지 리큐르의 일종인 큐라소를 이름으로 하고 있는 곳입니다. 아마도 사장님이 큐라소류 칵테일을 좋아하시는 듯.",
  publishedAt: "2025-09-21",
  hero: "/articles/nagoya-bar-curacao/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224016293039",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/nagoya-bar-curacao/00.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "「바 큐라소」는 나고야의 사카에 지역의 한 빌딩에 위치해 있는 바로, 오렌지 리큐르의 일종인 큐라소를 이름으로 하고 있는 곳입니다. 아마도 사장님이 큐라소류 칵테일을 좋아하시는 듯." },
    { kind: "paragraph", text: "첫 잔으로는 역시 하이볼을 추천을 부탁드렸고, 스카이 섬(Isle of Skye)의 신생 증류소라고 하는 토라벡(토라베이그/Torabhaig)을 추천 받았습니다." },
    { kind: "paragraph", text: "스카이 섬 + 신생이라는 조합에 호기심을 못이겨 주문을 했는데, 하이볼로 마시기 딱 좋은 정도의 피트감, 약간의 짭짤한 해초, 고소함이 느껴져 맛있게 마셨습니다." },
    { kind: "paragraph", text: "조금 찾아보니 토라벡은 탈리스커에 이어 스카이 섬에서 두 번째로 허가받은 증류소이며, 2017년에 지어져 2021년에 첫 위스키 제품을 출시했다고 합니다. 제가 마신 건 두 번째로 출시된 제품이자 Allt Gleann이라는 이름의 싱글몰트라 합니다." },
    { kind: "paragraph", text: "여기도 이전에 갔던 바 반즈처럼 사진을 찍을 때 조명을 비춰주시는 게 포인트" },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "다음 잔으로는 역시 바의 이름에 따라서 큐라소가 들어간 칵테일을 요청드렸는데, 사이드카(Sidecar)를 내어주셨습니다." },
    { kind: "paragraph", text: "셰이킹이 그렇게 강하지 않았는데도 공기가 생각보다 많이 주입된 게 신기했는데, 제가 마셔본 사이드카 중에서 세 손가락에 꼽을 정도로 맛있었습니다. 밸런스가 정말 좋아서 극한의 밸런스충인 저에게 딱 맞는 한 잔." },
    { kind: "paragraph", text: "사이드카와 관련해서 이런 저런 얘기를 나눴는데, 그 중에 가장 신기했던 건 잔에 따라서도 칵테일의 맛이 달라진다는 사장님의 얘기였습니다." },
    { kind: "paragraph", text: "제가 엥?스러운 반응을 하자 다른 칵테일 잔을 주시길래 거기에 따라 마셔봤더니 정말 맛이 달랐다는 게 충격적이었습니다. 그래서 본인은 칵테일을 여러 잔에 따라서 바셔보고 잔을 결정한다고." },
    { kind: "paragraph", text: "개인적으로 느낀 전 'V'자처럼 샤프한 잔은 레몬의 신맛이 두드러졌고, 'U'자처럼 둥근 잔은 좀 더 꼬냑스러운 느낌이 중심을 잘 잡는 느낌이었습니다. 얇은 림은 필수." },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/05.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/nagoya-bar-curacao/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "바 큐라소는 칵테일이 정말 맛있었지만, 위스키나 다른 스피릿 라인업도 꽤 많이 갖춰져 있습니다. 이 중에서 같은 나고야에 있는 바인 '루빈스 베이스(Rubin's-Vase)' 픽 위스키 중에 시크릿 오크니가 있어서 한 잔 마셔봤는데, 이거 꽤 괜찮았습니다." },
    { kind: "paragraph", text: "그 외에 한국에서 보기 정말 어렵지만, 아주 애정하는 마르(Marc) 중에 부르고뉴 지방의 마르가 있어서 이것도 한 잔 마셔주고, 아쉬워서 머레이 맥다비드의 쿨일라도 한 잔 마셨는데, 쿨일라는 굳이 싶었습니다." },
    { kind: "paragraph", text: "얘길 들어보니 사장님이 이전에 요이치 증류소에서 견습(?)을 했었는데, 그 인연으로 조만간 요이치 증류소에서 바틀을 보내준다고 하셨으니, 나고야에 방문하시는 분들 중 일본 위스키 관심 있는 분들은 방문을 추천드립니다." },
    { kind: "paragraph", text: "바 큐라소는 개인적으로 칵테일을 좋아하시는 분들에게 더 추천드리고 싶기는 하지만, 그렇다고 위스키 라인업이 부실한 건 절대 아닙니다. 편하게 방문해서 즐겨주시길." },
  ],
};
