import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "naked-and-famous",
  category: "cocktail",
  title: "네이키드 앤 페이머스",
  dek: "네이키드&페이머스(Naked&Famous)는 2011년 현대의 모던 클래식 칵테일에 많은 영향을 준 바인 뉴욕의 데스앤코(Death&Co)에서 호아킨 시모(Joaquin Simo)에 의해서 만들어졌습니다.",
  publishedAt: "2024-05-27",
  hero: "/articles/naked-and-famous/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223459736206",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/naked-and-famous/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "About the Drink" },
    { kind: "paragraph", text: "네이키드&페이머스(Naked&Famous)는 2011년 현대의 모던 클래식 칵테일에 많은 영향을 준 바인 뉴욕의 데스앤코(Death&Co)에서 호아킨 시모(Joaquin Simo)에 의해서 만들어졌습니다." },
    { kind: "paragraph", text: "컬트적인 인기를 끌고 있는 ‘라스트 워드(Last Word)’라는 칵테일을 좋아하는 분들이라면 이 칵테일의 레시피에 아주 익숙할 텐데, 샤르트뢰즈(옐로지만)를 포함한 4가지 재료가 동일하게 22.5ml씩 들어가기 때문일 겁니다." },
    { kind: "paragraph", text: "실제로 호아킨 시모는 ‘라스트 워드(Last Word)’와 ‘페이퍼 플레인(Paper Plane)’이라는 칵테일을 매시업해서 이 칵테일을 만들어 냈습니다(본인이 두 칵테일의 사생아 격이다라고 말했으니)." },
    { kind: "paragraph", text: "이 칵테일에서는 라스트 워드의 ‘그린 샤르트뢰즈’ 대신 좀 더 달고 도수가 낮은 ‘옐로우 샤르트뢰즈’를 사용하고, ‘아페롤’을 통해 시트러스와 달큰쌉쌀한 캐릭터를 더해줍니다." },
    { kind: "paragraph", text: "여기에 ‘메즈칼’이라는 ‘데낄라’의 친척격인 아가베 증류주가 들어가는데, ‘진’이나 ‘버번’보다는 단순하지만 아가베 특유의 달콤함에 더해 메즈칼 특유의 어씨(earthy)함과 스모키함으로 칵테일에 재미를 더해줍니다." },
    { kind: "paragraph", text: "최근 몇 년간 서양의 바 신을 중심으로 메즈칼 칵테일이 범람하였는데, 그 와중에도 유달리 유명세를 탄 칵테일 중 하나이며, 모던 클래식 칵테일에서 당당하게 한자리를 차지하고 있습니다." },
    { kind: "figure", src: "/articles/naked-and-famous/01.webp", width: 966, height: 725 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "22.5ml 메즈칼 (Mezcal)" },
    { kind: "paragraph", text: "22.5ml 옐로우 샤르트뢰즈 (Yellow Chartreuse)" },
    { kind: "paragraph", text: "22.5ml 아페롤 (Aperol)" },
    { kind: "paragraph", text: "22.5ml 라임 즙 (Lime Juice)" },
    { kind: "figure", src: "/articles/naked-and-famous/02.webp", width: 966, height: 1287 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커 안에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 넣고 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후 잔에 따라줍니다." },
    { kind: "paragraph", text: "네이키드&페이머스의 가장 큰 매력은 역시 그 재료의 조합이라 할 수 있습니다. 레시피의 구조 자체는 단순하나, 메즈칼이라는 아직 우리나라에서 익숙하지 않은 재료를 통해 예상치 못한 재미를 줍니다." },
    { kind: "paragraph", text: "시트러스+달달함+스모키함+허브의 모든 재료가 자기주장이 강하지만 캐릭터 중 어느 하나가 부담스럽게 튀지 않고 복합적으로 나는데, 꽤 복잡하고 오묘한 맛입니다." },
    { kind: "paragraph", text: "메즈칼은 아가베(Agave)를 주원료로 하는 증류주로, 데깔라와 일종의 친척 관계에 있다고 할 수 있습니다. 다만, 주원료인 아가베의 종류·지역·생산방법 등에서 많은 차이가 나며, 그로 인해 메즈칼은 어씨(earthy)함과 스모키함이라는 유니크한 캐릭터를 가지게 됩니다." },
    { kind: "paragraph", text: "메즈칼은 아직까지 우리나라에서 익숙하지 않은 증류주이지만, 서양권에서 발표하는 주류 트렌드에서 몇 년간 메즈칼(또는 데낄라를 포함하는 아가베 증류주)이 많은 인기를 끌고 유행할 것이라고 전망해왔습니다." },
    { kind: "paragraph", text: "실제로 최근 십여 년 사이에 서양에서 많은 인기를 얻으면서 많은 메즈칼 칵테일이 만들어졌으며, 다양한 메즈칼 제품이 만들어졌습니다." },
    { kind: "paragraph", text: "최근 2~3년 사이에 국내에서 좋은 퀄리티의 메즈칼이 많이 수입되었고, 바에서도 종종 찾을 수 있게 되었으니, 바에서 메즈칼이 보인다면 주저하지 마시고 메즈칼을 이용한 칵테일에 도전해 보시는 걸 추천드립니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
