import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "negroni",
  category: "cocktail",
  title: "네그로니 — 복잡하고 달콤쌉싸름한 매력",
  dek: "1919년 피렌체에서 백작의 아메리카노를 진으로 바꿔 태어난 1:1:1의 클래식. 오렌지 껍질과 레몬 껍질 사이에서 표정이 바뀐다.",
  publishedAt: "2025-01-30",
  hero: "/articles/negroni/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223742393163",
  relatedCocktailSlugs: ["negroni"],
  blocks: [
    { kind: "figure", src: "/articles/negroni/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "네그로니는 밀라노에서 탄생한 술인 ‘캄파리’와는 떼려야 뗄 수 없는 관계에 있으며, ‘밀라토-토리노 > 아메리카노 > 네그로니’와 같은 순서로 변형되어서 탄생되었다는 것이 가장 잘 알려져 있습니다." },
    { kind: "paragraph", text: "1919년, 이탈리아 피렌체의 한 바에서 단골손님이었던 ‘네그로니 백작’이 자신의 아메리카노 칵테일(캄파리, 스윗 버무스, 탄산수)를 더 강하게 만들어 달라 요청하였고, 바텐더였던 포스코 스카셀리(Fosco Scarselli)는 탄산수를 진으로 변경하였습니다." },
    { kind: "paragraph", text: "백작은 이를 매우 마음에 들어 했는데, 다른 손님들이 이후에 ‘네그로니 백작이 마신 술’을 주문하기 시작했고, 칵테일의 이름이 ‘네그로니’로 알려지게 되었습니다." },
    { kind: "paragraph", text: "기본적으로 네그로니는 모든 재료를 1:1:1로 만드는 아주 간단한 구조로 이루어져 있으며, 이 때문인지 ‘불바디에(Boulevardier), 올드팔(Old Pal), 화이트 네그로니(White Negroni)’ 등의 변형이 상당히 많은 칵테일이고, 이러한 변형들을 통틀어서 네그로니 트리(Negroni Tree)라고 부르기도 합니다." },
    { kind: "figure", src: "/articles/negroni/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 진(Gin)" },
    { kind: "paragraph", text: "30ml 캄파리(Campari)" },
    { kind: "paragraph", text: "30ml 스윗 버무스(Sweet Vermouth)" },
    { kind: "paragraph", text: "가니시: 오렌지(또는 레몬) 껍질" },
    { kind: "figure", src: "/articles/negroni/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 모든 재료를 락 잔에 넣어줍니다." },
    { kind: "paragraph", text: "2. 얼음을 채우고, 스터를 해줍니다." },
    { kind: "paragraph", text: "3. 잔 위로 오렌지 껍질을 짜서 오일을 뿌려줍니다." },
    { kind: "paragraph", text: "4. 사용한 껍질을 다듬어서 잔에 넣어줍니다." },
    { kind: "paragraph", text: "네그로니의 전통적인 비율은 1:1:1이지만, 최근에는 진을 늘리고 캄파리의 비율을 줄이는 등의 비율을 선호하는 바텐더들이 상당히 늘었습니다. 각자의 입맛에만 맞으면 되니, 맛을 봐가면서 각자의 비율을 찾아가는 재미도 있겠습니다." },
    { kind: "figure", src: "/articles/negroni/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "잔을 입으로 가져다 대면 먼저 달큼한 오렌지의 향이 코에 닿고, 한 모금 마시게 되면 중심을 잡아주는 진과 함께 보타니컬함, 달큼한 오렌지와 와인 계열의 맛, 기분 좋을 정도의 캄파리의 쌉쌀함이 아주 복잡한 맛을 내게 됩니다." },
    { kind: "paragraph", text: "가니시로 칵테일에 오일을 뿌려주는 시트러스로는 일반적으로 오렌지 껍질이 사용되지만, 레몬 껍질을 사용하기도 합니다." },
    { kind: "paragraph", text: "이건 취향의 문제인데, 오렌지 껍질을 사용하면 캄파리에 있는 오렌지 캐릭터를 끌어올리면서도 묵직한 네그로니를 만들 수 있고, 레몬 껍질을 사용하면 화사한 캐릭터의 네그로니가 만들어집니다." },
    { kind: "paragraph", text: "이런 특성에 따라서 취향껏 만들어 마실 수 있는데, 개인적으로는 더운 여름같이 묵직한 느낌은 부담스러우니 레몬 껍질을 이용한 네그로니를 선호하는 편입니다." },
  ],
};
