import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "oaxaca-old-fashioned",
  category: "cocktail",
  title: "와하카 올드패션드 — 클래식과 새로움의 만남",
  dek: "\"와하카 올드 패션드\"는 2007년 필 워드(Phil Ward)가 뉴욕의 바 데스앤코(Death&Co)에서 만들어낸 칵테일로, 특이하게도 아가베 증류주를 기주로 사용한 올드 패션드의 변형입니다.",
  publishedAt: "2024-09-19",
  hero: "/articles/oaxaca-old-fashioned/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223588722581",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/oaxaca-old-fashioned/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"와하카 올드 패션드\"는 2007년 필 워드(Phil Ward)가 뉴욕의 바 데스앤코(Death&Co)에서 만들어낸 칵테일로, 특이하게도 아가베 증류주를 기주로 사용한 올드 패션드의 변형입니다." },
    { kind: "paragraph", text: "'와하카'는 메즈칼의 최대 생산지 중 하나로, 메즈칼을 강조하기 위해서 붙은 이름이라 할 수 있습니다." },
    { kind: "paragraph", text: "와하카 올드 패션드는 모던 클래식 칵테일을 뽑을 때 반드시 손에 꼽히는 칵테일로, 최근의 아가베 증류주 붐이라는 트렌드를 이끌어내는데 큰 역할을 했다 할 수 있습니다." },
    { kind: "paragraph", text: "칵테일이 만들어질 당시는 한창 크래프트 칵테일 운동으로 인해 클래식 칵테일이나 새로운 재료에 대한 관심이 컸던 데다가, 메즈칼이 미국에 소개되기 시작했었고, 클래식 칵테일에 대한 소비자들의 관심 또한 커져갔습니다." },
    { kind: "paragraph", text: "그러니 이 칵테일은 당시 시대적 상황에 따라서 필연적으로 만들어질 수밖에 없었던 칵테일이라 할 수 있습니다." },
    { kind: "figure", src: "/articles/oaxaca-old-fashioned/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "45ml 레포사도 테킬라 (Reposado Tequila)" },
    { kind: "paragraph", text: "15ml 메즈칼 (Mezcal)" },
    { kind: "paragraph", text: "7.5ml 아가베 넥타 (Agave Nectar)" },
    { kind: "paragraph", text: "앙고스투라 비터 2대시" },
    { kind: "paragraph", text: "(Angostura Aromatic Bitters 2dashes)" },
    { kind: "paragraph", text: "가니시: 불에 그을린 오렌지 껍질" },
    { kind: "figure", src: "/articles/oaxaca-old-fashioned/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 가니시 이외의 모든 재료를 온더락 잔에 넣어줍니다." },
    { kind: "paragraph", text: "2. 잔에 얼음을 채워주고 스터 해줍니다." },
    { kind: "paragraph", text: "3. 성냥 등으로 오렌지 껍질 바깥 부분을 살짝 데운 후," },
    { kind: "paragraph", text: "칵테일을 향해 성냥 불을 두고 오렌지 껍질을 짜서 오일을 뿌려줍니다." },
    { kind: "figure", src: "/articles/oaxaca-old-fashioned/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "이 칵테일은 기주로 데킬라 45ml에 메즈칼 15ml를 사용하는데, 그럼에도 불구하고 메즈칼 특유의 스모키한 캐릭터가 꽤나 치고 나오는 독특한 캐릭터를 보여줍니다." },
    { kind: "paragraph", text: "이렇게 메즈칼을 단독 기주로 사용하는 것이 아니라 데킬라를 블렌딩한 것이 정말 좋은 선택이라 생각하는 것이 메즈칼에 익숙하지 않은 사람들이 좀 더 메즈칼에 편하게 접할 수 있기 때문입니다." },
    { kind: "paragraph", text: "메즈칼은 사실 특유의 스모키한 캐릭터가 꽤나 강해 처음 접하게 된다면 다소 버거울 수 있지만, 이 칵테일이라면 메즈칼의 캐릭터를 기분 좋게 경험해 볼 수 있겠습니다." },
    { kind: "paragraph", text: "칵테일은 전체적으로 캔디드 오렌지, 달달한 아가베, 약간의 스모키함에 더해 살짝의 향신료와 초콜릿(또는 카카오)의 캐릭터가 함께 느껴집니다." },
    { kind: "paragraph", text: "바를 방문했을 때 메즈칼이 보이신다면 주저 않고 주문해 보시는 걸 추천드립니다." },
  ],
};
