import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "octomore-14-1",
  category: "spirits",
  title: "옥토모어 14.1",
  dek: "옥토모어는 브룩라디(Bruichladdich)와 포트샬롯(Port Charlotte)과 함께 \"브룩라디 증류소\"의 코어 라인 중 하나로, 일반적으로 매년 xx.1 / xx.2 / xx.3 (+xx.4/없는 해도 있음)의 번호를 달고 출시되는 매번이 일",
  publishedAt: "2024-07-22",
  hero: "/articles/octomore-14-1/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223521509457",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/octomore-14-1/00.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/octomore-14-1/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "옥토모어는 브룩라디(Bruichladdich)와 포트샬롯(Port Charlotte)과 함께 \"브룩라디 증류소\"의 코어 라인 중 하나로, 일반적으로 매년 xx.1 / xx.2 / xx.3 (+xx.4/없는 해도 있음)의 번호를 달고 출시되는 매번이 일종의 한정판인 특이한 위스키입니다." },
    { kind: "paragraph", text: "옥토모어는 수퍼 헤빌리 피티드(Super Heavily Peated)가 가장 큰 특징인 위스키로, 페놀 수치가 보통 100ppm을 넘기는 게 일반적이며, 페놀 수치가 높은 편에 속하는 아드벡이 일반적으로 50~60ppm인 것에 비해서도 엄청나게 높은 걸 알 수 있죠." },
    { kind: "paragraph", text: "옥토모어 14.1은 2023년 출시한 에디션으로, xx.1은 스코틀랜드산 보리를 100% 사용하고, 엑스-아메리칸 오크(ex-American oak/버번 또는 테네시 위스키 캐스크)를 사용해서 숙성한다는 특징을 가지고 있습니다. 증류소에서는 이 xx.1을 각 시리즈의 중추라고 소개하고 있습니다." },
    { kind: "figure", src: "/articles/octomore-14-1/02.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/octomore-14-1/03.webp", width: 966, height: 543, caption: "브룩라디 증류소의 옥토모어 컬렉션" },
    { kind: "quote", text: "증류소: 브룩라디 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트" },
    { kind: "quote", text: "캐스크 정보: 퍼스트 필 버번 캐스크(First Fill Bourbon) 5년 숙성" },
    { kind: "quote", text: "보리 정보: 100% 스코틀랜드산 콘체르토(Concerto) / 2016년 수확" },
    { kind: "quote", text: "페놀 수치: 128.9ppm" },
    { kind: "quote", text: "도수: 59.6%" },
    { kind: "figure", src: "/articles/octomore-14-1/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 생각보다 강하지 않은 피트감, 숯불향, 약간의 베이컨스러운 향" },
    { kind: "paragraph", text: "- 달달하고 고소한 곡식향" },
    { kind: "paragraph", text: "- 허니콤과 약간의 달달한 과육의 과실" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 바나나 브륄레, 살짝 탄 것 같은 카라멜, 흑설탕" },
    { kind: "paragraph", text: "- 청사과" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "- 달달한 훈연향과 카라멜," },
    { kind: "paragraph", text: "- 스쳐가는 레몬타르트 같은 시트러스" },
    { kind: "paragraph", text: "- 끝으로 갈수록 강해지는 훈연향" },
    { kind: "paragraph", text: "옥토모어 14.1은 전체적으로 '달다'는 느낌이 강하게 들며, 이 단맛이 처음에는 피트의 향에 묻혀있다가 점점 모습을 드러내는 것 같습니다." },
    { kind: "paragraph", text: "오픈 직후에는 피트가 강하지만, 좀 지나면 피트감이 생각보다는 강하게 느껴지지 않고, 버번 캐스크와 피트의 조합이 빛나는 한 잔입니다." },
  ],
};
