import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "octomore-15-series",
  category: "spirits",
  title: "브룩라디 증류소, 옥토모어 15 시리즈 공개 — 시리즈 사상 두 번째로 높은 ppm을 기록",
  dek: "옥토모어(Octomore)는 브룩라디(Bruichladdich)와 포트샬롯(Port Charlotte)과 함께 \"브룩라디 증류소\"의 코어 라인 중 하나로, 일반적으로 매년 xx.1 / xx.2 / xx.3 (+xx.4/없는 해도 있음)의 번호를 달고",
  publishedAt: "2024-09-11",
  hero: "/articles/octomore-15-series/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223580412866",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/octomore-15-series/00.webp", width: 966, height: 966, caption: "사진 출처: 브룩라디 홈페이지" },
    { kind: "paragraph", text: "옥토모어(Octomore)는 브룩라디(Bruichladdich)와 포트샬롯(Port Charlotte)과 함께 \"브룩라디 증류소\"의 코어 라인 중 하나로, 일반적으로 매년 xx.1 / xx.2 / xx.3 (+xx.4/없는 해도 있음)의 번호를 달고 출시되는 매번이 일종의 한정판인 특이한 위스키입니다." },
    { kind: "paragraph", text: "옥토모어는 수퍼 헤빌리 피티드(Super Heavily Peated)가 가장 큰 특징인 위스키로, 페놀 수치가 보통 100ppm을 넘기는 게 일반적이며, 페놀 수치가 높은 편에 속하는 아드벡이 일반적으로 50~60ppm인 것에 비해서도 엄청나게 높은 걸 알 수 있죠." },
    { kind: "paragraph", text: "브룩라디 증류소에서는 올해 릴리스 되는 옥토모어 15 시리즈에 대한 정보를 공개했습니다." },
    { kind: "paragraph", text: "옥토모어 15 시리즈에 대한 정보를 정리해 보자면 다음과 같습니다." },
    { kind: "paragraph", text: "옥토모어 15.1" },
    { kind: "paragraph", text: "- 보리 정보: 100% Scottish Mainland Concerto barley" },
    { kind: "paragraph", text: "- 캐스크 정보: 퍼스트필 버번 배럴과 리차링한 엑스 버번 캐스크, 5년 숙성" },
    { kind: "paragraph", text: "(First-fill bourbon barrels with re-charred ex-bourbon casks)" },
    { kind: "paragraph", text: "- 증류: 2017년 보리 수확 후 2018년 증류" },
    { kind: "paragraph", text: "- 페놀 수치: 108.2 ppm" },
    { kind: "paragraph", text: "- 도수: 59.1%" },
    { kind: "paragraph", text: "- 출시 가격: 140 파운드" },
    { kind: "paragraph", text: "옥토모어 15.2" },
    { kind: "paragraph", text: "- 보리 정보: 100% Scottish Mainland Concerto barley" },
    { kind: "paragraph", text: "- 캐스크 정보: 세컨필 와인 캐스크와 세컨필 버번 캐스크에서 숙성한 원액을 섞고, 2023년 퍼스트필 꼬냑 캐스크에 담아 피니시함, 5년 숙성" },
    { kind: "paragraph", text: "(Originally filled into a combination of second fill wine casks and second fill bourbon casks. In 2023 the spirit was recasked into first fill Cognac casks for the remainder of its maturation.)" },
    { kind: "paragraph", text: "- 증류: 2017년 보리 수확 후 2018년 증류" },
    { kind: "paragraph", text: "- 페놀 수치: 108.2 ppm" },
    { kind: "paragraph", text: "- 도수: 57.9%" },
    { kind: "paragraph", text: "- 출시 가격: 155 파운드" },
    { kind: "paragraph", text: "옥토모어 15.3" },
    { kind: "paragraph", text: "- 보리 정보: 100% Islay grown Concerto barley from Octomore Farm" },
    { kind: "paragraph", text: "- 캐스크 정보: 퍼스트필 버번 캐스크와 스페인 헤레스 지방의 페르난도 데 카스티야의 퍼스트필 올로로소 혹스헤드에서 풀 숙성, 5년 숙성" },
    { kind: "paragraph", text: "(Full term maturation in first fill bourbon casks and first fill Oloroso hogsheads from Fernando de Castilla, Jerez, Spain.)" },
    { kind: "paragraph", text: "- 증류: 2017년 보리 수확 후 2018년 증류" },
    { kind: "paragraph", text: "- 페놀 수치: 307.2 ppm" },
    { kind: "paragraph", text: "- 도수: 61.3%" },
    { kind: "paragraph", text: "- 출시 가격: 195 파운드" },
    { kind: "paragraph", text: "옥토모어 15 시리즈에서 가장 주목할 만한 점은 옥토모어 시리즈 사상 두 번째로 높은 ppm의 옥토모어가 출시된다는 점입니다." },
    { kind: "paragraph", text: "시리즈 사상 가장 높은 ppm의 옥토모어는 08.3으로 ppm이 309.1이었으며, 이번 시리즈의 15.3은 그 뒤를 잇는 307.2 ppm이라는 높은 수치를 기록하게 되었습니다." },
    { kind: "paragraph", text: "물론 ppm이 높다고 숙성 후의 위스키가 피트감이 무조건 강하다 할 수는 없지만, 15.3은 5년 밖에 숙성하지 않았고, 이전에 마셔본 08.3의 피트감이 상당히 강했기 때문에 피트 러버로서는 기대가 될 수밖에 없네요." },
    { kind: "paragraph", text: "개인적으로 나중에 일본에 출시될 때 한 병 정도 집어와서 리뷰해보고 싶습니다." },
  ],
};
