import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "old-pal",
  category: "cocktail",
  title: "올드 팔 — 네그로니의 화사한 변형",
  dek: "'올드 팔'은 수 많은 네그로니(Negroni)의 변형 중 하나로, 파리의 해리스 뉴욕 바(Harry's New York Bar)에서 해리 맥켈혼(Harry MacElhone)의 저서 'Barflies and Cocktails'에서 처음 등장합니다.",
  publishedAt: "2024-11-09",
  hero: "/articles/old-pal/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223653506998",
  relatedCocktailSlugs: ["oldpal"],
  blocks: [
    { kind: "figure", src: "/articles/old-pal/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "'올드 팔'은 수 많은 네그로니(Negroni)의 변형 중 하나로, 파리의 해리스 뉴욕 바(Harry's New York Bar)에서 해리 맥켈혼(Harry MacElhone)의 저서 'Barflies and Cocktails'에서 처음 등장합니다." },
    { kind: "paragraph", text: "이 저서의 마지막 부분에는 '아서 모스(Arthur Moss)'가 쓴 에세이 'Cocktails Round Town'가 있는데, 여기서 이 칵테일의 기원에 대해서 얘기하며, 이후 개정판에서는 누구의 레시피인지 자세하게 나오게 됩니다." },
    { kind: "paragraph", text: "이에 따르면 칵테일을 만든 것은 '윌리엄 로빈슨(William Sparrow Robinson)'이며, 오랜 친구인 '저자(Writer)'를 위해 칵테일의 이름을 '오랜 친구'라는 의미의 '올드팔(정확히는 My Old Pal)'이라 명명했다고 합니다." },
    { kind: "paragraph", text: "여기서 다소 혼동이 발생하는데, '저자(Writer)'가 해리 맥켈혼을 의미하는지, 아서 모스를 의미하는지에 대해서 논란의 여지가 있기 때문입니다." },
    { kind: "paragraph", text: "다만, 이 내용이 'Barflies and Cocktails'의 메인 칵테일 리스트가 아니라, 아서 모스가 쓴 에세이 부분에 나온다는 점에서 이 '올드 팔'이 아서 모스를 지칭한다고 보는 시각이 최근에는 설득력을 얻고 있는 것 같습니다." },
    { kind: "paragraph", text: "레시피도 문제인게, 에세이에서는 캐나디안 클럽/이탈리안 버무스(Eyetalian Vermouth)/캄파리를 동률로 하는 레시피를 얘기하는데, 이 이탈리안 버무스가 단순히 이탈리아에서 만들어지는 버무스를 얘기하는 건지, 스윗 버무스를 얘기하는 건지는 알 수 없습니다." },
    { kind: "paragraph", text: "전자도 후자도 문제가 되는 게, 전자는 스위트/드라이/비앙코 중 어떤 버무스인지 알 수도 없고, 후자는 올드 팔이 본래는 드라이 버무스로 만들어지는 게 아니라는 점입니다. 다만, 당시에는 이탈리안 버무스가 일반적으로 스윗 버무스를 의미하긴 합니다." },
    { kind: "paragraph", text: "그러니 '올드 팔'은 시간이 지나면서 원래의 레시피에서 꽤나 많은 변화를 겪은 칵테일이라 할 수 있겠습니다." },
    { kind: "figure", src: "/articles/old-pal/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "Ingredietns" },
    { kind: "paragraph", text: "20ml 라이 위스키 (Rye Whiskey)" },
    { kind: "paragraph", text: "20ml 캄파리 (Campari)" },
    { kind: "paragraph", text: "20ml 드라이 버무스 (Dry Vermouth)" },
    { kind: "paragraph", text: "가니시: 레몬 껍질 (Lemon Peel)" },
    { kind: "paragraph", text: "*저는 용량이 작은 잔을 써서 20ml를 기준으로 동량을 사용했으니, 잔의 용량에 따라 양을 조절해주시면 됩니다." },
    { kind: "paragraph", text: "**동률의 레시피가 기본이긴 하지만, 2:1:1의 레시피도 있습니다." },
    { kind: "figure", src: "/articles/old-pal/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 믹싱 글라스에 모든 재료를 넣어줍니다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채워주고, 스터해줍니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 레몬 껍질을 짜서 오일을 뿌려줍니다." },
    { kind: "paragraph", text: "가니시는 오렌지 껍질과 레몬 껍질 중에 아무거나 사용하셔도 되지만, 저 같은 경우는 올드 팔의 화사함을 표현하기 위해서는 레몬 껍질이 더 잘 어울릴 것 같아서 레몬 껍질을 사용했습니다. 의외로 라이 위스키와 레몬 껍질의 궁합이 좋기도 하구요." },
    { kind: "paragraph", text: "올드팔은 그 원형인 네그로니 특유의 묵직한 단맛 대신에 좀 더 가볍고 화사한 느낌이 있는 칵테일입니다. 그래서 조금은 허브감이 더 잘 느껴지는 것 같은 기분도 드네요." },
    { kind: "paragraph", text: "전체적으로 쌉쌀함, 달달함, 허브감이 화사하게 느껴지는 칵테일이며, 여기에 약간의 바닐라 캐릭터가 느껴지기도 합니다. 물론, 바닐라 캐릭터의 경우는 사용하는 라이 위스키에 따라서 다르게 느껴질 수도 있습니다." },
  ],
};
