import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "paris-little-red-door",
  category: "bar",
  title: "리틀 레드 도어",
  dek: "\"리틀 레드 도어\"는 2012년 파리의 마레 지구에 오픈한 바로, 2023년까지 The World's Best Bars 50(월드 베스트 바)에 10번이나 선정되었으며, 2022년에는 5위에 이름을 올리기도 했습니다.",
  publishedAt: "2024-07-03",
  hero: "/articles/paris-little-red-door/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223500064122",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/paris-little-red-door/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "\"리틀 레드 도어\"는 2012년 파리의 마레 지구에 오픈한 바로, 2023년까지 The World's Best Bars 50(월드 베스트 바)에 10번이나 선정되었으며, 2022년에는 5위에 이름을 올리기도 했습니다." },
    { kind: "paragraph", text: "바의 이름 그대로 입구의 빨간색 작은 문이 아이코닉한 바로, 사실 빨간 문이 아니라 빨간 문 왼쪽편의 문으로 입장을 합니다." },
    { kind: "paragraph", text: "\"리틀 레드 도어\"는 비주얼적으로도 아름답고, 창의적인 칵테일을 만들면서도 \"팜 투 글라스(Farm to Glass)\"를 추구하고 있습니다." },
    { kind: "paragraph", text: "\"팜 투 글라스\"는 \"팜 투 바(Farm to Bar)\"와 같은 개념으로, 말 그대로 농장에서 자란 농작물을 글라스에, 바에 가져온다는 개념입니다." },
    { kind: "paragraph", text: "좀 더 풀어보자면, 생산자와 직접적으로 연결되어 바는 좀 더 저렴한 가격에 신선한 재료, 못난이 농산물 또는 지역의 특산물을 구매하고, 생산자는 좀 더 안정적으로 농작물을 공급할 수 있게 되고, 지역 특산물을 홍보할 수 있는 등, 서로에게 윈윈이 되는 '지속가능성, 제로 웨이스트, 커뮤니티 형성' 등과 같은 가치를 포함하는 개념입니다." },
    { kind: "paragraph", text: "국내에는 임병진 대표님의 \"참 제철\"이 대표적이라 할 수 있겠네요." },
    { kind: "figure", src: "/articles/paris-little-red-door/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/paris-little-red-door/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "메뉴는 아주 간단하게 되어 있으며, 칵테일의 이름은 주된 재료만으로 아주 간단하게 되어있습니다. 물론 클래식 칵테일도 주문 가능합니다." },
    { kind: "figure", src: "/articles/paris-little-red-door/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/paris-little-red-door/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/paris-little-red-door/05.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "저는 이전에 아마투스(Amathus)에서 마신 마르(Marc)가 정말 인상적이었어서 마르 드 부르고뉴(Marc de Bourgogne)가 들어간 \"라즈베리(Raspberry)\"를 첫 잔으로 주문했습니다." },
    { kind: "paragraph", text: "아주 강렬한 상큼달콤한 라즈베리 느낌의 칵테일로 정말 만족스러운 첫 잔이었습니다. 다만, 마르의 캐릭터가 그닥 나지 않아서 '꼭 마르를 썼어야 했나?'와 '왜 무알콜인 라이어스(Lyre's)의 제품을 사용했을까?'라는 의문이 들기도 했습니다." },
    { kind: "paragraph", text: "두 번째 잔으로는 파리에 도착해서 케임브리지 퍼블릭 하우스(Cambridge Public House)와 해리스 뉴욕 바(Harry's New York Bar)에 이어 세 번째로 \"사이드카(Sidecar)\"를 주문했습니다." },
    { kind: "paragraph", text: "그렇게 뭐 크게 기억에 남지 않는 사이드카였고, 다른 오리지널 칵테일을 마시고 싶었지만, 일이 생겨서 사이드카를 마지막으로 하고 일어나야 했습니다." },
    { kind: "figure", src: "/articles/paris-little-red-door/06.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "\"리틀 레드 도어\"는 전체적으로 아주 부산스러운 느낌으로, 약간은 클럽 비슷한 느낌을 받기도 했습니다. 예약은 받지 않고 워크인으로만 방문할 수 있는데, 웨이팅은 필수일 정도로 엄청난 핫플입니다." },
    { kind: "paragraph", text: "처음 방문했을 때에는 웨이팅 엄두가 안나서 들어가지 못했고, 이틀 뒤에 혼자 가서야 15분 정도 웨이팅을 하고 들어갔습니다. 혼자 가는 경우에는 그래도 좀 더 빨리 입장할 수 있습니다." },
    { kind: "paragraph", text: "내부는 노래가 아주 큰데다가 사람도 많으니 꽤나 시끄러운데, 여기에 더해 메이킹 하는 바텐더분이 불필요할정도로 요란하게 메이킹을 해서(그러다가 잔도 깨고.....) 분위기가 정말정말 부산스럽습니다." },
    { kind: "paragraph", text: "칵테일의 경우, 리틀 레드 도어는 다른 유럽의 여느 바처럼 믹솔로지적인 성격이 아주 강해서 클래식 칵테일보다는 리틀 레드 도어의 오리지널 칵테일들을 추천드리는 편입니다." },
    { kind: "paragraph", text: "혹시나 웨이팅이 너무 길다 싶으면 케임브리지 퍼블릭 하우스와 가까우니, 비교적 사람이 덜 붐비는 케임브리지 퍼블릭 하우스를 방문하시는 것도 좋은 대안입니다." },
  ],
};
