import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "pegu-club",
  category: "cocktail",
  title: "페구 클럽 — 미얀마에서 영국인들에 의해 시작되어 미국에서 꽃을 피운 칵테일",
  dek: "'페구 클럽'은 영국이 미얀마를 식민 지배하던 시절이었던 20세기 초에 미얀마의 수도였던 양곤에 위치했던 사교 클럽(신사 클럽)으로, 이 곳에서 탄생하여 사교 클럽과 같은 이름을 가지게 되었습니다.",
  publishedAt: "2024-10-03",
  hero: "/articles/pegu-club/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223605555360",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/pegu-club/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "'페구 클럽'은 영국이 미얀마를 식민 지배하던 시절이었던 20세기 초에 미얀마의 수도였던 양곤에 위치했던 사교 클럽(신사 클럽)으로, 이 곳에서 탄생하여 사교 클럽과 같은 이름을 가지게 되었습니다." },
    { kind: "paragraph", text: "이후 1920년대에 파리의 해리스 뉴욕 바로 유명한 해리 맥켈혼(Harry MacElhone)의 저서(Harry's ABC of Mixing Cocktails)에 기록되었습니다." },
    { kind: "paragraph", text: "다만 해리 맥켈혼의 저서는 12번의 리뉴얼을 거쳤는데, 이름이 조금씩 바뀌게 되고, 여기서 페구 클럽이 몇 번째 인쇄본에서 기록된 것인지는 사람들마다 주장하는 것이 모두 다른 걸 보아 명확하지 않은 것 같습니다." },
    { kind: "paragraph", text: "그 중 첫 번째 인쇄본인 Harry of Ciro's ABC of Mixing Cocktails(1922), 일곱 번째 인쇄본인 Barflies and Cocktails(1927)로 갈리는 편인 것 같습니다." },
    { kind: "paragraph", text: "페구 클럽은 그렇게 인기 있는 칵테일은 아니었고 서서히 잊혀져 가는 것처럼 보였습니다. 그러나 2000년대 초반 크래프트 칵테일 운동과 함께 오드리 손더스(Audrey Saunders)의 페구 클럽이 뉴욕에서 오픈하면서 다시 한 번 이름을 알리게 됩니다." },
    { kind: "paragraph", text: "오드리 손더스는 당시 주류였던 보드카 대신 진(Gin)을 주류로 끌고 오기 위해 노력했으며, 그러한 일환으로 바의 이름을 페구 클럽으로 짓게 됩니다. 다만, 페구 클럽은 코로나의 여파로 2020년 문을 닫게 됩니다." },
    { kind: "figure", src: "/articles/pegu-club/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "45ml 진 (London Dry Gin)" },
    { kind: "paragraph", text: "20ml 라임즙 (Lime Juice)" },
    { kind: "paragraph", text: "15ml 코앵트로 or 오렌지 큐라소" },
    { kind: "paragraph", text: "(Cointreau or Orange Curacao)" },
    { kind: "paragraph", text: "앙고스투라 비터 1대시" },
    { kind: "paragraph", text: "(Angostura Aromatic Bitters 1dash)" },
    { kind: "paragraph", text: "오렌지 비터 1대시" },
    { kind: "paragraph", text: "(Orange Bitters 1dash)" },
    { kind: "figure", src: "/articles/pegu-club/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 모든 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 칵테일 잔에 부어줍니다." },
    { kind: "paragraph", text: "페구 클럽은 상큼하고, 오렌지스러운 시트러스에 더해 비터에서 오는 향신료의 캐릭터가 은은하게 더해지는 맛입니다. 거기에 진에서 나는 약간의 후추 캐릭터도 같이 느껴지는데 이건 아마 탱커레이라 그럴 수도 있습니다." },
    { kind: "paragraph", text: "개인적으로 약간 슴슴한 느낌의 맛이라 생각되는데, 간이 약하다는 건 아니고, 비터의 캐릭터가 은은하게 나니까 슴슴하다 느끼는 걸 수도 있을 것 같습니다." },
    { kind: "paragraph", text: "그러니까 맛있긴 한데 개인적으로 더 많은 자극을 원해!!라고 할 수 있겠네요. 저 같은 분들은 앙고스투라 비터를 조금만 더 넣어도 좋을 것 같습니다." },
  ],
};
