import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "pelican",
  category: "cocktail",
  title: "펠리컨",
  dek: "펠리컨은 2015년경에 뉴욕 Attaboy라는 바에서 Andrew Rice에 의해 만들어졌습니다.",
  publishedAt: "2023-06-13",
  hero: "/articles/pelican/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223128021837",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/pelican/00.webp", width: 966, height: 773 },
    { kind: "paragraph", text: "- About the Drink -" },
    { kind: "paragraph", text: "펠리컨은 2015년경에 뉴욕 Attaboy라는 바에서 Andrew Rice에 의해 만들어졌습니다. 이 Attaboy라는 바는 현대 칵테일에 아주 큰 영향을 준 바인 Milk & Honey가 처음 있던 자리에 오픈한 바입니다." },
    { kind: "paragraph", text: "Attaboy를 오픈한 건 Sam Ross인데, Milk & Honey의 창업자 Sasha Petraske의 제자 중 한 명으로 제자가 스승의 바를 이어 새로운 바를 오픈한 것입니다. Milk & Honey는 사라졌고, Sasha Petraske는 2015년 42세의 나이로 갑작스럽게 세상을 떠났지만, 그가 남긴 유산은 계속 이어지고 있습니다." },
    { kind: "figure", src: "/articles/pelican/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 퍼넷 브랑카(Fernet Branca)" },
    { kind: "paragraph", text: "30ml 브랑카 멘타(Branc Menta)" },
    { kind: "paragraph", text: "30ml 커피 리큐르(Coffee Liqueur)" },
    { kind: "paragraph", text: "생크림" },
    { kind: "paragraph", text: "+ 옵션" },
    { kind: "paragraph", text: "3 - 5ml 설탕 시럽" },
    { kind: "paragraph", text: "초콜릿 비터(Chocolate Bitters) 1 대시" },
    { kind: "paragraph", text: "정말 특이하게 퍼넷이 주가 되는 칵테일이며, 레시피만 봤을 때는 정말 괴랄하기 짝이 없는 칵테일입니다." },
    { kind: "paragraph", text: "원래 재료 중에 커피 리큐르는 카페 롤리타(Caffe Lolita)가 사용되는데 우리나라에 수입이 되질 않습니다. Educated Barfly의 Leandro DiMonriva는 카페 롤리타에 대한 대안으로 미스터 블랙에 약간의 시럽과 초콜릿 비터를 넣는 것을 추천했는데, 카페 롤리타가 좀 더 달고, 미스터 블랙에는 없는 초콜릿 노트가 있기 때문이라고 합니다." },
    { kind: "paragraph", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 생크림 이외의 재료를 믹싱 글라스에 넣어줍니다." },
    { kind: "paragraph", text: "2. 얼음을 채워주고, 스터를 한 후에 칵테일 글라스(닉앤노라)에 따라줍니다." },
    { kind: "paragraph", text: "3. 생크림을 약간 휘핑한 후, 칵테일 위에 플로탕해줍니다." },
    { kind: "figure", src: "/articles/pelican/02.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "앞서 말했듯이 레시피 자체는 꽤나 매니악합니다. 꽤 쓰고 허브감이 강렬할 것 같은데, 의외로 생크림이 그런 맛을 꽤 줄여줘서 적당한 허브감과 약간은 강한 민트, 조금의 커피와 초콜릿의 뉘앙스가 납니다. 생크림이 정말 중요한 역할을 하는 게, 생크림이 없이 마시면 허브와 민트의 느낌이 필요 이상으로 느껴집니다. 생크림이 어찌보면 맛의 밸런스를 잡아준다고 볼 수도 있겠네요." },
    { kind: "paragraph", text: "여기에 초콜릿의 뉘앙스가 더 나면 개인적으로는 좋을 것 같고, 초코가 가미된 디저트와 먹으면 최고의 시너지를 낼 것 같습니다." },
    { kind: "paragraph", text: "칵테일의 외관과 맛이 이전에 소개한 도미니카나와 비슷하다는 생각을 떨칠 수가 없는데, 이 칵테일이 탄생한 Attavoy의 전신이 Milk & Honey이고, 원작자인 Andrew Rice가 Milk & Honey에서 근무했던 Sam Ross의 직원인 셈이니 어찌 보면 거기에서 아이디어를 얻었을지도 모른다는 추측을 조심스럽게 해봅니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
