import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "pierre-de-segonzac-tres-vieille-reserve-extra",
  category: "spirits",
  title: "피에르 드 세공작 트레뷰 리저브 엑스트라",
  dek: "\"피에르 드 세공작\"은 라벨에 그려진 할아버지 \"피에르 페랑(Pierre Ferrand)\"에 의해서 2000년경에 만들어진 꼬냑 브랜드로 얼마 되지 않은 것 같지만, 사실 페랑 가문의 꼬냑 역사는 1702년 자크 페랑(Jacques Ferrand)에",
  publishedAt: "2024-09-12",
  hero: "/articles/pierre-de-segonzac-tres-vieille-reserve-extra/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223581931252",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/pierre-de-segonzac-tres-vieille-reserve-extra/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "About The Cognac" },
    { kind: "paragraph", text: "\"피에르 드 세공작\"은 라벨에 그려진 할아버지 \"피에르 페랑(Pierre Ferrand)\"에 의해서 2000년경에 만들어진 꼬냑 브랜드로 얼마 되지 않은 것 같지만, 사실 페랑 가문의 꼬냑 역사는 1702년 자크 페랑(Jacques Ferrand)에 의해 시작됩니다." },
    { kind: "paragraph", text: "가문의 꼬냑을 생산하는 역사가 오래되었는데, 다만 많은 양을 큰 꼬냑 기업들에게 납품을 하고 소량만을 판매하였고, '피에르 드 세공작'이라는 브랜드를 만든 지가 오래되지 않은 것뿐이라 할 수 있겠습니다." },
    { kind: "paragraph", text: "꼬냑을 좋아하시는 분들이라면, 어디선가 피에르 페랑이라는 이름을 들어보셨을 텐데, 메종 페랑(Maison Ferrand)에서 나오는 꼬냑으로 동명의 '피에르 페랑'이 있습니다." },
    { kind: "paragraph", text: "사실 이 '메종 페랑의 꼬냑 피에르 페랑'은 앞서 말씀드린 피에르 드 세공작의 창업주 할아버지의 이름을 딴 것이 맞기는 합니다. 이게 참 복잡한 사연인데 얘기하게 되면 너무 길어지니 시음기 이후에 적어두겠습니다." },
    { kind: "paragraph", text: "여하튼 피에르 드 세공작은 꼬냑의 그랑 샹파뉴(Grande Champagne) 지역의 중심부인 세공작(Segonzac) 지역에 위치해있습니다." },
    { kind: "paragraph", text: "피에르 드 세공작은 우니 블랑(Uni-Blanc)이라는 포도 품종을 단일으로 사용하고, 자체 포도원에서 수확한 포도만을 사용해서 자가증류하는 몇 안되는 부이이외르 드 크뤼(bouilleur de cru) 가문입니다." },
    { kind: "paragraph", text: "피에르 드 세공작의 '트레뷰 리저브 엑스트라'는 구매할 때 물어보니 평균 숙성 50년의 원액을 블렌딩한 것이라 하는데, 바틀 하단의 Lot.50을 확인하실 수 있습니다." },
    { kind: "paragraph", text: "사실 이 Lot라는 표기는 평균 블렌딩된 원액의 숙성 연수, 증류 연대, 숙성 시작 연대 등 정립되지 않은 용어이기 때문에 판매자나 생산자의 얘기가 가장 정확합니다." },
    { kind: "paragraph", text: "또한 꼬냑은 오크 숙성을 끝내고 유리병이나 항아리에 원액을 담아내더라도 후숙(또는 병숙)을 인정하기 때문에 적힌 연수 대로 오크 숙성을 했구나!라고 단정할 수 없기도 합니다." },
    { kind: "figure", src: "/articles/pierre-de-segonzac-tres-vieille-reserve-extra/01.webp", width: 966, height: 966 },
    { kind: "quote", text: "생산자: 피에르 드 세공작" },
    { kind: "quote", text: "아펠라시옹: 그랑 샹파뉴" },
    { kind: "quote", text: "포도 품종: 우니 블랑 100%" },
    { kind: "quote", text: "캐스크: 리무쟁 오크" },
    { kind: "quote", text: "숙성: 평균 50년 숙성된 원액의 블렌딩" },
    { kind: "figure", src: "/articles/pierre-de-segonzac-tres-vieille-reserve-extra/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "- 크루아상 같은 버터리함" },
    { kind: "paragraph", text: "- 약간은 묵직한 달달함" },
    { kind: "paragraph", text: "- 미묘하게 나는 오래 후숙된 과일 or 설탕에 졸인 핵과류 과일" },
    { kind: "paragraph", text: "- 올스파이스 따위의 향신료" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 달달하고, 깔끔하고, 생각보다는 가벼운 맛" },
    { kind: "paragraph", text: "- 건과일" },
    { kind: "paragraph", text: "- 복잡하고도 다채로운 풍미 (이걸 설명하기 어렵다...)" },
    { kind: "paragraph", text: "- 마지막에는 홍차의 쌉쌀한 끝 맛을 연상시키는 쌉쌀하고 우디한 맛이 입에 남음" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "-무겁지는 않지만 다소 복잡하며, 달큰 쌉쌀한 피니시" },
    { kind: "paragraph", text: "장기 숙성된 (과하게 숙성되지 않은) 코냑은 란시오로 인해 아주 복합적인 캐릭터를 내는데, 개인적으로 이런 복합성을 좋아하면서도 사실 이걸 하나하나 캐릭터를 집으면서 글로 풀어내기는 상당히 어렵다고 생각됩니다." },
    { kind: "paragraph", text: "그나마 가장 잘 느껴지는 점은 볼드체로 했으니 참고해 주세요." },
    { kind: "paragraph", text: "피에르 페랑 할아버지는 왜 본인의 이름으로 꼬냑을 판매하지 않을까?에 대한 간략한(?) 정리" },
    { kind: "paragraph", text: "피에르 드 세공작의 창업주 할아버지는 초기 메종 페랑(꼬냑 페랑)의 창업주들과 동업(또는 고용) 관계였으며, 이 과정에서 이들은 회사를 설립하고 \"피에르 페랑\"을 브랜드로 하여 꼬냑을 판매하였습니다." },
    { kind: "paragraph", text: "이후 모종의 이유로 이들 간에 불화가 생기며 결별했고, 피에르 페랑(세공작)은 전 파트너들의 회사의 브랜드인 본인의 이름으로 꼬냑을 판매하기 시작합니다." },
    { kind: "paragraph", text: "메종 페랑은 이에 위조 혐의로 소송을 제기하게 되었고, 결국 2000년에 법원은 메종 페랑의 손을 들어줬습니다." },
    { kind: "paragraph", text: "정확하지는 않지만 어찌 됐건 피에르 페랑은 정당하게 메종 페랑의 브랜드이고, 회사 설립 전에 '피에르 페랑'이라는 이름이나 명칭이 꼬냑 업계에서 유명했던 것이 아니었기 때문에 상표적으로 사용했다 볼 수 없어서 그런 것 같습니다." },
    { kind: "paragraph", text: "결국 본인의 이름을 뺏긴 격이 된 피에르 페랑(세공작)은 피에르 드 세공작이라는 새로운 이름으로 꼬냑을 판매하게 되었고, 메종 페랑은 \"엘리 페랑(Elie Ferrand)\" 가문의 유산을 인수하여 꼬냑을 생산하고 있습니다." },
    { kind: "paragraph", text: "두 페랑에 대한 자세한 이야기는 다른 글로 다시 풀어보겠습니다." },
  ],
};
