import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "pimms-cup",
  category: "cocktail",
  title: "핌스 컵 — 오이, 여름, 제철과일을 더한 윔블던의 칵테일",
  dek: "\"핌스컵\"은 영국의 전통적인 칵테일로, 과일컵(Fruit Cup)의 일종입니다.",
  publishedAt: "2024-09-04",
  hero: "/articles/pimms-cup/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223572075568",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/pimms-cup/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"핌스컵\"은 영국의 전통적인 칵테일로, 과일컵(Fruit Cup)의 일종입니다. 과일컵이란 과일, 기주, 향신료나 허브(또는 향신료나 허브가 들어간 주류), 탄산음료로 만들어지는 칵테일입니다. 일종의 펀치라고 볼 수도 있죠." },
    { kind: "paragraph", text: "19세기 영국에서는 이 과일컵이 인기가 있었는데, 식당마다 저마다의 레시피대로 과일컵을 판매하였으며, 이 칵테일들을 작은 No.1 사이즈의 탱커드 잔(Tankard)에 담아서 서브했다고 합니다." },
    { kind: "paragraph", text: "1840년에는 제임스 핌(James Pimm)이라는 사람이 런던에 위치한 본인의 식당인 핌스 오이스터 웨어하우스(Pimm's Oyster Warehouse)의 바에서 과일컵을 제공하였습니다." },
    { kind: "paragraph", text: "이 과일컵이 후에 핌스 넘버 원 컵(Pimm's No.1 Cup)이라 불리게 되었고, 탄산음료와 과일, 허브를 더해서 간단하게 만들 수 있도록 핌스 넘버 원(Pimm's No.1)이라는 진을 기반으로 하는 리큐르를 판매하게 됩니다." },
    { kind: "paragraph", text: "1971년에는 최초의 핌스 바(Pimm's Bar)가 윔블던 테니스 토너먼트에서 오픈하였으며, 켄터키 더비와 민트 줄렙처럼 핌스 컵은 윔블던 테니스 토너먼트를 상징하는 주류가 되었다고 할 정도로 인기를 끌었다고 합니다." },
    { kind: "paragraph", text: "얼마나 인기가 많았는지 영국에서 여름의 핌스 컵의 수요가 오이의 수요를 늘릴 정도였다고 합니다." },
    { kind: "figure", src: "/articles/pimms-cup/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "45ml 핌스 넘버 원 (Pimm's No.1)" },
    { kind: "paragraph", text: "7.5ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "진저에일 적당량" },
    { kind: "paragraph", text: "가니시: 민트, 오이, 시트러스(레몬, 오렌지 등)" },
    { kind: "paragraph", text: "옵션 가니시: 딸기, 기타 제철과일" },
    { kind: "figure", src: "/articles/pimms-cup/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 긴 잔에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "2. 모든 재료를 넣고 살짝 저어줍니다." },
    { kind: "paragraph", text: "3. 가니시로 장식해줍니다." },
    { kind: "paragraph", text: "핌스 컵은 핌스의 살짝 쌉쌀하고 달달한 맛에 과일의 달달함, 오이의 시원함, 생강의 알싸함에 약간의 탄산까지 나는 아주 복합적인 캐릭터이지만 마시기 쉬운 칵테일입니다." },
    { kind: "paragraph", text: "핌스 컵은 여름에 마시는 칵테일이라는 인식이 강한데, 그 맛을 보면 동의히지 않을 수가 없습니다." },
    { kind: "paragraph", text: "영국에서는 딸기를 넣는 것이 일반적인 거 같은데, 영국의 딸기는 3월부터 12월까지 재배되지만 우리나라는 제철이 겨울이라 굳이 넣지는 않았습니다. 다른 제철 과일을 넣어도 괜찮구요." },
    { kind: "paragraph", text: "오이는 웬만하면 넣는 걸 추천드리는 것이, 오이의 시원한 맛이 아주 상쾌하게 다가옵니다." },
  ],
};
