import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "port-charlotte-rockndaal-03-2-feis-ile-2024",
  category: "spirits",
  title: "포트 샬롯 로큰달 03.2 페스 아일 2024",
  dek: "\"포트샬롯(Port Charlotte)\" 위스키는 \"브룩라디 증류소\"의 코어 위스키 라인업 3종 중 하나로, 브룩라디 증류소에서 남서쪽으로 3km 떨어진 마을인 포트 샬롯의 이름을 딴 것입니다.",
  publishedAt: "2024-08-19",
  hero: "/articles/port-charlotte-rockndaal-03-2-feis-ile-2024/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223553186100",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/port-charlotte-rockndaal-03-2-feis-ile-2024/00.webp", width: 540, height: 720 },
    { kind: "figure", src: "/articles/port-charlotte-rockndaal-03-2-feis-ile-2024/01.webp", width: 522, height: 696 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "\"포트샬롯(Port Charlotte)\" 위스키는 \"브룩라디 증류소\"의 코어 위스키 라인업 3종 중 하나로, 브룩라디 증류소에서 남서쪽으로 3km 떨어진 마을인 포트 샬롯의 이름을 딴 것입니다." },
    { kind: "paragraph", text: "원래 포트 샬롯 마을 내에는 1829년 문을 연 \"로킨달(Lochindaal) 증류소\"가 존재했는데, 여러 차례 주인이 바뀌고, 폐쇄했다가 재개장하는 등의 고난을 겪다가 1929년 문을 닫게 됩니다." },
    { kind: "paragraph", text: "2007년, 브룩라디 증류소는 이 로킨달 증류소의 건물들을 사들였고, 포트 샬롯이라는 이름의 증류소를 세울 계획을 발표했습니다만, 2008년 금융위기로 보류하게 되었습니다." },
    { kind: "paragraph", text: "대신 2007년부터 남아있는 로킨달 증류소 창고에 포트샬롯 원액을 숙성하기 시작하였습니다." },
    { kind: "paragraph", text: "포트샬롯은 헤빌리 피티드(Heavily Peated)로 출시되며, 페놀 수치는 40ppm입니다. 이는 킬달튼 3형제(라프로익, 라가불린, 아드벡)와 비슷한 수치입니다." },
    { kind: "paragraph", text: "현대에 아드벡과 브룩라디의 슈퍼 헤빌리 피티드 경쟁에서 탄생한 아드벡의 슈퍼노바나 브룩라디의 옥토모어 등으로 인해 이 정도 ppm이 낮다고 생각할 수는 있지만, 40ppm도 충분히 높은 수치입니다." },
    { kind: "paragraph", text: "포트 샬롯 로큰달 03.2은 올해 페스 아일을 기념하여 출시된 것으로, 브룩라디 증류소의 페스 아일 오픈 데이 이벤트인 로큰달 축제(ROCK'NDAAL Festival)의 이름을 따온 바틀입니다." },
    { kind: "paragraph", text: "이 축제는 2022년부터 시작되어 이때부터 01번이 붙게 되었고, 00.1은 브룩라디 바틀을, 00.2는 포트 샬롯 바틀을 지칭합니다." },
    { kind: "quote", text: "증류소: 브룩라디 증류소" },
    { kind: "quote", text: "위스키 타입: 싱글 몰트 위스키" },
    { kind: "quote", text: "캐스크 정보: 버번 캐스크 풀 숙성(Bourbon Cask 70%) + 퍼스트필 소테른 캐스크(1st fill Sauternes Cask 30%)를 배팅 / 20년 숙성" },
    { kind: "quote", text: "보리 정보: 100% 스코틀랜드산 보리 (Scottish Barley)" },
    { kind: "quote", text: "페놀 수치: 40ppm" },
    { kind: "quote", text: "도수: 54%" },
    { kind: "quote", text: "시리즈: 로큰달 (ROCK'NDAAL)" },
    { kind: "figure", src: "/articles/port-charlotte-rockndaal-03-2-feis-ile-2024/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "-디저트 와인 같은 달큰한 향" },
    { kind: "paragraph", text: "-복숭아, 살구 등과 같은 달달한 핵과류의 향" },
    { kind: "paragraph", text: "-바닐라와 견과류" },
    { kind: "paragraph", text: "-허브의 터치" },
    { kind: "paragraph", text: "-생각보다 강하지 않은 피트감" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "-향에 비해서는 약간 드라이함" },
    { kind: "paragraph", text: "-바닐라, 과실감" },
    { kind: "paragraph", text: "-가죽, 우디함" },
    { kind: "paragraph", text: "-어딘가 화이트, 디저트 와인 같은 느낌" },
    { kind: "paragraph", text: "-강하지는 않지만 존재감 있는 피트" },
    { kind: "paragraph", text: "-혀끝에 남는 꿀의 느낌" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "-꽤나 긴 피니시" },
    { kind: "paragraph", text: "-시트러스, 허니콤, 살짝의 피트" },
    { kind: "paragraph", text: "포트 샬롯 로큰달 03.2는 전체적으로 핵과류, 바닐라, 화이트/디저트 와인스러운 캐릭터가 주가 되며, 피트감이 튀지 않고, 크게 흠잡을 곳 없이 아주 밸런스가 좋은 느낌입니다." },
    { kind: "paragraph", text: "브룩라디 증류소의 위스키 중 소테른 캐스크를 사용하는 브룩라디, 옥토모어, 포트샬롯을 모두 마셔봤는데 확실히 다른 증류소들보다 와인 캐스크를 잘 사용하는 인상을 다시 한번 받았습니다." },
    { kind: "paragraph", text: "또한 포트 샬롯 로큰달 03.2은 제가 알기로 브룩라디 증류소가 출시한 오피셜 포트샬롯 중 가장 숙성 연수가 긴 걸로 알고 있는데, 길고 우아한 피니시로 고숙성의 기대감을 채워주기도 했습니다." },
    { kind: "paragraph", text: "함께 아일라 여행을 갔던 친구가 사 온 바틀인데, 개인적으로 아주 맛있게 마셨네요." },
  ],
};
