import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "rob-roy",
  category: "cocktail",
  title: "롭 로이 — 맨하탄의 스코틀랜드 출신 형제, 스카치 위스키를 사용한 맨하탄",
  dek: "가장 많이 언급되는 이야기에 따르면, 「롭 로이」는 「월도프-아스토리아(Waldorf-Astoria) 호텔」의 한 바텐더에 의하여 1894년에 만들어졌다고 합니다.",
  publishedAt: "2025-04-25",
  hero: "/articles/rob-roy/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223846355977",
  relatedCocktailSlugs: ["robroy"],
  blocks: [
    { kind: "figure", src: "/articles/rob-roy/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "가장 많이 언급되는 이야기에 따르면, 「롭 로이」는 「월도프-아스토리아(Waldorf-Astoria) 호텔」의 한 바텐더에 의하여 1894년에 만들어졌다고 합니다." },
    { kind: "paragraph", text: "그 이름은 오페레타(Operetta) '롭 로이'의 초연을 기념하기 위하여 지어졌는데, 이 오페레타의 주인공인 '로버트 로이 멕그리거(Robert Roy MacGregor)'의 약칭이기도 합니다." },
    { kind: "paragraph", text: "이 '롭 로이'라는 인물은 스코틀랜드의 민속 영웅이라고 하는데, 들어가는 재료를 생각하면 그럴듯한 작명 센스긴 하죠." },
    { kind: "paragraph", text: "다만, 이 설에 대해서는 어느 정도 의문점이 존재합니다." },
    { kind: "figure", src: "/articles/rob-roy/01.webp", width: 966, height: 1288 },
    { kind: "quote", text: "정말 월도프-아스토리아 호텔에서 만들어졌을까?" },
    { kind: "paragraph", text: "이미 10년 전인 1884년에 다른 이름으로 스카치 + 버무스 조합의 칵테일이 존재했음." },
    { kind: "paragraph", text: "그 이전에 이미 기주만 다른 맨하탄(Manhattan)이 존재했음." },
    { kind: "paragraph", text: "당시에는 스윗 버무스가 들어간 칵테일이 크게 유행하였음." },
    { kind: "paragraph", text: "이런 점들을 보면 정말 월도프-아스토리아 호텔에서 롭로이 칵테일이 \"탄생\"하였는지에는 약간의 의문이 들기는 합니다만, 모든 칵테일에는 이야기가 필요한 법이니까요." },
    { kind: "figure", src: "/articles/rob-roy/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "45ml 스카치 위스키(Scotch Whisky)" },
    { kind: "paragraph", text: "15ml 스윗 버무스(Sweet Vermouth)" },
    { kind: "paragraph", text: "*1~2dashes 앙고스투라 아로마틱 비터" },
    { kind: "paragraph", text: "(Angostura Aromatic Bitters)" },
    { kind: "paragraph", text: "*8~20drops" },
    { kind: "paragraph", text: "가니시: 오렌지 껍질, 마라스키노 체리(옵션)" },
    { kind: "paragraph", text: "롭 로이는 대부분 맨하탄처럼 기주와 버무스가 2:1 또는 3:1이 가장 대중적인 비율입니다. 입맛과 사용하시는 버무스에 따라서 마음에 드는 비율로 만드시면 되겠습니다." },
    { kind: "paragraph", text: "또, 기주에 있어서 블렌디드 스카치 위스키를 사용해도 전혀 상관 없습니다만, 개인적으로는 캐릭터가 확실한 싱글 몰트 위스키를 사용하시는 걸 추천드립니다." },
    { kind: "paragraph", text: "개인적으로는 점잖고, 부드럽고 살짝 달큰한 롭 로이는 발베니 12년 더블우드를 사용하고 있습니다. 어떤 분들은 피트 위스키를 소량 첨가하기도 하더군요. 이 부분도 취향대로." },
    { kind: "figure", src: "/articles/rob-roy/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 가니시 외의 재료를 믹싱글라스에 넣습니다." },
    { kind: "paragraph", text: "2. 얼음을 채우고, 스터합니다." },
    { kind: "paragraph", text: "3. 칵테일 잔에 따라줍니다." },
    { kind: "paragraph", text: "4. 잔 위로 *오렌지 껍질을 짜서 오일을 뿌립니다." },
    { kind: "paragraph", text: "5. 마라스키노 체리를 하나 넣어습니다(옵션)" },
    { kind: "paragraph", text: "*오렌지 껍질은 취향에 따라서 버리거나," },
    { kind: "paragraph", text: "다듬어서 잔에 꽃아서 장식해줍니다." },
    { kind: "paragraph", text: "롭 로이의 맛" },
    { kind: "paragraph", text: "- 바닐라 느낌이 적고, 더욱 섬세한 캐릭터의 맨하탄 같은 느낌" },
    { kind: "paragraph", text: "- 생각보다 달큰하고, 복잡한 맛" },
    { kind: "paragraph", text: "- 사용하는 스카치에 따라서 편차가 좀 있는 맛" },
    { kind: "paragraph", text: "개인적으로 맨하탄보다는 롭 로이를 더 좋아하는 편인데, 스카치 위스키를 좋아하시는 분들이라면 꼭 한 번쯤은 마셔보시는 걸 추천드리는 편입니다." },
  ],
};
