import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "rome-with-a-view",
  category: "cocktail",
  title: "롬윗어뷰 — 로마의 오후의 풍경이 보이는 저도수 칵테일",
  dek: "'롬 윗 어 뷰'는 2008년에 현대 칵테일계에 많은 영향을 미친 뉴욕의 밀크앤허니(Milk&Honey)라는 바에서 마이클 매킬로이(Michael McIlroy)에 의해서 만들어졌습니다.",
  publishedAt: "2024-10-13",
  hero: "/articles/rome-with-a-view/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223617184701",
  relatedCocktailSlugs: ["romewithaview"],
  blocks: [
    { kind: "figure", src: "/articles/rome-with-a-view/00.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "'롬 윗 어 뷰'는 2008년에 현대 칵테일계에 많은 영향을 미친 뉴욕의 밀크앤허니(Milk&Honey)라는 바에서 마이클 매킬로이(Michael McIlroy)에 의해서 만들어졌습니다." },
    { kind: "paragraph", text: "당시에 미국에서는 쓴맛이 나는 아페리티프나 저도수 술에 대한 유행이 생기기 전이었고, 아직까지 캄파리나 네그로니 같은 쓴 맛의 술이 미국에서 큰 인기를 끌지도 못하는 시기였습니다." },
    { kind: "paragraph", text: "이런 시기에 매킬로이는 밀크앤허니에 오는 손님들 중 쓴맛이 나는 칵테일을 싫어한다는 얘기를 듣고는 '그럴리가요, 이것 한 번 드셔보세요.'라 하면서 롬윗어뷰를 만들어줬다고 합니다." },
    { kind: "paragraph", text: "칵테일의 구조 자체는 피즈(Fizz) 류의 칵테일과 아메리카노(Americano) 칵테일을 매시업한 느낌이 드는 것 같습니다." },
    { kind: "paragraph", text: "여담으로 매킬로이는 이후에 샘 로스(Sam Ross)와 밀크앤허니가 있던 자리에 아타보이(Attaboy)라는 바를 오픈했는데, 2015년 아타보이에서 댄 그린바움(Dan Greenbaum)에 의해서 롬윗어뷰의 변형 격인 세컨드 서브(Second Serve)가 만들어집니다." },
    { kind: "figure", src: "/articles/rome-with-a-view/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 캄파리 (Campari)" },
    { kind: "paragraph", text: "30ml 드라이 버무스 (Dry Vermouth)" },
    { kind: "paragraph", text: "30ml 라임즙 (Lime Juice)" },
    { kind: "paragraph", text: "15ml 설탕 시럽 (Simple Syrup)" },
    { kind: "paragraph", text: "탄산수 탑 업" },
    { kind: "paragraph", text: "가니시: 오렌지 휠" },
    { kind: "figure", src: "/articles/rome-with-a-view/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 탄산수 이외의 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 넣고, 셰이킹 해줍니다." },
    { kind: "paragraph", text: "3. 셰이킹 후, 얼음을 채운 긴 잔에 부어줍니다." },
    { kind: "paragraph", text: "4. 탄산수를 적당량 채워줍니다." },
    { kind: "paragraph", text: "살짝 찌르는 듯한 상큼함에 쌉쌀하고 좋은 허브감이 살짝 느껴지는 것이 재미있는 칵테일이며, 캄파리로 인해서 약간은 자몽 같은 시트러스의 캐릭터가 느껴지기도 합니다." },
    { kind: "paragraph", text: "캄파리와 라임 조합의 칵테일이 그렇게 많은 편은 아닌데, 이 칵테일만 마셔봐도 둘의 조합이 꽤나 잘 어울린다는 걸 알 수 있습니다." },
    { kind: "paragraph", text: "저도수이기 때문에 아주아주 편하게 마실 수 있으며, 여름이나 초가을에 꽤나 잘 어울리는 칵테일이라 생각되며, 식전주로 마시기에도 부담스럽지 않을 것 같습니다." },
  ],
};
