import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "rusty-nail",
  category: "cocktail",
  title: "러스티 네일 — 매력적인 스카치위스키와 드람부이의 콤비네이션",
  dek: "\"러스티 네일\"은 직역하면 '낡은 못'으로 칵테일의 색이 낡은 못과 비슷하다",
  publishedAt: "2024-09-11",
  hero: "/articles/rusty-nail/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223580334379",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/rusty-nail/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"러스티 네일\"은 직역하면 '낡은 못'으로 칵테일의 색이 낡은 못과 비슷하다 하여 붙은 이름이라는 설이 있으며, 영국 속어로 '예스러운 것'이라는 뜻을 가지며 칵테일의 재료나 맛이 예스럽다는 점에서 이름이 붙었다는 설이 있습니다." },
    { kind: "paragraph", text: "러스티 네일의 탄생 자체는 꽤 모호하지만, 드람부이가 상업화되었다고 하는 1910년대 이후에나 탄생한 것이 명확하며, 두 명의 칵테일 역사가 및 전문가에 의해 두 가지 설이 주류가 되고 있습니다." },
    { kind: "figure", src: "/articles/rusty-nail/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "① 데이비드 원드리치 (David Wondrich)" },
    { kind: "paragraph", text: "원드리치는 러스티 네일이 1937년 소개된 BIF라는 칵테일에서 시작되었다고 주장합니다." },
    { kind: "paragraph", text: "이 BIF라는 칵테일은 1937년 영국 산업 박람회(British Industries Fair)에서 그 이름을 따서 베니먼(F. Benniman)이라는 사람에 의해 만들어졌으며, 현재 흔하게 알려진 러스티 네일에 비터가 소량 첨가된 칵테일입니다." },
    { kind: "paragraph", text: "원드리치는 BIF에서 시작하여 이후 D&S, Little Club No.1, Mig-21 등의 이름으로 러스티 네일과 비슷한 칵테일이 존재했고, 결국에 출처는 확실하지는 않지만 현재의 레시피와 이름이 최종적으로 살아남았다고 주장합니다." },
    { kind: "paragraph", text: "② 데일 데그로프 (Dale DeGroff)" },
    { kind: "paragraph", text: "데그로프는 러스티 네일이 1960년대 초에 뉴욕 맨해튼에 위치한 21 클럽(21 Club)이라는 레스토랑에서 일하던 한 바텐더가 만들어낸 것이 좀 더 설득력 있다고 주장합니다." },
    { kind: "paragraph", text: "그러한 근거는 당시에 미국에서 러스티 네일이 유행하기도 했고, 21 Club에서는 브랜디와 베네딕틴으로 만드는 B&B를 만들어냈는데, 러스티 네일은 B&B와 꽤나 유사한 형식의 칵테일이기 때문이라는 것입니다." },
    { kind: "paragraph", text: "다만, 데그로프 자신 또한 이 근거를 입증할 수 있는 자료나 증거를 찾아내지는 못하였다고 합니다." },
    { kind: "paragraph", text: "1963년 드람부이 회사의 회장은 뉴욕 타임즈에서 러스티 네일이 21 Club에서 만들어졌다는 주장을 지지했는데, 이것도 곧이곧대로 믿기 어렵긴 합니다." },
    { kind: "paragraph", text: "21 Club은 많은 유명 인사들이 다니던 곳으로 유명했는데, 드람부이 회사의 입장에서는 21 Club의 유명세를 바탕으로 러스티 네일과 드람부이를 광고할 스토리를 하나 얻을 수 있으니 손해 볼 것이 없었겠죠." },
    { kind: "figure", src: "/articles/rusty-nail/02.webp", width: 966, height: 427 },
    { kind: "figure", src: "/articles/rusty-nail/03.webp", width: 966, height: 419 },
    { kind: "paragraph", text: "여담으로 \"러스티 네일\"은 상표로 등록된 몇 안 되는 칵테일 중 하나로, 1960년대에 미국에서 상표등록이 되었으며, 우리나라에서도 1990년대 후반에 등록된 바 있습니다." },
    { kind: "figure", src: "/articles/rusty-nail/04.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "45ml 싱글몰트 또는 블렌디드 스카치 위스키 (Scotch Whisky)" },
    { kind: "paragraph", text: "15ml 드람부이 (Drambuie)" },
    { kind: "paragraph", text: "옵션 가니시: 레몬 껍질 (Lemon Peel)" },
    { kind: "figure", src: "/articles/rusty-nail/05.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 모든 재료를 온더락 잔에 넣어줍니다." },
    { kind: "paragraph", text: "2. 얼음을 채워주고, 가볍게 스터 해줍니다." },
    { kind: "paragraph", text: "3. **레몬 껍질에서 오일을 짜넣어줍니다(옵션)." },
    { kind: "paragraph", text: "러스티 네일은 꿀과 허브 캐릭터의 드람부이와 다양한 캐릭터의 여러 스카치 위스키의 콤비네이션이 돋보이는 칵테일입니다." },
    { kind: "paragraph", text: "러스티 네일의 골자는 물론 드람부이의 꿀과 허브감이지만, 어떤 스카치 위스키를 사용하냐에 따라 맛이 다양하게 바뀝니다." },
    { kind: "paragraph", text: "피트가 없는 스카치를 사용한다면 좀 더 달달한 느낌의 러스티 네일이 만들어지며, 강한 피트 캐릭터가 있는 스카치를 사용하더라도 생각보다 피트감이 강하지 않으며, 피트·꿀·허브감이 멋들어진 삼박자를 이룹니다." },
    { kind: "paragraph", text: "개인적으로는 라가불린 16년으로 만드는 러스티 네일을 좋아하는데, 드람부이의 꿀과 허브 캐릭터가 라가불린 특유의 피트와 곡식의 달달한 캐릭터가 절묘한 밸런스를 이루며, 마시고 난 후에는 살짝 쌈쌀함이 입안에 남습니다." },
    { kind: "paragraph", text: "다만, 라가불린 16년을 기주로 해서 바에서 마시기에는 너무 비싸지게 됩니다. 그럴 때는 드람부이가 탄생한 스카이(Skye)섬에서 생산되는 탈리스커(Talisker) 10년을 기주로 하는 것도 센스 있는 주문이겠네요." },
    { kind: "paragraph", text: "더 저렴하게는 피트 캐릭터가 특징인 조니워커 블랙 또는 더블 블랙을 추천드립니다." },
    { kind: "paragraph", text: "러스티 네일은 스카치와 드람부이의 비율이 최근에는 3:1이 일반적인데, 2:1 ~ 4:1까지 입맛 또는 사용하는 스카치의 종류에 따라 조정하면 되겠습니다." },
  ],
};
