import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-bar-nano-femto",
  category: "bar",
  title: "나노 펨토 — 일본의 캐릭터를 더한 칵테일이 돋보이는 바",
  dek: "'나노 펨토(Bar nano femto)'는 삿포로 시내 스스키노역 근처 빌딩의 7층에 위치한 바로, 근처의 '나노 굴드(Bar nano gould)' 및 '파반(Bar Pavane)'은 이곳의 자매점입니다.",
  publishedAt: "2024-11-03",
  hero: "/articles/sapporo-bar-nano-femto/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223645145610",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/00.webp", width: 966, height: 1289 },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/01.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "'나노 펨토(Bar nano femto)'는 삿포로 시내 스스키노역 근처 빌딩의 7층에 위치한 바로, 근처의 '나노 굴드(Bar nano gould)' 및 '파반(Bar Pavane)'은 이곳의 자매점입니다. 의외로 오너는 자매점인 나노 굴드에서 손님을 맞이하고 있다고 하네요." },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/03.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "메뉴는 일본어와 영어 메뉴가 구비되어 있으니 영어 메뉴를 요청하시면 됩니다. 삿포로 시내의 바는 외국인이 많이 와서 그런지 메뉴가 있는 곳은 모두 영어 메뉴를 구비해놓은 것 같습니다." },
    { kind: "paragraph", text: "이번 여행에서는 클래식 칵테일은 잘 안 마시고, 대부분 위스키와 바의 시그니처를 주로 마셨는데, 나노 펨토에서도 그런 느낌이었습니다. 일단 이곳 자체가 칵테일로 유명하기도 했고." },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/05.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "메뉴를 보다 보니 최근 많이 마셨던 러스티 네일을 일본 이모 쇼츄(고구마 쇼츄)를 기주로 해서 사쿠라 우드로 훈연을 해서 변형한 '재패니즈 이모 쇼츄 러스티 네일'이 눈에 띄어 이것부터 주문했습니다." },
    { kind: "paragraph", text: "첫 잔이어서 동영상을 못 찍었는데, 서브할 때 얼음만 채운 잔과 연기로 훈연 중인 칵테일을 담은 디캔터(?)를 같이 가지고 나오고, 손님이 보는 앞에서 따라줍니다." },
    { kind: "paragraph", text: "이렇게 되면 서브할 때 칵테일과 연기가 같이 나오면서 연출적으로도 흥미롭고, 연기의 단 향이 코에 닿게 되는데 이게 또 참 향기롭습니다." },
    { kind: "paragraph", text: "맛은 확실히 러스티 네일의 구조를 가지고 있는데, 기주를 이모 쇼츄로 하면서 좀 더 산뜻하고, 아마 드람부이의 양을 줄이면서 꿀을 넣은 건지 적절한 단맛과 허브감이 나며, 훈연으로 인해서 맛이 꽉 차있는 것에 더해 감칠맛이 상당합니다." },
    { kind: "paragraph", text: "개인적으로 올해 마신 최고의 칵테일." },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/06.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "다음 잔을 위해서 메뉴를 보다가 '마르티네즈'의 재료 조합이 눈에 확 들어와서 주문을 했습니다. 소테른 와인과 몽키47 진의 조합이라니... 정말 흥미롭고, 왜 이런 생각을 못 해봤을까라는 생각을 하면서 주문했습니다." },
    { kind: "paragraph", text: "개인적으로는 마르티네즈보다는 마티니의 변형이 아닌가?라는 생각이 계속해서 드는 맛이었고, 마티니를 싫어하신다면 절대 비추입니다. 마티니를 좋아하신다면 추천할만하네요." },
    { kind: "figure", src: "/articles/sapporo-bar-nano-femto/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "자리 앞의 바 카운터를 둘러보다 보니 '글렌파클라스 패밀리 리저브 1997 마데이라 캐스크'가 눈에 띄어서 주문했습니다. 예전에 봐뒀던 생년 빈티지인데다가 글렌파클라스에서 흔치 않은 마데이라 캐스크여서 한 번 마셔보고 싶었는데 여기서 만나니 꽤나 반가웠습니다." },
    { kind: "paragraph", text: "맛은 정확히는 기억이 안 나는데, 엄청 인상 깊지는 않았지만 셰리 캐스크를 사용한 글렌파클라스들보다는 여리여리하게 단맛이었고, 입맛에 잘 맞았던 걸로 기억합니다." },
    { kind: "paragraph", text: "직원분들이 아주 친절하고, 칵테일과 위스키를 마시면서 매니저님(아마도?)과 서로 스코틀랜드에 갔다 왔던 얘기를 하다 보니 시간 가는 줄 몰랐습니다." },
    { kind: "paragraph", text: "칵테일이 정말 맛있었는데, 삿포로 마지막 날에 가서 이번 여행에서는 더 방문할 수 없는 데다가 자매점인 '나노 굴드'를 못 가본 게 참 아쉬웠습니다. 나중에 나노 펨토에 다시 가고 싶어서라도 삿포로에 한 번쯤은 방문할 것 같습니다." },
  ],
};
