import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-bar-proof",
  category: "bar",
  title: "바 프루프 — 시간이 멈춰 있는 것만 같은, 올드 보틀을 이용한 칵테일",
  dek: "'바 프루프'는 삿포로 스스키노역 근처 한 빌딩의 5층에 위치한 바로, 이전에 리뷰했던 나노 펨토(Bar nano femto)와 같은 건물에 위치해 있습니다.",
  publishedAt: "2025-01-22",
  hero: "/articles/sapporo-bar-proof/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223734088668",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-bar-proof/00.webp", width: 966, height: 1718 },
    { kind: "figure", src: "/articles/sapporo-bar-proof/01.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/sapporo-bar-proof/02.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "'바 프루프'는 삿포로 스스키노역 근처 한 빌딩의 5층에 위치한 바로, 이전에 리뷰했던 나노 펨토(Bar nano femto)와 같은 건물에 위치해 있습니다. 이 날은 나노 펨토가 만석이여서 프루프를 방문했었습니다." },
    { kind: "paragraph", text: "이 곳 프루프는 나이가 지긋한 사장님이 직접 메이킹을 해주시는데, 특이하게도 80~90년대의 올드 보틀으로 대부분의 칵테일을 만든다고 하십니다." },
    { kind: "paragraph", text: "여담으로 일본에는 아직까지도 80~90년대의 위스키, 꼬냑, 리큐르들을 쉽게 찾을 수 있는 편인데, 아마 산토리의 존재와 일본의 버블 호황기로 인해 그러지 않을까 짐작해봅니다." },
    { kind: "figure", src: "/articles/sapporo-bar-proof/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "첫 잔은 하이볼" },
    { kind: "paragraph", text: "대부분의 칵테일에 올드 보틀을 사용한다는 설명이 무색하게 하이볼은 현행 글렌리벳 12년으로 만들어주셨는데, 무난하게 맛있었습니다." },
    { kind: "paragraph", text: "다음 잔으로는 여행 당시에 빠져 있었던 '러스티 네일(Rusty Nail)'을 주문했는데, 이건 듀어스의 올드 보틀과 드람부이의 올드 보틀로 만들어주셨습니다." },
    { kind: "paragraph", text: "듀어스인데도 불구하고 위스키의 캐릭터가 죽지 않고, 드람부이와 적절한 밸런스를 이뤘던 게 인상적이 었습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-proof/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/sapporo-bar-proof/05.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "다음 잔을 주문하려고 백바를 둘러보니 멀리서 서던 컴포트의 올드 보틀이 보이길래 바로 '스칼렛 오하라(Scarlett O'Hara)'를 주문했습니다." },
    { kind: "paragraph", text: "서던 컴포트는 원래 40도가 넘는 리큐르였는데, 세월이 지나면서 도수가 떨어지면서 맛이 변했다는 얘기가 있었어서 항상 궁금했었습니다. 현재에 국내에 35도의 제품이 일반적으로 들어오고 있습니다." },
    { kind: "paragraph", text: "자극적이고 새콤달콤한 한 잔이라는 말로 정리될 수 있는데, 단 걸 그렇게 좋아하지 않는 저도 아주아주 맛있었습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-proof/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-bar-proof/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "올드 보틀로 마시는 김에 한 잔 더 마시자고 해서 시킨 '사이드카(Sidecar)'. 코앵트로와 꼬냑 모두 80년대의 것이었는데, 특이한 건 프라팡 VSOP를 사용한다는 점이었습니다." },
    { kind: "paragraph", text: "지금의 프라팡은 좀 섬세하고 여리여리한 면이 있어서 칵테일의 기주로 사용되는 경우를 본 적이 없는데, 80년대 프라팡을 니트로 마셔보지는 않았지만 현행과는 맛이 다른지 전혀 위화감이 없었습니다." },
    { kind: "paragraph", text: "프루프는 올드 보틀으로 칵테일을 메이킹하는 것에 비해서 가격이 그닥 비싸지는 않은데, 올드 보틀 칵테일에 관심이 있는 분들에게는 꼭 추천해드리고 싶습니다." },
    { kind: "paragraph", text: "다만, 접객에 있어서는 고객과 살짝 거리를 두는 듯한 이미지로, 딱 필요한 정도의 접객을 제공하는 곳이니 막 살갑게 말을 붙여주는 바를 선호하신다면 살짝 소외감을 느낄 수도 있겠습니다." },
  ],
};
