import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-the-whisky-tasting-room",
  category: "bar",
  title: "위스키 테이스팅 룸 — 많은 독립병입자 제품을 시음해보고 구매할 수 있는 리쿼샵",
  dek: "'위스키 테이스팅룸'은 삿포로의 스스키노역 근처에 위치한 보틀샵이며, 일본의 주류회사인 '스카치 몰트 판매 주식회사'에서 운영하고 있어서 독립병입자가 꽤나 많이 놓여져 있습니다.",
  publishedAt: "2024-11-13",
  hero: "/articles/sapporo-the-whisky-tasting-room/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223659384518",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "'위스키 테이스팅룸'은 삿포로의 스스키노역 근처에 위치한 보틀샵이며, 일본의 주류회사인 '스카치 몰트 판매 주식회사'에서 운영하고 있어서 독립병입자가 꽤나 많이 놓여져 있습니다." },
    { kind: "paragraph", text: "독립병입자 위스키 외의 특이점이라면 보틀샵 내부에서 유료로 시음이 가능하며, 시음한 주류를 바틀로 구매하면 구매한 주류의 시음료를 빼준다는 점입니다." },
    { kind: "paragraph", text: "독립병입자 같은 경우는 증류소 오피셜과 다른 경우가 꽤나 많고, 지뢰도 많은데 이렇게 시음 후 바틀을 구매할 수 있고, 한 잔 분량의 시음료를 빼준다는 게 장점이라 할 수 있죠." },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/01.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/02.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/03.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "스카치 몰트 판매 주식회사에서 운영하고 있는 만큼 해당 회사가 유통하는 독립병입자인 디스틸러리즈 콜렉션(Distilleries Collection), 더 몰트만(The Maltman), 쿠퍼스 초이스(Cooper's Choice), 하트 브라더스(Heart Brothers), 더 테이스터(The Taster), 위스키 스폰지(Whisky Sponge) 등의 제품이 상당히 많습니다." },
    { kind: "paragraph", text: "참고로 이 곳의 점장님이 삿포로 스스키노역 근처의 베키오(Shot Bar Vecchio)라는 바의 오너이신데, 그러다보니 이 바에도 독립병입자 제품이 많이 있습니다." },
    { kind: "paragraph", text: "저는 사실 이전에 스코틀랜드에서 마셔본 아일라 스폰지 킬달튼이 있는 사진만 보고 간 거였는데, 그건 몇 달 전에 이미 다 팔렸다고....심지어 들어오자마자 거의 바로 팔렸었다고 해서 구하지는 못했습니다. 아드벡에 셰리 캐스크니 그러려니....." },
    { kind: "paragraph", text: "그 외에 울프번(Wolfburn), 코츠월드(Cotswolds), 글렌파클라스(Glenfarclas)의 오피셜이나, 꼬냑, 럼, 보드카 등도 구비되어 있으며, 바로 옆에는 진 갤러리(The Gin Gallery)에서는 다양한 진을 경험할 수도 있습니다." },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "시음은 직원 분에게 얘기해서 자유롭게 할 수 있는데, 점포 내의 위스키는 거의 대부분 시음할 수 있으며, 이전에 판매하지만 보틀은 솔드아웃된 제품도 시음해볼 수 있습니다." },
    { kind: "paragraph", text: "추천을 받아볼 수도 있는데 직원분들이 몇 가지 보틀을 가져와서 꽤 자세하게 설명해주시고, 그 중에서 하나 고르는 식으로 추천을 받았습니다. 직원분들이 위스키에 대해서 꽤나 잘 아시니 추천 받아보시길 바랍니다." },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/05.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/06.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "저는 이틀에 걸쳐서 방문을 했었는데, 만족스러운 제품들이 꽤 있었습니다." },
    { kind: "paragraph", text: "먼저 고양이와 물범이 그려진 바틀은 올해 홋카이도 위스키 페스티벌에서 출시된 것들인데, 고양이는 클라이넬리쉬(추정), 물범은 아드벡(추정)이라고 합니다. 꽤나 좋은 퀄리티들이여서 고민하다가 아드벡을 구매했습니다." },
    { kind: "paragraph", text: "다음으로 아카이브(Archives)의 링크우드와 디스틸러리즈 콜렉션의 발메냑 이 둘 중에도 정말 고민을 많이 햇는데, 발메냑이 제가 딱 좋아하는 대추야자 캐릭터의 셰리 캐스크라서 발메냑을 구매했습니다." },
    { kind: "figure", src: "/articles/sapporo-the-whisky-tasting-room/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "구매하지는 않았지만, 디스틸러리즈 콜렉션의 윌리엄슨(Williamson) 13년 같은 경우는 아스팔트, 뜨거워진 고무타이어(...?) 같은 캐릭터가 나서 아주 재미있었습니다. 참고로 윌리엄슨은 라프로익의 티스푼 몰트입니다." },
    { kind: "paragraph", text: "그 외에 브라운 슈거의 클라렌든(Clarendon Estate)은 럼을 좋아하시는 분이라면 꼭 시음해보는 걸 권해드리는데, 69.1%라는 엄청난 고도수의 강력함과 자메이칸 럼 특유의 펑키함이 아주아주 매력적인 럼입니다. 관세만 아니었으면 한 병 샀을텐데...." },
    { kind: "paragraph", text: "사진에는 없지만 점포 내에서 숙성 중인 위스키도 볼 수 있는데, 하나는 시크릿 아일라, 하나는 시크릿 하이랜드라고 써져있습니다." },
    { kind: "paragraph", text: "이 중 아일라는 스카치 몰트 판매 주식회사에서 병입하는 저숙성 아드벡을 미즈나라 캐스크에서 추가 숙성한 것으로, 이것도 한 번 경험해 보는 걸 추천드립니다." },
  ],
};
