import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-bar-owl-and-rooster",
  category: "bar",
  title: "아울 앤 루스터 — 아마로, 진, 압생트 칵테일을 좋아한다면 여기로",
  dek: "'바 아울 앤 루스터'는 삿포로 스스키노역 근처 한 빌딩의 6층에 위치한 바로, 위스키보다는 칵테일이 아주 집중한 바이며, 저처럼 칵테일 덕후들이라면 아주 환장을 할만한 바입니다.",
  publishedAt: "2025-01-27",
  hero: "/articles/sapporo-bar-owl-and-rooster/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223740081893",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "'바 아울 앤 루스터'는 삿포로 스스키노역 근처 한 빌딩의 6층에 위치한 바로, 위스키보다는 칵테일이 아주 집중한 바이며, 저처럼 칵테일 덕후들이라면 아주 환장을 할만한 바입니다." },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/01.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/02.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/03.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "바는 바백에 진열되어 있는 보틀들을 보면 그 바의 성격을 유추할 수 있는데, 아울앤루스터에는 정말 많은 진과 아로마를 단번에 확인할 수 있고, 오른편으로 보면 압생트 분수 서브할 수 있는 유리병이 있습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "메뉴를 보면 바의 시그니처 메뉴들을 확인할 수 있는데, 이 메뉴들의 재료 설명만 봐도 칵테일 덕후들이 흥미로워할 만한 칵테일이 아주 많습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/05.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "첫 번째 잔으로는 시그니처 중 하나인 압생트 초콜릿을 주문했습니다. 압생트와 초콜릿의 조합이라니 칵테일을 받기 전부터 떨리는 조합입니다." },
    { kind: "paragraph", text: "의외로 압생트의 아니스, 허브 캐릭터가 초콜릿과 꽤 잘 어울린다는 느낌을 받았고, 압생트나 파스티스를 좋아하는 분들에게는 추천할 만한 한 잔입니다." },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/06.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "다음 잔으로는 샘 로스의 유명 칵테일인 페니실린을 변형한 아크틱 페니실린(Arctic Peniciline)을 주문했는데, 재료만 봐서는 정말 이게 페니실린 싶은 생각이 듭니다." },
    { kind: "paragraph", text: "홋카이도에 위치한 요이치 증류소의 위스키를 사용하는데, 아마 그런 이유로 이름을 이렇게 짓지 않았을까 싶습니다." },
    { kind: "paragraph", text: "색깔부터 페니실린이라고는 믿기지 않는 비주얼인데, 맛을 보면 모든 사람들이 납득할 수 있을 정도로 페니실린이 맞습니다." },
    { kind: "paragraph", text: "기본적인 페니실린 구조의 맛에 베리 등의 캐릭터가 추가된 느낌이며, 설명에 스파이시라고 쓰여 있긴 했는데, 저는 개인적으로 그 부분은 크게 느끼진 못했습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-owl-and-rooster/07.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "마지막으로는 평소에 궁금했었던 그랑 클라시코(Gran Classico Bitter)가 눈에 띄어서 이걸로 칵테일을 한 잔 만들어달라고 부탁드렸습니다." },
    { kind: "paragraph", text: "네그로니 류의 칵테일을 만들어주셨는데, 아마 메뉴의 럼 네그로니를 만들어주신 것 같습니다. 아주 깊고, 초콜레틱한 느낌의 네그로니로 아주 맛있게 마셨습니다. 캄파리 네그로니보다 맛있는 듯" },
    { kind: "paragraph", text: "아울 앤 루스터는 전형적인 일본의 오센틱 바라기보다는 좀 더 믹솔로지 스타일에 가까운 바로, 시그니처와 클래식 변형 칵테일이 아주 돋보입니다." },
    { kind: "paragraph", text: "칵테일, 아마로, 압생트, 진 등에 관심이 있는 분들에게 아주아주 강추드리며, 개인적으로 이곳에서는 클래식 보다 시그니처 위주로 마셔보는 걸 추천드립니다." },
  ],
};
