import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-bar-brora",
  category: "bar",
  title: "브로라 — 얼큰하게 취한 사장님이 반겨주는 바",
  dek: "'바 브로라'는 삿포로 스스키노역 근처 한 빌딩의 3층에 위치해 있는 바로, 사장님이 혼자서 운영하는 곳인데, 몇몇 블로그나 리뷰에서도 볼 수 있듯이 사장님이 기분이 좋으면 손님 응대를 하면서 술을 마셔 취하는 특이한 바입니다.",
  publishedAt: "2024-12-29",
  hero: "/articles/sapporo-bar-brora/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223708461782",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-bar-brora/00.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-bar-brora/01.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "'바 브로라'는 삿포로 스스키노역 근처 한 빌딩의 3층에 위치해 있는 바로, 사장님이 혼자서 운영하는 곳인데, 몇몇 블로그나 리뷰에서도 볼 수 있듯이 사장님이 기분이 좋으면 손님 응대를 하면서 술을 마셔 취하는 특이한 바입니다." },
    { kind: "figure", src: "/articles/sapporo-bar-brora/02.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-bar-brora/03.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-bar-brora/04.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-bar-brora/05.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "이곳 브로라는 백바가 꽤 볼만한데, 처음 보는 보틀이 정말 많았고, 특히 레이디번(Ladyburn)의 오피셜 보틀은 여기서 처음 봤습니다." },
    { kind: "paragraph", text: "일단은 하이볼부터" },
    { kind: "paragraph", text: "첫 잔으로 당연히(?) 하이볼을 부탁드렸는데, 아유 그러면 역시 벤로막이지 하고는 바로 앞에 있는 엄청 큰 사이즈의 벤로막(Benromach) 10년으로 만들어주셨습니다." },
    { kind: "paragraph", text: "그렇게 크게 기억나는 맛은 아니었기는 한데, 무난무난하게 괜찮은 하이볼이었던 것 같습니다. 뭔가 이 보틀에 대해서 자랑을 하셨는데, 내용은 기억이 안나네요." },
    { kind: "figure", src: "/articles/sapporo-bar-brora/06.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "하이볼을 마시면서 사장님과 스코틀랜드에 갔다 온 얘기를 하다가 스프링뱅크 중에서는 헤이즐번을 좋아한다고 하니 헤이즐번(Hazelburn) 핸드필을 추천해주셨습니다." },
    { kind: "paragraph", text: "맛은 이번 삿포로 여행 중에 가장 별로였던 위스키였던...이와 별개로 저는 개인적으로 스프링뱅크 증류소의 핸드필은 일본에서 잔에 2만원이 넘어간다면 그다지 추천드리지는 않을 것 같습니다." },
    { kind: "paragraph", text: "일단 스프링뱅크 증류소에서의 가격에 비해서 너무 뻥튀기가 되어있는데다가, 증류소에 가보니 캐스크에서 바로 뽑아주는 핸드필이 아니라 여러 원액을 배팅한 것을 보틀링해주는 걸 봤어서 일정 가격 이상이면 굳이 싶습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-brora/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "계속되는 나 홀로 아드벡 데이" },
    { kind: "paragraph", text: "다음 잔으로는 무카와에서 보고 궁금했었던 아드벡(Ardbeg) 독립병입된 보틀을 마셔봤습니다. 이 시리즈는 일본의 위스키 수입사인 루더(The Ultimate Spirits Rudder Ltd)의 첫 독립병입 시리즈인 'Art Session'의 첫 번째 릴리즈라 합니다." },
    { kind: "paragraph", text: "타는 듯한 피트감이 꽤 강하고, 살짝의 달달함+시트러스의 캐릭터를 느낄 수 있었는데, 다른 캐릭터를 더 느끼기에는 피트감이 조금 거슬렸던 것 같습니다." },
    { kind: "paragraph", text: "마시면서 사장님과 이런저런 얘기도 하고, 같이 짠도 하기도 하고, 꽤나 재미있게 즐겼습니다." },
    { kind: "paragraph", text: "개인적으로 이 곳은 일본어 소통이 어느정도 되시는 분들이나, 위스키를 좋아하시고 가격에 대해서도 어느정도 파악이 쉬운 분들에게 추천을 드리고 싶습니다. 이 곳의 가격이 저렴한 편은 아니기도 하니까요." },
    { kind: "paragraph", text: "※주의점?" },
    { kind: "paragraph", text: "이 곳 리뷰를 보면서 '혐한'이라는 리뷰를 하나 봤는데, 제가 한국인이라 밝히면서 한국 얘기도 조금 했는데 저는 그런 느낌은 못 받았던 것 같습니다." },
    { kind: "paragraph", text: "다만, 본인이 일본어 소통이 어려우신 분들은 가게의 단골이 있을 때 가신다면 살짝 소외된 느낌을 느끼실 수는 있을 것 같습니다. 사장님이 취하시면 텐션이 올라가니 아무래도 접객에 갭 차이가 있을 수 밖에 없겠죠." },
    { kind: "paragraph", text: "또한, 사장님이 술을 마시면서 접객을 하는 경우가 왕왕 있는 것 같은데, 그런 분위기를 선호하지 않는 분들에게는 그다지 추천드리지는 못하겠습니다." },
  ],
};
