import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-shot-bar-vecchio",
  category: "bar",
  title: "샷 바 베키오 — 더 위스키 테이스팅 룸에서 여기까지 왔다!",
  dek: "'샷 바 베키오(Shot Bar Vecchio)'는 삿포로 시내 스스키노역 근처 빌딩의 7층에 위치한 바로, 이전에 소개한 바틀샵 '더 위스키 테이스팅 룸(The Whisky Tasting Room)'의 점장이자, 일본의 주류 수입회사인 스카치 몰트",
  publishedAt: "2024-12-27",
  hero: "/articles/sapporo-shot-bar-vecchio/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223706937101",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/00.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/01.webp", width: 966, height: 544 },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/02.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "'샷 바 베키오(Shot Bar Vecchio)'는 삿포로 시내 스스키노역 근처 빌딩의 7층에 위치한 바로, 이전에 소개한 바틀샵 '더 위스키 테이스팅 룸(The Whisky Tasting Room)'의 점장이자, 일본의 주류 수입회사인 스카치 몰트 판매 주식회사의 일원이자, 홋카이도 바텐더 협회의 회장님이 운영하는 바입니다." },
    { kind: "paragraph", text: "워낙 겸임하는 게 많으셔서 이 분한테서 명함을 서너 장은 받은 것 같습니다." },
    { kind: "paragraph", text: "메뉴는 따로 없는 것 같고, 역시 스카치 몰트 판매 주식회사에서 수입하는 위스키 스폰지(Whisky Sponge)의 시리즈라던가, 병입하는 더 테이스터(The Taster)의 시리즈 등이 눈에 띕니다." },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "사실 더 위스키 테이스팅 룸을 거쳐서 여기까지, 아니 삿포로까지 오게 된 계기는 이 녀석입니다." },
    { kind: "paragraph", text: "'아일라 스폰지 킬달튼(Islay Sponge Kildalton)'" },
    { kind: "paragraph", text: "독립병입 위스키인 위스키 스폰지의 시리즈 중에 하나로, 독병으로는 일본에서도 드물게 아드벡 증류소의 원액 중에서도 셰리 캐스크에서 숙성한 제품입니다." },
    { kind: "paragraph", text: "스코틀랜드에서 마시고 정말 맛있어서 여기저기 찾아보고 있다가 올해 7월(?)까지는 더 위스키 테이스팅 룸에 있다는 걸 확인하고, 재취업이 결정되자마자 삿포로행 티켓을 끊었는데...." },
    { kind: "paragraph", text: "더 위스키 테이스팅 룸에서 수입하고 얼마 안 돼서 다 팔렸다는 얘기를 듣고, 지푸라기라도 잡는 심정으로 사실은 점장님의 바인 베키오를 찾아온 거였는데, 드디어 이렇게 만나게 됐습니다." },
    { kind: "paragraph", text: "가격은 원가를 생각하면 너~~무 비싸니, 정말 궁금한 분들만 드시는 걸 추천드립니다. 저는 가격 때문에 하프로만 마신.... 그래도 맛은 확실합니다." },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/05.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "일본 각지에서는 진(Gin), 럼 등을 생산하는 곳이 정말 많은데, 홋카이도에도 위스키 증류소 이외에 진 증류소가 꽤 있습니다." },
    { kind: "paragraph", text: "그래서 홋카이도의 진으로 진 토닉을 추천해달라고 부탁드렸는데, 오호로(Ohoro)라는 진으로 토닉과 탄산수의 양을 반반으로 해서 만들어주셨습니다. 아마도 진의 캐릭터를 좀 더 느낄 수 있게 하려고 해서인 것 같습니다." },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-shot-bar-vecchio/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "그 외에도 사장님과 이런저런 얘기를 하다가 올해 스코틀랜드를 갔다 온 이후로 브룩라디를 좋아하게 됐다는 얘기를 하게 됐고, 의식의 흐름으로 하이볼 한 잔과 위스키 한 잔을 추천받아서 마셨습니다." },
    { kind: "paragraph", text: "독립병입자인 엘리먼츠 오브 아일라(Elements of Islay) 시리즈 중에서 브룩라디의 다섯번째 배치로, 이 시리즈는 라벨을 보면 증류소의 이름을 유추할 수 있게 해두었습니다. 하이볼로 마시니 아주 기똥차네요." },
    { kind: "paragraph", text: "마지막으로 일본 위스키 수입 회사인 스카치 몰트 판매 주식회사의 독립병입 시리즈인 더 테이스터(The Taster) 중에서도 브룩라디를 추천해 주셔서 한 잔 마셨습니다. 이건 향긋한 풀 내음+벌꿀의 캐릭터가 꽤나 인상적인 한 잔이었습니다." },
    { kind: "paragraph", text: "이 테이스터 시리즈는 일본의 주류 애호가가 선택한 배럴을 보틀링 한 것으로, 일본에서는 꽤 인기가 있는 건지 찾아보면 대부분 품절이거나 물량을 찾기가 쉽지 않을 정도이니 눈에 띄면 한 번 정도는 마셔볼만합니다." },
    { kind: "paragraph", text: "베키오는 칵테일보다는 위스키를 주로 드시는 분들께 추천드리고 싶은 바로, 더 위스키 테이스팅 룸에 들렀다가 가보는 건 어떨까 싶습니다." },
  ],
};
