import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sapporo-bar-farben",
  category: "bar",
  title: "파벤 — 크래프트 칵테일을 즐길 수 있는 작고 소중한 바",
  dek: "「바 파벤」은 삿포로 스스키노역 근처 한 빌딩의 6층에 위치한 바로, 오너 바텐더인 '야자키 신(Yazaki Shin)' 혼자서 운영하는 소규모의 바입니다.",
  publishedAt: "2025-02-08",
  hero: "/articles/sapporo-bar-farben/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223752969062",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/sapporo-bar-farben/00.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/sapporo-bar-farben/01.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "「바 파벤」은 삿포로 스스키노역 근처 한 빌딩의 6층에 위치한 바로, 오너 바텐더인 '야자키 신(Yazaki Shin)' 혼자서 운영하는 소규모의 바입니다." },
    { kind: "paragraph", text: "'야자키 신'은 홋카이도 니세코의 '바 규+(Bar Gyu+)', 런던 등지에서 바텐더 생활을 한 후, 2024년 8월 6일 현재의 파벤을 오픈했다고 합니다. 제가 방문한 10월 말 기준으로는 오픈한 지 2달이 됐었네요." },
    { kind: "paragraph", text: "저는 이전에 방문했던 '아울&루스터(Bar Owl&Rooster)'에서 최근 생긴 괜찮은 바라고 추천받아서 방문하게 됐습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/02.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "파벤은 메뉴나 백 바만 살짝 확인해도 위스키보다는 칵테일에 좀 더 중점을 둔 바이며, 진이나 오드비의 종류가 꽤 있는 바입니다. 추천해 줬던 아울&루스터처럼 믹솔로지적인 성향이 뚜렷한 느낌입니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "첫 잔은 역시 하이볼" },
    { kind: "paragraph", text: "파벤에는 위스키의 종류가 그렇게 많은 편은 아닌데, 하이볼 기주로 주라 10년, 부나하벤 12년을 추천해 주셔서 주라로 한 잔 마셨습니다. 뭔들 맛없겠냐만, 개인적으로 주라 10년으로 만드는 하이볼을 꽤 좋아하는 편입니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "파벤의 시그니처 칵테일들은 꽤 재미난 조합을 가지는 것들이 있는데, 그중 페어 앤 압생트 토닉(Pear and Absinthe Tonic)과 마스카포네 앤 커피 디저트 칵테일(Mascarpone and Coffee Dessert Cocktail)을 마셔봤습니다." },
    { kind: "paragraph", text: "인상에 깊었던 「페어 앤 압생트 토닉」은 기주를 배로 만든 브랜디로 하고, 거기에 압생트·로즈 플라워 워터를 넣고, 토닉 워터에 탄산수를 넣는 소닉 스타일의 칵테일입니다." },
    { kind: "paragraph", text: "아직 배로 만든 브랜디를 마셔본 적이 없어서 시켰는데, 호불호는 엄청나게 갈릴 것 같으면서도 아주 재미있는 맛으로, 플로럴 하면서도 상당히 섬세하다는 느낌을 받았습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/05.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "클래식 칵테일인 김렛도 마셔봤는데, 이전에 베키오에서 마셨던 것도 그렇고 확실히 삿포로의 칵테일은 다른 지역과는 맛이 다른 것 같습니다." },
    { kind: "paragraph", text: "최근 몇 년간 유행해 온 하드 셰이킹을 하지 않고 만드는 것처럼 보이는데, 그래서 그런지 꽤나 쥬시하고, 맛이 강한 칵테일이 만들어집니다. 국내에서는 최근에 보기 힘든 스타일이라 오히려 신선한 느낌을 받았습니다." },
    { kind: "paragraph", text: "백 바를 보다가 「닛카 코페이 진(Nikka Coffey Gin)」이 보였는데,  아무래도 홋카에도에 닛카의 증류소가 있기도 했고, 평소에 궁금하기도 해서 바로 진 토닉을 부탁드렸습니다." },
    { kind: "paragraph", text: "이 닛카 코페이 진으로 만든 진 토닉도 정말 재밌었는데, 지금까지 제가 마셔봤던 진과는 꽤나 다른 유니크한 캐릭터를 가지고 있었고, 찌르는 듯한 시소 그리고 아마도 고수의 캐릭터가 꽤나 밝고 강렬하게 느껴지는 게 아주 상쾌한 진 토닉이었습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/06.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "저는 4박 5일의 일정 중에 3번을 파벤에 방문하면서 사장님이랑 친해지게 됐는데, 마지막 날이라 아쉬워하니 하쿠슈 미즈와리 한 잔과 타케츠루로 만든 롭로이(또는 맨하탄)의 변형을 서비스로 만들어주셨습니다. 조금 취했어서 한 잔만 서비스였나 기억이..." },
    { kind: "paragraph", text: "타케츠루 마사타카가 지은 요이치 증류소가 있는 홋카이도에서 타케츠루로 만드는 칵테일이 작별 선물이라니, 정말이지 홋카이도의 바텐더라 할 수 있는 꽤나 운치 있는 선물이 아닐까 싶습니다." },
    { kind: "figure", src: "/articles/sapporo-bar-farben/07.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "파벤에서의 좋았던 기억이 하나 더 있는데, 계산하고 나가기 전에 사장님이 바텐더스 핸드셰이크(Bartender's Handshake)라고 하면서 페르넷 브랑카를 한 잔씩 꼭 주었던 점이었습니다." },
    { kind: "paragraph", text: "이 바텐더스 헨드셰이크라는 게 일본에서는 잘 안 하는 서비스인데, 역시 서양 쪽 바 문화의 영향을 받았다는 걸 짐작해 볼 수 있네요." },
    { kind: "paragraph", text: "파벤은 사장님 혼자서 운영하는 작은 바로, 처음 방문하더라도 은근하게 환영받는다는 느낌을 받았습니다. 아마 사장님이 영어도 가능하실 거라 일본어가 안되더라도 소통에 크게 문제는 없을 듯싶으니 가볍게 방문해서 한 잔 하는 것도 좋을 것 같습니다." },
  ],
};
