import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep0",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep0 — 아일라, 피트 위스키 축제가 열리는 아일라로 가자",
  dek: "아일라 여행은 너무나도 급작스럽게도 장난삼아 한 말이 발단으로 시작됐다.",
  publishedAt: "2024-08-12",
  hero: "/articles/scotland-whisky-ep0/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223545245219",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "quote", text: "오, 아일라에서는 위스키 축제를 한다는데, 유럽 여행 함 가실?" },
    { kind: "paragraph", text: "아일라 여행은 너무나도 급작스럽게도 장난삼아 한 말이 발단으로 시작됐다. 2023년 3월 즈음에 아일라에서는 5월 마지막 주 ~ 6월 첫째 주에 열리는 위스키 축제가 있다는 걸 알게 됐고, 조금씩 위스키에 관심을 갖게 된 친구에게 물어본 것이 시작." },
    { kind: "paragraph", text: "그렇게 2024년 아일라에서 열리는 페스 아일(Feis Ile) 기간을 알아보고, 비행기표를 속전속결로 예약했다. 중간 과정을 뛴 것 같지만 놀랍게도 중간 과정은 없었는걸...." },
    { kind: "paragraph", text: "그러고 나서 곧바로 숙소를 예약하지 않은 걸 아직까지도 후회한다." },
    { kind: "paragraph", text: "아일라에서 숙박을 해결할 수 있는 방법은 아주 다양하다. 호텔, 코티지, 도미토리, B&B, 캠핑카, 텐트가 그 방법들인데, 먼저 캠핑카와 텐트는 일단 제외하고, 코티지는 단체로 갈 거 아니면 너무 비싸니 다른 것을 찾아보자." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0/00.webp", width: 837, height: 837, caption: "아일라 섬 / 출처: Google Map" },
    { kind: "paragraph", text: "일단 아일라에서 그래도 큰 마을은 보모어와 포트 엘런 지역이다. 여기서 호텔과 B&B를 찾아볼 수 있고, 생각보다 숙소가 많은 편이다. 그 외에 포트 샬롯 지역에는 유스호스텔이 있는데, 여기가 제일 가격적으로는 싸다." },
    { kind: "paragraph", text: "가격은 코티지>>호텔>B&B>유스호스텔 순" },
    { kind: "paragraph", text: "숙소를 여기저기 알아보면서 아직 가기까지 1년 넘게 남았네~하고 여유 부리고 있었는데, 가기 10개월 전에야 가는 날짜 세기가 지루해서 숙소에 예약 가능 여부를 물어봤다." },
    { kind: "paragraph", text: "대강 열 곳이 넘는 곳에 메일을 보냈는데, 충격적이게도 축제 기간에는 B&B를 운영하지 않는 곳도 있거니와 이미 방이 다 찼다는 답변만 받았다. 축제 기간이라는 것과 전 세계 술쟁이들이 모이는 축제인 걸 간과한 탓에 아일라 가서 텐트 치고 자게 생긴 것이다." },
    { kind: "paragraph", text: "여담으로 축제 기간에는 아일라 주민들이 축제 준비를 도와주거나 스태프로 참여하는 경우가 있어서 B&B를 축제 기간 동안 운영하지 않는 경우가 많다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "'숙소를 예약 못했더니 아일라 섬에서 텐트 치기라는 이색 경험을 하게 됐네!'라는 원영적 사고를 친구와 하고 있던 참에, 다행히도 보모어에 위치한 보모어 호텔에서 2박 3일은 가능하다고 해서 원래 계획에서 하루를 줄이게 되었다." },
    { kind: "paragraph", text: "남자 두 명이서 바다가 보이는 스위트룸을 1박에 230파운드로 사용하게 됐고.... 아직까지도 3박 4일 일정을 계획했는데 하루가 줄어든 게 너무 아쉽다." },
    { kind: "paragraph", text: "혹시라도 페스 아일 기간에 아일라를 방문하려고 계획하는 분들은 이 글을 보자마자 숙소를 알아보시길...." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "아일라 섬을 들어가는 방법으로는 글래스고 공항에서 출발하는 로건에어(Logan Air)의 경비행기와 케나크레이그(Kennacraig)와 포트 에스케이그(Port Askaig) / 포트 엘런(Port Ellen)을 연결해 주는 페리가 있다." },
    { kind: "paragraph", text: "1. 경비행기" },
    { kind: "paragraph", text: "- 빠르게 갈 수 있음 (약 30분)" },
    { kind: "paragraph", text: "- 이른 시간에 섬에 들어가서 하나라도 더 증류소 체험이 가능함" },
    { kind: "paragraph", text: "- 경비행기를 경험할 수 있음(?)" },
    { kind: "paragraph", text: "- 날씨에 따라서 결항될 위험이 높음" },
    { kind: "paragraph", text: "2. 페리" },
    { kind: "paragraph", text: "- 저렴함" },
    { kind: "paragraph", text: "- 글래스고(뷰캐넌 버스터미널)에서 케나크레이그까지 가서 페리로 갈아타야 함" },
    { kind: "paragraph", text: "- 버스와 페리 시간을 잘 맞춰야 함" },
    { kind: "paragraph", text: "- 입항 당일에는 증류소 체험할 시간이 안될 수 있음" },
    { kind: "paragraph", text: "- 페리 스케줄 사이트" },
    { kind: "paragraph", text: "개인적으로 섬에 들어갈 때는 경비행기를, 섬에서 나갈 때는 페리를 이용하는 게 좋은 것 같다. 어차피 마지막 날에는 페리 시간 맞추느라 증류소 방문하기가 좀 어렵기 때문에." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "아일라 내부에서 이동할 때는 생각보다 많은 이동 수단이 존재하니 시간과 예산에 맞춰서 이용하는 걸 추천한다." },
    { kind: "paragraph", text: "1. 버스" },
    { kind: "paragraph", text: "- 아일라 섬 내 버스 스케줄" },
    { kind: "paragraph", text: "- 버스가 적고, 시간대마다 코스나 정류장이 다를 수 있으니 주의" },
    { kind: "paragraph", text: "- 꽤 이른 시간부터 있고, 막차가 오후 5~6시 즈음이니 주의" },
    { kind: "paragraph", text: "- 4월 경에 스케줄이 변경되니 주의" },
    { kind: "paragraph", text: "2. 택시" },
    { kind: "paragraph", text: "- 비싸지만 가장 편한 이동 수단" },
    { kind: "paragraph", text: "- 공항 갈 때나 부나하벤 같은 버스가 안 가는 증류소들 방문 시 추천" },
    { kind: "paragraph", text: "- 메일이나 전화로 예약해서 이용해야 함" },
    { kind: "paragraph", text: "- 아예 위스키 투어를 해주는 경우도 있음" },
    { kind: "paragraph", text: "3. 자전거" },
    { kind: "paragraph", text: "- 가장 맘 편한 이동 수단" },
    { kind: "paragraph", text: "- 금액이 합리적인 편" },
    { kind: "paragraph", text: "- 방문하려는 코스에 따라서 배터리가 다르니 주의" },
    { kind: "paragraph", text: "4. 히치하이킹" },
    { kind: "paragraph", text: "- 축제 기간에는 차가 많아서 가능할지도?" },
    { kind: "paragraph", text: "5. 렌터카" },
    { kind: "paragraph", text: "- 안 해봐서 잘 모르지만, 아마 글래스고나 에든버러에서 렌트해서 페리 타고 입항해야 하는 걸로 알고 있음" },
  ],
};
