import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep14",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep14 — 스프링뱅크 증류소 샵과 워시백 바",
  dek: "스프링뱅크 증류소(Springbank Distillery)는 스코틀랜드의 캠벨타운에 위치해 있으며, 스프링뱅크·롱로우·헤이즐번을 생산하고 있는 증류소이다.",
  publishedAt: "2024-10-09",
  hero: "/articles/scotland-whisky-ep14/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223612719499",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep14/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "스프링뱅크 증류소(Springbank Distillery)는 스코틀랜드의 캠벨타운에 위치해 있으며, 스프링뱅크·롱로우·헤이즐번을 생산하고 있는 증류소이다. 증류소는 오전 10시부터 오픈하며, 일요일에는 문을 닫는다." },
    { kind: "paragraph", text: "우리가 증류소를 방문한 날은 월요일이었는데, 월요일 아침 9시 40분 정도였는데도 우리 앞에 8명 정도가 줄을 서고 있었다." },
    { kind: "paragraph", text: "사실 우리가 방문하기 약 2주 전에 캠벨타운에서 몰츠 페스티벌을 했어서 그 때 릴리즈된 바틀과 증류소에서만 구매할 수 있는 일명 '케이지 바틀'을 구매하러 온 사람들이 대부분이었다." },
    { kind: "paragraph", text: "케이지 바틀은 증류소 입구 바로 왼쪽의 증류소 샵에 들어가자마자 볼 수 있는데, 스프링뱅크 제품군을 아주 저렴한 가격으로 구매할 수 있어서 인기가 높은 제품이다. 가격은 숙성년도에 따라서 나뉘는데, 첫 번째 사진에서 볼 수 있듯이 꽤나 싼 편이다." },
    { kind: "paragraph", text: "케이지 바틀은 1인당 일주일에 하나만 구매할 수 있다고 써져있으며, 한 번 들여놓은 바틀이 모두 판매되어야만 새로운 바틀을 채워준다. 우리가 있을 때는 한 번 다시 채워졌으니 아마 하루에 두 번 정도는 채워지지 않을까 싶다." },
    { kind: "paragraph", text: "다만, 고숙성은 보기가 쉽지 않은 편인 듯. 우리가 갔을 때는 고숙성은 없었어서 나는 헤이즐번 셰리 캐스크 8년 숙성을 구매했고, 친구는 롱로우 버번 캐스크를 구매했다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "케이지 바틀에서 왼쪽으로 가서 증류소 샵의 한쪽을 보면 완전히 하나의 작은 스프링뱅크 박물관이라 할 수 있다. 지금까지 출시했던 바틀들을 구경해 볼 수 있는데, 평생 한 번쯤은 마셔볼 수 있을까 싶은 바틀들이 즐비하다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/03.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "반대편으로 가보면 증류소 관련 굳즈와 위스키를 판매하고 있다. 우리가 갔을 때는 고숙성은 없었고, 방문 전에 열렸던 캠벨타운 몰츠 페스티벌에서 릴리즈된 제품들을 볼 수 있었다. 그 중 롱로우 16년은 사서 여행 중에 마셨는데, 이게 정말 맛있었다." },
    { kind: "paragraph", text: "둘러보다 보면 세 번째 사진처럼 스프링뱅크, 롱로우, 헤이즐번, 킬커란이 들어있는 큰 유리 디스펜서을 볼 수 있는데, 핸드필(?)이었던 걸로 기억한다." },
    { kind: "paragraph", text: "설명으로는 한 병 용량에 못미쳐서 남는 원액들이나 미출시 원액을 계속해서 채워주는 것 같다. 이렇게 말하면 뭔가 남은 원액들 처리용 술인가 싶은데, 이 핸드필 제품들도 꽤나 맛있었다." },
    { kind: "paragraph", text: "이 정도면 증류소 샵에서의 볼 일은 다 끝난다. 이제 샵에서 나와서 몇 발자국 직진하면 스프링뱅크 증류소에 딸려 있는 '워시백 바(Washback Bar)'에 도착하게 된다." },
    { kind: "quote", text: "워시백 바 (Washback Bar)" },
    { kind: "paragraph", text: "워시백 바에서는 스프링뱅크 증류소의 제품군과 킬커란을 아주 저렴한 가격에 마셔볼 수 있다. 우리가 갔을 때는 많은 제품이 비워진 상태였는데, 마침 운나쁘게도 우리가 간 다음날에 메뉴를 개편한다고 하더라." },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/05.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "먼저 마셔봤던 캠벨타운 몰츠 페스티벌 스프링뱅크 증류소 오픈데이의 헤이즐번 8년과 스프링뱅크 10년은 솔직히 그렇게 인상에 남는 맛은 아니었고, 나중에 바틀로 사서 마셔 본 롱로우 16년은 정말 맛있었다." },
    { kind: "paragraph", text: "그 외에도 스프링뱅크 로컬발리 9년, 로컬 발리 8년, 팔로 코르타도 10년, 18년, 25년을 마셔봤는데, 친구와 공통적으로 말한 게 스프링뱅크는 저숙성과 버번 캐스크 위주가 맛있다는 점이었다. 둘 다 셰리 캐스크를 그렇게 선호하는 편이 아니기도 하고." },
    { kind: "paragraph", text: "개인적으로는 로컬발리 8년, 9년과 팔로 코르타도가 이 중에는 제일 괜찮았고, 팔로 코르타도를 주문할 때 증류소 직원이 엑설런트 초이스라고 했던 게 기억에 남는다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep14/07.webp", width: 966, height: 1288 },
  ],
};
