import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep3",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep3 — 낭만 넘치는 브룩라디 증류소 웨어하우스 테이스팅 투어",
  dek: "보모어에서 브룩라디 증류소(Bruichladdich Distilley)까지는 버스로 약 20분가량이 소요되는데, 해안선을 따라 달리는 버스에서 바깥 풍경과 건너편에서 작게나마 보이는 브룩라디 증류소를 보고 있으면 두근거리기 마련이다.",
  publishedAt: "2024-08-16",
  hero: "/articles/scotland-whisky-ep3/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223550131652",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep3/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "보모어에서 브룩라디 증류소(Bruichladdich Distilley)까지는 버스로 약 20분가량이 소요되는데, 해안선을 따라 달리는 버스에서 바깥 풍경과 건너편에서 작게나마 보이는 브룩라디 증류소를 보고 있으면 두근거리기 마련이다." },
    { kind: "paragraph", text: "우리가 탔던 버스는 브룩라디까지 아무도 타지 않았고, 기사님은 \"오늘 너네가 버스 전세 냈네!\"라며 너스레를 떨었고, 지나치는 사람들은 손을 흔들며 환호했다. 이른 아침부터 다들 축제로 들뜬 분위기." },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "브룩라디에 도착하기 전에 식사를 하지 않았다면 증류소 옆의 미니 마켓에서 때우는 걸 추천한다. 영국 커피는 정말 맛없었는데, 샌드위치는 꽤 맛있더라." },
    { kind: "paragraph", text: "이날의 첫 끼를 빠르게 해치우고 브룩라디 투어 전에 증류소 샵을 보러 갔다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/03.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "증류소 샵은 이것저것 판매하고 있었고, 하이라이트는 역시 올해 축제 바틀이었다. 축제 바틀로는 브룩라디, 포트샬롯, 옥토모어, 발린치가 각각 나왔는데, 옥토모어는 500미리 325파운드라는 가격으로 말문을 막히게 했다." },
    { kind: "paragraph", text: "물론 올해 옥토모어 페스 아일 바틀은 쉬라 캐스크에서 12년을 숙성한 것으로, 아마 현재까지 나온 증류소 오피셜 옥토모어 중에서 가장 숙성이 길기는 하다. 그렇지만 500미리에 325파운드...." },
    { kind: "paragraph", text: "옥토모어는 깔끔하게 포기하고, 발린치가 세컨 필 셰리 벗 17년 숙성인데 80파운드였고(이것도 500미리....), 시음해 보고 이걸 샀는데 정말 맛있어서 후회는 없다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/04.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "증류소 샵에서 투어 시간이 되면 코피타 잔을 주면서 본격적인 투어가 시작된다. 우리는 웨어하우스 투어를 신청했는데, 꼭 반드시 이 투어를 하는 걸 추천한다. 웨어하우스에서 릴리즈되지 않는 브룩라디, 포트 샬롯, 옥토모어를 한 잔씩 맛볼 수 있는 투어기 때문이다." },
    { kind: "paragraph", text: "위스키는 이런 식으로 캐스크에서 바로바로 빼서 잔에 따라준다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/05.webp", width: 966, height: 1288, caption: "바이알은 요청하면 무료로 준다." },
    { kind: "paragraph", text: "이날의 베스트는 옥토모어였는데, 14년 소테른 캐스크 숙성이었다. ppm은 110이었나 했는데, 피트감이 전혀 강하지 않고, 달달한 소테른 캐스크의 캐릭터와 고소한 보리의 캐릭터와 함께 느껴지는 것이 지금까지 마신 위스키 top3에 들었다." },
    { kind: "paragraph", text: "물론 아일라 섬에서, 증류소의 웨어하우스에서 마셨다는 점과 증류소 스태프의 낭만 넘치는 대사를 들은 것도 영향이 있었을 것 같다." },
    { kind: "quote", text: "이 세 위스키를 좋아하되, 사랑에 빠지지는 마세요." },
    { kind: "quote", text: "지금 여기서만 마실 수 있으니" },
    { kind: "paragraph", text: "이러는데 맛이 없을 수가 있을까? 듣는 순간 투어에 참여한 모든 사람이 감탄을 내뱉었고, 그 순간부터는 낭만에 취하는 느낌이었다." },
    { kind: "paragraph", text: "여담으로, 투어 안내를 해준 스태프는 '루비'라는 분이었는데, 우리가 한국에서 왔다고 하니 이 분이 이전에 아드벡에서 일했었다면서 화심주조의 오수민 대표님이 잘 있냐며 보고 싶다고 하더라." },
    { kind: "paragraph", text: "마지막으로 시음과 관련한 팁을 하나 공유하자면, 기본적으로 브룩라디 증류소에는 테이스팅 공간이 없다." },
    { kind: "paragraph", text: "다만, 증류소 샵의 계산대 쪽에서 직원에게 뒤편의 위스키들을 시음해 볼 수 있는지 물어보면 시음을 도와준다. 딱히 제한도 없어서 이것저것 꼭 마셔보시길(무한으로 즐겨요)." },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/06.webp", width: 966, height: 1287 },
    { kind: "figure", src: "/articles/scotland-whisky-ep3/07.webp", width: 966, height: 1288, caption: "주섬주섬 꺼내든 건 발린치아름다운 하늘색의 브룩라디를 추억하며" },
  ],
};
