import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep8",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep8 — 페스 아일의 피날레, 스펙타귤러한 아드벡 증류소의 서커스",
  dek: "올해 페스 아일(Feis Ile)의 마지막 오픈 데이는 아드벡 데이(Ardbeg Day)로, 아드벡 증류소에서는 서커스를 주제로 축제를 진행했고, 한국에서도 아드벡 스펙타큘러 행사를 진행하기도 했다.",
  publishedAt: "2024-08-23",
  hero: "/articles/scotland-whisky-ep8/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223557978077",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep8/00.webp", width: 966, height: 644 },
    { kind: "paragraph", text: "올해 페스 아일(Feis Ile)의 마지막 오픈 데이는 아드벡 데이(Ardbeg Day)로, 아드벡 증류소에서는 서커스를 주제로 축제를 진행했고, 한국에서도 아드벡 스펙타큘러 행사를 진행하기도 했다." },
    { kind: "paragraph", text: "오전 10시에 오픈이라 9시 반 정도까지 갔는데, 이미 줄이 엄청 서있었다. 코스튬을 입고 온 사람들, 방송국 카메라의 등장, 긴 오픈런 줄임에도 즐거워하는 사람들까지 축제는 축제였다." },
    { kind: "paragraph", text: "10시를 조금 넘긴 시간에 서커스 단원들이 길게 늘어선 줄을 지나 아드벡 증류소 입구를 거쳐 들어가면서 축제는 막을 올렸다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "먼저 정문에서 사전 예약을 확인하고 나서 티켓과 작은 잔을 하나 챙겨주는데, 아드벡 스펙타큘러나 코어 레인지 한 잔과 아드벡 하이볼 한 잔을 공짜로 제공해 주는 티켓이었다." },
    { kind: "paragraph", text: "아드벡의 마스코트인 강아지가 묘기를 부리고 있는 티켓이라니, 이번 아드벡 데이의 컨셉을 귀엽고도 확실하게 보여준다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/03.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "술쟁이로서 아드벡 데이에서 가장 좋았던 점은 로스트 앤 파운드 드램이라 해서 단종된 아드벡들을 잔 당 아주 싼 가격에 판매한다는 점이었다." },
    { kind: "paragraph", text: "여기서 아일라에 들어가는 분들에게 드리고 싶은 팁은 **섬에 들어가기 전에 반드시 파운드 현금을 어느 정도 찾아 놓으라는 점이다." },
    { kind: "paragraph", text: "당일 저 아드벡 바에서는 현금만을 받았는데, 우리가 가지고 있는 건 80파운드가 전부였고, 결국 마셔 볼 위스키를 취사선택할 수밖에 없었다. 그렇게 마신 게 아래의 리스트" },
    { kind: "paragraph", text: "아드벡 스틸영(Ardbeg Still Young, 2006)" },
    { kind: "paragraph", text: "아드벡 투엔티썸띵(Ardbeg Twenty Something) - 22년" },
    { kind: "paragraph", text: "아드벡 수퍼노바(Ardbeg Supernova, 2014)" },
    { kind: "paragraph", text: "아드벡 다크코어(Ardbeg Dark Core, 2016)" },
    { kind: "paragraph", text: "아드벡 킬달튼(Ardbeg Kildalton, 2014)" },
    { kind: "paragraph", text: "아드벡 데이(Ardbeg day, 2012)" },
    { kind: "paragraph", text: "아드벡 르네상스(Ardbeg Renaissance, 2008)" },
    { kind: "paragraph", text: "80파운드가 넘지 않나? 싶지만, 아드벡 르네상스는 사실 축제에서 만나서 얘기 나누던 영국인 형님이랑 킬달튼을 바꿔마셨다." },
    { kind: "paragraph", text: "개인적으로 제일 맛있었던 건 스틸영과 수퍼노바로, 올해 마신 위스키 top5에 들어갈만했다. 이 두 위스키를 마실 기회가 있다면 꼭 한 번씩은 드셔보시길." },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "서커스가 컨셉인만큼 대형 미끄럼틀 같은 서커스 관련 콘텐츠에 더해 락 밴드의 노래, 간단한 음식들까지 올해 아드벡 데이는 위스키나 칵테일 외에도 즐길 게 다양했다. 그냥 그 공간 안에 있는 자체로 텐션이 올라갔다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/05.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/06.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "증류소샵도 이용 가능했고, 여기서 아드벡 증류소의 마스코트도 만나볼 수 있다. 이 날은 아드벡 싱글 캐스크도 판매하고 있었는데, 이걸 구매하려는 사람들이 많아 줄을 설 정도였다. 가격이 너무 비싸 구매하지는 않았지만" },
    { kind: "paragraph", text: "외부에서는 카드 결제가 안됐지만, 증류소샵에서는 카드 결제가 가능하다." },
    { kind: "paragraph", text: "분위기도 신나고, 날씨도 너무 좋아서 축제를 더 즐기고 싶었지만, 킬달튼 3형제를 모두 들러보기 위해서 축제를 뒤로하고 라프로익 증류소로 이동했다." },
    { kind: "paragraph", text: "아드벡 증류소에 마신 마지막 잔은 친구의 로망. 우가달을 좋아하는 친구가 증류소에서 꼭 우가달을 마셔보고 싶다는 얘기에 로망 한 잔을 나눠마셨다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep8/07.webp", width: 966, height: 966 },
  ],
};
