import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep0-5",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep0.5 — 아일라 섬에서 열리는 위스키 축제, 페스 아일에 대해서 알아보자",
  dek: "페스 아일(Feis Ile)은 매년 5월 마지막 주에 아일라(Islay) 섬과 주라(Jura) 섬에서 약 1~2주간에 걸친 위스키 관련 축제입니다.",
  publishedAt: "2024-08-13",
  hero: "/articles/scotland-whisky-ep0-5/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223546572556",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/00.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "페스 아일(Feis Ile)은 매년 5월 마지막 주에 아일라(Islay) 섬과 주라(Jura) 섬에서 약 1~2주간에 걸친 위스키 관련 축제입니다." },
    { kind: "paragraph", text: "1985년, 아일라 섬에서는 관광객을 유치하고, 사라져가는 게일어를 지키기 위하는 등의 목적으로 지역 위원회가 구성되었고, 1986년에 첫 번째 페스 아일(Feis Isle)이 개최되었습니다." },
    { kind: "paragraph", text: "다만, 처음부터 오늘날과 같이 위스키에 초점을 맞춘 축제는 아니었고, 아일라의 아름다운 자연 풍경과 더불어 게일어 연극이나 음악과 관련된 콘텐츠나 지역 커뮤니티 연계 콘텐츠가 주였다고 합니다." },
    { kind: "paragraph", text: "2000년에 들어서야 아일라 섬의 증류소들이 마스터 클래스나 오픈 데이(Open Day)를 여는 등 축제에 참여하기 시작했고, 축제 기념 위스키를 출시하게 되기에 이릅니다. 여기에 더해 독립병입자들 또한 축제 한정 바틀을 출시하기도 합니다." },
    { kind: "paragraph", text: "이 아일라 섬에서 열리는 축제는 지역민의 자원봉사로 이루어지는 것으로 알고 있는데, 그래서인지 업데이트가 다소 느린 편이고, 지역민이 운영하던 가게나 B&B를 축제 기간에 문을 닫기도 하는 경우도 왕왕 있습니다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "페스 아일 기간에 증류소는 각각 오픈 데이를 가지면서 증류소 한정 제품을 선보이거나, 록 밴드를 불러 공연을 하는 등의 각종 엔터테인먼트 거리를 제공합니다. 예를 들어, 올해 아드벡 데이에는 서커스를 테마로 했고, 그 외에 록 밴드의 공연이 있었습니다." },
    { kind: "paragraph", text: "페스 아일 일정과 티켓에 관한 정보는 여기에서 확인할 수 있습니다." },
    { kind: "paragraph", text: "참고로, 각 증류소의 오픈 데이가 아니라 하더라도 해당 증류소 투어나 비지터 센터 이용이 가능합니다. 다만, 투어 예약은 각 증류소 사이트에서 해야합니다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/04.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/05.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/06.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep0-5/07.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "증류소마다 출시하는 축제 바틀은 매년 다른 스펙으로 출시되며, 기본적으로 정보가 공개되지만 증류소에 따라서 공개하지 않는 경우도 있습니다." },
    { kind: "paragraph", text: "예를 들어서 브룩라디 증류소는 브룩라디와 포트샬롯에 대해서는 사전예약을 통한 판매를 했었는데, 옥토모어와 발린치에 대해서는 따로 공개를 하지 않았던 걸로 기억합니다." },
    { kind: "paragraph", text: "축제 한정 위스키들은 축제 기간에 대부분 증류소에서 맛볼 수 있으며, 증류소가 없는 독립병입자들 같은 경우는 레스토랑 등에서 시음회를 열기도 합니다. 이 티켓들은 공식 축제 홈페이지에서 확인할 수 있습니다." },
    { kind: "paragraph", text: "아래는 올해 페스 아일을 기념해 출시한 바틀들이니 참고해 주세요." },
    { kind: "paragraph", text: "**페스 아일 2024 출시 바틀 정보" },
    { kind: "paragraph", text: "보모어 (Bowmore)" },
    { kind: "paragraph", text: "- 19년" },
    { kind: "paragraph", text: "- 버진 아메리칸 오크에서 더블 메추어드" },
    { kind: "paragraph", text: "- 54.8%" },
    { kind: "paragraph", text: "브룩라디" },
    { kind: "paragraph", text: "1. 브룩라디 록앤달 03.1 (Bruichladdich ROCK‘NDAAL 03.1)" },
    { kind: "paragraph", text: "- 100% 스코틀랜드 보리(Scottish Barley)" },
    { kind: "paragraph", text: "- 소테른 캐스크(Sauterne Cask, 12.5%), 오스트리아 디저트 와인 캐스크(Austrian Dessert Wine Cask, 12.5%), PX 셰리를 숙성한 후 스페인 브랜디(페르난도 드 카스티야/Fernando de Castilla)를 숙성한 엑스 브랜디 캐스크(ex-Brandy Cask, 75%)의 원액을 엑스 버번 캐스크(ex-Bourbon Cask)에서 2017년~2023년 숙성" },
    { kind: "paragraph", text: "- 10년" },
    { kind: "paragraph", text: "-50%, 논피트" },
    { kind: "paragraph", text: "2. 포트샬롯 (Port Charlotte)" },
    { kind: "paragraph", text: "- 100% 스코틀랜드 보리(Scottish Barley)" },
    { kind: "paragraph", text: "- 20년" },
    { kind: "paragraph", text: "- 버번 캐스크(Bourbon Cask, 70%), 퍼스트 필 소테른 캐스크(First fill Sauterne Cask, 30%)" },
    { kind: "paragraph", text: "- 54%, 40ppm" },
    { kind: "paragraph", text: "3. 옥토모어 발린치 0.3 (Octomore Valinch 0.3)" },
    { kind: "paragraph", text: "- 12년" },
    { kind: "paragraph", text: "- 세컨 필 시라 캐스크(2nd fill Syrah Cask)" },
    { kind: "paragraph", text: "- 싱글 캐스크" },
    { kind: "paragraph", text: "- 58.2%, 150.2ppm, 500ml" },
    { kind: "paragraph", text: "4. 발린치 (Valinch)" },
    { kind: "paragraph", text: "- 17년" },
    { kind: "paragraph", text: "- 세컨 필 셰리 벗(2nd fill Sherry Butt)" },
    { kind: "paragraph", text: "- 57.1%, 논피트, 500ml" },
    { kind: "paragraph", text: "라가불린" },
    { kind: "paragraph", text: "1. 라가불린 10년 (Lagavulin 10yo feis ile 2024)" },
    { kind: "paragraph", text: "- 10년" },
    { kind: "paragraph", text: "- 리필 헤빌리 차드 캐스크(Refill, Heavili Charred Cask), 퍼스트 필 엑스 버번 아메리칸 오크 혹스헤드 캐스크(1st fill ex-Bourbon American Oak Hogshead Cask)" },
    { kind: "paragraph", text: "- 56.7%, 기존의 라가불린보다 강한 피트감이 특징" },
    { kind: "paragraph", text: "2. 라가불린 스카이 오브 페스 아일(Lagavulin Skies of Feis ile)" },
    { kind: "paragraph", text: "- 엑스 보데가 셰리 캐스크(ex-Bodega Sherry Cask)에서 1995년 5월부터 약 20년 숙성 후, 아모로소 세리 와인으로 시즌된 아메리칸 오크를 헤빌리 차드한 베럴(heavily charred barrel of American oak treated with Amoroso)에서 8년 숙성" },
    { kind: "paragraph", text: "- 52.4%" },
    { kind: "paragraph", text: "아드벡 스펙타큘러 (Ardbeg Spectacular)" },
    { kind: "paragraph", text: "- 포트 캐스크(Port Cask), 엑스 버번 캐스크(ex-Bourbon Cask)" },
    { kind: "paragraph", text: "- 46%" },
    { kind: "paragraph", text: "라프로익 카데어스 (Laphroaig Cairdeas)" },
    { kind: "paragraph", text: "- 10년" },
    { kind: "paragraph", text: "- 엑스 버번 캐스크 + 쿼터 캐스크를 PX 셰리 캐스크에서 피니시 (ex-bourbon + Quarter Cask finished in PX)" },
    { kind: "paragraph", text: "- 52.4%" },
    { kind: "paragraph", text: "부나하벤" },
    { kind: "paragraph", text: "1. 27년" },
    { kind: "paragraph", text: "- 모스카텔 캐스크에서 9년간 피니시(Moscatel Cask Finish)" },
    { kind: "paragraph", text: "- 46.4" },
    { kind: "paragraph", text: "2. 23년" },
    { kind: "paragraph", text: "- 트리플 셰리 우드 피니시(Triple Sherry Wood Finish)" },
    { kind: "paragraph", text: "- 아몬티야도(Amontillado), 만자니야(Manzanilla), 올로로소(Olorosso)의" },
    { kind: "paragraph", text: "- 53.3%, 캐스크 스트렝스" },
    { kind: "paragraph", text: "3. 14년" },
    { kind: "paragraph", text: "- 버번 캐스크(Bourbon Cask) 11년 숙성 후, 루피 포트 혹스헤드(Ruby Port Hogshead)에서 3년 피니시" },
    { kind: "paragraph", text: "- 58.7%" },
    { kind: "paragraph", text: "4. 19년" },
    { kind: "paragraph", text: "- 버번 캐스크(Bourbon Cask)에서 12년 숙성 후, 마데이라 혹스헤드(Madeira Hogshead)에서 7년 피니시" },
    { kind: "paragraph", text: "- 51.2%, 피티드" },
    { kind: "paragraph", text: "킬호만 (Kilchoman)" },
    { kind: "paragraph", text: "- 2011년 증류한 두 개의 버번 캐스크를 배팅한 것(Vatting of two fresh Bourbon Barrels)" },
    { kind: "paragraph", text: "- 53%, 논피티드" },
    { kind: "paragraph", text: "쿨일라 (Caol Ila)" },
    { kind: "paragraph", text: "- 13년" },
    { kind: "paragraph", text: "- 루비 포트 프렌치 오크(Ruby Port French Oak)" },
    { kind: "paragraph", text: "- 54.5%" },
    { kind: "paragraph", text: "아드나호 (Ardnahoe)" },
    { kind: "paragraph", text: "- 5년" },
    { kind: "paragraph", text: "- 퍼스트필 & 리필 버번 캐스크(1st Fill & Refill Bourbon Barrel)" },
    { kind: "paragraph", text: "- 59.3%" },
    { kind: "paragraph", text: "주라 (Jura)" },
    { kind: "paragraph", text: "- 15년" },
    { kind: "paragraph", text: "- 퍼스트필 버번 캐스크(1st fill Bourbon Cask)" },
    { kind: "paragraph", text: "- 55.5%, 캐스크 스트렝스" },
    { kind: "paragraph", text: "빅피트 (Big Peat)" },
    { kind: "paragraph", text: "- 럼 캐스크 피니시(Rum Finish)" },
    { kind: "paragraph", text: "- 48%" },
    { kind: "paragraph", text: "엘리먼트 오브 아일라 (Elements of Islay)" },
    { kind: "paragraph", text: "- 쿨일라 & 부나하벤 블렌디드" },
    { kind: "paragraph", text: "- 헤빌리 리-차드 혹스헤드(Heavily re-charred Hogshead), 아메리칸 오크 올로로소 셰리 혹스헤드(American Oak Oloroso Sherry Hogshead), 유로피안 오크 올로로소 셰리 벗(European Oak Oloroso Sherry Butt)" },
    { kind: "paragraph", text: "- 54.5%" },
    { kind: "paragraph", text: "막탈라 (Mac-Talla)" },
    { kind: "paragraph", text: "- 15년" },
    { kind: "paragraph", text: "- 혹스헤드(Hogshea) 10년 숙성 후, 크루잔 럼 캐스크(Cruzan Rum Cask) 5년 숙성" },
    { kind: "paragraph", text: "- 53.7%" },
    { kind: "paragraph", text: "스카치 몰트 오브 스코틀랜드 (SMWS)" },
    { kind: "paragraph", text: "1. Sm'oak!" },
    { kind: "paragraph", text: "- 증류소 코드: 29" },
    { kind: "paragraph", text: "- 25년" },
    { kind: "paragraph", text: "- 리필 혹스헤드(Refill hogsheads), 퍼스트필 올로로소 바리끄 STR(1st-fill Oloroso barriques STR)" },
    { kind: "paragraph", text: "- 56.3%, 헤빌리 피티드" },
    { kind: "paragraph", text: "2. Winter's green" },
    { kind: "paragraph", text: "- 증류소 코드: 53" },
    { kind: "paragraph", text: "- 12년" },
    { kind: "paragraph", text: "- 리필 혹스헤드(Refill hogsheads)" },
    { kind: "paragraph", text: "- 57.6%" },
    { kind: "paragraph", text: "드램풀 리키 라디 (Dramfool Leaky Laddie)" },
    { kind: "paragraph", text: "- 브룩라디 15년" },
    { kind: "paragraph", text: "- 퍼스트필 버번 캐스크(1st fill Bourbon cask) 숙성 중 리필 셰리 옥타브로 리랙킹(re-racked into a refill sherry octave)" },
    { kind: "paragraph", text: "- 58%, 캐스크 스트렝스" },
    { kind: "paragraph", text: "- 200ml로 77병 출시" },
    { kind: "paragraph", text: "더 싱글 캐스크 (The Single Cask/TSC)" },
    { kind: "paragraph", text: "- 린스(rhinns) > 브룩라디 증류소" },
    { kind: "paragraph", text: "- 12년" },
    { kind: "paragraph", text: "- 버번 캐스크(Fresh Bourbon Barrel)" },
    { kind: "paragraph", text: "- 60.4%" },
    { kind: "paragraph", text: "핀라간 (Finlaggan)" },
    { kind: "paragraph", text: "- 템프라니요 바리끄(Tempranillo Barrique)" },
    { kind: "paragraph", text: "- 50%" },
    { kind: "paragraph", text: "아일라 미스트 (Islay Mist)" },
    { kind: "paragraph", text: "- 17년" },
    { kind: "paragraph", text: "- 40%" },
  ],
};
