import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep1",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep1 — 글래스고, 이곳에도 위스키와 증류소가 있어",
  dek: "아일라나 스코틀랜드의 다른 위스키 지역을 가기 위해서는 글래스고와 에든버러 둘 중에 웬만하면 한 곳은 들러야 한다.",
  publishedAt: "2024-08-13",
  hero: "/articles/scotland-whisky-ep1/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223546645087",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "paragraph", text: "아일라나 스코틀랜드의 다른 위스키 지역을 가기 위해서는 글래스고와 에든버러 둘 중에 웬만하면 한 곳은 들러야 한다." },
    { kind: "paragraph", text: "개인적으로 글래스고를 선택한 이유는 에든버러보다는 조금 더 아일라가 가까웠기 때문이고, 위스키 성지인 팟스틸(Pot Still)이 있기 때문이었다. 그런데 시내에 증류소도 있더라." },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "처음 도착한 글래스고는 도시 자체가 너무나 이뻤다. 술과는 전혀 상관없지만, 그냥 찍었던 사진을 넣고 싶어서..." },
    { kind: "quote", text: "클라이드사이드 증류소" },
    { kind: "quote", text: "Clydeside Distillery" },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/01.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "\"클라이드사이드 증류소\"는 글래스고 시내에 위치한 증류소로, 2017년에 오픈한 신생 증류소이며, 2021년 첫 번째 싱글몰트 위스키를 출시했다. 지역적으로 로우랜드(Lowland) 싱글몰트 위스키." },
    { kind: "paragraph", text: "재밌는 점은 빔 산토리가 보모어 증류소를 인수하기 전까지 보모어 증류소를 소유하고 있던 모리슨 패밀리가 이 증류소를 소유하고 있다는 점이다." },
    { kind: "paragraph", text: "증류소에서는 투어를 즐길 수도 있으며, 내부의 카페에서 간단한 음식을 먹거나 위스키 시음이 가능하다. 글래스고 여행자들이 라이트 하게 접하기 좋은 투어이며, 학생이면 할인도 된다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/02.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/03.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "증류소는 '클라이드 강' 바로 옆에 있는데, 투어 중 증류소 스태프가 투어 참가자들에게 질문을 해온다." },
    { kind: "paragraph", text: "\"위스키를 만드는 데 있어서 좋은 물은 필수입니다. 우리 증류소는 어디에서 물을 길어올까요?\"" },
    { kind: "paragraph", text: "강을 옆에 두고 이런 질문을 하는 데는 다 이유가 있다. 참가자 대부분은 당연히 옆에 있는 강이라고 답변하는데, 스태프는 낚시에 성공했다는 듯이 웃으며 카트린 호(Loch Katrine)가 수원이라고 한다. 관광객이 어떻게 아냐고....ㅋㅋㅋㅋ" },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "투어에는 위스키 테이스팅이 포함되는데, 클라이드사이드의 뉴메이크 스피릿(NMS)과 미출시 바틀들을 시음할 수 있다. 이 뉴메이크 스피릿이 꽤 맛있었던 기억이 있었는데, 사실 뉴메이크 스피릿을 시음할 수 있는 증류소 투어는 많지 않다." },
    { kind: "paragraph", text: "물론, 나중에 라가불린에서 가격대가 좀 있는 투어를 했을 때는 뉴메이크 스피릿을 마셔봤지만, 저렴한 가격의 투어라면 굳이 뉴메이크 스피릿을 제공하지 않는다. 아마 클라이드 사이드가 신생 증류소라 제공해 주지 않았을까 싶긴 하다." },
    { kind: "quote", text: "바 팟 스틸" },
    { kind: "quote", text: "Bar Pot Still" },
    { kind: "paragraph", text: "\"팟 스틸\"은 글래스고 시내에 위치한 바로, 위스키 러버들에게는 스코틀랜드 위스키 성지 취급을 받으며, 우리나라 방송에도 노출된 적이 있을 정도로 꽤나 유명한 곳이다. 일찍부터 오픈하니 낮술 하기에도 딱 좋다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/05.webp", width: 966, height: 1717 },
    { kind: "paragraph", text: "백바에는 수많은 위스키가 있으며, 당연히 우리나라에서 볼 수 없는 위스키들도 많다. 다만, 특이한 점은 대부분의 손님이 꽤 나이가 지긋했고, 대부분 맥주를 마신다는 점이었다. 위스키를 마시는 건 관광객 정도." },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/06.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/scotland-whisky-ep1/07.webp", width: 966, height: 1717, caption: "첫 번째 사진처럼 푸어하는 건팟 스틸의 시그니처" },
    { kind: "paragraph", text: "이날 위스키를 다양하게 마시긴 했지만, 병을 바로바로 치우는 바람에 사진을 많이 찍지는 못했다. 그중 이날의 베스트는 위스키 스펀지의 킬달튼(이라 쓰고 아드벡이라 읽음)이었다." },
    { kind: "paragraph", text: "출시할 때부터 마셔보고 싶었는데, 마침 선반에 있길래 바로 주문했고, 지금에 와서는 구체적인 맛까지는 기억이 안 나지만 마시자마자 감탄했던 기억이 있다." },
    { kind: "paragraph", text: "주문에 관해서 팟 스틸에는 메뉴가 따로 없어서 백바를 확인하고 종업원에게 부탁을 하거나, 잘 모르겠다 싶으면 추천을 해달라고 할 수도 있다. 예를 들어, \"몇 잔을 몇 파운드까지의 예산으로 ~~캐릭터의 위스키로 추천해 주세요.\" 정도로 물어볼 수도 있다." },
    { kind: "paragraph", text: "어디까지 예시이니 편하게 물어보면 되겠다. 몇몇 분들은 가격을 물어봐도 될까?라는 생각을 하실 수 있는데, 가격 물어보는 게 전혀 실례는 아니니 마음껏 물어보시라." },
    { kind: "paragraph", text: "다만, 되도록이면 구체적으로 추천해달라고 문의하는 것이 좋은 게, 직원들이 되도록이면 증류소의 오피셜 라인 중에서도 코어 라인을 위주로 추천하는 경향이 있는 것 같다." },
    { kind: "paragraph", text: "그 와중에 오큰토션은 여기서도 찬밥 신세....(아메리칸 오크가 단돈 3파운드!)" },
  ],
};
