import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep10",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep10 — 직접 핸드필로 위스키를 담아 온 라가불린 증류소 투어",
  dek: "아드벡 데이의 경험이 너무 즐거웠지만, 사실 이번 스코틀랜드 여행은 계획할 때만 해도 라가불린이 하이라이트였다.",
  publishedAt: "2024-08-24",
  hero: "/articles/scotland-whisky-ep10/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223559164258",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep10/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "아드벡 데이의 경험이 너무 즐거웠지만, 사실 이번 스코틀랜드 여행은 계획할 때만 해도 라가불린이 하이라이트였다." },
    { kind: "paragraph", text: "우리 둘 다 라가불린을 좋아하기도 하고, 이왕 가는 거 하나 정도는 비싼 투어를 체험하자고 해서 라가불린 증류소 익스클루시브 익스피리언스 투어(Lagavulin Distillery Exclusive Experience)를 예약했다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/01.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "투어는 라가불린 생산 과정을 일부 보여주는 것부터 시작하는데, 투어 시작부터 피트가 반겨준다. 투어 내용 자체는 반절 좀 넘게 이해한 것 같은데, 영어를 좀 더 잘하면...." },
    { kind: "paragraph", text: "생산 과정에 대한 섹션이 끝나면 밖으로 나와서 증류소 내부 해안가에서 잠시 시간을 가지게 되는데, 개인적으로는 날씨가 좋아서 이 시간이 좀 더 마음에 들었다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/03.webp", width: 966, height: 644 },
    { kind: "paragraph", text: "이 해안선을 보다 보면 투어를 안내하는 스태프가 이런저런 얘기를 하다가 던우베이그 성(Dunyvaig Castle)의 유적에 대한 얘기를 해주기도 한다(두 번째 사진)." },
    { kind: "paragraph", text: "여담으로, 라가불린은 독립병입자가 라가불린 명칭을 쓰는 걸 지양하는 증류소 중에 하나인데, 이러한 점 때문에 독립병입자들은 라가불린 원액의 경우 던우베이그 성의 유적을 라벨에 종종 그려 넣고는 한다." },
    { kind: "paragraph", text: "이렇게 해안선 구경까지 끝나게 되면 매키 테이스팅 룸(Mackie Tasting Room)이라는 증류소 내의 프라이빗 한 테이스팅 룸으로 향한다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/05.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "테이스팅 룸에서는 총 6가지를 마셔봤는데, 그중 하나는 라가불린 뉴메이크 스피릿(NMS)이었다. 지금까지 로즈뱅크, 클라이드사이드의 뉴메이크는 마셔봤는데, 피트 처리된 뉴메이크는 처음이어서 아주 기대됐다." },
    { kind: "paragraph", text: "라가불린 뉴메이크 스피릿 (Lagavulin NMS)" },
    { kind: "paragraph", text: "라가불린 디아지오 SR 2021 (Lagavulin Diageo SR 2021, 26yo)" },
    { kind: "paragraph", text: "라가불린 아일라 재즈 페스티벌 2022 (Lagavulin Islay Jazz Festival 2022, 14yo)" },
    { kind: "paragraph", text: "라가불린 페스 아일 2023 (Lagavulin Feis Ile 2023, 14yo)" },
    { kind: "paragraph", text: "라가불린 페스 아일 2024 (Lagavulin Feis Ile 2024, 10yo)" },
    { kind: "paragraph", text: "라가불린 8년 퍼스트필 엑스-버번 혹스헤드 (Lagavulin 1st fill ex-Bourbon Hogshead, 8yo)" },
    { kind: "paragraph", text: "가장 먼저 뉴메이크를 마셔봤는데, 라가불린은 이미 뉴메이크부터 특유의 고소한 곡식+피트감이 나타난다. 거기에 핵과류의 달달함이 같이 나는데, 이거 정말 맛있었다." },
    { kind: "paragraph", text: "다음으로 라가불린 디아지오 SR 2021의 차례였는데, 향만큼은 이번 아일라 여행에서 맡은 위스키 중에 top3에서도 1, 2위를 차지할 정도였다. 맛에서는 향만큼의 퍼포먼스를 보여주지 못한 건 아쉽지만." },
    { kind: "paragraph", text: "재즈 페스티벌과 페스 아일 2023 바틀은 사실 정확히 맛이 기억은 안 난다. 라가불린의 캐릭터가 있던 것 정도만 기억났고, 페스 아일 2024는 기존 라가불린보다 피트감이 높은 게 인상적이었다." },
    { kind: "paragraph", text: "마지막 라가불린 8년은 이날 투어의 마지막으로 우리가 핸드필해서 가져갈 위스키였다. 8년 숙성인 건 조금 아쉽지만 그래도 라가불린 핸드필을 받은 것만으로도 만족스럽다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/06.webp", width: 540, height: 720 },
    { kind: "figure", src: "/articles/scotland-whisky-ep10/07.webp", width: 966, height: 1288, caption: "라벨 작업하는 곳에는 올드 라가불린과 뗄래야 뗄 수 없는 관계인화이트 홀스도 보인다." },
    { kind: "paragraph", text: "핸드필하는 원액의 정보를 꽤 잘 알려주는 편이고, 핸드필 할 때는 병의 라벨 정보를 본인이 쓴 후에 직접 붙이게 되는데, 이 작업이 또 재미있다. 200미리를 받아왔는데, 이거 오픈할 수 있을지나 모르겠다." },
    { kind: "paragraph", text: "아일라섬의 증류소 투어를 알아보다 보면 100~200미리 핸드필을 받아갈 수 있는 투어가 꽤 있는데, 강력하게 추천한다." },
  ],
};
