import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep7",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep7 — 포트 엘런의 굴뚝에서는 연기가 나고 있다",
  dek: "포트 엘런(Port Ellen)은 보모어와 더불어 아일라 섬에서 가장 큰 도시로, 포트 애스케이크(Port Askaig)와 더불어 스코틀랜드 내륙과 이어지는 페리 노선이 운영되는 마을이다.",
  publishedAt: "2024-08-21",
  hero: "/articles/scotland-whisky-ep7/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223555650827",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep7/00.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/01.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "포트 엘런(Port Ellen)은 보모어와 더불어 아일라 섬에서 가장 큰 도시로, 포트 애스케이크(Port Askaig)와 더불어 스코틀랜드 내륙과 이어지는 페리 노선이 운영되는 마을이다." },
    { kind: "paragraph", text: "이곳에는 보모어보다 B&B 숙소가 많이 위치해있어 많은 여행자가 포트 엘런을 거점으로 아일라 섬을 여행하기도 한다." },
    { kind: "paragraph", text: "마을에서부터 포트 엘런 증류소까지 이어지는 해안선이 아주 아름다우며, 후에 방문할 킬달튼 3형제(라프로익, 라가불린, 아드벡)을 만나기 위해서는 반드시 거쳐야 하는 도시이다." },
    { kind: "paragraph", text: "보모어에서부터 킬달튼으로 가는 거라면 물론 포트 엘런을 방문하지 않고 지나갈 수 있지만, 아침 일찍부터 아드벡 증류소를 가야 해서 아침도 해결하고, 포트 엘런 증류소도 볼 겸 방문했다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/03.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "포트 엘런은 설립 후 몇 번의 고비를 겪다가 결국 1983년에 결국 문을 닫아버린 증류소로, 이후 증류는 하지 않고 맥아 제조를 위한 몰팅(Malting) 작업만을 하게 되었다." },
    { kind: "paragraph", text: "자가 몰팅을 하지 않는 아일라 증류소는 대부분 포트 엘런의 몰트를 사용하며, 아일라 섬 이외에도 몰트를 공급하기도 한다." },
    { kind: "paragraph", text: "이렇게 포트 엘런 증류소는 유령 증류소가 되었고, 남아 있는 원액들은 간간이 디아지오에 의해서 레어 몰츠 셀렉션(Rare Malts Selection)이나 독립병입자들에 의해서 소량 출시되었다." },
    { kind: "paragraph", text: "다만, 가격이 매우 높은 데다가 소량만 출시되기 때문에 컬렉터가 아닌 이상에야 구매하기는 상당히 어렵다. 일본에서는 종종 바에서 볼 수 있기도 하지만 역시나 가격이 높다." },
    { kind: "paragraph", text: "이후 소유주인 디아지오는 서덜랜드 지역의 브로라(Brora) 증류소와 함께 재개장할 계획을 발표하고, 2024년 3월 19일 마침내 포트 엘런 증류소를 재개장하기에 이른다." },
    { kind: "paragraph", text: "우리가 가서 포트 엘런을 보았을 때는 이른 시간이라 아직 문을 열지 않았는데, 비지터 센터가 있는지, 일반 방문객이 방문할 수 있는지는 잘 모르겠다." },
    { kind: "paragraph", text: "다만, 디아지오 사이트인 malts.com에서 투어를 예약할 수 있는 걸 보면 아마 방문이 가능할 것 같기는 하다. 단순 방문에서 포트 엘런을 마셔볼 수 있을지는 모르지만." },
    { kind: "paragraph", text: "포트 엘런은 간단하게 둘러보고, 아침을 해결하고 아드벡으로 발걸음을 옮겼다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/05.webp", width: 966, height: 644 },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/06.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/scotland-whisky-ep7/07.webp", width: 966, height: 966, caption: "커피는 여기도 여전히 맛없다" },
  ],
};
