import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "scotland-whisky-ep13",
  category: "spirits",
  title: "스코틀랜드 위스키 여행 ep13 — 캠벨타운의 근본 독립병입자, 카덴헤드의 위스키 샵과 테이스팅 룸",
  dek: "카덴헤드(Wm Cadenhead's Ltd)는 1842년에 설립된 가장 오래된 독립병입자로, 캠벨타운의 스프링뱅크 증류소와 글렌가일 증류소의 소유주인 제이앤에이 미첼앤코(J&A Mitchell & Co.",
  publishedAt: "2024-10-08",
  hero: "/articles/scotland-whisky-ep13/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223611465006",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/scotland-whisky-ep13/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "카덴헤드(Wm Cadenhead's Ltd)는 1842년에 설립된 가장 오래된 독립병입자로, 캠벨타운의 스프링뱅크 증류소와 글렌가일 증류소의 소유주인 제이앤에이 미첼앤코(J&A Mitchell & Co. Ltd)에 1972년 인수되었다." },
    { kind: "paragraph", text: "이 인수 이후로는 캠벨타운에 본사를 두고 있으며, 캠벨타운에서는 이 카덴헤드 위스키 샵과 테이스팅 룸이 있어 카덴헤드의 제품을 시음해 볼 수도 있다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/01.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "먼저 테이스팅룸에 가기 앞서서 카덴헤드 위스키 샵에 들렀는데, 만약 여러분이 캐리어를 가지고 있으면 마음씨 좋은 직원들이 캐리어를 보관해줄까 물어봐준다. 원래는 스프링뱅크 증류소에 맡기려했는데, 어쩌다보니 여기 맡기게 되었다." },
    { kind: "paragraph", text: "샵 내부 사진을 많이 찍지는 않았는데, 기본적으로 무료 시음이 가능한 4가지의 카덴헤드 위스키(아마 블렌디드 였던 걸로 기억함)와 럼을 마셔볼 수 있다. 이후에 테이스팅룸과 증류소 방문을 해야 해서 마셔보지는 않았지만." },
    { kind: "paragraph", text: "판매하는 제품군이 아주 다양하게 있으며, 리틀밀(Little Mill)처럼 폐쇄증류소도 찾아볼 수 있다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/02.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "카덴헤드 테이스팅 룸은 위스키 샵에서 조금 떨어져있는데, 아마 위스키 샵 내부에서 테이스팅 룸까지 이어지는 통로가 있던 것 같다. 증류소를 들렀다가 다시 오느라 이용하지는 않았지만." },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/03.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/04.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "카덴헤드 테이스팅룸에서는 많은 카덴헤드 라인업을 아주 저렴한 가격에 경험해 볼 수 있다는 장점을 가지고 있다. 플라이트로 소량씩 마셔보는 것도 좋지만 따로 하나하나 마셔보는 것도 좋다." },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/05.webp", width: 966, height: 543 },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/06.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/scotland-whisky-ep13/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "친구는 30파운드짜리 플라이트를 마셨는데, 여기에 카덴헤드에서 병입한 스프링뱅크 11년도 있었다. 스프링뱅크 증류소의 워시백 바 이외에 카덴헤드에도 스프링뱅크가 있으니 참고하시길." },
    { kind: "paragraph", text: "나는 플라이트 말고 따로 하나씩 주문했는데, 스프링뱅크 26년, 번사이드 25년, 아드벡 29년을 한 잔씩 마셨고, 언제 이 가격에 이 증류소들의 고숙성을 마셔보겠어 하고 주문하게 되었다." },
    { kind: "paragraph", text: "번사이드(Burnside)는 발베니(Balvenie) 99%에 글렌피딕(Glenfiddich) 1%를 섞은 티스푼 위스키(Teaspooned Whisky)인데, 발베니를 그렇게까지 좋아하는 편은 아니지만 25년 숙성된 게 15파운드라면 마실 수 밖에 없다." },
    { kind: "paragraph", text: "이 바틀을 잘 보면 \"1 of 1 Bottle\"이라고 써져있는데, 그럼 이 테이스팅 룸에서만 마실 수 있겠다 싶었던 것도 주문한 이유 중 하나였고, 여기에 대해 재밌는 얘기를 들을 수 있었다." },
    { kind: "paragraph", text: "위스키 바틀의 용량이 다르면 각각 1 of 1 bottle이라고 쓸 수 있다는 것. 그러니까 200ml, 350ml, 700ml를 한 바틀씩만 릴리즈한다면 각각 1 of 1 bottle이라고 표기할 수 있다고 한다." },
    { kind: "paragraph", text: "스프링뱅크와 아드벡은 직원 추천을 받았던 건데, 메뉴에 없는 것들도 있으니 직원 추천을 받아보는 것도 좋은 선택이다. 그리고 고숙성이 이 가격이 맞나 싶을 정도로 싸니까 고숙성 마시자." },
  ],
};
