import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "shandy-gaff",
  category: "cocktail",
  title: "샌디 가프 — 저도수 생강 맛 맥주의 매력",
  dek: "\"샌디 가프\"는 쉽게 얘기해서 진저비어와 맥주를 동량으로 섞는 칵테일로, 집에서도 만들기 아주 간단하지만 생강의 달달한 알싸함에 맥주를 더한 매력적인 칵테일입니다.",
  publishedAt: "2024-08-21",
  hero: "/articles/shandy-gaff/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223555778355",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/shandy-gaff/00.webp", width: 524, height: 524 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"샌디 가프\"는 쉽게 얘기해서 진저비어와 맥주를 동량으로 섞는 칵테일로, 집에서도 만들기 아주 간단하지만 생강의 달달한 알싸함에 맥주를 더한 매력적인 칵테일입니다." },
    { kind: "paragraph", text: "샌디 가프는 그 유래가 투명하지는 않은데, 영국에서 시작됐을 거라고 보는 것이 주된 설입니다. 그럴만한 게 진저비어가 처음 만들어진 건 18세기 중반 영국의 요크셔에서 였기 때문입니다." },
    { kind: "paragraph", text: "그러다 보니 누군가가 맥주와 진저비어를 섞어서 마신 것이 샌디가프의 시작이었을 것이고, 만들기도 쉬우니 일반 술집에서도 간단하게 팔기 시작하면서 유행을 타지 않았을까 싶습니다." },
    { kind: "paragraph", text: "현재에는 영국에서는 샌디가프를 줄여서 샌디라고 부르며, 진저비어가 아닌 레모네이드를 맥주에 섞는 것이 일반적이라 합니다." },
    { kind: "paragraph", text: "이걸 프랑스에서는 파나셰(Panache), 독일에서는 라들러(Radler)라고 부르고 있습니다." },
    { kind: "paragraph", text: "일본의 이자카야를 가면 진저에일을 사용하는 샌디가프를 심심찮게 볼 수 있는데, 다른 술들을 마시다가 저도수로 체이서를 마시고 싶다 했을 때 딱 좋은 칵테일입니다." },
    { kind: "figure", src: "/articles/shandy-gaff/01.webp", width: 501, height: 501 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "진저비어" },
    { kind: "paragraph", text: "좋아하는 맥주" },
    { kind: "figure", src: "/articles/shandy-gaff/02.webp", width: 500, height: 500 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 차갑게 해둔 잔에 맥주를 따른다." },
    { kind: "paragraph", text: "2. 진저비어를 동량 따라준다." },
    { kind: "paragraph", text: "진저비어와 맥주를 동량 따르는 레시피이지만, 굳이 동량을 맞추지 않아도 상관없습니다. 두 재료가 모두 탄산을 가지고 있어서 지거를 사용한다면 탄산이 많이 빠지겠죠." },
    { kind: "paragraph", text: "그것보다는 눈대중으로 어느 정도 동량을 맞춰도 되며, 입맛에 따라서 양을 조절하셔도 전혀 상관없습니다." },
    { kind: "paragraph", text: "맥주의 경우 본래는 에일을 썼다고 합니다만, 이것도 굳이 신경 쓰지 말고 좋아하는 맥주를 사용하시면 됩니다(다만, 흑맥주는 제외)." },
    { kind: "paragraph", text: "저도수이니만큼 마시기 아주 쉬우며, 진저비어의 단맛과 알싸한 맛이 맥주 특유의 쓴맛을 가려주기 때문에 맥주의 쓴맛이 싫어하시는 분들도 가볍게 마시기 좋습니다." },
    { kind: "paragraph", text: "진저에일을 사용해도 되기는 하지만, 진저비어가 생강의 맛이 좀 더 뚜렷하기 때문에 진저비어로 만드는 걸 추천드리는 편입니다." },
  ],
};
