import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "shirley-temple",
  category: "cocktail",
  title: "셜리 템플 — 쉬어가는 타이밍에 마시는 논알콜 칵테일",
  dek: "\"셜리 템플\"은 1930~1940년대 할리우드의 전설적인 아역배우인 셜리 템플(Shirley Jane Temple)의 이름을 딴 무알콜 칵테일로, 무알콜 칵테일 중 가장 인지도가 높은 칵테일입니다.",
  publishedAt: "2024-09-03",
  hero: "/articles/shirley-temple/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223570716549",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/shirley-temple/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "\"셜리 템플\"은 1930~1940년대 할리우드의 전설적인 아역배우인 셜리 템플(Shirley Jane Temple)의 이름을 딴 무알콜 칵테일로, 무알콜 칵테일 중 가장 인지도가 높은 칵테일입니다." },
    { kind: "paragraph", text: "그 기원에 관련된 설이 정말 다양한데, 기본적인 골조는 레스토랑에서 미성년자였던 셜리 템플이 술을 마시지 못해 그녀를 위해 바텐더가 만들어준 무알콜 칵테일이라는 점입니다." },
    { kind: "paragraph", text: "기본적으로는 그레나딘 시럽에 진저에일을 더하는 칵테일인데, 이후에 레몬즙이나 라임즙을 소량 추가한다거나, 진저에일을 레모네이드, 레몬라임소다(ex. 스프라이트), 콜라 등으로 변경하는 식으로 개인 기호에 따라 만들어지게 되었습니다." },
    { kind: "paragraph", text: "셜리 템플에 술을 소량 넣어서 \"더티 셜리(Dirty Shirley)\"라는 칵테일으로 마신다고도 합니다만, 굳이 시도할 것 같지는 않네요." },
    { kind: "figure", src: "/articles/shirley-temple/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "10ml 그레나딘 시럽 (Grenadine)" },
    { kind: "paragraph", text: "진저에일/진저비어/스프라이트/콜라" },
    { kind: "figure", src: "/articles/shirley-temple/02.webp", width: 966, height: 966 },
    { kind: "figure", src: "/articles/shirley-temple/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 긴 잔에 얼음을 채워주고, 그레나딘을 부어줍니다." },
    { kind: "paragraph", text: "2. **탄산음료를 살짝 부어주고, 잘 섞어줍니다." },
    { kind: "paragraph", text: "3. 탄산음료를 더 부어주고," },
    { kind: "paragraph", text: "바스푼으로 얼음을 한두 번 위아래로 들어올려줍니다." },
    { kind: "paragraph", text: "**그레나딘은 당도가 높아 가라앉아있기 때문에 탄산음료를 모두 부어 준 후에 섞으려면 잘 섞이지 않고, 탄산이 많이 빠지게 됩니다." },
    { kind: "paragraph", text: "그러니 그레나딘이 바닥에 가라앉아있지 않게 탄산음료를 소량 넣어서 잘 섞어주고, 나머지 탄산음료를 따라서 잘 섞이면서 탄산이 최대한 남게 만들어주는 것이 좋습니다." },
    { kind: "figure", src: "/articles/shirley-temple/04.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "셜리 템플의 재밌는 점은 본인 입맛에 맞춰서 탄산음료를 넣으면 된다는 점입니다. 저는 진저비어가 남아있어서 진저비어를 썼는데, 생강의 캐릭터가 다소 강하네요." },
    { kind: "paragraph", text: "거기에 더해서 레몬즙이나 라임즙을 소량 넣으면 좀 더 입체감 있는 맛을 낼 수도 있습니다." },
    { kind: "paragraph", text: "술을 마시다가 쉬어가거나, 다른 사람들과 바에 갔지만 술을 마시기 어려운 상황에 마시기 딱 좋은 칵테일입니다." },
  ],
};
