import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "shoyojurin",
  category: "cocktail",
  title: "조엽수림 — 차의 길을 따라 걷는, 쌉쌀하고 고요한 숲 같은 한 잔",
  dek: "「조엽수림」은 그 기원에 대해서는 잘 알려지지 않은 칵테일입니다만, 일본 만화 바텐더에 따르면 산토리 스쿨에서 강사를 했었던 바텐더 '후쿠니시 에이조'에 의해서 만들어졌다고 합니다.",
  publishedAt: "2025-07-04",
  hero: "/articles/shoyojurin/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223921937397",
  relatedCocktailSlugs: ["shoyojurin"],
  blocks: [
    { kind: "figure", src: "/articles/shoyojurin/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "「조엽수림」은 그 기원에 대해서는 잘 알려지지 않은 칵테일입니다만, 일본 만화 바텐더에 따르면 산토리 스쿨에서 강사를 했었던 바텐더 '후쿠니시 에이조'에 의해서 만들어졌다고 합니다." },
    { kind: "paragraph", text: "조엽수림은 녹차 리큐르를 단독 기주로 하는데, 산토리 스쿨에서 만들어진 만큼, 산토리에서 생산하는 헤르메스 그린 티 리큐르가 원조일 것으로 보입니다. 산토리에서는 이 리큐르가 1950년대에 처음 발매됐다고 할 정도로 오래된 리큐르입니다." },
    { kind: "paragraph", text: "조엽수림은 '습기가 많은 곳에 분포되어 있는 상록 활엽수를 주로 한 삼림 군계'라고 하는데, 만화 바텐더에서는 히말라야 중턱에서 동남아시아, 중국, 한반도를 거쳐 일본에 이르는 차의 루트와 일치한다고 표현합니다." },
    { kind: "paragraph", text: "칵테일의 색과 스토리에 딱 맞는 이름이라는 뜻이죠. 저는 차에 대해서 잘 모르기 때문에 정말 신빙성 있는 이야기인지는 둘째로 치고..." },
    { kind: "figure", src: "/articles/shoyojurin/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Recipe" },
    { kind: "paragraph", text: "45ml 녹차 리큐르" },
    { kind: "paragraph", text: "120~135ml 우롱차" },
    { kind: "paragraph", text: "조엽수림은 녹차 리큐르 + 우롱차라는 차에 차를 더하는 특이한 칵테일입니다. 맛의 변화를 주는 재료가 적기 때문에 어떤 우롱차를 쓰느냐가 중요한데, 너무 맛이 연한 것은 피하도록 합시다." },
    { kind: "figure", src: "/articles/shoyojurin/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 차게 식혀둔 긴 잔에 얼음을 채운다." },
    { kind: "paragraph", text: "2. 녹차 리큐르를 넣고 살짝 스터해준다." },
    { kind: "paragraph", text: "3. 우롱차를 넣고, 얼음을 몇 번 올렸다 내려줍니다." },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 쌉쌀하고, 달큰한 차" },
    { kind: "paragraph", text: "- 살짝 쌉쌀하고 텁텁한 끝 맛" },
    { kind: "paragraph", text: "조엽수림은 도수도 낮은 편이고, 굳이 따지자면 달큰한 맛이 좀 있는 편에 속하는 칵테일이기 때문에 마시기 꽤나 편한 칵테일이며, 개인적으로는 식후 또는 마지막 한 잔으로 어울리는 칵테일이라 생각합니다." },
  ],
};
