import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "sloe-gin-fizz",
  category: "cocktail",
  title: "슬로 진 피즈 — 진 피즈의 새콤달콤한 변형",
  dek: "「슬로 진 피즈」는 일반적인 진 피즈(Gin Fizz)에서 기주를 진에서 슬로 진으로 변경한 아주 간단한 변형으로, 그 기원 자체는 명확하지 않지만 아무래도 슬로 진의 상업화와 칵테일 문화의 발전이 맞물리며 형성된 것으로 보입니다.",
  publishedAt: "2026-03-29",
  hero: "/articles/sloe-gin-fizz/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/224233308186",
  relatedCocktailSlugs: ["sloeginfizz"],
  blocks: [
    { kind: "figure", src: "/articles/sloe-gin-fizz/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「슬로 진 피즈」는 일반적인 진 피즈(Gin Fizz)에서 기주를 진에서 슬로 진으로 변경한 아주 간단한 변형으로, 그 기원 자체는 명확하지 않지만 아무래도 슬로 진의 상업화와 칵테일 문화의 발전이 맞물리며 형성된 것으로 보입니다." },
    { kind: "paragraph", text: "슬로진은 이전부터 영국 가정에서 많이 만들어지던 리큐르로, 토지 경계를 구분하기 위한 울타리에서 흔히 볼 수 있는 블랙손(Blackthorn) 가지의 열매인 슬로베리를 진에 침출하는 방식으로 만들어집니다." },
    { kind: "paragraph", text: "이 슬로베리는 그대로 먹기에는 떫고 신맛이 강하기 때문에 진에 담가 설탕과 함께 침출하기 시작했고, 단순히 병에 담아 만들 수 있을 정도로 간단했기 때문에 자연스럽게 가정에서 편하게 만들어 마실 수 있게 되었습니다." },
    { kind: "paragraph", text: "이 슬로 진의 역사는 생각보다 꽤나 오래되었는데, 진 브랜드 중 하나인 십스미스(Sipsmith)에서는 1717년에 쓰인 한 시에서 홈메이드 슬로 진이 사회적 병폐로 언급된 사례를 소개하기도 합니다." },
    { kind: "paragraph", text: "이렇게 영국 가정에서 만들어지던 슬로 진은 19세기 말 ~ 20세기 초에 영국에서 상업적으로 생산되기 시작하였다고 합니다." },
    { kind: "paragraph", text: "또한, 19세기 말에는 이미 여러 칵테일 관련 저서에서 다양한 기주의 피즈(Fizz)류 칵테일이 소개되었으며, 특히 제리 토마스의 저서 '바텐더스 가이드'의 1876년판 부록에서 'Fiz'라는 이름으로 여러 피즈류 칵테일이 소개됩니다." },
    { kind: "paragraph", text: "이러한 흐름을 종합해 보면, 슬로진피즈는 약 19세기 말에 탄생하지 않았을까 추정해 볼 수 있으며, 가정에서 만들어진 술이 상업화를 거쳐 바의 칵테일 문화로 편입된 독특한 이력의 칵테일이라 할 수 있습니다." },
    { kind: "figure", src: "/articles/sloe-gin-fizz/01.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "Ingredietns" },
    { kind: "paragraph", text: "45ml 슬로 진 (Sloe Gin)" },
    { kind: "paragraph", text: "20ml 레몬즙 (Lemon Juice)" },
    { kind: "paragraph", text: "10ml 심플 시럽(Simple Syrup)" },
    { kind: "paragraph", text: "탄산수 (Soda Water)" },
    { kind: "figure", src: "/articles/sloe-gin-fizz/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 탄산수 외의 재료를 셰이커에 넣는다" },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 넣고 셰이킹한다" },
    { kind: "paragraph", text: "3. 얼음을 채운 하이볼 잔에 부어준다" },
    { kind: "paragraph", text: "4. 탄산수를 적당량 2~3번에 나누어 부어준다" },
    { kind: "paragraph", text: "5. 바스푼으로 얼음을 위아래로 들어 섞어준다" },
    { kind: "paragraph", text: "슬로 진 피즈는 그 원형인 진 피즈와는 다르게 풍부한 과실미가 있는 칵테일로, 슬로 진의 도수가 26%이기 때문에 도수가 훨씬 낮아 알콜감이 느껴지지 않아 마시기 아주 편합니다." },
    { kind: "paragraph", text: "베리류 및 핵과류의 달큰한 과실감에 레몬의 상큼함이 더해져서 전체적으로 새콤달콤한 맛이 주를 이루고, 탄산이 더해져 가볍고 청량한 느낌을 줍니다. 개인적으로는 로즈시럽 같은 느낌도 살짝 있는 거 같네요." },
    { kind: "paragraph", text: "가볍고 새콤달콤한 맛으로 봄 ~ 여름에 마시기 딱 좋을 법한 칵테일입니다." },
    { kind: "paragraph", text: "탄산수를 따를 때, 거품이 확 올라오기 때문에 2~3번에 끊어서 조심조심히 넣는 게 팁이라면 팁이라 할 수 있겠네요" },
  ],
};
