import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "springbank-distillery-tour",
  category: "whisky",
  title: "스프링뱅크 증류소 투어 — 술 기행의 종착점",
  dek: "회사를 그만두고 친구를 끌고 아일라를 거쳐 캠벨타운까지. 스코틀랜드 위스키 여행의 마지막 목적지에서 남긴 기록.",
  publishedAt: "2024-12-15",
  hero: "/articles/springbank-distillery-tour/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223694261963",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/springbank-distillery-tour/00.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "스프링뱅크 증류소 샵을 들렀다가 건너편의 워시백 바에서 위스키를 마시다보니 어느새 증류소 투어를 할 시간이 왔다. 증류소 투어는 꼭 홈페이지에서 예약하고 가자." },
    { kind: "figure", src: "/articles/springbank-distillery-tour/01.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/02.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/03.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/04.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/05.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/06.webp", width: 966, height: 1717 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/07.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "스프링뱅크의 증류소 투어는 몰팅하는 것부터 발효, 증류의 과정을 쭉 설명해주는 식으로 이루어지며, 제가 기억하기로는 특히 자사의 플로어 몰팅과 맥아에 대해서 꽤 공들여서 설명해주는 듯한 인상이었다." },
    { kind: "paragraph", text: "사실 증류소를 방문한지 너무 오래됐기도 했고, 가이드를 해주신 직원의 억양이 상당히 강했어서 내용 자체는 그렇게 자세하게 기억나지는 않지만, 여느 증류소 투어에서나 나던 특유의 맥주향 비슷한 시큼한 발효향의 기억은 여전히 기억이 난다." },
    { kind: "figure", src: "/articles/springbank-distillery-tour/08.webp", width: 966, height: 544 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/09.webp", width: 966, height: 544 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/10.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "이후에는 작은 웨어하우스로 이동해서 숙성되고 있는 캐스크들을 구경할 수 있는데, 당연한 얘기지만 여기서는 캐스크에 정보가 적혀있지 않다. 다른 증류소는 그래도 몇몇은 캐스크 정보를 확인할 수 있었는데, 스프링뱅크 증류소는 완전히 캐스크 정보를 가리고 있더라." },
    { kind: "figure", src: "/articles/springbank-distillery-tour/11.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/12.webp", width: 966, height: 1288 },
    { kind: "paragraph", text: "마지막으로 스프링뱅크 10년, 헤이즐번, 롱로우의 기본 엔트리 라인 중 하나를 선택해서 시음하고, 시음한 잔과 투어 기념 미니 바틀 하나를 받으면 증류소 투어는 끝이 난다." },
    { kind: "paragraph", text: "투어 기념 미니 바틀은 물어보니 스프링뱅크 6년 숙성이라고 하며, 아마도 버번 캐스크라 했던 걸로 기억한다. 궁금하기는 한데, 이걸 오픈해서 마실 수나 있을지." },
    { kind: "paragraph", text: "단지 아일라와 스프링뱅크의 위스키를 좋아해서 회사를 퇴사까지 해서 친구를 끌고 아일라를 거쳐 캠벨타운까지 갔는데, 이 마지막 글을 쓰면서 돌아보니 지금 봐도 정말 현실감이 없는 경험이었다." },
    { kind: "figure", src: "/articles/springbank-distillery-tour/13.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/14.webp", width: 966, height: 1288 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/15.webp", width: 966, height: 725 },
    { kind: "figure", src: "/articles/springbank-distillery-tour/16.webp", width: 966, height: 543 },
    { kind: "paragraph", text: "증류소와 맛있는 위스키도 좋았지만, 그 사이사이의 사진으로는 온전히 담을 수 없는 자연의 풍경과 여유로움을 넋 놓고 즐겼던 것 같다. 음식은 대부분 맛없었지만." },
    { kind: "paragraph", text: "같이 갔던 친구와 다시 스코틀랜드를 가자는 약속을 했는데, 언제가 될지는 모르겠지만 그 현실성 없고, 기약 없는 약속이 또 기다려진다." },
  ],
};
