import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "spumoni",
  category: "cocktail",
  title: "스푸모니 — 부담 없이 마실 수 있는 캄파리와 자몽을 사용한 칵테일",
  dek: "스푸모니는 어디에서, 누가 만들었는지 어떤 단서도 없을 정도로 기원이 불명확한 칵테일입니다.",
  publishedAt: "2024-10-17",
  hero: "/articles/spumoni/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223622428420",
  relatedCocktailSlugs: ["spumoni"],
  blocks: [
    { kind: "figure", src: "/articles/spumoni/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "스푸모니는 어디에서, 누가 만들었는지 어떤 단서도 없을 정도로 기원이 불명확한 칵테일입니다." },
    { kind: "paragraph", text: "우리나라나 일본에서는 스푸모니는 그 이름이 \"거품이 나다\"라는 뜻의 이탈리아어 [spumare]에서 유래한 이탈리아에서 탄생한 칵테일로 잘 알려져 있습니다." },
    { kind: "paragraph", text: "그런데 재미있는 점은 서양에서는 오히려 이 스푸모니를 일본의 칵테일로 인식하고 있다는 점입니다. 한 이탈리아 음식 및 문화 전문가는 본인이 이탈리아에서 스푸모니라는 이름의 칵테일을 듣도보도 못했다고 할 정도입니다." },
    { kind: "paragraph", text: "심지어 피셀리노(Pisellino)라는 바의 매니저 존 뮬렌(Jon Mullen)은 본인 버전의 스푸모니를 소개하면서 칵테일을 좋아한다면 알만한 '바텐더'라는 이름의 일본 애니에서 스푸모니가 잠깐 언급된 것을 소개하기도 하였다고 합니다." },
    { kind: "paragraph", text: "사실 이탈리아에서 'Spumoni'라고 함은 전통적인 아이스크림을 이용한 디저트로 알려져 있으며, 스푸모니 칵테일과는 전혀 상관이 없는 것 같습니다." },
    { kind: "paragraph", text: "결국 스푸모니 칵테일과 이탈리아의 연관점은 사실 캄파리라는 이탈리아에서 만들어지는 리큐르 밖에 없습니다." },
    { kind: "paragraph", text: "그래서 개인적인 생각으로는 스푸모니의 이름이 \"이탈리아어 [spumare]에서 유래했다\"는 것이 와전되어 스푸모니 칵테일 자체가 이탈리아에서 유래했다고 받아들여지지 않았을까 싶습니다." },
    { kind: "figure", src: "/articles/spumoni/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "30ml 캄파리 (Campari)" },
    { kind: "paragraph", text: "45ml 자몽즙 (Grapefruit Juice)" },
    { kind: "paragraph", text: "60~75ml 토닉워터 (Tonic Water)" },
    { kind: "paragraph", text: "옵션 가니시: 자몽 조각" },
    { kind: "figure", src: "/articles/spumoni/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 긴 잔에 얼음을 채워줍니다." },
    { kind: "paragraph", text: "2. 잔에 캄파리와 자몽즙을 넣고 잠시 스터해줍니다." },
    { kind: "paragraph", text: "3. 얼음에 닿지 않게 토닉워터를 따라줍니다." },
    { kind: "paragraph", text: "4. 바스푼으로 얼음을 위아래로 들어줍니다." },
    { kind: "paragraph", text: "5. 가니시로 장식해줍니다." },
    { kind: "paragraph", text: "스푸모니는 캄파리의 쌉쌀하고 시트러시한 맛이 자몽과 정말 잘 어울리는 칵테일로, 사용하는 토닉워터에 따라 다르겠지만 과하게 달지는 않고, 약간은 쌉쌀한 칵테일입니다." },
    { kind: "paragraph", text: "도수도 상당히 낮아 누구든 편하게 즐길 수 있으며, 특히 캄파리의 쌉쌀한 맛 때문에 캄파리를 싫어하시는 분들도 맛있게 마실 수 있을 것 같습니다." },
    { kind: "paragraph", text: "개인적으로 캄파리를 정말 좋아하는 만큼 이 칵테일도 극호일 수 밖에 없네요." },
  ],
};
