import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "starward-solera",
  category: "spirits",
  title: "스타워드 솔레라",
  dek: "\"스타워드\"는 호주에서 생산되는 위스키로, \"스타워드 증류소\"는 2007년 호주의 국영 항공사인 콴타스(Qantas)의 격납고에서 처음 설립되었습니다.",
  publishedAt: "2024-08-11",
  hero: "/articles/starward-solera/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223544208786",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/starward-solera/00.webp", width: 533, height: 533 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "\"스타워드\"는 호주에서 생산되는 위스키로, \"스타워드 증류소\"는 2007년 호주의 국영 항공사인 콴타스(Qantas)의 격납고에서 처음 설립되었습니다." },
    { kind: "paragraph", text: "스타워드 위스키는 변덕스러운 멜버른의 날씨로 인해서 증발량이 많고, 비교적 짧은 시간의 숙성에도 풍부한 풍미를 가지게 되었습니다." },
    { kind: "paragraph", text: "\"스타워드 솔레라\"는 호주의 주정강화 와인인 아페라(Apera) 와인을 숙성했던 캐스크에서 숙성된 위스키인데, 이 아페라 와인은 호주 버전의 셰리 와인이라 할 수 있습니다." },
    { kind: "paragraph", text: "다만, 2000년대 중반부터 세계적으로 유럽 연합이 무역 협정 협상에서 샴페인, 스카치, 꼬냑 등과 같은 지리적 표시의 보호를 강력하게 요구하면서 호주의 셰리 와인 또한 영향을 받게 되었습니다." },
    { kind: "paragraph", text: "셰리 와인은 스페인의 헤레스(Jerez) 지역에서 생산되는 주정강화 와인으로, 원산지 증명과 지리적 표시 보호를 받아 이 지역에서 생산된 것이 아니면 '셰리'라는 이름을 사용하지 못합니다. 이로 인해 호주의 셰리 와인은 이름을 아페라 와인으로 변경하게 되었다고 합니다." },
    { kind: "paragraph", text: "아페라 와인 캐스크를 사용해서 셰리 위스키 숙성 방식인 '솔레라 방식'으로 위스키를 숙성한다고 하며, 간략히 얘기해서 가장 오래 숙성된 캐스크에서 위스키를 일정량 병입하고, 그만큼을 덜 숙성된 캐스크에서 채워 넣는 식의 일종의 계단식 숙성 시스템입니다." },
    { kind: "paragraph", text: "이런 숙성 방법으로 인해 스타워드에서는 \"오늘날 만들어진 모든 병에는 여전히 최초의 통이 약간 들어 있다는 것\"이라 이야기하고 있습니다." },
    { kind: "figure", src: "/articles/starward-solera/01.webp", width: 540, height: 540 },
    { kind: "quote", text: "증류소: 스타워드 증류소" },
    { kind: "quote", text: "위스키 타입: 오스트레일리아 싱글 몰트" },
    { kind: "quote", text: "캐스크 정보: 아페라 와인 배럴(Apera Wine Barrel)" },
    { kind: "quote", text: "보리 정보: 100% 호주산 보리" },
    { kind: "quote", text: "도수: 43%" },
    { kind: "figure", src: "/articles/starward-solera/02.webp", width: 501, height: 501 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "-시나몬이나 정향 같은 향신료" },
    { kind: "paragraph", text: "-달달한 건과일, 건포도" },
    { kind: "paragraph", text: "-바닐라" },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "-건과일" },
    { kind: "paragraph", text: "-살짝 달달한 카카오닙" },
    { kind: "paragraph", text: "-약간의 바닐라빈" },
    { kind: "paragraph", text: "-혀 끝에 남는 카라멜" },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "-건과일" },
    { kind: "paragraph", text: "-향신료" },
    { kind: "paragraph", text: "-흑설탕{?} 또는 카라멜" },
    { kind: "paragraph", text: "스타워드 노바보다는 좀 더 복잡하고, 달큰한 느낌입니다. 어딘가 셰리 캐스크를 사용한 스카치와 비슷한 인상이 드는 것이 스카치 위스키를 좋아하는 분들에게는 이 쪽이 좀 더 익숙한 맛이지 않을까 싶습니다." },
    { kind: "paragraph", text: "마실 당시에는 느끼지 못했는데, 테이스팅 노트를 보니 어느 정도 크리스마스 시즌의 슈톨렌을 연상시키기도 할 것 같습니다." },
  ],
};
