import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "starward-nova",
  category: "spirits",
  title: "스타워드 노바",
  dek: "\"스타워드\"는 호주에서 생산되는 위스키로, \"스타워드 증류소\"는 2007년 호주의 국영 항공사인 콴타스(Qantas)의 격납고에서 처음 설립되었습니다.",
  publishedAt: "2024-08-10",
  hero: "/articles/starward-nova/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223543055543",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/starward-nova/00.webp", width: 522, height: 522 },
    { kind: "heading", text: "About The Whisky" },
    { kind: "paragraph", text: "\"스타워드\"는 호주에서 생산되는 위스키로, \"스타워드 증류소\"는 2007년 호주의 국영 항공사인 콴타스(Qantas)의 격납고에서 처음 설립되었습니다." },
    { kind: "paragraph", text: "2015년에는 디아지오의 주류 스타트업 자금 조달 프로젝트인 '디스틸 벤처스(Distill Ventures)'의 지원을 받으면서 증류소를 확장할 수 있었고, 2016년에는 현재 위치인 멜버른(Melbourne)으로 이주하게 되었습니다." },
    { kind: "paragraph", text: "스타워드 위스키는 변덕스러운 멜버른의 날씨로 인해서 증발량이 많고, 비교적 짧은 시간의 숙성에도 풍부한 풍미를 가지게 되었습니다. 호주에서 생산되는 와인을 담았던 캐스크를 사용하면서 많은 주목을 받았으며, 이후에는 진저비어 캐스크, 라가불린 캐스크 등 재미있는 시도를 하기도 하였습니다." },
    { kind: "paragraph", text: "2022년에는 샌프란시스코 월드 스피릿 대회(San Francisco World Spirits Competition)에서 참가한 수 많은 증류소 중 가장 많은 상을 수상한 증류소가 되기도 하였습니다." },
    { kind: "paragraph", text: "\"스타워드 노바\"는 호주산 레드 와인 통에서 숙성된 것으로, 숙성 년수는 표기되지 않았습니다. \"스타워드 솔레라\"와 함께 국내에 수입되는 스타워드의 싱글 몰트 프로파일 중 코어 라인이라 할 수 있겠습니다." },
    { kind: "figure", src: "/articles/starward-nova/01.webp", width: 540, height: 540 },
    { kind: "quote", text: "증류소: 스타워드 증류소" },
    { kind: "quote", text: "위스키 타입: 오스트레일리아 싱글몰트" },
    { kind: "quote", text: "캐스크 정보: 호주산 레드 와인 통 (Australian Red Wine Barrel)" },
    { kind: "quote", text: "도수: 41%" },
    { kind: "figure", src: "/articles/starward-nova/02.webp", width: 540, height: 540 },
    { kind: "heading", text: "Nose" },
    { kind: "paragraph", text: "- 달달한 붉은 베리, 약간의 검붉은 포도 껍질" },
    { kind: "paragraph", text: "- 약간의 진저 캐릭터" },
    { kind: "paragraph", text: "- 약간의 우디함" },
    { kind: "paragraph", text: "- 요구르트(?)" },
    { kind: "heading", text: "Palate" },
    { kind: "paragraph", text: "- 바닐라, 흑설탕 내지는 캬라멜" },
    { kind: "paragraph", text: "- 라즈베리처럼 느껴질 수도 있는 약간의 탄닌감" },
    { kind: "paragraph", text: "- 살짝 크리미한 질감" },
    { kind: "heading", text: "Finish" },
    { kind: "paragraph", text: "- 처음 맡던 향과 거의 동일함" },
    { kind: "paragraph", text: "- 와인스러운 캐릭터" },
    { kind: "paragraph", text: "- 꽤 짧은 편임" },
    { kind: "paragraph", text: "스타워드 위스키는 국내에서는 아직까지 많이 알려지지 않은 위스키이지만, 개인적으로 뉴 월드 위스키에 대한 편견을 깨준 위스키로, 아주 좋아하는 브랜드입니다." },
    { kind: "paragraph", text: "스타워드 노바는 향에서는 생각보다 숙성감이 느껴지며, 전체적으로 저숙성임에도 레드 와인 캐스크의 특징이 나름대로 잘 갈무리된 위스키라 생각됩니다." },
  ],
};
