import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "stay-up-late",
  category: "cocktail",
  title: "스테이 업 레이트 — 화려한 느낌의 진 피즈",
  dek: "'스테이 업 레이트'는 미국의 언론인이자 작가였던 루시우스 비비(Lucius Beebe)가 1946년에 집필한 저서인 '스토크 클럽 바 북(The Stork Club Bar Book)'의 부록에 실린 칵테일입니다.",
  publishedAt: "2025-01-04",
  hero: "/articles/stay-up-late/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223714417131",
  relatedCocktailSlugs: ["stayuplate"],
  blocks: [
    { kind: "figure", src: "/articles/stay-up-late/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "'스테이 업 레이트'는 미국의 언론인이자 작가였던 루시우스 비비(Lucius Beebe)가 1946년에 집필한 저서인 '스토크 클럽 바 북(The Stork Club Bar Book)'의 부록에 실린 칵테일입니다." },
    { kind: "paragraph", text: "이 '스토크 클럽'은 1929~1965까지 운영되던 뉴욕 맨해튼의 유명했던 나이트클럽으로, 운영 당시 많은 유명인이 찾았던 클럽이라고 합니다." },
    { kind: "paragraph", text: "재밌는 점은 이 '스토크 클럽 바 북의 부록'은 스토크 클럽의 스태프들을 취재하여 추가한 칵테일 리스트로, 이 칵테일은 클럽의 모자 관리 부서의 '베로니카 해롤드(Veronica Harrold)'에 의하여 추가되었다고 합니다." },
    { kind: "paragraph", text: "그녀가 만든 칵테일인지는 알 수는 없지만, 나이트클럽과 정말 잘 어울리는 작명이라 할 수 있겠네요." },
    { kind: "figure", src: "/articles/stay-up-late/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "왼쪽의 레시피는 제가 조정한 레시피이고, 원래 오리지널 레시피는 비율이 꽤 다른 편입니다. 혹시 비교해보실 분들을 위해 오리지널 레시피를 같이 첨부해두겠습니다." },
    { kind: "figure", src: "/articles/stay-up-late/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 탄산수를 제외한 재료를 셰이커에 넣어줍니다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹해줍니다." },
    { kind: "paragraph", text: "3. 긴 잔에 얼음을 채우고, 셰이커에서 부어줍니다." },
    { kind: "paragraph", text: "4. 탄산수를 적당량 부어줍니다." },
    { kind: "paragraph", text: "5. 얼음을 위아래로 살짝 들었다 놔줍니다." },
    { kind: "paragraph", text: "6. 레몬 껍질에서 오일을 짜주고," },
    { kind: "paragraph", text: "잘 다듬어서 넣어줍니다." },
    { kind: "paragraph", text: "스테이 업 레이트는 구조 자체는 진피즈에 꼬냑을 살짝 더해준 것인데, 마치 사이드카와 진 피즈를 매시업한 것 같은 맛으로, 꽤나 화려한 느낌의 진 피즈라 할 수 있을 것 같습니다." },
    { kind: "paragraph", text: "서양에서는 톰 콜린스의 변형이라 보고 있는데, 아마 서양에서는 진 피즈에 계란 흰자를 사용하는 게 일반적이여서 그런 것 같습니다." },
    { kind: "paragraph", text: "사용하는 주류의 종류가 꽤나 중요할 것 같은 맛인데, 제가 만든 건 레미 마틴의 시트러시함과 달달한 꼬냑의 카라멜 느낌이 도드라지고, 마지막에 탱커레이 넘버 텐의 후추 같은 향신료가 킥을 줍니다." },
    { kind: "paragraph", text: "개인적으로 이 칵테일을 좋아하는 이유는 진과 꼬냑을 함께 사용하는 재밌는 조합도 있지만, 유자가 전혀 들어가진 않지만 뭔가 유자청 같은 맛을 만들어낸다는 점으로, 한 번쯤은 마셔보시는 걸 추천드립니다." },
  ],
};
