import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "talisker-port-ruighe",
  category: "spirits",
  title: "탈리스커 포트 리",
  dek: "스카이(Skye)섬에서 가장 큰 마을이자 항구인",
  publishedAt: "2021-10-03",
  hero: "/articles/talisker-port-ruighe/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/222525449933",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/talisker-port-ruighe/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "위스키 이야기" },
    { kind: "paragraph", text: "이 위스키는 탈리스커 디스틸러리가 있는" },
    { kind: "paragraph", text: "스카이(Skye)섬에서 가장 큰 마을이자 항구인" },
    { kind: "paragraph", text: "포트리(Portree)의 이름에서 따왔다고 합니다." },
    { kind: "paragraph", text: "다만 스펠링이 다른데, 이는 게일어로 발음상 포트 리가 된다고 합니다." },
    { kind: "paragraph", text: "이 위스키는 포트 캐스크에서 마지막으로 잠시 숙성되었는데" },
    { kind: "paragraph", text: "위스키의 이름인 포트 리와 라임을 잘 맞췄다는 게 재미있는 점이고," },
    { kind: "paragraph", text: "아마 디스틸러리에서 작명을 할 때 이를 감안한 것 같습니다." },
    { kind: "paragraph", text: "2013년 탈리스커의 정규 라인으로서 릴리즈되었지만" },
    { kind: "paragraph", text: "국내에 들어온 지는 오래되지 않은 것 같습니다." },
    { kind: "figure", src: "/articles/talisker-port-ruighe/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "향" },
    { kind: "paragraph", text: "탈리스커의 향이 아주 부드럽게 나며, 그 너머로 과실향이 납니다." },
    { kind: "paragraph", text: "탈리스커 10년은 알콜 향이 조금 튀는 반면에," },
    { kind: "paragraph", text: "탈리스커 포트 리는 전혀 그런 향이 없고 아주 점잖습니다." },
    { kind: "paragraph", text: "탈리스커 라인 중에서는 가장 점잖고 밸런스가 잡힌 향을 가지고 있지 않을까 생각됩니다." },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "탈리스커의 맛을 잃지 않으나 훨씬 부드럽고 프루티합니다." },
    { kind: "paragraph", text: "개인적으로 탈리스커 10년보다 짠맛이 더 잘 느껴지는 것 같은데" },
    { kind: "paragraph", text: "거의 소금을 혀에 직접 대는 정도의 짠맛이 느껴질 정도였습니다." },
    { kind: "paragraph", text: "처음 오픈 했을 때는 잘 몰랐었는데," },
    { kind: "paragraph", text: "에어링이 진횅된 이후로는 달달한 과실과 은은한 꿀의 맛이 나기도 합니다." },
    { kind: "heading", text: "여운" },
    { kind: "paragraph", text: "맛에서 느껴진 것과 거의 비슷한 향이 피니쉬에도 이어집니다." },
    { kind: "paragraph", text: "탈리스커 특유의 피트향이 나며, 여기에 포트 캐스크의 캐릭터가 약간 더해지면서" },
    { kind: "paragraph", text: "아주 둥글둥글한 피니쉬를 만들어냅니다." },
    { kind: "paragraph", text: "인스타그램" },
  ],
};
