import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "vesper",
  category: "cocktail",
  title: "베스퍼 — 제임스 본드가 사랑한 칵테일",
  dek: "이언 플레밍이 쓰고 제임스 본드가 바텐더에게 직접 읊은 레시피. 진 3, 보드카 1, 릴레 블랑 0.5의 파괴적인 한 잔.",
  publishedAt: "2025-08-16",
  hero: "/articles/vesper/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223972463957",
  relatedCocktailSlugs: ["vesper"],
  blocks: [
    { kind: "figure", src: "/articles/vesper/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About the Cocktail" },
    { kind: "paragraph", text: "「베스퍼」는 이언 플레밍(Ian Fleming)의 소설 카지노 로얄(Casino Royale)에서 제임스 본드가 바텐더에게 직접 레시피를 읊어주는 것으로 처음 등장하며, 베스퍼 마티니(Vesper Martini)라고 불리기도 합니다." },
    { kind: "quote", text: "Three measures of Gordon's, one of vodka, half a measure of Kina Lillet." },
    { kind: "quote", text: "Shake it very well until it's ice-cold, then add a large thin slice of lemon peel. Got it?" },
    { kind: "paragraph", text: "저는 소설을 보지는 않았지만, 다니엘 크레이그 주연의 007 시리즈에서도 이 칵테일이 등장하는데, 역시 2006년에 개봉한 007 카지노 로얄에서 등장하게 됩니다." },
    { kind: "paragraph", text: "영화에서는 꽤나 로맨틱하고 애틋한 장치로 쓰이기도 하는데, 연인인 베스퍼 린드에게 이 칵테일의 이름을 '베스퍼'라 해야겠다고 하면서 그 이유를 \"한 번 맛보고 나면 다른 건 마실 수 없기 때문\"이라고 합니다." },
    { kind: "paragraph", text: "속편에서는 볼리비아로 향하는 비행기의 바에 합류한 매티스가 무슨 술을 마시냐고 묻자, 본드가 대답을 못하는 와중에 바텐더가 위의 레시피를 읊어줍니다. 이때, 본드는 이 술을 6잔이나 마신 상태라 하는데, 베스퍼에 대한 그리움과 애틋함을 은근하게 드러냅니다." },
    { kind: "figure", src: "/articles/vesper/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Recipe" },
    { kind: "paragraph", text: "45ml 진" },
    { kind: "paragraph", text: "15ml 보드카" },
    { kind: "paragraph", text: "7.5-10ml 릴레 블랑" },
    { kind: "paragraph", text: "레몬 껍질" },
    { kind: "paragraph", text: "재료로 들어가는 진, 보드카, 릴레 블랑이 3 : 1 : 0.5의 비율로 들어가는, 거의 술을 때려 붓다시피 하는 파괴적인 레시피입니다." },
    { kind: "paragraph", text: "원래는 퀴닌이 들어가는 키나 릴레(Kina Lillet)를 사용하는데, 1986년에 릴레에서 쓴맛을 내는 퀴닌의 함량을 줄이고, 단맛을 높이는 식으로 레시피를 변경하며, 이름을 현재의 릴레 블랑으로 바꾸게 됩니다." },
    { kind: "paragraph", text: "몇몇 바텐더들의 말로는 '코키 아메리카노(Cocchi Americano)'가 그래도 키나 릴레와 좀 더 가깝다고 하니 맛을 비교해 보는 것도 재미있을 것 같습니다." },
    { kind: "figure", src: "/articles/vesper/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 레몬 껍질 이외의 재료를 셰이커에 넣는다." },
    { kind: "paragraph", text: "2. 셰이커에 얼음을 채우고, 셰이킹한다." },
    { kind: "paragraph", text: "3. 잔에 따른 후, 레몬 껍질에서 오일을 짜준다." },
    { kind: "paragraph", text: "4. 레몬 껍질을 다듬어서 장식한다(옵션)." },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 잔을 입에 가져대면 자연스럽게 나는 기분 좋은 레몬향" },
    { kind: "paragraph", text: "- 보태니컬, 허브와 약간의 술 자체의 단맛" },
    { kind: "paragraph", text: "- 살짝 느껴지는 릴레의 와인스러운 뉘앙스" },
    { kind: "paragraph", text: "- 비교적 깔끔하고, 깨끗한 맛" },
    { kind: "paragraph", text: "베스퍼는 재료 대부분의 양을 진과 보드카가 차지하기 때문에 도수가 상당히 높은 칵테일이며, 맛에 변화를 줄 수 있는 요소가 그렇게 많지는 않습니다." },
    { kind: "paragraph", text: "'왜 술만 들어가는데 셰이킹을 하지?'라는 근본적인 의문이 생길 수 있는데, 아마 다음과 같은 이유를 들 수 있지 않을까 싶습니다." },
    { kind: "paragraph", text: "- '스팅어'처럼 술만 들어가더라도 셰이킹은 할 수 있다." },
    { kind: "paragraph", text: "- 마티니를 셰이킹해서 마시는 제임스 본드의 취향이 반영된 것." },
    { kind: "paragraph", text: "물론, 스터를 해서 만들더라도 전혀 문제는 없고, 가장 큰 차이는 칵테일에 들어가게 되는 물의 양이지 않을까 싶습니다. 술만 들어갔기 때문에 액체에 주입된 공기도 금방 빠지는 거 같기도 하구요." },
    { kind: "paragraph", text: "개인적으로는 원작처럼 셰이킹을 하는 걸 더 좋아하는데, 물이 좀 들어가야 알콜이 안튀는 것 같아서 그런 것 같습니다." },
  ],
};
