import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "vieux-carre",
  category: "cocktail",
  title: "뷰 카레 — 뉴올리언스에서 탄생한 맨하탄의 허브감 있는 변형",
  dek: "\"뷰 카레\"는 1938년 뉴올리언스(New Orleans)의 호텔 몬텔레온(Hotel Monteleone)에 있는 바의 헤드 바텐더 월터 버저론(Walter Bergeron)에 의해 만들어졌습니다.",
  publishedAt: "2024-10-01",
  hero: "/articles/vieux-carre/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223603174986",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/vieux-carre/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "About The Cocktail" },
    { kind: "paragraph", text: "\"뷰 카레\"는 1938년 뉴올리언스(New Orleans)의 호텔 몬텔레온(Hotel Monteleone)에 있는 바의 헤드 바텐더 월터 버저론(Walter Bergeron)에 의해 만들어졌습니다." },
    { kind: "paragraph", text: "뷰 카레는 프랑스어로 '오래된 광장'을 의미하며, 뉴올리언스의 프렌치 쿼터(French Quarter) 지역을 지칭하기도 합니다." },
    { kind: "paragraph", text: "이 칵테일은 맨하탄과 보비 번스라는 칵테일을 뉴올리언스 식으로 매시업한 느낌의 칵테일이며, 미국에 위치한 프랑스어로 된 지명의 이름을 기리기 위해서인지 기주를 라이 위스키와 꼬냑을 반반으로 만드는 특이한 레시피를 가지고 있습니다." },
    { kind: "paragraph", text: "뉴올리언스에서는 사제락(Sazerac)이나 라모스 진 피즈(Ramos Gin Fizz) 같이 현재에도 사랑 받는 클래식 칵테일이 만들어졌는데, 뷰 카레는 클래식 칵테일이라 하기에는 그만큼의 인지도를 얻지는 못했습니다." },
    { kind: "figure", src: "/articles/vieux-carre/01.webp", width: 966, height: 966 },
    { kind: "heading", text: "Ingredients" },
    { kind: "paragraph", text: "22.5ml 라이 위스키 (Rye Whiskey)" },
    { kind: "paragraph", text: "22.5ml 꼬냑 (Cognac)" },
    { kind: "paragraph", text: "22.5ml 스윗 버무스 (Sweet Vermouth)" },
    { kind: "paragraph", text: "7.5-10ml 베네딕틴 돔 (Benedictine DOM)" },
    { kind: "paragraph", text: "앙고스투라 비터 2대시" },
    { kind: "paragraph", text: "(Angostura Aromatic Bitters)" },
    { kind: "paragraph", text: "페이쇼드 비터 2대시" },
    { kind: "paragraph", text: "(Peychaud's Bitters)" },
    { kind: "paragraph", text: "가니시: 레몬 껍질, 마라스키노 체리(옵션)" },
    { kind: "figure", src: "/articles/vieux-carre/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "How to Mix" },
    { kind: "paragraph", text: "1. 가니시 이외의 재료를 믹싱 글라스에 넣어줍니다." },
    { kind: "paragraph", text: "2. 믹싱 글라스에 얼음을 채우고, 스터 해줍니다." },
    { kind: "paragraph", text: "3. 차게 해 둔 온더락 잔에 얼음을 채우고, 칵테일을 부어줍니다." },
    { kind: "paragraph", text: "4. 레몬 껍질을 짜서 오일을 뿌려줍니다." },
    { kind: "paragraph", text: "5. 마라스키노 체리를 하나 넣어줍니다(옵션)." },
    { kind: "paragraph", text: "뷰 카레는 체리 맛 술은 들어가지 않지만 어딘가 마라스키노 체리나 포도 껍질 같은 달달한 맛이은은한 허브의 캐릭터와 함께 납니다. 아마 재료의 조합에서 나오는 맛이겠죠." },
    { kind: "paragraph", text: "베네딕틴의 허브감과 달달함이 은은하게 느껴지면서 스윗 버무스의 달달함, 꼬냑의 화사함과 라이 위스키의 스파이시함이 입체적으로 느껴집니다." },
    { kind: "paragraph", text: "시럽 없이 술만 들어갔지만, 높은 도수감을 잊을 정도로 생각보다 달달하기도 합니다." },
    { kind: "paragraph", text: "꽤나 맨하탄이 생각나는 맛이기도 한데 구조적으로 맨하탄에 베네딕틴이 들어간 것이라고 볼 수도 있을 것 같습니다." },
    { kind: "paragraph", text: "칵테일의 밸런스는 칼끝을 타는 것처럼 아슬아슬할 정도로 절묘하다고 생각합니다만, 사람에 따라서는 밸런스가 좋지 않다고 할 수도 있을 것 같은 칵테일입니다." },
  ],
};
