import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "white-negroni",
  category: "cocktail",
  title: "화이트 네그로니 — 클래식의 무게감을 덜어, 밝고 섬세하게 해석한 프렌치식 변주",
  dek: "「화이트 네그로니」는 현대에 만들어진 네그로니의 변형 중 아마 가장 유명한 칵테일이지 않을까 싶습니다.",
  publishedAt: "2025-06-06",
  hero: "/articles/white-negroni/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223890597534",
  relatedCocktailSlugs: ["whitenegroni"],
  blocks: [
    { kind: "figure", src: "/articles/white-negroni/00.webp", width: 966, height: 966 },
    { kind: "heading", text: "칵테일 이야기" },
    { kind: "paragraph", text: "「화이트 네그로니」는 현대에 만들어진 네그로니의 변형 중 아마 가장 유명한 칵테일이지 않을까 싶습니다." },
    { kind: "paragraph", text: "2001년 여름, 당시 플리머스 진(Plymouth)의 디렉터였던 닉 블랙넬(Nick Blacknell)은 주류 박람회(Vinexpo)에 참여하기 위해, 런던의 바텐더 웨인 콜린스(Wayne Collins)는 칵테일 경연 대회에 참여하기 위해 프랑스로 향했습니다." },
    { kind: "paragraph", text: "두 사람은 대회 전날에 보르도(Bordeaux) 근처 메독(Medoc)의 한 게스트 하우스에서 머물렀는데, 매우 더운 날씨로 인해서 아주 차갑고, 상쾌한 네그로니를 마시고 싶어졌습니다." },
    { kind: "figure", src: "/articles/white-negroni/01.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "그러나 마을은 너무 작고 시골이라 괜찮은 바가 없어 보였고, 둘은 마을 리쿼샵에 들어가서 네그로니의 재료를 찾기로 하는데, 여기서 콜린스는 '프랑스 재료로 네그로니를 만들어보자'는 아이디어를 내게 됩니다." },
    { kind: "paragraph", text: "그렇게 해서 캄파리처럼 쌉쌀하고 단맛이 나는 프랑스의 아페리티프인 수즈(Suze)와 와인 베이스 아페리티프인 릴레 블랑(Lillet Blanc)에 플리머스 진을 사용해서 이 칵테일이 만들어집니다." },
    { kind: "paragraph", text: "블랙넬은 이 칵테일을 '화이트 네그로니'라 부르자고 했는데, 네그로니의 색인 어두운 적갈색이니 완전히 반대되게 '화이트'로 부르자고 한 것 같은데, 실상은 금색 또는 노란색에 가깝죠." },
    { kind: "figure", src: "/articles/white-negroni/02.webp", width: 966, height: 966 },
    { kind: "heading", text: "레시피" },
    { kind: "paragraph", text: "45ml 진" },
    { kind: "paragraph", text: "30ml 릴레 블랑" },
    { kind: "paragraph", text: "22.5ml 수즈" },
    { kind: "paragraph", text: "가니시: 레몬 껍질(or 자몽 껍질)" },
    { kind: "paragraph", text: "*화이트 네그로니는 처음에는 네그로니의 변형이니 만큼 1:1:1의 비율로 만들어졌을 것으로 보이긴 하지만, 시간이 지나면서 다양한 비율의 레시피가 생기게 됩니다. 그러니 만들어보고 입맛에 가장 잘 맞는 비율을 골라주시면 됩니다." },
    { kind: "figure", src: "/articles/white-negroni/03.webp", width: 966, height: 966 },
    { kind: "heading", text: "만드는 법" },
    { kind: "paragraph", text: "1. 락 글라스에 모든 재료를 넣는다." },
    { kind: "paragraph", text: "2. 얼음을 채워주고, 스터한다." },
    { kind: "paragraph", text: "3. 레몬 껍질의 오일을 잔 위에 뿌려준다." },
    { kind: "paragraph", text: "4. 사용한 레몬 껍질을 다듬어서 넣어준다." },
    { kind: "heading", text: "맛" },
    { kind: "paragraph", text: "- 진의 도수감과 보타니컬함이 중심을 잡아줌" },
    { kind: "paragraph", text: "- 수즈의 달큰하면서도 살짝 쌉쌀한 뿌리 식물 캐릭터가 은은하게 나타남" },
    { kind: "paragraph", text: "- 릴레의 달큰한 와인 캐릭터가 생각보다 이 칵테일의 밸런스를 맞추려 노력하는 느낌" },
    { kind: "paragraph", text: "- 클래식 네그로니보다 한껏 가볍고, 섬세한 캐릭터" },
    { kind: "paragraph", text: "화이트 네그로니는 일반적인 네그로니를 생각하고 마시게 된다면 고개를 갸웃할 수 있는 맛이기는 합니다만, 캄파리와 수즈 모두 뿌리 식물 캐릭터를 가지고 있는 만큼 어느정도는 공유하는 캐릭터가 있습니다." },
    { kind: "paragraph", text: "당연히 비율마다 맛이 다르게 되는데, 재료들 간의 밸런스를 맞추는 것이 정말 어려운 칵테일이라 생각되며, 가니시는 자몽 껍질이나 자몽 웨지가 좀 더 쌉쌀한 맛을 살려줄 수 있어서 잘 어울린다고 생각합니다." },
    { kind: "paragraph", text: "수즈 경우, 저는 해외직구를 했는데, 우리나라로는 수입되지 않는 제품입니다. 그래도 맛이 좀 다르긴 하지만 아베제(Aveze)라는 수즈와 같이 용담(Gentain) 리큐르가 수입되기는 하니 참고해주세요." },
  ],
};
