import type { Article } from "../types";

export const ARTICLE: Article = {
  slug: "yukiguni",
  category: "cocktail",
  title: "설국",
  dek: "설국은 일본에서 만들어진 일본의 스탠다드 칵테일(클래식 칵테일)로, 바텐더 이야마 케이이치에 의해 만들어졌습니다.",
  publishedAt: "2024-02-08",
  hero: "/articles/yukiguni/00.webp",
  sourceUrl: "https://blog.naver.com/shakinglikebartender/223348256651",
  relatedCocktailSlugs: [],
  blocks: [
    { kind: "figure", src: "/articles/yukiguni/00.webp", width: 966, height: 725 },
    { kind: "paragraph", text: "About the Drink" },
    { kind: "paragraph", text: "설국은 일본에서 만들어진 일본의 스탠다드 칵테일(클래식 칵테일)로, 바텐더 이야마 케이이치에 의해 만들어졌습니다. 이야마 옹은 1958년 산토리(당시에는 코토부키야)가 주최하는 제3회 홈 칵테일 콩쿨에서 설국으로 우승(1959년 수상)을 하였고, 이후 칵테일이 유명세를 타면서 일본의 스탠다드 칵테일로 자리 잡았다고 합니다." },
    { kind: "paragraph", text: "이야마 옹은 1955년 본인의 고향인 야마가타현 사카타시 바&카페인 ‘쾰른’을 개업했으며, 90이 넘은 나이에도 바에 서서 설국을 만들었다고 하며, 2021년 5월 10일 오래된 바텐더 생활을 마치고 고인이 되었다고 합니다." },
    { kind: "paragraph", text: "현재에는 아들이 자리를 이어받아 운영하고 있는 것으로 보이는데, 구글 맵에는 폐업이라 되어있으나 잘못된 정보인 것 같고, 아직까지 ‘쾰른’에서는 유키구니가 만들어지고 있습니다." },
    { kind: "paragraph", text: "2018년에는 이 칵테일에 대한 영화 <YUKIGUNI>가 일본에서 만들어졌을 정도로 꽤나 인기 있는 칵테일이었지 않았을까 생각해봅니다." },
    { kind: "paragraph", text: "잔의 림에 장식된 설탕이 눈을 형상화하며, 녹색의 체리는 겨울의 눈 밑에서 봄을 힘차게 기다리고 있는 녹색(생명력?)을 형상화한 것이라 하며, 꽤나 직관적이면서도 이름이 걸맞는 칵테일입니다." },
    { kind: "figure", src: "/articles/yukiguni/01.webp", width: 966, height: 725 },
    { kind: "heading", text: "재료" },
    { kind: "paragraph", text: "40ml 보드카" },
    { kind: "paragraph", text: "10ml 화이트 큐라소" },
    { kind: "paragraph", text: "10ml 라임 코디얼" },
    { kind: "paragraph", text: "가니쉬: 설탕 리밍 & 녹색 체리" },
    { kind: "figure", src: "/articles/yukiguni/02.webp", width: 966, height: 725, caption: "설탕을 리밍할 때는 잔 안으로 설탕이 들어가지 않게 하자" },
    { kind: "paragraph", text: "How to Mix?" },
    { kind: "paragraph", text: "1. 잔 바깥 부분에 설탕을 묻히고," },
    { kind: "paragraph", text: "녹색 체리를 잔 안에 떨어뜨려줍니다." },
    { kind: "paragraph", text: "*잔 안쪽으로 설탕이 묻지 않도록 주의할 것!" },
    { kind: "paragraph", text: "2. 가니쉬 이외의 재료를 쉐이커에 넣어줍니다." },
    { kind: "paragraph", text: "3. 쉐이킹 후 잔에 따라줍니다." },
    { kind: "figure", src: "/articles/yukiguni/03.webp", width: 966, height: 966 },
    { kind: "paragraph", text: "먼저 재료에 있어서 생라임즙을 사용할지, 라임 코디얼을 사용할지 헷갈릴 수 있습니다. 몇몇 레시피에서도 생라임즙을 사용하는 경우가 있기도 합니다." },
    { kind: "paragraph", text: "다만, 설국이 만들어진 1958년 당시에는 일본에서 라임을 구하기가 어려웠을테니 라임 코디얼을 사용했지 않을까라는 추론이 가능합니다." },
    { kind: "paragraph", text: "무엇보다 원작자인 이야마 옹이 메이킹하는 영상을 보면 산토리의 라임 코디얼을 사용하고 있는 것을 볼 수 있으며, 참고로 화이트 큐라소, 보드카 모두 산토리의 제품을 사용하는 것을 보아 오리지널은 라임 코디얼을 사용한 것이 아닐까 어느 정도 확신할 수 있습니다. 설탕의 경우는 상백당을 믹서기에 갈아서 사용한다는 것 같습니다." },
    { kind: "paragraph", text: "다만, 오리지널을 마셔보고 본인의 입맛에 맞게 변형하는 것도 하나의 재미이니 오리지널부터 마셔보시는 걸 추천드립니다." },
    { kind: "paragraph", text: "도수가 꽤나 높지만 알콜감이 그렇게 심하지는 않으며, 단맛과 신맛이 은근히 밸런스 좋게 느껴진 점이 꽤 마음에 들었습니다. 생즙을 사용하지 않아 어딘가 올드한 정취가 들기도 하는 칵테일이기도 합니다." },
    { kind: "paragraph", text: "좀 더 많은 칵테일 정보는" },
  ],
};
