-- ISSUE-036 — 프로토타입 재료 마스터 77종 시드 (SPEC-01 §6 · SPEC-06 §6).
--
-- ⚠️ **손으로 고치지 않는다.** `packages/domain/src/data.ts` 를 고치고
--    `npx tsx scripts/seed-from-prototype.ts` 로 다시 만든다.
--    변환 규칙은 그 스크립트에 있고, 그것이 이관 근거다.

INSERT INTO ingredient (slug, name_ko, name_en, aliases, category, domestic_availability, is_approved)
VALUES
    ('absinthe', '압생트', 'Absinthe', '{}', 'spirit', 'common', true),
    ('angostura-bitters', '앙고스투라 비터스', 'Angostura Bitters', ARRAY['앙고스투라 비터', '앙고스투라 아로마틱 비터']::TEXT[], 'bitters', 'common', true),
    ('banana-liqueur', '바나나 리큐르', 'Banana Liqueur', '{}', 'liqueur', 'common', true),
    ('barbados-rum', '바베이도스 럼', 'Barbados Rum', '{}', 'spirit', 'common', true),
    ('benedictine-dom', '베네딕틴 돔', 'Bénédictine DOM', '{}', 'liqueur', 'specialty', true),
    ('blanco-tequila', '블랑코 데킬라', 'Blanco Tequila', '{}', 'spirit', 'common', true),
    ('blended-scotch', '블렌디드 스코치', 'Blended Scotch', '{}', 'spirit', 'common', true),
    ('blue-curacao', '블루 큐라소', 'Blue Curaçao', '{}', 'liqueur', 'common', true),
    ('bourbon', '버번', 'Bourbon', '{}', 'spirit', 'common', true),
    ('bourbon-rye', '버번 또는 라이', 'Bourbon / Rye', '{}', 'spirit', 'common', true),
    ('bourbon-whiskey', '버번 위스키', 'Bourbon Whiskey', '{}', 'spirit', 'common', true),
    ('calvados', '칼바도스', 'Calvados', '{}', 'spirit', 'common', true),
    ('campari', '캄파리', 'Campari', '{}', 'liqueur', 'common', true),
    ('cherry', '마라스키노 체리', 'Cherry', '{}', 'garnish', 'common', true),
    ('citron-vodka', '시트론 보드카', 'Citron Vodka', '{}', 'spirit', 'common', true),
    ('citrus-shrub-syrup', '시트러스 슈럽 시럽', 'Citrus Shrub Syrup', '{}', 'syrup', 'specialty', true),
    ('coconut-cream', '코코넛 크림', 'Coconut Cream', '{}', 'syrup', 'common', true),
    ('coffee-liqueur', '커피 리큐어', 'Coffee Liqueur', '{}', 'liqueur', 'common', true),
    ('cointreau', '코앵트로', 'Cointreau', ARRAY['쿠앵트로']::TEXT[], 'liqueur', 'common', true),
    ('cranberry-juice', '크랜베리 주스', 'Cranberry Juice', '{}', 'juice', 'common', true),
    ('creme-de-cassis', '크렘 드 카시스', 'Crème de Cassis', '{}', 'liqueur', 'common', true),
    ('dark-rum', '다크 럼', 'Dark Rum', '{}', 'spirit', 'common', true),
    ('distilled-soju', '증류식 소주', 'Distilled Soju', '{}', 'spirit', 'common', true),
    ('dry-gin', '진', 'Dry Gin', '{}', 'spirit', 'common', true),
    ('dry-vermouth', '드라이 베르무트', 'Dry Vermouth', '{}', 'liqueur', 'common', true),
    ('egg-white', '달걀 흰자', 'Egg White', '{}', 'garnish', 'common', true),
    ('espresso', '에스프레소', 'Espresso', '{}', 'juice', 'common', true),
    ('fino-sherry', '피노 셰리', 'Fino Sherry', '{}', 'liqueur', 'specialty', true),
    ('ginger-beer', '진저비어', 'Ginger Beer', '{}', 'mixer', 'common', true),
    ('grapefruit-juice', '자몽 주스', 'Grapefruit Juice', '{}', 'juice', 'common', true),
    ('grapefruit-slice', '자몽 조각', 'Grapefruit Slice', '{}', 'garnish', 'common', true),
    ('grapefruit-soda', '자몽 소다', 'Grapefruit Soda', '{}', 'mixer', 'common', true),
    ('green-tea-liqueur', '녹차 리큐르', 'Green Tea Liqueur', '{}', 'liqueur', 'specialty', true),
    ('honey-ginger-syrup', '생강 꿀 시럽', 'Honey-Ginger Syrup', '{}', 'syrup', 'common', true),
    ('islay-single-malt', '아일라 싱글몰트', 'Islay Single Malt', '{}', 'spirit', 'specialty', true),
    ('jamaican-rum', '자메이카 럼', 'Jamaican Rum', '{}', 'spirit', 'common', true),
    ('jocheong-syrup', '조청 시럽', 'Jocheong Syrup', '{}', 'syrup', 'specialty', true),
    ('lager-beer', '맥주', 'Lager Beer', '{}', 'liqueur', 'common', true),
    ('lemon-juice', '레몬 주스', 'Lemon Juice', '{}', 'juice', 'common', true),
    ('lemon-peel', '레몬 필', 'Lemon Peel', '{}', 'garnish', 'common', true),
    ('lemon-wheel', '레몬 휠', 'Lemon Wheel', '{}', 'garnish', 'common', true),
    ('lillet-blanc', '릴레 블랑', 'Lillet Blanc', '{}', 'liqueur', 'specialty', true),
    ('lime', '라임', 'Lime', '{}', 'garnish', 'common', true),
    ('lime-juice', '라임 주스', 'Lime Juice', '{}', 'juice', 'common', true),
    ('lime-wedge', '라임 웨지', 'Lime Wedge', '{}', 'garnish', 'common', true),
    ('lychee-liqueur', '리치 리큐르', 'Lychee Liqueur', '{}', 'liqueur', 'specialty', true),
    ('makgeolli', '막걸리', 'Makgeolli', '{}', 'liqueur', 'common', true),
    ('milk', '우유', 'Milk', '{}', 'juice', 'common', true),
    ('mint', '민트', 'Mint', '{}', 'garnish', 'common', true),
    ('munbaeju-40', '문배주 40도', 'Munbaeju 40%', '{}', 'spirit', 'common', true),
    ('oolong-tea', '우롱차', 'Oolong Tea', '{}', 'juice', 'common', true),
    ('orange-bitters', '오렌지 비터', 'Orange Bitters', ARRAY['오렌지 비터스']::TEXT[], 'bitters', 'common', true),
    ('orange-curacao', '오렌지 큐라소', 'Orange Curaçao', '{}', 'liqueur', 'common', true),
    ('orange-peel', '오렌지 필', 'Orange Peel', '{}', 'garnish', 'common', true),
    ('orange-wheel', '오렌지 휠', 'Orange Wheel', '{}', 'garnish', 'common', true),
    ('orgeat', '오르자 시럽', 'Orgeat', '{}', 'syrup', 'specialty', true),
    ('pear-peel', '배 껍질', 'Pear Peel', '{}', 'garnish', 'common', true),
    ('pineapple-juice', '파인애플 주스', 'Pineapple Juice', '{}', 'juice', 'common', true),
    ('rhum-agricole', '아그리콜 럼', 'Rhum Agricole', '{}', 'spirit', 'specialty', true),
    ('rich-simple-syrup', '리치 시럽', 'Rich Simple Syrup', '{}', 'syrup', 'common', true),
    ('rosemary', '로즈마리', 'Rosemary', '{}', 'garnish', 'common', true),
    ('rum', '럼', 'Rum', '{}', 'spirit', 'common', true),
    ('rye-whiskey', '라이 위스키', 'Rye Whiskey', '{}', 'spirit', 'common', true),
    ('salt', '소금', 'Salt', '{}', 'garnish', 'common', true),
    ('scotch-whisky', '스카치 위스키', 'Scotch Whisky', '{}', 'spirit', 'common', true),
    ('simple-syrup', '설탕 시럽', 'Simple Syrup', '{}', 'syrup', 'common', true),
    ('sloe-gin', '슬로 진', 'Sloe Gin', '{}', 'liqueur', 'common', true),
    ('soda-water', '탄산수', 'Soda Water', ARRAY['소다']::TEXT[], 'mixer', 'common', true),
    ('sugar', '설탕', 'Sugar', '{}', 'garnish', 'common', true),
    ('suze', '수즈', 'Suze', '{}', 'liqueur', 'specialty', true),
    ('sweet-vermouth', '스위트 베르무트', 'Sweet Vermouth', '{}', 'liqueur', 'common', true),
    ('tomato-juice', '토마토 주스', 'Tomato Juice', '{}', 'juice', 'common', true),
    ('tonic-water', '토닉워터', 'Tonic Water', '{}', 'mixer', 'common', true),
    ('vodka', '보드카', 'Vodka', '{}', 'spirit', 'common', true),
    ('vsop-cognac', '꼬냑', 'VSOP Cognac', '{}', 'spirit', 'common', true),
    ('white-rum', '화이트 럼', 'White Rum', '{}', 'spirit', 'common', true),
    ('worcestershire-tabasco', '우스터소스 · 타바스코', 'Worcestershire · Tabasco', '{}', 'garnish', 'common', true)
-- RED 32·33 — repeatable 이라 체크섬이 바뀌면 다시 돈다.
-- **덮어쓰지 않는다**: 운영에서 에디터가 고친 값을 시드가 되돌리면 안 된다.
ON CONFLICT (slug) DO NOTHING;
